### ISSUE TITLE
能否添加一个相册的单独页面

### ISSUE THREAD

**Issue by SenLief** [tangly1024/NotionNext#1]
notion的相册视图最好。

**Comment by tangly1024** [comment]
我没有太理解，您的意思是增加一个相册页面，用来专门展示图片吗😄

**Comment by SenLief** [comment]
是的，notion的优点在于有强大的图床能力啊，就像about这样的单页用来展示相册。其实能添加单页也可以的，布局最好是网格那种的。

**Comment by tangly1024** [comment]
添加单页的方法可以参考这个 issue: #38 布局可以可以在页面上手动排版。

针对图床功能，暂时不考虑增加一个网格布局页面，原因是使用率比较低😂，感谢您的提议😁
