### ISSUE TITLE
更新blog.config.js后重新部署，不生效

### ISSUE THREAD

**Issue by cogitate3** [tangly1024/NotionNext#100]
更新了blog.config.js设置里面的博客标题、描述、作者等等信息，再deploy之后这些更改在blog上都没生效。

**Comment by tangly1024** [comment]
可以的话检查一下你的`blog.config.js`文件😉。

这种情况大概率是由于文件编辑后格式错乱（例如少了一个引号），导致重新deploy失败，从而blog上没生效。
