### ISSUE TITLE
【文章分享】在文章底部增加分享按钮，将当前文章分享到社交平台

### ISSUE THREAD

**Issue by hjwucc** [tangly1024/NotionNext#1000]
**为什么提出这个新的特性改动**
希望更加方便的将文章分享到如微博、微信、twitter等社交平台；可在配置文件中开启或隐藏分享按钮

**描述一下你推荐的解决方案**
无

**描述一下你考虑过的其它替代解决方案**
无

**补充说明**
如下图所示分享到twitter：
![image](https://user-images.githubusercontent.com/44704392/233607885-8f6d691e-9892-454b-ae79-2d428bb28b60.png)

**Comment by 22Goose** [comment]
请问一下这个发的图用的是哪个theme啊？

**Comment by hjwucc** [comment]
> 请问一下这个发的图用的是哪个theme啊？

nobelium，图片来源于：https://yokinist.me/

**Comment by tangly1024** [comment]
https://github.com/tangly1024/NotionNext/releases/tag/v3.13.5
