### ISSUE TITLE
建议增加选项，支持将通用库切换至字节的cdn

### ISSUE THREAD

**Issue by emengweb** [tangly1024/NotionNext#1003]
**为什么提出这个新的特性改动**
站点css和js库文件较多，且载入慢，可以更换为使用大厂cdn加速通用库的加载速度

**描述一下你推荐的解决方案**
字节提供有通用库加速服务，常用库都有，建议使用类似的cdn服务，如果可以提供开关等附加选项就更好了

**描述一下你考虑过的其它替代解决方案**
国内应该也有其他的类似替代品

**补充说明**
ssl对同一个域下同时加载的线程数量有限制，可以尽量使用其他域提高同时加载的线程数量，变相的提高网络利用率和加载速度。我甚至考虑过notion.so的反代，但是无奈其官网在cf设置了禁止其他服务反代:p

**Comment by emengweb** [comment]
附上字节静态库cdn的地址

**Comment by emengweb** [comment]
像font-awesome可以使用cdn加速，降低服务端带宽压力
http://cdn.bytedance.com/?query=font-awesome&version=6.0.0

**Comment by tangly1024** [comment]
支持在此配置：
https://github.com/tangly1024/NotionNext/blob/19b1b43c9685eff4bebb45f8ffbf4a743fe476b0/blog.config.js#L69

示例配置:
```
FONT_AWESOME: 'https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/font-awesome/6.0.0/css/all.min.css'
```

**Comment by emengweb** [comment]
感谢，下午在代码里找到了，预留了接口，很赞！👍

tangly1024 ***@***.***> 于 2023年4月24日周一 17:52写道：
