### ISSUE TITLE
[缓存]navbar显示错误、部分页面显示的导航栏是旧的

### ISSUE THREAD

**Issue by 22Goose** [tangly1024/NotionNext#1009]
**描述bug**
简单说明navbug的现象、相关的错误提示、日志等
使用了simple theme
我修改了主页的navbar的名称，但跳转到其他页面时navbar仍变回原来的样式
**复现步骤**
出现这个bug的操作步骤
我首先将notion database中的title更改，并删除了icon
结果如下
<img width="260" alt="Screenshot 2023-04-24 at 22 29 21" src="https://user-images.githubusercontent.com/66151506/234027556-fe5a2d9c-b594-4968-9a7a-659d931afa93.png">
⬆️ here is bar at home page
<img width="310" alt="Screenshot 2023-04-24 at 22 30 11" src="https://user-images.githubusercontent.com/66151506/234027771-6fe02804-e094-4c38-94ca-f9cfa91d5bc6.png">
⬆️ here is navbar at tag page
**期望的正常结果**
希望按这个步骤，正常操作结果是什么
期望的结果应该是其他页面和主页的navbar是一样的，但是没有🤷🏻‍♂️
**截图**
相关的页面，应该用结果

**环境**
vercel部署，NotionNext latest version
- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
与问题相关的其它说明
在其他主题下没有尝试

**Comment by tangly1024** [comment]
页面缓存，可能导致此问题，尝试刷新页面解决。

**Comment by 22Goose** [comment]
确实啊。我今天早起看看就好了。没事了🥲（

**Comment by 22Goose** [comment]
确实啊。我今天早起看看就好了。没事了🥲（
