### ISSUE TITLE
更新后部署失败

### ISSUE THREAD

**Issue by snipersteve** [tangly1024/NotionNext#102]
原本一直是正常的，最近一次拉取更新，vercel部署就报错了，如下：
Error occurred prerendering page "/article/snow". Read more: https://nextjs.org/docs/messages/prerender-error
13:12:25.190 | TypeError: Cannot read property 'length' of undefined
13:12:25.190 | at getRecommendPost (/vercel/path0/.next/server/pages/article/[slug].js:138:40)
13:12:25.191 | at getStaticProps (/vercel/path0/.next/server/pages/article/[slug].js:107:28)
13:12:25.191 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
13:12:25.191 | at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:465:20)
13:12:25.193 | at async /vercel/path0/node_modules/next/dist/export/worker.js:269:36
13:12:25.193 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)

请问如何解决。

**Comment by tangly1024** [comment]
Hi，我已经确认了这个报错的原因，并在最新版本中已修复 https://github.com/tangly1024/NotionNext/pull/104 。

再更新一下代码即可修复🤔
