### ISSUE TITLE
需要通过多次访问/刷新才能触发notion内容的更新

### ISSUE THREAD

**Issue by zdf1230** [tangly1024/NotionNext#1020]
**描述bug**
在Notion里更新了内容，需要两次强制刷新才能触发更新机制

这里包括各种更新动作，包括修改menu，删除/添加post。

尤其是menu更新，就算通过两次刷新更新了主页menu，subpage的menu也没有自动更新，需要再次二次刷新。

**复现步骤**
删除了一个post，比如进入archive页面，就算用一个之前从访问过的设备，这篇已经删除的post还会出现在页面上。

**期望的正常结果**
希望在notion上的修改能够自动被抓取，而不是只有客户端多次访问才会更新（抓取notion内容）

**截图**
如有需要可提供截图

**环境**

- 操作系统: iOS & macOS
- 浏览器 chrome & safari
- 版本 NotionNext 3.13.5

**补充说明**
请问是我的理解有误吗？还是本身设计就是这样的呢？
我理解的是notion这边更新内容，一定时间之后，服务器端会与notion同步。

**Comment by tangly1024** [comment]
NotionNext仅当页面被访问时才会抓取

**Comment by zdf1230** [comment]
> NotionNext仅当页面被访问时才会抓取

明白了 那需要刷新两次才能获得更新 是有什么设置么 

被访问能不能马上触发更新呢？

目前的困扰是notion这边更新了之后 页面总是要多次刷新才能触发抓取 非常不方便

请问定时后台刷新抓取更新的feature会有必要吗

**Comment by SkysCrystal** [comment]
`blog.config.js` 文件下：   `NEXT_REVALIDATE_SECOND: process.env.NEXT_PUBLIC_REVALIDATE_SECOND || 5`
