### ISSUE TITLE
 排序方式设置为“notion”不生效

### ISSUE THREAD

**Issue by DuckDuck88** [tangly1024/NotionNext#1040]
**描述bug**
1. 排序方式设置为“notion”不生效，明显与 notion 不一致
2. 文章总数显示为 0
3. 归档 tag 后文章数量为 0
博客地址：http://yaya.run/

**复现步骤**
刷新

**期望的正常结果**
期望一致
**截图**
notion 排序
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/45893278/237024086-1aaad1d0-32be-4d60-9bd2-34062a45de64.png">
博客页面
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/45893278/237024164-f89352a3-e40a-41ad-bc2f-173ff94e6fdd.png">

**环境**
- 操作系统: 腾讯云轻量级服务器  centos
- 浏览器 chrome,
- 版本 NotionNext 3.13.2

**Comment by tangly1024** [comment]
请尝试 删除 Notion模板中的多余视图，数据库在多个视图时会导致排序错乱的问题，参考以下：
https://github.com/tangly1024/NotionNext/issues/1056#issuecomment-1549431084

**Comment by DuckDuck88** [comment]
> 请尝试 删除 Notion模板中的多余视图，数据库在多个视图时会导致排序错乱的问题，参考以下： [#1056 (comment)](https://github.com/tangly1024/NotionNext/issues/1056#issuecomment-1549431084)

排序问题解决啦，但是还有下面两个问题：
1. 文章总数显示为 0
2. 归档 tag 后文章数量为 0

**Comment by DuckDuck88** [comment]
> 这个问题在先前的版本中修复了，[更新](https://tangly1024.com/article/how-to-update-notionnext)到最新版本的NotionNext即可解决。

已解决，感谢。还有一个问题。不支持渲染board view吗？如下
<img width="1024" alt="image" src="https://github.com/tangly1024/NotionNext/assets/45893278/0a47af4c-8d16-41d6-b34c-e37dab10b678">
页面展示如下：
<img width="864" alt="image" src="https://github.com/tangly1024/NotionNext/assets/45893278/9d2732a4-0370-4295-9752-5e282f2a9049">
