### ISSUE TITLE
【next主题】文章列表太宽

### ISSUE THREAD

**Issue by fantansi** [tangly1024/NotionNext#1060]
**截图**
相关的页面，应该用结果
![image](https://github.com/tangly1024/NotionNext/assets/110267748/6374552f-da1f-4f94-94bd-bb41c2f844d7)

**Comment by fantansi** [comment]
![image](https://github.com/tangly1024/NotionNext/assets/110267748/d3409211-a2a0-4850-80a7-991494433fb3)

**Comment by tangly1024** [comment]
感谢反馈，此处的高度是因为我设置了底部留白 24.

相关代码： https://github.com/tangly1024/NotionNext/blob/133bcd6aa713157d360160553ddc27ac8db7a17b/themes/next/components/BlogPostCard.js#L68

新版本中我将减小此处高度。
