### ISSUE TITLE
【环境变量不生效】NEXT_PUBLIC_WIDGET_PET在vervel设置env后不生效

### ISSUE THREAD

**Issue by c1awn** [tangly1024/NotionNext#1061]
**描述bug**
我想关闭宠物挂件，在vercel设置NEXT_PUBLIC_WIDGET_PET:false，但是宠物挂件仍在。但是我修改[blog.config.js]的NEXT_PUBLIC_WIDGET_PET为FALSE后宠物挂件消失

**复现步骤**
[blog.config.js]的NEXT_PUBLIC_WIDGET_PET不变，在vercel设置NEXT_PUBLIC_WIDGET_PET:false

**期望的正常结果**
关闭宠物挂件

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/29470764/70c5180d-52ed-4f73-87a8-aecdd020732d)

**环境**

- 操作系统: [windows]
- 浏览器 [chrome
- 版本 [113.0.5672.93（正式版本） （64 位）]

**补充说明**
无

**Comment by tangly1024** [comment]
> vercel设置NEXT_PUBLIC_WIDGET_PET:false

设置环境变量后，需要redeploy才能生效：

![image](https://github.com/tangly1024/NotionNext/assets/15920488/fc3ae692-8c30-43ff-bca9-eece153901ad)

**Comment by RedhairHambagu** [comment]
如果部分env能生效，可以试下把dockerfile删掉
