### ISSUE TITLE
建议支持内嵌B站视频播放

### ISSUE THREAD

**Issue by Allwillcome** [tangly1024/NotionNext#1064]
**为什么提出这个新的特性改动**
尽管博客以文字为主，但是现在是视频时代，插入自己拍摄、制作的视频，能够更好的展示自己的作品，丰富内容形式。

**描述一下你推荐的解决方案**
目前 notion 支持内嵌 B 站视频，并进行播放。B站内嵌的视频在博客里只有视频栏，点击无法正常播放。
![image](https://github.com/tangly1024/NotionNext/assets/35840764/8e7c970c-97d8-4bd9-85d6-42b12052105a)
![image](https://github.com/tangly1024/NotionNext/assets/35840764/c2dc4d0d-c796-4b3e-9c9c-61b52eeb9042)

**描述一下你考虑过的其它替代解决方案**
暂无

**补充说明**
暂无

**Comment by Angel0726** [comment]
你内嵌错了，你点击分享，使用iframe内嵌。

**Comment by Allwillcome** [comment]
> 你内嵌错了，你点击分享，使用iframe内嵌。

谢谢，确实是我弄错了，不过直接使用 iframe 内嵌似乎也不能成功。具体可以参考limi 的网站。[Notion 中如何嵌入 B 站视频？](https://linmi.cc/2853.html) 另外文中提到使用 high_quality=1 提高视频清晰度的方法已经失效。
