### ISSUE TITLE
没fork，如何更新源码

### ISSUE THREAD

**Issue by sorabug** [tangly1024/NotionNext#107]
之前看文档的时候没注意，就没fork，直接通过文档里面的链接部署了，然后现在发现貌似，没法更新源码

**Comment by tangly1024** [comment]
一键部署链接是默认会自动fork的🤔

无法更新的话可以删除原仓库并重新部署✅

**Comment by sorabug** [comment]
> 一键部署链接是默认会自动fork的🤔
> 
> 无法更新的话可以删除原仓库并重新部署✅
![image](https://user-images.githubusercontent.com/45709238/160262864-6c037f17-ed61-46f3-bcd9-ba473e5271dc.png)
但实际上他是这样的，直接变私人仓库，我无法更新源码

**Comment by tangly1024** [comment]
确认了一下确实如此，Vercel的一键部署是基于Clone而非Fork。真是令人头疼😂
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/15920488/160264151-cbc768ae-8105-43c1-b51f-307f25fcd437.png">

**Comment by sorabug** [comment]
> 确认了一下确实如此，Vercel的一键部署是基于Clone而非Fork。真是令人头疼😂 <img alt="image" width="1035" src="https://user-images.githubusercontent.com/15920488/160264151-cbc768ae-8105-43c1-b51f-307f25fcd437.png">

看来我得先fork再用自己的项目了，给部署文档先fork再建哪里加个强调吧，或者改下文档，我先重新部署去了

**Comment by tangly1024** [comment]
👌，我改一下文档
