### ISSUE TITLE
[Hexo/Matery主题] 在不显示Banner时的顶部边距优化

### ISSUE THREAD

**Issue by hprandom** [tangly1024/NotionNext#1083]
**为什么提出这个新的特性改动**
Hexo主题，能否美化一个小细节。

**描述一下你推荐的解决方案**
在不显示Banner的情况下，这里没有间隙，不太好看。能否加一点间隙。

**描述一下你考虑过的其它替代解决方案**
如上述。

**补充说明**
补充与此特性相关的内容
![image](https://github.com/tangly1024/NotionNext/assets/48062021/ba20af5d-e594-408c-9215-aa910a99a77d)

**Comment by tangly1024** [comment]
感谢反馈，此问题已经由 [kitety](https://github.com/kitety)修复；再次感谢kitety..
