### ISSUE TITLE
[性能优化] 打开网站CPU占用飙升

### ISSUE THREAD

**Issue by W4nde3** [tangly1024/NotionNext#1092]
**描述bug**
不确定是否为NotionNext的原因，访问NotionNext网站（如 [https://tangly1024.com/](https://tangly1024.com/)），Chrome占用率飙升，使用开发者工具-性能分析工具，发现Chrome不断重复“重新计算样式-绘制-分层-渲染“步骤，导致单页面占用大量CPU)

**复现步骤**
访问NotionNext网站（如[https://tangly1024.com/](https://tangly1024.com/)），稍等几秒钟即可看到CPU占用明显提高

**期望的正常结果**
访问NotionNext网站（如[https://tangly1024.com/](https://tangly1024.com/)），CPU占用维持在合理水平

**截图**
性能截图：
<img width="1824" alt="image" src="https://github.com/tangly1024/NotionNext/assets/45825507/2f4fbbbb-2c3b-4780-9ea2-1eef4c2d21a0">

性能截图-部分展开：
<img width="1826" alt="image" src="https://github.com/tangly1024/NotionNext/assets/45825507/e333c1f1-7151-4b25-9619-dac029340d7f">

性能截图-完全展开：
<img width="1825" alt="image" src="https://github.com/tangly1024/NotionNext/assets/45825507/75075f31-2bbe-4747-8190-5a1cc509a539">

**环境**

- 操作系统: macOS 13.3.1 、2.3 GHz 八核Intel Core i9、16 GB 
- 浏览器: Chrome 113.0.5672.126（正式版本） (x86_64)
- NotionNext版本 3.14.0 (作者博客)

**补充说明**
1. 不确定是否是NotionNext或其使用的js或Chrome问题，我对前端了解不够深入，如果此问题与NotionNext无关还请忽略
2. 访问其他网站时CPU占用正常
3. [访问其他使用NotionNext的大佬博客时（如[https://www.chancesha.com/](https://www.chancesha.com/)]，也可复现Chrome CPU占用飙升的问题
4. 资源占用对比：
<img width="466" alt="image" src="https://github.com/tangly1024/NotionNext/assets/45825507/4d9b8de7-3c2b-47d3-94ee-047b2c1f5fcb">
<img width="466" alt="image" src="https://github.com/tangly1024/NotionNext/assets/45825507/6dc07926-257a-4b5f-85f2-545706565468">

**Comment by tangly1024** [comment]
感谢您详细的bug反馈，我在关注此问题。
