### ISSUE TITLE
404并未生效

### ISSUE THREAD

**Issue by ottocsb** [tangly1024/NotionNext#1093]
**描述bug**
如题，会正常加载但内容为空

**复现步骤**
在博客站输入任意无意义的后缀

**期望的正常结果**
出现404

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/83228451/0878595d-a7d5-463f-ad2b-db6958ac52fe)

**环境**

- 操作系统: win
- 浏览器 chrome
- NotionNext版本 [e.g. 3.14.0]

**补充说明**
与问题相关的其它说明

**Comment by ottocsb** [comment]
还有一个小问题是关于``giscus``的评论插件，会有个滚动条，影响观感
![image](https://github.com/tangly1024/NotionNext/assets/83228451/75e4f614-37d3-4449-ae81-0366f7c72608)

**Comment by ottocsb** [comment]
> 还有一个小问题是关于`giscus`的评论插件，会有个滚动条，影响观感 ![image](https://user-images.githubusercontent.com/83228451/242846659-75e4f614-37d3-4449-ae81-0366f7c72608.png)

滚动条是layoutSlug中评论互动块的x-auto属性导致，可能是需要适配其他插件？这个我使用```giscus```自己去掉了没关系

**Comment by tangly1024** [comment]
感谢反馈，
- 404bug已修复。 https://github.com/tangly1024/NotionNext/pull/1099
- giscus插件的滚动条问题，我暂时无法复现，理论上不应有此现象。
