### ISSUE TITLE
跳转问题

### ISSUE THREAD

**Issue by ottocsb** [tangly1024/NotionNext#1102]
**描述bug**
在category页或tag页，点击任意文章跳转至文章页时跳转链接多了tag或category的字段导致无法正常跳转，未在您的网站复现，在我fork的分支上出现了此问题

**复现步骤**
出现这个bug的操作步骤
上述步骤
复现链接：[(https://vercel.com/luck/notion-next/5iF9nRsKe6JRwXtc5HyvRy4hyg2h)](https://notion-next-3kj6e6dla-luck.vercel.app/)

**期望的正常结果**
正常跳转

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/83228451/904a5ba6-4149-4161-b68f-d0640c03855e)
![image](https://github.com/tangly1024/NotionNext/assets/83228451/4c9de57f-ec12-4815-8667-032ea38fbe8b)

**环境**

- 操作系统: [windows]
- 浏览器 [chrome,]
- NotionNext版本 [e.g. 3.14.0，库内最新]

**补充说明**
与问题相关的其它说明

**Comment by lzmchina** [comment]
我也遇到这个bug了，不知道啥情况

**Comment by lzmchina** [comment]
找到问题了，themes里面的category页或tag页相关的超链接作者没有修改，比方说themes/hexo/components/BlogPostCard.js这里，要把`${post.slug`前面加一个`/`符号。其他主题类似

**Comment by LeoYoung-code** [comment]
遇到了同样的问题
