### ISSUE TITLE
博客主题Hexo的dark mode能否换成dev community这种色调

### ISSUE THREAD

**Issue by eliaszon** [tangly1024/NotionNext#111]
这是原本的css
![image](https://user-images.githubusercontent.com/73749474/160247725-05704716-abfb-42bb-90fd-f4a1af7ecb79.png)

这是dev cocommunity的
![image](https://user-images.githubusercontent.com/73749474/160247111-a67eebbb-ee53-465d-b381-e38c6bd29b1f.png)

能否更换一下css颜色……或者大佬教我把自己的换一下也行，并不一定要整个模板都换成这样

**Comment by tangly1024** [comment]
dev cocommunity 这个色调很不错，我尝试一下

**Comment by tangly1024** [comment]
> 能否更换一下css颜色……或者大佬教我把自己的换一下也行，并不一定要整个模板都换成这样
如果需要自己修改的话，也可以参考一下：[TailwindCss文档中的深色模式](https://www.tailwindcss.cn/docs/dark-mode)
如果可以的话，欢迎将你的代码提交PR😁

**Comment by eliaszon** [comment]
大佬我自己尝试修改了博客界面的css，我的思路是这样的。首先我把我要更换的两个颜色用取色器取下来，然后更换我要的那个颜色。

17, 24, 39  -> 0, 0, 0
31, 41, 55  ->  17, 19, 19

所以我的步骤是这样的，首先用fork把项目clone到本地，然后我再在vscode中搜索17, 24, 39，然后再全局替换成0, 0, 0这个颜色。另一个颜色同理。按理来说不应该有什么问题。然后我把这个更改推送到云端了。再用Vercel重新编译发现错误。

![image](https://user-images.githubusercontent.com/73749474/160343515-a2696dab-3544-4931-9f9d-6b664c603862.png)

大佬我看不太懂这个报错😂好像是什么依赖的问题，能否教我解决一下这个问题

**Comment by eliaszon** [comment]
几乎没什么项目经验……仍然是学生和小白……😂如果犯了stupid fault请包涵

**Comment by tangly1024** [comment]
Hi 
> 几乎没什么项目经验……仍然是学生和小白……😂如果犯了stupid fault请包涵

看了你的思路是完全可以实现的，真的是小白吗😂

你的编译错误，仅仅只是因为你的博客名字中不能有单引号`'`，也就是说，像这样改动一下即可：

*ELIAS's BLOG* => *ELIAS`s BLOG* ;
 ` 和 ' 这两个符号长得真是太像了😂

**Comment by tangly1024** [comment]
另外，devCommunity 的样式确实好看，我已经着手在最新版本中调整了样式

**Comment by eliaszon** [comment]
感谢大佬😍
