### ISSUE TITLE
bug: 首页文件路径异常

### ISSUE THREAD

**Issue by yuzhanglong** [tangly1024/NotionNext#112]
首页的图片展示没有考虑第三方图片。
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/56540811/160270019-d75397a8-52f2-42d6-b554-23100960b5e9.png">

**Comment by tangly1024** [comment]
#110 相同的错误

**Comment by tangly1024** [comment]
#113 已修复问题

**Comment by yuzhanglong** [comment]
> #113 已修复问题

感觉可以适配以下图片尺寸不一致带来的问题，保证填满外框，多余的剪裁：
<img width="501" alt="image" src="https://user-images.githubusercontent.com/56540811/160282356-03e2a2cf-40cd-4c68-ac4d-0f90892e2017.png">
```
img {
 height: 100%;
 object-fit: cover;
}
```

**Comment by yuzhanglong** [comment]
> > #113 已修复问题
> 
> 感觉可以适配以下图片尺寸不一致带来的问题，保证填满外框，多余的剪裁： <img alt="image" width="501" src="https://user-images.githubusercontent.com/56540811/160282356-03e2a2cf-40cd-4c68-ac4d-0f90892e2017.png">
> 
> ```css
> img {
>  height: 100%;
>  object-fit: cover;
> }
> ```

hi，这个问题有解决方案吗

**Comment by tangly1024** [comment]
这个问题，我也发现并解决过了，更新一下代码即可~

**Comment by tangly1024** [comment]
最新版本中这个封面图的代码：

```html
<div className='flex w-full relative duration-200 rounded-t-xl lg:rounded-r-xl lg:rounded-t-none cursor-pointer transform overflow-hidden'>
  {/* eslint-disable-next-line @next/next/no-img-element */}
  <img src={post?.page_cover} alt={post.title} className='hover:scale-125 rounded-t-xl lg:rounded-r-xl lg:rounded-t-none transform object-cover duration-500'/>
</div>
```

**Comment by yuzhanglong** [comment]
> 最新版本中这个封面图的代码：
> 
> ```
> <div className='flex w-full relative duration-200 rounded-t-xl lg:rounded-r-xl lg:rounded-t-none cursor-pointer transform overflow-hidden'>
>   {/* eslint-disable-next-line @next/next/no-img-element */}
>   <img src={post?.page_cover} alt={post.title} className='hover:scale-125 rounded-t-xl lg:rounded-r-xl lg:rounded-t-none transform object-cover duration-500'/>
> </div>
> ```

好了，Thanks♪(･ω･)ﾉ
