### ISSUE TITLE
[日期不显示] 手机端 create 时间异常-(我修改了表格的时间格式)

### ISSUE THREAD

**Issue by 668168** [tangly1024/NotionNext#1122]
**描述bug**
参考截图, 手机端create time 显示异常. 电脑端正常.
其实不算 bug, 因为我修改了 notion 表格的时间格式. 
模版的时间格式每次要重新选时间, 我修改为当前时间了.
<img width="275" alt="image" src="https://github.com/tangly1024/NotionNext/assets/1046701/cb1c2e64-773c-4d43-9467-edfe59fdaa73">

**复现步骤**

**期望的正常结果**
希望按这个步骤，正常操作结果是什么
手机端正常显示

**截图**
1/2 手机端异常图片
2/2 pc 端正常图片

![telegram-cloud-photo-size-1-4904745621903223604-y](https://github.com/tangly1024/NotionNext/assets/1046701/4770b6b5-1fb0-402f-8f4c-a5d0aef107a5)
<img width="548" alt="image" src="https://github.com/tangly1024/NotionNext/assets/1046701/7f964704-5ab8-4232-a84d-db55abd77217">

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- NotionNext版本 [e.g. 3.13.6]
iPhone
chrome 

**补充说明**
与问题相关的其它说明

**Comment by happyzhangyyds** [comment]
我也出现了此问题，如果在一个页面内，再添加一个页面就会出现此问题

**Comment by tangly1024** [comment]
比较奇怪，我试着打了点补丁， 可能会有帮助 https://github.com/tangly1024/NotionNext/pull/1213
