### ISSUE TITLE
[simple主题] darkmode切换按钮 fa-moon 看不到

### ISSUE THREAD

**Issue by RedhairHambagu** [tangly1024/NotionNext#1126]
**描述bug**
https://tangly1024.com/ simple主题的 darkmode切换按钮 fa-moon 看不到，fa-sun看得到
尝试替换别的icon 没成功

**复现步骤**
无

**期望的正常结果**
像fa-sun显示或者换个白色的icon

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/129669334/0a0f863d-8b11-4545-aad7-ad9f5fc279c4)

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- NotionNext版本 3.15.0

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
感谢反馈
