### ISSUE TITLE
[暗黑模式显示bug]github链接和密码提示看不清

### ISSUE THREAD

**Issue by zhiqing0205** [tangly1024/NotionNext#1138]
**描述bug**
github链接和密码提示看不清

**复现步骤**
进入暗黑模式

**期望的正常结果**
应该是白色字体

**截图**
![密码输入界面](https://img.ziuch.top/i/2023/06/11/202306111947288_6485b493cdccc.png)

![github链接preview展示](https://img.ziuch.top/i/2023/06/11/202306111950828_6485b503eb531.png)

**环境**

- 操作系统: windows
- 浏览器 chrome
- NotionNext版本 3.15.0

**补充说明**
无

**Comment by tangly1024** [comment]
感谢反馈，bug将尽快被修复
