### ISSUE TITLE
原页面跳转到新页面后回退，加载动画效果一直存在

### ISSUE THREAD

**Issue by linfeng-weng** [tangly1024/NotionNext#1142]
**描述bug**
原页面跳转到新页面后回退，加载动画效果一直存在，需要重新刷新才能去除

**复现步骤**
![uTools_1686539348203](https://github.com/tangly1024/NotionNext/assets/122910465/8d3e3ea1-fd71-42ae-af78-28c0ea296a9a)
![uTools_1686496858695](https://github.com/tangly1024/NotionNext/assets/122910465/e13bcbeb-48ba-4162-bbb2-8f01b8e11e30)

**期望的正常结果**
回退后无加载动画

**环境**

- 操作系统: [windows]
- 浏览器 [chrome]
- NotionNext版本 [3.15.0]

**Comment by tangly1024** [comment]
已修复

https://github.com/tangly1024/NotionNext/commit/980f02260c588bb67bba79787481f68c1ea31e64
