### ISSUE TITLE
[列表无限滚动bug]一行展示两列并且宽度不一致

### ISSUE THREAD

**Issue by zhiqing0205** [tangly1024/NotionNext#1146]
**描述bug**
调整成scroll模式后 一行展示两列并且宽度不一致

**复现步骤**
调整成scroll模式后

**期望的正常结果**
正常还是一行一列 只是可以一直往下滚到底

**截图**
![](https://img.ziuch.top/i/2023/06/12/202306121606956_6486d1fe9d6b7.png)

**环境**

- 操作系统: windows
- 浏览器 chrome
- NotionNext版本 3.15.0(git clone的最新代码)

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
已在新版本中修复
