### ISSUE TITLE
Page 出现在了菜单栏

### ISSUE THREAD

**Issue by Ningscode** [tangly1024/NotionNext#1147]
**描述bug**
更新部署后菜单栏出错了，Menu 这个标签貌似失效了，取而代之的是 Page 出现在了菜单栏

**环境**

- 操作系统: macOS
- 浏览器 chrome
- [NotionNext 3.15.0]

**补充说明**
以后 Menu 是要被 Page 取代吗，还是 Menu 这个标签有别的用途，比如二级菜单？

**Comment by tangly1024** [comment]
https://tangly1024.com/article/notion-next-secondary-menu

**Comment by Ningscode** [comment]
我的意思是：这次更新后，菜单栏的控制又回到旧版了

[cid:0c5fe3b2-d111-460a-8d23-d0f8d0f40637]

[cid:20dae67b-1647-406d-923e-d74bca326435]
________________________________
发件人: tangly1024 ***@***.***>
发送时间: 2023年6月12日 22:06
收件人: tangly1024/NotionNext ***@***.***>
抄送: Ning ***@***.***>; Author ***@***.***>
主题: Re: [tangly1024/NotionNext] Page 出现在了菜单栏 (Issue #1147)


Closed #1147<https://github.com/tangly1024/NotionNext/issues/1147> as completed.

―

**Comment by Ningscode** [comment]
![1686580315028](https://github.com/tangly1024/NotionNext/assets/77867541/ced0dcae-c9c1-4830-8b82-dd2248a68f0f)
<img width="190" alt="image" src="https://github.com/tangly1024/NotionNext/assets/77867541/17366dd9-6fd7-4a56-9914-2038bd5ac8bb">

**Comment by tangly1024** [comment]
试着重新修改一下配置，升级到新版的菜单
