### ISSUE TITLE
[Hexo主题]标题长度过长、将内容挤下去

### ISSUE THREAD

**Issue by zhiqing0205** [tangly1024/NotionNext#1154]
**描述bug**
Hexo主题下标题过长将内容挤下去了

**复现步骤**
Hexo主题下标题过长将内容挤下去了

**期望的正常结果**
超过两行最后显示省略号

**截图**
![](https://img.ziuch.top/i/2023/06/14/202306140051210_64889e9f58e17.png)

**环境**

- 操作系统: windows
- 浏览器 chrome
- NotionNext版本 3.15.0

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
(｀・ω・´) 好多马赛克
