### ISSUE TITLE
能否支持静态html页面导出

### ISSUE THREAD

**Issue by yyzfish** [tangly1024/NotionNext#116]

**Comment by tangly1024** [comment]
Hi ,NextJS是支持纯静态Html导出的。
感兴趣的话可以参考这两篇文档：
- https://www.nextjs.cn/docs/advanced-features/static-html-export
- https://nextjs.org/docs/api-reference/next.config.js/exportPathMap

导出的话项目要做相应的配置：
参考此分支代码中next.config.js的配置 https://github.com/tangly1024/NotionNext/tree/feature_html_export

另外，导出的纯静态文件是引用的绝对地址，需要放在Nginx等服务器中才可以正常显示样式。

**Comment by yyzfish** [comment]
因为可以部署在ipfs呀

**Comment by yyzfish** [comment]
一定要在nginx下才能正常运行吗

**Comment by yyzfish** [comment]
有一个逻辑问题想问一下，我看到pageid要求share to web，但是password字段是公开的话，那不是没有意义了吗

**Comment by tangly1024** [comment]
> 有一个逻辑问题想问一下，我看到pageid要求share to web，但是password字段是公开的话，那不是没有意义了吗

1. notion的这个页面确实会被共享到互联网，不排除有被访问到的风险，如果被查到pageid的话页面确实就没有意义。
2. pageid这个字段可以放在Vercel的环境变量中，不必在blog.config.js中编写，从而隐藏起来。
3. 如果加密的要求更高的话，可能就需要noton页面不共享到互联网，而是通过notion的access_token进行数据的访问。

**Comment by tangly1024** [comment]
> 经过几个小时的测试，看来并不能部署在ipfs上，因为ipfs没有Nginx环境

#120 ，你应该已经能在ipfs上部署，具体问题将在[这里](https://github.com/tangly1024/NotionNext/issues/120)  讨论

**Comment by yyzfish** [comment]
好的

**Comment by sunnoy** [comment]
> > 有一个逻辑问题想问一下，我看到pageid要求share to web，但是password字段是公开的话，那不是没有意义了吗
> 
> 1. notion的这个页面确实会被共享到互联网，不排除有被访问到的风险，如果被查到pageid的话页面确实就没有意义。
> 2. pageid这个字段可以放在Vercel的环境变量中，不必在blog.config.js中编写，从而隐藏起来。
> 3. 如果加密的要求更高的话，可能就需要noton页面不共享到互联网，而是通过notion的access_token进行数据的访问。
access_token 这个我们支持么 如何配置哈 😃

**Comment by tangly1024** [comment]
> access_token 这个我们支持么 如何配置哈 😃
你可以在浏览器的cookies中找到这个参数，它的变量名为 `token_v2`

但是这种方式并不被推荐，要注意的是Notion的token有效期是180天，你需要在Vercel的控制台中定期手动刷新，另外，Notion数据库中的图片用这种方式可能无法展示。

<img width="1635" alt="image" src="https://user-images.githubusercontent.com/15920488/160539907-733ea257-8f6a-4bee-b3e0-57200d48ebb9.png">

**Comment by Ylarod** [comment]
> > access_token 这个我们支持么 如何配置哈 😃
> > 你可以在浏览器的cookies中找到这个参数，它的变量名为 `token_v2`
> 
> 但是这种方式并不被推荐，要注意的是Notion的token有效期是180天，你需要在Vercel的控制台中定期手动刷新，另外，Notion数据库中的图片用这种方式可能无法展示。
> 
> <img alt="image" width="1635" src="https://user-images.githubusercontent.com/15920488/160539907-733ea257-8f6a-4bee-b3e0-57200d48ebb9.png">

我在填 NOTION_ACCESS_TOKEN 错误的使用了 https://developers.notion.com/docs/authorization 生成的一个TOKEN，是否可以通过该 token 代替 cookies 中的 `token_v2` 达到不需要手动刷新 token 和展示数据库中图片的目的

**Comment by SkysCrystal** [comment]
> > > access_token 这个我们支持么 如何配置哈 😃
> > > 你可以在浏览器的cookies中找到这个参数，它的变量名为 `token_v2`
> > 
> > 
> > 但是这种方式并不被推荐，要注意的是Notion的token有效期是180天，你需要在Vercel的控制台中定期手动刷新，另外，Notion数据库中的图片用这种方式可能无法展示。
> > <img alt="image" width="1635" src="https://user-images.githubusercontent.com/15920488/160539907-733ea257-8f6a-4bee-b3e0-57200d48ebb9.png">
> 
> 我在填 NOTION_ACCESS_TOKEN 错误的使用了 https://developers.notion.com/docs/authorization 生成的一个TOKEN，是否可以通过该 token 代替 cookies 中的 `token_v2` 达到不需要手动刷新 token 和展示数据库中图片的目的

同问是否能用这个 token ？
