### ISSUE TITLE
[新主题] 类似Gitbook主题发布文档

### ISSUE THREAD

**Issue by emengweb** [tangly1024/NotionNext#1162]
**为什么提出这个新的特性改动**
有的时候需要使用notion制作好的相关页面，发布为类似gitbook结构的文档。

**描述一下你推荐的解决方案**
可否将类似的主题移植到NotionNext平台

**描述一下你考虑过的其它替代解决方案**
notion导出数据库内容为md格式，之后再生成gitbook。这种方案对于需要维护的类文档站不太友好，notion做内容管理的优势还是很大的。

**补充说明**
有类似项目已经实现了此类功能osmium

**Comment by emengweb** [comment]
这个项目实现了类似的效果，不过他的演示站证书貌似过期了...
https://github.com/osmium-blog/osmium

**Comment by tangly1024** [comment]
很不错的主题！感谢分享，也许不就就会加入NotionNext

**Comment by emengweb** [comment]
哦哦~太好啦~（｡ò ∀ ó｡）

tangly1024 ***@***.***> 于 2023年6月20日周二 14:54写道：

**Comment by jmc-123** [comment]
> 这个项目实现了类似的效果，在线效果： https://osmium-blog.vercel.app/osmium-v1.2-zh 项目地址 https://github.com/osmium-blog/osmium

我正好也想把我的md图书放到个人站上面!
