### ISSUE TITLE
[图片] 修复编译问题后，发现背景图、头像图以及文章内的图无法显示了

### ISSUE THREAD

**Issue by Flyingpen** [tangly1024/NotionNext#1164]
**描述bug**
修复编译问题后，发现背景图、头像图以及文章内的图无法显示了

**复现步骤**
修复编译问题前，图片显示正常。更新后，图片无法显示。

**期望的正常结果**
正常的结果，应该是背景图、头像图以及文章内图片正常显示。

**截图**

**环境**

- 操作系统: [ windows与安卓]
- 浏览器 [chrome,EDGE]
- NotionNext版本 [e.g. 3.13.6]

**补充说明**
与问题相关的其它说明

**Comment by jimmyhuang22** [comment]
是的，我也遇到了同样的问题。我拿更新前的本地项目运行了下，图片显示正常，所以不是Notion的问题，应该是修复编译问题后出了Bug。

**Comment by sucooer** [comment]
合并后就G了

**Comment by chwl66** [comment]
暂时退回去了！

**Comment by sucooer** [comment]
> 暂时退回去了！

怎么回退的？
