### ISSUE TITLE
希望加入一个google收录的功能和站点地图的功能

### ISSUE THREAD

**Issue by 3dswicks** [tangly1024/NotionNext#1174]
**为什么提出这个新的特性改动**
无法被引擎抓取，根本没人能看到

**描述一下你推荐的解决方案**
google的生成的收录证明的html和站点地图

**描述一下你考虑过的其它替代解决方案**
其他的引擎也可以

**补充说明**

**Comment by tangly1024** [comment]
原先以支持该功能，您的站点 /sitemap.xml 提交谷歌即可收录。
例如我的地图：
https://tangly1024.com/sitemap.xml

**Comment by 3dswicks** [comment]
ok，已解决，谢谢大神
