### ISSUE TITLE
[Hexo主题] 文章展示封面图

### ISSUE THREAD

**Issue by psycounselor** [tangly1024/NotionNext#1182]
**描述bug**
如何让不同的文章，在网站展示文章默认的图，现在hexo主题下，每篇文章展示的都是同一张图

**复现步骤**
每篇文章展示的都是同一张图

**期望的正常结果**
让不同的文章，在网站展示文章默认的图

**截图**
相关的页面，应该的结果

**环境**

电脑和上搜极端

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
![image](https://github.com/tangly1024/NotionNext/assets/15920488/b5821b87-6ed8-4b0d-b5fa-44cfd4e7c44e)

Notion每篇文章都可以在右上角的change cover 中设置封面图

**Comment by psycounselor** [comment]
感谢，问题已解决
