### ISSUE TITLE
Mermaid 图无法展示

### ISSUE THREAD

**Issue by BJTiew** [tangly1024/NotionNext#1184]
**描述bug**
mermaid 图无法显示

**复现步骤**
今天修改了一些 mermaid 的 CSS 代码（见下图），然后无数次更新网页（电脑&电话）都无法显示出 mermaid 图了。
在那之后，我把 CSS 代码改回了您的源代码，数次（deploy+加载跟新）之后，还是一样无法显示。

**期望的正常结果**
希望能正常加载 mermaid 图

**截图**
CSS 修改（后来已经改回和您的一致）
![image](https://github.com/tangly1024/NotionNext/assets/132333550/109e20a5-30d6-4183-9dd0-908be30290a0)

notion 上（同时也是期待的正常结果）
<img width="323" alt="image" src="https://github.com/tangly1024/NotionNext/assets/132333550/0ef2c488-db76-4c92-86de-a8eee6fb77dc">

网页上（报错，无法显示）
<img width="226" alt="image" src="https://github.com/tangly1024/NotionNext/assets/132333550/c9a1a4e5-4ced-4975-8cb8-567877c148f1">

**环境**

电脑windows11 edge + opera
三星手机 edge + opera

**补充说明**
--

**Comment by BJTiew** [comment]
刚发现刷了很多遍以后偶尔 mermaid 图能成功被加载（见下图）
（左边是加载成功）（右边是加载失败）

<img width="1284" alt="image" src="https://github.com/tangly1024/NotionNext/assets/132333550/5ee31849-0578-4396-93df-266c802db57b">

如图所示，感觉大部分时候是cdn加载问题，导致 mermaid 图加载不了。但是

**Comment by tangly1024** [comment]
已修复 https://github.com/tangly1024/NotionNext/pull/1194
