### ISSUE TITLE
[hexo主题]  卡牌大小参差不齐

### ISSUE THREAD

**Issue by tdouguo** [tangly1024/NotionNext#1188]
**描述bug**
主页 显示卡片 错乱 这个是因为 什么啊 正常应该统一大小吧

**复现步骤**
我的网站 
https://www.tdouguo.com/

**期望的正常结果**
希望能正常显示 大小 

**截图**
<img width="800" alt="image" src="https://github.com/tangly1024/NotionNext/assets/22972345/3e6fd546-760c-48b9-9d04-4147b448d283">

**环境**

- 操作系统: [macOS, windows]
- 浏览器 [chrome, safari, firefox]
- NotionNext版本 [3.15.2](https://github.com/tangly1024/NotionNext).

**补充说明**
与问题相关的其它说明

**Comment by tdouguo** [comment]
<img width="936" alt="image" src="https://github.com/tangly1024/NotionNext/assets/22972345/3a32fd67-933f-4227-b943-3f42198638ac">
<img width="918" alt="image" src="https://github.com/tangly1024/NotionNext/assets/22972345/16a0e354-7f0c-4d07-a81a-3eaf0abcb4f6">
补充 notion 截图

**Comment by tangly1024** [comment]
可能是误操作修改了代码导致，检查一下

**Comment by tangly1024** [comment]
已在新版本中修复
