### ISSUE TITLE
notion写完文章怎么没有同步呢

### ISSUE THREAD

**Issue by sunnoy** [tangly1024/NotionNext#119]
notion写完文章需要在vercel重新部署么

**Comment by sunnoy** [comment]
是的看到了，谢谢回复，还有个问题哈，博客的字体有变更的入口么，不太喜欢宋体

**Comment by tangly1024** [comment]
字体改动的话留意一下这几个文件即可：
1.[_document.js](https://github.com/tangly1024/NotionNext/blob/main/pages/_document.js)中的谷歌字体镜像
2.[font.js](https://github.com/tangly1024/NotionNext/blob/main/lib/font.js)中的fontFamilies
3.[blog.config.js](https://github.com/tangly1024/NotionNext/blob/main/blog.config.js) 中的FONT

**Comment by sunnoy** [comment]
> 字体改动的话留意一下这几个文件即可： 1.[/_document.js](https://github.com/tangly1024/NotionNext/blob/main/pages/_document.js)中的谷歌字体镜像 2.[/blog.config.js](https://github.com/tangly1024/NotionNext/blob/main/blog.config.js) 中的FONT 3.[/lib/font.js](https://github.com/tangly1024/NotionNext/blob/main/lib/font.js)中的fontFamilies

好的 谢谢
