### ISSUE TITLE
preview的内容是怎样控制的

### ISSUE THREAD

**Issue by weizhenhuan** [tangly1024/NotionNext#12]
preview显示的篇幅有时并不令我满意。我查看源代码，这是由<NotionRenderer>标签实现的，但我太菜了，看不懂这里。所以我想简单了解下这里的原理，方便我进行更改。或者，hexo是通过在文章中加入去实现修改preview的内容，能不能在该项目中引入该功能呢？

**Comment by tangly1024** [comment]
🙋🏻‍♂️hi~，我也在想preview显示的篇幅该如何设置。
hexo中我了解到用的是使用文章中截断 `<!-- more -->` 或主题配置`auto_excerpt`字数长度来控制自动摘要。

在刚刚更新的最新版本中，我在[配置文件](https://github.com/tangly1024/NotionNext/blob/main/blog.config.js)中新增了 `previewLines`配置，表示摘要显示的行数，它的默认值是12；你可以尝试一下。
