### ISSUE TITLE
[部署ipfs]部署在ipfs最后一步出错

### ISSUE THREAD

**Issue by yyzfish** [tangly1024/NotionNext#120]
文章无法显示，请问有办法解决吗
主页均显示正常

![image](https://user-images.githubusercontent.com/69407830/160441056-40830f67-79fb-48f7-9ae6-e559dc6c018a.png)

**Comment by yyzfish** [comment]
![image](https://user-images.githubusercontent.com/69407830/160441421-974f3d65-71ee-4a19-8d7a-83b7bbaff1d6.png)
chrome调试如图

**Comment by yyzfish** [comment]
html导出显示正常 唯有文章不行

**Comment by yyzfish** [comment]
yyzfish.com 这是部署的地址可以进去看一下

**Comment by SenLief** [comment]
貌似是因为路径的问题，你需要一个静态的服务器才行。

**Comment by yyzfish** [comment]
我看了一下out文件夹 里面并没有这个文件 查询了一下资料貌似是js的路径要设置还是什么的 我不太懂😂

**Comment by tangly1024** [comment]
问题已经定位，参考[feature_html_export](https://github.com/tangly1024/NotionNext/pull/121/files)分支的代码改动；需要改动这几处配置后才可以实现完全的静态html导出。

1.next.config.js 的exportPathMap、images两处
2./article/[slug] 的fallback要为false。静态的html[不支持动态增加文章](https://nextjs.org/docs/messages/ssg-fallback-true-export)

**Comment by tangly1024** [comment]
在这个分支里，我成功导出并运行了静态html版本的NotionNext，我觉得这是一个很有趣的尝试，打开了新世界的大门。
另外ipfs这个概念我第一次听说，似乎和web3.0还有些关系，有机会的话我研究研究~

**Comment by yyzfish** [comment]
经测试，已经可以正常使用，感谢

**Comment by yyzfish** [comment]
经测试，倘若从主页，即index访问可以正常打开文章，但是从url进去则无法访问如图
![image](https://user-images.githubusercontent.com/69407830/160516330-a7da3575-f1fd-4e68-9a2e-15baf25ee3ff.png)

**Comment by yyzfish** [comment]
是的 ipfs手web3的基础设施

**Comment by tangly1024** [comment]
> 经测试，倘若从主页，即index访问可以正常打开文章，但是从url进去则无法访问如图

我使用nginx测试的：
这种情况应该是服务器的限制，在url末尾加个.html 即可访问，或者利用nginx的tryfiles特性：
```
location / {
    try_files $uri $uri/ @rewrite;
}
location @rewrite {
    rewrite ^(.+)/$ $1.html permanent;
}
```

**Comment by yyzfish** [comment]
能否默认.html配置在index页面中（即index进入文章链接默认就有.html） 有点不太利于分享文章给别人

**Comment by tangly1024** [comment]
这样做就要改动到代码了，一种比较粗暴的做法是：
全局搜索`/article/${post.slug}` 并替换为 `/article/${post.slug}.html`

**Comment by yyzfish** [comment]
好的 谢谢

**Comment by yyzfish** [comment]
![image](https://user-images.githubusercontent.com/69407830/160523955-756c435b-44b7-4129-9a01-c555f025446e.png)
tu'p图片是否忘记增加在article目录

**Comment by tangly1024** [comment]
相对路径导致的。部分 图片用到了next/Image组件，导出静态后`/avatar.png`被解析成`avatar.png`，如下：

```
  <img alt="tangly1024" srcSet="avatar.png?imwidth=128 1x, avatar.png?imwidth=256 2x" src="avatar.png?imwidth=256" decoding="async" data-nimg="intrinsic" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%" class="rounded-full" loading="lazy"/>
```
解决方法：
- [简单]复制public/avatar.png 到 public/article/avatar.png

- [麻烦]修改<Image/>为<img/> ,可能要适配一下样式

**Comment by yyzfish** [comment]
好的

**Comment by yyzfish** [comment]
![image](https://user-images.githubusercontent.com/69407830/160548952-8013be46-523b-4dcc-b470-832a1d1c358a.png)
按照之前的方法，如下，遇到如图上的错误

> 这样做就要改动到代码了，一种比较粗暴的做法是： 全局搜索`/article/${post.slug}` 并替换为 `/article/${post.slug}.html`

**Comment by yyzfish** [comment]
大佬，有时间看一下哦

**Comment by yyzfish** [comment]
改了代码以后是可以正常显示的，“/article/xx -> /article/xx.html”唯一就是会出现找不到那个json文件的情况

**Comment by tangly1024** [comment]
> 改了代码以后是可以正常显示的 ... 唯一就是会出现找不到那个json文件的情况

待我重现一下这个bug

**Comment by yyzfish** [comment]
好的 大佬请喝茶

**Comment by tangly1024** [comment]
- 问题确实存在况：
原因类似之前的图片bug：next框架的组件特性导致：
NextJS框架会在页面显示后，或鼠标指向超链接时预读取JSON格式的文章数据；
由于将地址改为/article/xx.html 导致预加载json的路径错误。（变成了 `data/xx/article/example-1.html.json` ，正确应该是`data/xx/article/example-1.json`)

- 问题的影响：
这个问题不会影响页面的正常访问，仅导致页面的预加载失败，不过在纯静态的模式下，预加载数据的意义其实并不大。

- 解决的方法：
暂时无解😂
