### ISSUE TITLE
[部署报错] 使用vps部署3.16.0后报错

### ISSUE THREAD

**Issue by Qiup7664** [tangly1024/NotionNext#1201]
**描述bug**
使用vps部署3.16.0版本，会报错

**复现步骤**
yarn start 后网页部署成功，点击其他页面，网页502

**期望的正常结果**
报错显示是Next/Router的相关问题

**截图**
![aab64d559fded90a2899924c457268f](https://github.com/tangly1024/NotionNext/assets/56213419/2d3a9c2f-d216-4915-a259-6fb9f73c5e5f)
**环境**

- 操作系统: windows
- 浏览器 chrome
- NotionNext版本 3.16.0

**补充说明**

**Comment by Qiup7664** [comment]
可以正常使用3.15.2

**Comment by tangly1024** [comment]
bug源自nextJs框架

https://nextjs.org/docs/app/api-reference/functions/use-router

我将尽快修复此问题
