### ISSUE TITLE
[如何修改菜单] 菜单中的超链接地址如何修改

### ISSUE THREAD

**Issue by githubyangkai** [tangly1024/NotionNext#1209]
**描述bug**
简单说明bug的现象、相关的错误提示、日志等

**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
相关的页面，应该的结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- NotionNext版本 [e.g. 3.13.6]
- 主题 [例如. hexo]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
https://docs.tangly1024.com/article/notion-next-secondary-menu


链接在slug修改

**Comment by githubyangkai** [comment]
非常感谢您百忙之中抽出时间帮我解答疑难，之前的slug已经修改过了，一直没有生效，后来Redeploy解决了。在此非常感谢😘😘😘😘
但是我现在还有个小小的疑问，就是之前点击”关于我“就会跳转到您的博客，现在我想让他点击后打开一页是关于我写的介绍，我把这页改成下面这样了
[image: image.png]
但是，结果是404
[image: image.png]
我想请教一下哪里错了，以及我该怎么做🤔🤔
其实我想要的效果就是像留言板这样就好了，可以有这样的一个页面
[image: image.png]


如果您有时间看到的话，万分感谢😘😘😘

tangly1024 ***@***.***> 于2023年6月28日周三 10:27写道：

**Comment by githubyangkai** [comment]
我知道怎么修改了，非常抱歉打扰你😊😊😊😊
