### ISSUE TITLE
[日期格式] 文章上方date格式统一的建议

### ISSUE THREAD

**Issue by jimmyhuang22** [tangly1024/NotionNext#1215]
**为什么提出这个新的特性改动**
date格式统一感觉看着更舒服一些

**描述一下你推荐的解决方案**

**描述一下你考虑过的其它替代解决方案**

**补充说明**
![sfasfasfa](https://github.com/tangly1024/NotionNext/assets/52233941/96f419f8-9702-42ef-8e00-a3a6048f0006)

**Comment by tangly1024** [comment]
很好的建议，感谢！
