### ISSUE TITLE
关于访问/xxx/会被重定向到/xxx的问题

### ISSUE THREAD

**Issue by 821869798** [tangly1024/NotionNext#1216]
**描述遇到的问题**
想请教下，怎么样不让/xxx/重定向到/xxx，已经修改了vercel.json中的trailingSlash，但是没用，会显示重定向过多的错误。
我想加一些gitbook页面，但是里面加载css都是使用相对html文件的路径，然后会导致加载路径不对。

**相应配置**
网站链接
`https://bfgame.eu.org/book` 
vercel.json
```json
{
  "cleanUrls": true,
  "trailingSlash": true,
  "headers": []
}

```

**截图**

**环境**
- 操作系统:  windows
- 浏览器 edge

**Comment by tangly1024** [comment]
我不太理解你说的问题，请具体描述一下场景，预期效果、实际效果。
目前已知：
背景
> 我想加一些gitbook页面

操作
> 已经修改了vercel.json中的trailingSlash，但是没用，会显示重定向过多的错误。
> {
  "cleanUrls": true,
  "trailingSlash": true,
  "headers": []
}

实际
> https://bfgame.eu.org/book 会跳到 https://bfgame.eu.org/book/

问题
> 但是里面加载css都是使用相对html文件的路径，然后会导致加载路径不对。

**Comment by 821869798** [comment]
我在public目录中放了一个books目录，里面放了一些gitbook的静态页面，目录结构如下。

-- public
&emsp;-- books
&emsp;&emsp;-- gitbook1
&emsp;&emsp;&emsp;-- index.html
&emsp;&emsp;&emsp;-- ebook.css
---
当我访问 `/books/gitbook1/`时会被重定向到`/books/gitbook1`，但是index.html中的加载css的路径写的是`<link rel="stylesheet" href="ebook.css">` ，结果导致加载ebook.css的路径变成了`/books/ebook.css`，但是实际的css文件路径如上面的目录结构所示，应该是`/books/gitbook1/ebook.css` 
我预期效果是能够正确访问到ebook.css文件

**Comment by 821869798** [comment]
我现在通过next.js上同样issue的实验配置关闭的/的重定向，暂时解决了这个问题。
想问问有没有更好的解决方案，不太懂前端技术。
https://github.com/vercel/next.js/discussions/23988#discussioncomment-4213430

**Comment by tangly1024** [comment]
你是指 skipTrailingSlashRedirect: true, 这项配置吗？

目前这是最好的解决方案了

**Comment by 821869798** [comment]
是的，感觉解答。
