### ISSUE TITLE
目录条

### ISSUE THREAD

**Issue by klzxuanye** [tangly1024/NotionNext#122]
你好，我的目录条太长了，只有拖到最下面才能看到完整的目录，能不能给目录条加个滚动条
![image](https://user-images.githubusercontent.com/101911388/160522808-8312986a-a556-46fb-8533-e125ba1b5187.png)

**Comment by tangly1024** [comment]
可以加

安排😎

**Comment by tangly1024** [comment]
预览地址：
https://preview.tangly1024.com/article/example-1
