### ISSUE TITLE
【代码下载】GitHub Desktop Error

### ISSUE THREAD

**Issue by misopurr** [tangly1024/NotionNext#1226]
fatal: git show-ref: bad ref refs/tags/v3.15 - Copy.2 (0000000000000000000000000000000000000000)
a835c56fec010a06ee259519c4d3031e217c1adb refs/tags/3.10.2
90db01ae90b6824d9b10417463c92e780315480a refs/tags/V1.0.0
6988de56b9363a200ce239ef59a6e16432549d59 refs/tags/V2.2.0
7cafa1d4a491967afae115adbd58a008d2f0d678 refs/tags/V3.3.0
ad32f1e4664a253eb40102d57cfc6992752b1942 refs/tags/V3.3.4
eea28a32a916a9cdc9c06529a256f5750030d63d refs/tags/V3.4.5
246ae4fa6df60159a3c45fbb669ffb71f5f39d6e refs/tags/v.3.13.1
a97517de6797d111799dca7ffe76c61bf48bb358 refs/tags/v.3.13.3
e430d55cf8fa144028d2f0fb457d0afbf0f4a062 refs/tags/v1.0.0
a98f2fb67fcb1ebbfd194c9e060168780e2d84a6 refs/tags/v1.1.0
8f543ab0e70871074a7114fd45241c27b15636de refs/tags/v1.2.0
9f7ed83d023ab52f5fa4c5fe5cc6b730dbe05fb9 refs/tags/v2.3.0
90db01ae90b6824d9b10417463c92e780315480a refs/tags/v2.4.0
53659819f788efa00df9406fcbf5aa4d5512ef61 refs/tags/v2.5.0
1c3694c06e04fff258f42e30cfbd02b9dc070612 refs/tags/v2.6.0
1810de59f6b72892364c2ac0d82ce866fc05ba16 refs/tags/v2.7.0
7396f18a272cf7d7dc0365d6d941932a7861499d refs/tags/v2.7.1
c47eef875a9d2b37236bc5be463d3195bc90f475 refs/tags/v2.8.0
86c42aedc47544ef309b0ce8e7b64a6003652ae0 refs/tags/v2.8.1
63eaf71776d0cb4f518a1aa50548c20140d3ec06 refs/tags/v2.8.2
69070ebbcabd4355d0d21a328458e81509c9bb6e refs/tags/v2.8.3
69070ebbcabd4355d0d21a328458e81509c9bb6e refs/tags/v2.8.4
373017f8304e96c08dd478a40f938332ab8447c3 refs/tags/v2.9.0
d95b535352c85fabdd7ba8b187a78ca8d44c8423 refs/tags/v2.9.1
91d50dc91410a853e8470a5afaf685e7354ac368 refs/tags/v3.0.0
82a4c73910c26ac632c63e8151d9b49b26a21060 refs/tags/v3.1.0
05618cd755334450a580b275f97eb6f4ab808ea6 refs/tags/v3.10.0
87e4b2cb24508d8b33d16dfbbe7f1961400dba5a refs/tags/v3.11.0
42ef2ad566c9bac8989302840ab127c70c96fc06 refs/tags/v3.12.0
480aa28b21a44124946236377a55225967525a76 refs/tags/v3.12.1
cec38ebb8e21a859d089aa6c779b4db30d191de7 refs/tags/v3.12.2
97363a6aca01d10e636f81f5d28c47f81c9736a4 refs/tags/v3.12.3
bd5ddd30dfdf1ed643c72b029456e257ee68925a refs/tags/v3.12.4
f841e7b3e1b81b9f77efc4ab8603de86b3d2b5de refs/tags/v3.13.0
a09ce9f63037d318e0c6a1d893044de745983097 refs/tags/v3.13.2
b567cf4821cecebb34c76bc41d544b682e9637d4 refs/tags/v3.13.4
182834d3849b780e17cbe9cf0a76840220fbedbe refs/tags/v3.13.5
6357aa8cd1d544a5082b61d8cb5e16adfada75d6 refs/tags/v3.13.6
c6c7b095e6510702109edbf1b324782d2af37db9 refs/tags/v3.14.0

**Comment by tangly1024** [comment]
不太明白您的问题，但是我建议可以重新clone代码。
