### ISSUE TITLE
[Gitbook主题] 没有按照相同标签进行整理排序

### ISSUE THREAD

**Issue by RedhairHambagu** [tangly1024/NotionNext#1229]
**描述bug**
该主题下 标签会重复，且只能显示部分文章。

**复现步骤**
https://www.tangly1024.com/about?theme=gitbook

**期望的正常结果**
无重复标签，且显示对应全部文章

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/129669334/4ddb99be-4202-4c65-8b0d-2182c61f576f)

**环境**

- 操作系统: macOS
- 浏览器: chrome
- NotionNext版本: 3.16.3
- 主题 Gitbook

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
设计如此的，需要手动在notion中将分类相同的文章排序：

参考 https://docs.tangly1024.com/article/notionnext-gitbook

这个主题通常在专栏或教程文档中使用，需要作者按照整本书的目录排列好文章。通常不适用于普通博客的写作排序

**Comment by vvfgg** [comment]
时间也需要改，不然也是分离的
