### ISSUE TITLE
使用access token提示401通过curl测试access token没有问题

### ISSUE THREAD

**Issue by sunnoy** [tangly1024/NotionNext#125]
![image](https://user-images.githubusercontent.com/19342276/160547487-af94a95e-40c4-4cd4-b507-b0c6366d99d3.png)

curl 'https://api.notion.com/v1/databases/xxxxx' \
  -H 'Authorization: Bearer 'xxxx'' \
  -H 'Notion-Version: 2022-02-22'

这个可以请求到

**Comment by sunnoy** [comment]
还有一个问题是 文章内有子页面的时候是不会渲染的是吧

**Comment by tangly1024** [comment]
> 还有一个问题是 文章内有子页面的时候是不会渲染的是吧

不会被渲染。除非是一个引用页面，会被渲染成一个超链接。
<img width="281" alt="image" src="https://user-images.githubusercontent.com/15920488/160571819-0b468027-7060-409c-8f85-2e2800b10044.png">

**Comment by tangly1024** [comment]
> curl 'https://api.notion.com/v1/databases/xxxxx' -H 'Authorization: Bearer 'xxxx'' -H 'Notion-Version: 2022-02-22'
> 
> 这个可以请求到

应该是ACCESS_TOKEN错误，检查一下配置
1.在Vercel的环境变量中正确配置：NOTION_ACCESS_TOKEN 变量。
2. ACCESS_TOKEN的获取方式：访问notion.so网站，在cookies中获取`token_v2`，通常是一个156位的字符串。

**Comment by sunnoy** [comment]
我试一下 但是最版构建报错了

**Comment by tangly1024** [comment]
可能是新版本合并时代码冲突了，现在构建情况如何啦
