### ISSUE TITLE
[禁止复制] 希望新增防止复制的功能

### ISSUE THREAD

**Issue by yyzfish** [tangly1024/NotionNext#1266]
**为什么提出这个新的特性改动**
不想自己辛辛苦苦写的内容，被板砖了

**描述一下你推荐的解决方案**
应该蛮多这种方案的把，nextjs

**Comment by tangly1024** [comment]
感谢 @LooseLi  ❤❤

**Comment by LooseLi** [comment]
> 

在Vercel后台配置NEXT_PUBLIC_CAN_COPY变量为false即可防止复制。pc端配合NEXT_PUBLIC_CUSTOM_RIGHT_CLICK_CONTEXT_MENU变量为true效果更佳！
