### ISSUE TITLE
最新的更改无法fetch upstream，显示有冲突

### ISSUE THREAD

**Issue by eliaszon** [tangly1024/NotionNext#128]
![image](https://user-images.githubusercontent.com/73749474/160841283-d10c9b69-5c34-4cc5-92af-1ba66d2c1867.png)

**Comment by tangly1024** [comment]
近期版本改动范围比较大，导致很多地方可能同时编辑导致了冲突，尤其是blog.config.js有做变化。
>[ V2.9.0](https://github.com/tangly1024/NotionNext/releases/tag/v2.9.0) :网站标题、封面图和描述将读取Notion中的数据。

冲突需要手动解决一下，与你的代码进行合并，这里的方法也挺多种：
1. 直接点击这里的Open pull request， 将我的代码内容分支合并到你的仓库中，一一对比差异后进行resolve。
2. 又或者你可以备份一下自己的blog.config.js 等修改过的文件。然后重新fork我的仓库，再用备份的文件进行替换处理。

**Comment by eliaszon** [comment]
好的大佬，已经采用方法二了😂
