### ISSUE TITLE
HEXO主题下标签tag显示错误

### ISSUE THREAD

**Issue by Brookocola** [tangly1024/NotionNext#1293]
**描述bug**
在HEXO主题下,单击某个标签时,显示为#undefined

**复现步骤**
在HEXO主题博客中,单击某个标签后,页面左上角将显示为#undefined

**期望的正常结果**
页面左上角应显示为所单击的标签名称

**截图**
此处应显示为所单击的标签名称
![image](https://github.com/tangly1024/NotionNext/assets/77874674/c8e8ffcc-9349-454f-9bc5-4c03739f8844)

**环境**

- 操作系统: windows
- 浏览器: chrome
- NotionNext版本: 4.0.1
- 主题: hexo

**Comment by tangly1024** [comment]
感谢反馈，bug已修复
