### ISSUE TITLE
Heo Mobile DarkMode catalog Bug

### ISSUE THREAD

**Issue by Mossworm** [tangly1024/NotionNext#1296]
**描述bug**
在手机暗色模式下，目录背景颜色不变

**复现步骤**
在暗色模式下以手机分辨率查看 Heo 主题的目录时出现这种情况

**期望的正常结果**
背景应该变暗

**截图**
相关的页面
![image](https://github.com/tangly1024/NotionNext/assets/55495046/da1ee021-4e1c-4d94-b440-f77f0b2dcd9f)

**环境**

- 操作系统: [Android, windows]
- 浏览器 [chrome]
- NotionNext版本 [4.02]
- 主题 [heo]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
感谢反馈，bug已修复，更新即可 https://github.com/tangly1024/NotionNext/commit/c83cd9d2cda0ee0ded6a4ccff17a57a461a803e6
