### ISSUE TITLE
Hexo主题下font awesome图标无法显示

### ISSUE THREAD

**Issue by LooseLi** [tangly1024/NotionNext#1298]
**描述bug**
Hexo主题下，自定义二级菜单时，Font Awesome图标无法正常显示

**复现步骤**
Hexo主题下，自定义二级菜单时，Font Awesome图标无法正常显示

**期望的正常结果**
Hexo主题下，应该正常显示icon图标

**截图**
<img width="1003" alt="image" src="https://github.com/tangly1024/NotionNext/assets/66111974/83f61d6b-b1bf-4527-9fb7-4a0e476480d3">
<img width="1546" alt="image" src="https://github.com/tangly1024/NotionNext/assets/66111974/6c809c48-64de-48a3-84eb-03eb477f3ea4">
<img width="1512" alt="image" src="https://github.com/tangly1024/NotionNext/assets/66111974/69b94eac-a5c6-417b-a30c-c3858695edbc">

**环境**

- 操作系统: macOS
- 浏览器 chrome
- NotionNext版本 4.0.2
- 主题 hexo

**补充说明**
与问题相关的其它说明

**Comment by tanglyqq** [comment]
感谢反馈,bug已修复，原因是配置文件的变量名冲突。

请更新代码，并重新检查后台环境变量,NEXT_PUBLIC_FONT_AWESOME_PATH 这个变量的值不能为false

```javascript
 FONT_AWESOME: process.env.NEXT_PUBLIC_FONT_AWESOME_PATH || 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css', // font-awesome 字体图标地址; 可选 /css/all.min.css ， https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/font-awesome/6.0.0/css/all.min.css

 CUSTOM_RIGHT_CLICK_CONTEXT_MENU: process.env.NEXT_PUBLIC_CUSTOM_RIGHT_CLICK_CONTEXT_MENU || true, // 自定义右键菜单，覆盖系统菜单
```

**Comment by tangly1024** [comment]
相关代码 https://github.com/tangly1024/NotionNext/commit/175fc852a53f66576a62dd2ca03e1a03dd4be5ad

**Comment by LooseLi** [comment]
> 感谢反馈,bug已修复，原因是配置文件的变量名冲突。
> 
> 请更新代码，并重新检查后台环境变量,NEXT_PUBLIC_FONT_AWESOME_PATH 这个变量的值不能为false
> 
> ```js
>  FONT_AWESOME: process.env.NEXT_PUBLIC_FONT_AWESOME_PATH || 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css', // font-awesome 字体图标地址; 可选 /css/all.min.css ， https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/font-awesome/6.0.0/css/all.min.css
> 
>  CUSTOM_RIGHT_CLICK_CONTEXT_MENU: process.env.NEXT_PUBLIC_CUSTOM_RIGHT_CLICK_CONTEXT_MENU || true, // 自定义右键菜单，覆盖系统菜单
> ```

非常完美，感谢fix！
