### ISSUE TITLE
【bug】heo主题在配置里关闭切换主题，却依然还能切换主题

### ISSUE THREAD

**Issue by Bashir-1** [tangly1024/NotionNext#1305]
**描述bug**
heo主题在配置里关闭切换主题，却依然还能切换主题

**复现步骤**
在“blog.config.js”中，将切换主题选项关闭后，却依然在heo主题中依然显示切换主题按钮

**期望的正常结果**
不应该出现切换主题按钮

**截图**
![image1](https://github.com/tangly1024/NotionNext/assets/120711536/c0d55688-ad14-4355-b9c5-a966b9b30094)
![image2](https://github.com/tangly1024/NotionNext/assets/120711536/f09cac69-eb49-4022-91be-80a7b60c5952)

**环境**

- NotionNext版本 4.0.3
- 主题 [例如. heo]

**补充说明**

**Comment by jxpeng98** [comment]
这是因为自定义右键菜单还开着，你需要关掉这个：
blog.config 77-78行
```
  CUSTOM_RIGHT_CLICK_CONTEXT_MENU: process.env.NEXT_PUBLIC_CUSTOM_RIGHT_CLICK_CONTEXT_MENU || false, // 自定义右键菜单，覆盖系统菜单
```

**Comment by Bashir-1** [comment]
> 这是因为自定义右键菜单还开着，你需要关掉这个： blog.config 77-78行
> 
> ```
>   CUSTOM_RIGHT_CLICK_CONTEXT_MENU: process.env.NEXT_PUBLIC_CUSTOM_RIGHT_CLICK_CONTEXT_MENU || false, // 自定义右键菜单，覆盖系统菜单
> ```

好的，谢谢！已找到配置。
