### ISSUE TITLE
[自定义字体] 4.0.3版本无法渲染自定义字体

### ISSUE THREAD

**Issue by happyzhangyyds** [tangly1024/NotionNext#1310]
**描述bug**
在v4.0.3版本中，无法渲染自定义字体，以霞鹜文楷为例，使用git回退到v4.0.2版本则可以正常渲染

**复现步骤**
当使用vscode对最新的代码进行合并的时候，一切都很顺利，但是自定义字体出现了问题，在尝试很多方法修改blog.js文件时，发现对自定义字体的改动始终无法生效。于是使用git回退到旧版本中，发现同样的配置在v4.0.2之前可以生效。

**期望的正常结果**
期望自定义字体可以正常适配新版本

**截图**
v4.0.3自定义字体（不生效）配置截图
![截屏2023-07-23 16 09 43](https://github.com/tangly1024/NotionNext/assets/119606309/337f4394-0040-4866-a351-ac540519ec04)

v4.0.2自定义字体（生效）配置截图
![截屏2023-07-23 16 11 56](https://github.com/tangly1024/NotionNext/assets/119606309/397e93cb-1d41-4250-be86-1ec9b65d7d81)

**环境**

- 操作系统: [macOS]
- 浏览器 [safari]
- NotionNext版本 [e.g. 4.0.3]
- 主题 [例如. medium]

**补充说明**
如果能在notionnext的指导手册中详细说明自定义字体配置的执行逻辑也许会更加便于理解和帮助解决问题，幸苦作者大大了，比心♥️！

**Comment by jxpeng98** [comment]
#1312 我试了一下，在commonhead里边，把这个改了就行了。

**Comment by tangly1024** [comment]
4.0.3版本中的bug，在最新版中已经修复

**Comment by tangly1024** [comment]
目前字体文件统一在 pages/_document.js中处理，相关代码：

```javascript
  <Head>
  <link rel='icon' href= {`${BLOG.BLOG_FAVICON}`} />
    <CommonScript />

    {/* 预加载字体 */}

    {BLOG.FONT_AWESOME && <>
        <link rel='preload' href={BLOG.FONT_AWESOME} as="style" crossOrigin="anonymous" />
        <link rel="stylesheet" href={BLOG.FONT_AWESOME} crossOrigin="anonymous" referrerPolicy="no-referrer" />
    </>}

    {BLOG.FONT_URL?.map((fontUrl, index) => {
      if (fontUrl.endsWith('.css')) {
        return <link key={index} rel="stylesheet" href={fontUrl} />
      } else {
        return <link key={index} rel="preload" href={fontUrl} as="font" type="font/woff2" />
      }
    })}

  </Head>
···
