### ISSUE TITLE
[切换主题失败] Abort fetching component for route '/'

### ISSUE THREAD

**Issue by Liboq** [tangly1024/NotionNext#1317]
**描述bug**
简单说明bug的现象、相关的错误提示、日志等
![image](https://github.com/tangly1024/NotionNext/assets/99778162/002e143a-f875-4100-869b-b9fcd01bd246)
![image](https://github.com/tangly1024/NotionNext/assets/99778162/81d7a433-3b37-4548-8e56-6ec66eca024c)

**复现步骤**
出现这个bug的操作步骤
点击小动物，主题切换，然后点击文章，找不到相应的路由
**期望的正常结果**
希望按这个步骤，正常操作结果是什么
正常显示文章
**截图**
相关的页面，应该的结果
![image](https://github.com/tangly1024/NotionNext/assets/99778162/f14ab9ef-5d6e-41d2-8089-8c38a0e8ddba)

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]windows
- 浏览器 [例如. chrome, safari, firefox]chrome
- NotionNext版本 [e.g. 3.13.6] 最新
- 主题 [例如. hexo] hexo

**补充说明**
我可以试着解决

**Comment by tangly1024** [comment]
代码业务流程：
1. 点击宠物挂件
2. 网页会切换主题文件
3. 根据目前页面路由获取对应的组件代码
4. 目前路由 '/' ，所以会从服务端获取首页组件
5. 报错 Abort fetching component for route: '/' 意思是获取首页在另一个主题下的组件时被中断
6. 可能是网络问题

我尝试在您的页面上重复此流程，没有出现对应错误

```
点击小动物，主题切换，然后点击文章，找不到相应的路由
```

**Comment by Liboq** [comment]
不好意思，我可能没有说清楚，你可以试下点击三次小动物，然后点击进入一篇文章，你会发现会出现这个问题

**Comment by Liboq** [comment]
`https://www.pikachu1024.com/article/fun-not-return?theme=next,medium&theme=next&theme=medium`
![image](https://github.com/tangly1024/NotionNext/assets/99778162/b52ef3ef-efbf-49e4-a7ec-ee86721e002b)
我发现第一个theme是这个就会加载不到路由
