### ISSUE TITLE
【缓存问题】删除tag不生效

### ISSUE THREAD

**Issue by Ghlerrix** [tangly1024/NotionNext#1322]
**描述bug**
当我在Notion中删除部分Tag之后，标签页面生效，但是具体到文章不会生效
![image](https://github.com/tangly1024/NotionNext/assets/114851291/97ae0067-ce9b-4035-8837-b1c7ab6268b4)

**复现步骤**
在Notion上删除Tag或者修改Tag

**期望的正常结果**
所有的Tag均修改正常

**环境**

- 操作系统: [windows]
- 浏览器 [chrome]
- NotionNext版本 [4.0.4]
- 主题 [all]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
每个页面有独立缓存，刷新清缓存

**Comment by Ghlerrix** [comment]
我已经浏览器全部时间的缓存清除

**Comment by Ghlerrix** [comment]
![image](https://github.com/tangly1024/NotionNext/assets/114851291/b159c008-e584-45f6-a265-171710854f32)

**Comment by Ghlerrix** [comment]
已找到解决方案。
在Notion上删除所有tags 重新添加即可
