### ISSUE TITLE
QQ分享不可用

### ISSUE THREAD

**Issue by Liboq** [tangly1024/NotionNext#1332]
**描述bug**
QQ分享不可用，点击无效
**复现步骤**
点击QQ不可用
**期望的正常结果**
正常跳转
**截图**
![image](https://github.com/tangly1024/NotionNext/assets/99778162/26b4fd8b-90be-4178-aabe-62fb3a4af834)
**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]windows
- 浏览器 [例如. chrome, safari, firefox]chrome
- NotionNext版本 [e.g. 3.13.6]最新
- 主题 [例如. hexo]hexo

**补充说明**
与问题相关的其它说明

**Comment by tanglyqq** [comment]
创建PR https://github.com/tangly1024/NotionNext/compare
https://www.freecodecamp.org/chinese/news/how-to-make-your-first-pull-request-on-github/

**Comment by Liboq** [comment]
大佬，我提交这么多，你是可以只选择最后一个的吗，我不知道怎么只提交一个commit😥




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tangly1024/NotionNext"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月24日(星期一) 下午5:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tangly1024/NotionNext] QQ分享不可用 (Issue #1332)





 
创建PR https://github.com/tangly1024/NotionNext/compare
 https://www.freecodecamp.org/chinese/news/how-to-make-your-first-pull-request-on-github/

**Comment by tangly1024** [comment]
1. 推荐是创建一个新分支，专门只改动这个功能的代码，然后用这个新分支合并。
2. 不太推荐、但也可以，你直接发起pr，我会从你的代码请求中手动摘录需要的代码。不过需要你额外在pr中备注有用的代码部分

**Comment by tangly1024** [comment]
已修复
