### ISSUE TITLE
主题设置好像还是有些问题

### ISSUE THREAD

**Issue by NowScott** [tangly1024/NotionNext#1339]
**描述bug**
我是在vercel的环境变量中设置的，无论我设置为哪个，都会显示为同一个主题（重新部署过）
然后这个默认的主题中的两个按钮好像没对齐
<img width="611" alt="截屏2023-07-25 00 59 28" src="https://github.com/tangly1024/NotionNext/assets/86339284/65c16414-7fa1-4124-9e20-1847b3cc4c2f">

**期望的正常结果**
正常的结果就应该是我设置完一进去就是设置的哪个主题

**环境**
- 操作系统: macOS
- 浏览器 chrome
- NotionNext版本 4.0.5.
- 主题 gitbook

**Comment by happyzhangyyds** [comment]
试着在blog.js文件里修改主题呢，里面有切换主题的配置

**Comment by tangly1024** [comment]
1. 再次检查NEXT_PUBLIC_THEME 
2. Redploy的时候，不要勾选 Use existing Build Cache

3. 按钮不对齐的问题我将提交补丁修复
