### ISSUE TITLE
heo 支持最后更新时间显示

### ISSUE THREAD

**Issue by youngxhui** [tangly1024/NotionNext#1350]
**为什么提出这个新的特性改动**

对于博客来说，最后更新时间是一个很重要的属性，可以让读者了解到当前博客内的内容是否可以继续使用与现在。

**描述一下你推荐的解决方案**

新增一个 modify 字段，用于填写最后更新日期

**Comment by Synchronized1** [comment]
gitbook主题显示的last update为发布时间,能否修复这个小bug
或者直接使用notion的last edited time 作为 页面的last update
![image](https://github.com/tangly1024/NotionNext/assets/58451554/ebe53391-0124-4d56-809a-e79d64a2e6be)
