### ISSUE TITLE
【博客】ALGOLIA使用教程

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#1365]
**为什么提出这个新的特性改动**
博客的搜索速度太慢了，ALGOLIA速度快很多，作者也是使用的ALGOLIA服务。我想问一下作者的博客可以更新一版ALGOLIA搜索的使用教程吗？

**描述一下你推荐的解决方案**
简要说明你的解决方案建议，例如，『Giscus评论插件功能更加强大，用户只需留言既可在你的邮箱收到通知。。。』

**描述一下你考虑过的其它替代解决方案**
简要说明你所有想过的有可能解决此问题的方案。

**补充说明**
补充与此特性相关的内容

**Comment by tangly1024** [comment]
可以的，安排

**Comment by tangly1024** [comment]
https://docs.tangly1024.com/article/notion-next-algolia

文档更新地址
