### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by ApolloDPP** [tangly1024/NotionNext#1366]
**描述遇到的问题**
简单说明你遇到的问题，相关的日志、错误信息

**相应配置**
相关的配置，例如notion_page_id；你的网站地址

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**Comment by ApolloDPP** [comment]
notion的写作模板在哪可以duplicate

**Comment by happyzhangyyds** [comment]
在作者的博客可以进行具体查看

**Comment by tangly1024** [comment]
https://docs.tangly1024.com/article/vercel-deploy-notion-next
