### ISSUE TITLE
[Next主题] 样式一点小问题

### ISSUE THREAD

**Issue by NowScott** [tangly1024/NotionNext#1379]
**描述bug**
Next主题，翻页按钮的向前翻页上面缺少了一个横。

**截图**
以下是鼠标分别放在向前翻页、1、2、向后翻页上时的图片
<img width="184" alt="向前翻页" src="https://github.com/tangly1024/NotionNext/assets/86339284/9d1d1e17-3940-4087-9048-71ab53ce070e"><img width="186" alt="1" src="https://github.com/tangly1024/NotionNext/assets/86339284/392b2fd1-26f2-41ce-965c-acc3d203229f">
<img width="144" alt="2" src="https://github.com/tangly1024/NotionNext/assets/86339284/9ad244e3-1b30-4466-807f-3c95d6867cd1"><img width="199" alt="向后翻页" src="https://github.com/tangly1024/NotionNext/assets/86339284/2a7677a9-3aa5-42da-b936-ae54fdbfa0af">

**环境**

- 操作系统: macOS
- 浏览器 chrome
- NotionNext版本 4.0.8
- 主题 next

**Comment by tangly1024** [comment]
补丁已提交 https://github.com/tangly1024/NotionNext/commit/587ba56e244302d461c51b5979991bf3cfe85b68
