### ISSUE TITLE
更新后在 Vercel 上部署时出现问题

### ISSUE THREAD

**Issue by BJTiew** [tangly1024/NotionNext#1400]
**描述遇到的问题**
首先，我用 NotionNext 在 Vercel 上部署了两个网站（A与B）。
有小段时间没更新。昨晚更新到最新版本后，A网站没问题，B网站部署失败。

在 vercel 上部署B网站出些下列问题：-
[[101710.555].txt](https://github.com/tangly1024/NotionNext/files/12246367/101710.555.txt)

TypeError: Cannot destructure property 'auth' of 'urlObj' as it is null.
然后就部署失败了。

然后我尝试在 vercel 上再次重新部署 B（用同样的 Notion ID，但全新的部署），一样也失败了。

**相应配置**
网站地址：https://www.eliteworld.top/
Notion ID：e6a6a7d4372e40e48362d8f8debc9ec6

**截图**
无截图，有部署失败的文档。

**环境**

- 操作系统: [windows 11]
- 浏览器 [edge]
- 版本 [最新]

[[101710.555].txt](https://github.com/tangly1024/NotionNext/files/12246367/101710.555.txt)

**Comment by BJTiew** [comment]
已经解决，谢谢

**Comment by yancyuu** [comment]
咋解决的

**Comment by BJTiew** [comment]
> 咋解决的

我经过多次试错后，发现问题出在 notion database 里的日期设定。在一个个手动重新输入日期后，一切都恢复正常了。
