### ISSUE TITLE
heo主题默认search结果不显示文章summary

### ISSUE THREAD

**Issue by B3nDan** [tangly1024/NotionNext#1403]
**描述bug**
heo主题默认search结果不显示文章summary

**复现步骤**
去search也随便搜一个文章

**期望的正常结果**
和主页文章列表一样，显示summary

**截图**
![Screenshot_20230803_152247](https://github.com/tangly1024/NotionNext/assets/129975925/dffd6627-5dc9-4049-bb57-080a1c8a51a6)
![Screenshot_20230803_152159](https://github.com/tangly1024/NotionNext/assets/129975925/8df02d97-b70d-40e0-a273-e9f78a972f18)
![Screenshot_20230803_152234](https://github.com/tangly1024/NotionNext/assets/129975925/68d60069-dda1-4322-8c00-dab11d7c7525)

**环境**

- 操作系统: [iOS, Android, macOS, windows]
- 浏览器 [chrome, safari, firefox,edge,brave]
- NotionNext版本 [4.0.11]
- 主题 [heo]

**补充说明**
在测试这个问题的时候
我还去您的站点
preview.tangly1024.com
Blog.tangly1024.com
但是发现您的俩站点默认search无法搜索（点击搜索在很短的时间显示404，然后回到搜索界面）

**Comment by tangly1024** [comment]
Bug已修复
对于补充说明的解释：我的站点关闭了搜索，只使用 algolia
