### ISSUE TITLE
[获取不到notion的文章]  pull代码后获取不到文章

### ISSUE THREAD

**Issue by Liboq** [tangly1024/NotionNext#1404]
**描述bug**
![image](https://github.com/tangly1024/NotionNext/assets/99778162/0270d467-4d19-4c85-ae2f-8652ad0cea06)

**复现步骤**
今天pull代码后，发现获取不到 notion的文章 
notion 地址 https://pikachu1024.notion.site/c642617a38d8433aba9b3c76919db8b1?v=526916851aa64f8eb671dc8b89e22cfd&pvs=4
![image](https://github.com/tangly1024/NotionNext/assets/99778162/f7e6d940-eb29-4fca-8944-6c08fe39f185)

**期望的正常结果**
获取到notion的文章 pikachu1024.com

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]windows
- 浏览器 [例如. chrome, safari, firefox]chrome
- NotionNext版本 [e.g. 3.13.6]latest
- 主题 [例如. hexo]hexo

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
感谢反馈，经确认是一个bug导致

**Comment by tangly1024** [comment]
https://github.com/tangly1024/NotionNext/pull/1416
