### ISSUE TITLE
支持分页吗

### ISSUE THREAD

**Issue by luckypoem** [tangly1024/NotionNext#1413]
**为什么提出这个新的特性改动**
简要说明此特性解决的问题，例如，『博客站点的读者互动性不够强，和读者无法建立紧密的联系...』

**描述一下你推荐的解决方案**
建议提供分页功能

**描述一下你考虑过的其它替代解决方案**
暂无其它替代解决方案

**补充说明**
如果不分页，看博客会很累

**Comment by tangly1024** [comment]
默认每页12条，超出会自动分页
https://github.com/tangly1024/NotionNext/blob/307dd428b58b0d04a090d74ebfefdd2408953f92/blog.config.js#L143


![图片](https://github.com/tangly1024/NotionNext/assets/15920488/863b69a2-fa19-4f4f-b8dc-b654fa1c6dfe)
