### ISSUE TITLE
[无法更新内容] 新文章首页不显示，归档和最新发布里面可看到

### ISSUE THREAD

**Issue by zs6** [tangly1024/NotionNext#1414]
**描述bug**

- 新发布的文章的的首页不显示，但是可以才归档和最新发布里面看到

**复现步骤**

- 新建一篇文章，首页不显示，但是可以才归档和最新发布里面看到。
- 这时候再新建一篇文章，就可以让前一篇无法正常显示的文章出现在首页。

**期望的正常结果**
首页正常显示

**截图**

- ![image](https://github.com/tangly1024/NotionNext/assets/45552564/7e89e669-eba5-45f2-8c7e-e40f4c98ef96)
- ![image](https://github.com/tangly1024/NotionNext/assets/45552564/52b260d6-a9d4-4ea4-b5d6-d867526a4491)

**环境**

- 操作系统: windows
- 浏览器 chrome
- NotionNext版本 4.0.11
- 主题 全部

**补充说明**

- 与问题相关的其它说明

**Comment by tangly1024** [comment]
用无痕模式打开网站试一下，也有可能是缓存导致。

另外有两个相似的issue反映的问题很类似。我提交了新代码，更新看一下


https://github.com/tangly1024/NotionNext/issues/1404

https://github.com/tangly1024/NotionNext/issues/1384

**Comment by zs6** [comment]
现在更新完，问题已经没有了
