### ISSUE TITLE
[Menu菜单用法]  Menu菜单要以/开头否则跳转路径出错

### ISSUE THREAD

**Issue by BJTiew** [tangly1024/NotionNext#1415]
**描述bug**
发现两个 BUG

BUG #1：目录结构限制 
=====
在 notion slug 里，如果设定为 ABC （母目录结构）或 ABC/DEF（母+子目录结构）都没有问题。但一旦使用 ABC/DEF/GHI （母+子+孙目录结构）或以上的话，GHI 或以上的页面是不会被渲染的，而是会回报 404 页面。

BUG #2：跳转错误
=====
首先，我设定了 menu 为 ABC 页面（完整网址为 localhost:3000/ABC） ，同时也在 notion database 里的 Category 里设定了 XYZ 标签。
在HEXO里（其他 theme 未测试） ，我先进路了首页（localhost:3000）。
如果我点击 ABC menu，则会正常跳转到 ABC 页 （localhost:3000/ABC）。
但如果我先点击 XYZ 标签跳转到 localhost:3000/category/XYZ,，然后才点击 ABC menu 的话，则会错误地跳到 localhost:3000/category/ABC （中间多了个 category）。

**复现步骤**
见上文

**期望的正常结果**
麻烦修复（尤其是第2个BUG）。

**截图**
无

**环境**

- 操作系统: [windows 11]
- 浏览器 [edge]
- NotionNext版本 [e.g. 4.().11]
- 主题 [hexo]

**补充说明**
无

**Comment by tangly1024** [comment]
![图片](https://github.com/tangly1024/NotionNext/assets/15920488/6b3c99bc-e458-49d9-a4eb-5101bebdecde)


Menu 要以  / 开头 ，表示绝对路径

例如 /tag ，你在任何页面点击该菜单，都会跳转到  https://xxx.com/tag 页面。
如果是 tag ，表示相对路径，在当前页面结尾拼上tag ， 例如 https://xxx.com/category 页面点击tag回跳到 https://xxx.com/category/tag

**Comment by tangly1024** [comment]
只支持二级url，不支持孙url
