### ISSUE TITLE
[Nobelium主题] 开发类似HEO主题的菜单

### ISSUE THREAD

**Issue by B3nDan** [tangly1024/NotionNext#1420]
**描述bug**

nobelium主题没有menu这个东西吗，就像heo主题那样

**复现步骤**
使用nobelium主题

**期望的正常结果**
和notion设定的menu一样

**截图**
注意红框部分
heo主题下
![image](https://github.com/tangly1024/NotionNext/assets/129975925/901565cc-5acb-414d-ab19-8474505498c9)

nobelium主题下
![image](https://github.com/tangly1024/NotionNext/assets/129975925/418241e6-a768-4533-903e-073f7283a90a)

**环境**

- 操作系统: [iOS, Android, macOS, windows]
- 浏览器 [chrome, safari, firefox]
- NotionNext版本 [最新版]
- 主题 [heo, nobelium]

**补充说明**
无

**Comment by tangly1024** [comment]
每个主题都是独立设计开发，没有必然联系
