### ISSUE TITLE
[ackee统计] 不起作用

### ISSUE THREAD

**Issue by B3nDan** [tangly1024/NotionNext#1435]
**描述bug**
两种方式分别部署ackee
没有作用
等待几个小时，也没反应

**复现步骤**
我看到commonscript里有预设ackeescript
但是被注释掉了
于是我把注释删了，并在config里配置三个环境变量。
正常部署，发现没作用后
我直接改成在commonscript里
写ackee的script代码
也没有作用。

**期望的正常结果**
我之前配置过
谷歌、baidu、微软、umami等统计工具
所以代码应该没有问题
也用gpt4检测过了
正常应该起作用的

**截图**
相关的页面，应该的结果

**环境**

- 操作系统:  iOS, Android, macOS, windows
- 浏览器 chrome, safari, firefox
- NotionNext版本 [最新版]
- 主题 [heo，nobelium，next]

**补充说明**
无

**Comment by tangly1024** [comment]
## 难倒我了
我不知道问题出在哪里，我的ackee目前是正常的。而我只是配置了三个环境变量、没有改动其它。
暂时没有更好的建议，不知道有没有人可以解答此问题；或者你可以尝试看看Ackee的后台有没有报错。


## 附一些信息：
刚检查了你的博客网页，一切运行正常，页面的访问数据正常地送到了你的ackee后台：
1. 网页的ackee脚本引入：一切正常
2. 调用ackee后端接口：一切正常，没有报错

## 现象
唯一的问题:  你的Ackee后台不显示统计结果数据
另外，Ackee统计的数据是实时显示的，没有延迟，因此也无需等待几个小时。

**Comment by B3nDan** [comment]
> ## 难倒我了
> 我不知道问题出在哪里，我的ackee目前是正常的。而我只是配置了三个环境变量、没有改动其它。 暂时没有更好的建议，不知道有没有人可以解答此问题；或者你可以尝试看看Ackee的后台有没有报错。
> 
> ## 附一些信息：
> 刚检查了你的博客网页，一切运行正常[https://blog.b3ndan.com/，页面的访问数据正常地送到了你的ackee后台。](https://blog.b3ndan.com/%EF%BC%8C%E9%A1%B5%E9%9D%A2%E7%9A%84%E8%AE%BF%E9%97%AE%E6%95%B0%E6%8D%AE%E6%AD%A3%E5%B8%B8%E5%9C%B0%E9%80%81%E5%88%B0%E4%BA%86%E4%BD%A0%E7%9A%84ackee%E5%90%8E%E5%8F%B0%E3%80%82)
> 
> 1. 网页的ackee脚本引入：一切正常
> 2. 调用ackee后端接口：一切正常，没有报错
> 
> ## 现象
> 唯一的问题: 你的Ackee后台不显示统计结果数据 另外，Ackee统计的数据是实时显示的，没有延迟，因此也无需等待几个小时。

刚才检查了一下，确实有了，很抱歉哈，比我想的慢好多，白天我刷新检查了半天都看不到数据。
