### ISSUE TITLE
[页面渲染] 不能渲染Latex Chemical Equation

### ISSUE THREAD

**Issue by e9965** [tangly1024/NotionNext#145]
![image](https://user-images.githubusercontent.com/63435466/161409700-09291d2f-c15b-4fac-9dd6-a1ce57e559bd.png)
![image](https://user-images.githubusercontent.com/63435466/161409701-e8fea4cc-1cfe-4f37-80ef-4de0ccd3fb43.png)

**Comment by tangly1024** [comment]
这是react-notion-x的bug，渲染化学方程式时，解析格式错误。
需要在这里[react-notion-x/issues/255](https://github.com/NotionX/react-notion-x/issues/255)下跟进，我也将关注这个问题

**Comment by tangly1024** [comment]
此项目使用Katex渲染公式。正如 [transitive-bullshit](https://github.com/transitive-bullshit) 所说，化学方程式([mhchem](https://mhchem.github.io/MathJax-mhchem/))属于扩展插件并没有默认支持。

> Hmmm, it looks like \ce and other chemistry-oriented latex features may not be included in katex by default. https://github.com/KaTeX/KaTeX/blob/b1311aff1bfeebd75df9389aadfba7a4a697b203/contrib/mhchem/README.md

同时在katex的react版本中，也有用户反馈过此问题[react-katex/issues/69](https://github.com/talyssonoc/react-katex/issues/69)。不过似乎没有得到解决。

现在的困难之处是，如何开启mhchem的支持。

**Comment by e9965** [comment]
> 此项目使用Katex渲染公式。正如 [transitive-bullshit](https://github.com/transitive-bullshit) 所说，化学方程式([mhchem](https://mhchem.github.io/MathJax-mhchem/))属于扩展插件并没有默认支持。
> 
> > Hmmm, it looks like \ce and other chemistry-oriented latex features may not be included in katex by default. https://github.com/KaTeX/KaTeX/blob/b1311aff1bfeebd75df9389aadfba7a4a697b203/contrib/mhchem/README.md
> 
> 同时在katex的react版本中，也有用户反馈过此问题[react-katex/issues/69](https://github.com/talyssonoc/react-katex/issues/69)。不过似乎没有得到解决。
> 
> 现在的困难之处是，如何开启mhchem的支持。

🙈谢谢大佬帮我问，我看看考完高考能不能研究研究一下

**Comment by tangly1024** [comment]
功能已更新
https://github.com/tangly1024/NotionNext/releases/tag/v3.6.0
