### ISSUE TITLE
vercel  中的nextjs版本错误

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#1460]
**描述bug**
简单说明bug的现象、相关的错误提示、日志等
![image](https://github.com/tangly1024/NotionNext/assets/32816780/c9ab2c51-33ad-4815-90f0-ec0dc833586e)

**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
相关的页面，应该的结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- NotionNext版本 [e.g. 3.13.6]
- 主题 [例如. hexo]

**补充说明**
与问题相关的其它说明

**Comment by lifeafter619** [comment]
您只需在vercel的项目设置中微调即可
![image](https://github.com/tangly1024/NotionNext/assets/65111206/ad9b2069-0e6c-4dd2-9448-bcb5300430f5)
