### ISSUE TITLE
为什么第二页数据加载不出来

### ISSUE THREAD

**Issue by mageAoe** [tangly1024/NotionNext#1485]
![image](https://github.com/tangly1024/NotionNext/assets/67148153/f658356a-9fbe-44a1-9c08-8bfc8fc61702)

我现在是有 17 篇文章的，按照 page = 12 ，那么下一页应该展示剩余5篇文章

![image](https://github.com/tangly1024/NotionNext/assets/67148153/13a0832c-9baf-47bf-ae41-d935db23f661)

但是当我切换到第二页的时候，文章总数变成12，然后没有数据

![image](https://github.com/tangly1024/NotionNext/assets/67148153/40e12518-d304-437f-bb64-e924c1329cdd)

这个是我部署的 vercel 项目 https://notion-next-coral-one.vercel.app/

**Comment by tangly1024** [comment]
重新刷新一下，缓存导致

**Comment by rainnn-w** [comment]
请问这个问题现在解决了吗，我也遇到了刷新没有用
![image](https://github.com/tangly1024/NotionNext/assets/114235528/ccead707-8e1a-4a03-9ef9-50c839ede740)

**Comment by tangly1024** [comment]
最新版已修复此问题，bug关闭
