### ISSUE TITLE
今天上传的图片都无法显示，有人遇到一样的情况吗？

### ISSUE THREAD

**Issue by weijunext** [tangly1024/NotionNext#1492]
**描述bug**
今天上传的图片都无法显示，控制台查看图片url，变成https://prod-files-secure.s3.us-west-2.amazonaws.com/***** 的地址，但是之前发布的文章里图片地址都是https://www.notion.so/image/****** 的地址。

**复现步骤**
在这个网站可以看：https://weijunext.com/

**期望的正常结果**
图片地址是在https://www.notion.so/image，可以正常显示

**截图**
（好像无法上传图片，https://weijunext.com/ 这个地址里9月1日发布的文章图片无法显示，辛苦点开查看）

**环境**

- 操作系统: macOS
- 浏览器： chrome
- NotionNext版本： [3.16.4]
- 主题： fukasawa

**补充说明**
部署后代码没有变更，尝试过新建文章上传图片、在原来的文章上传图片，图片地址均为amazon的地址，而不是notion；环境变量原本没有配置NEXT_PUBLIC_IMG_TYPE，图片看不到后增加NEXT_PUBLIC_IMG_TYPE配置，配置是Notion，重新部署后再次上传图片，地址仍然是amazon的。

**Comment by JohnSpirit** [comment]
遇到了同样的问题！

**Comment by breezedeus** [comment]
遇到了同样的问题！

是不是notion的图片服务器有问题？

**Comment by RyanNiu** [comment]
同样的问题+1

**Comment by zzy-design** [comment]
同样的问题+1

**Comment by zzy-design** [comment]
+1

**Comment by weijunext** [comment]
notion分享链接打开，图片地址是notion，可以正常显示。仅自己域名下的图片地址是amazon。

**Comment by tangly1024** [comment]
感谢反馈
问题已确认：notion升级导致图片路径变化，升级到4.0.14版本已修复 。

https://github.com/tangly1024/NotionNext/releases
