### ISSUE TITLE
有个按键没有用

### ISSUE THREAD

**Issue by HelIwalker** [tangly1024/NotionNext#150]
主题很漂亮，刚刚去作者的博客看了下，发现中间那个聊天气泡按钮点了没用
![image](https://user-images.githubusercontent.com/19471848/161729513-c8fbb0d1-c5c2-4276-9e39-bd55740f7cdb.png)

**Comment by tangly1024** [comment]
Hi~
此按钮功能是，点击后跳转到评论区，需要配置评论功能才有效。
1. 配置评论在这 [blog.config.js](https://github.com/tangly1024/NotionNext/blob/main/blog.config.js) `COMMENT_GISCUS_REPO`2. 

2.  如果想隐藏按钮，可以在 [/config_hexo.js](https://github.com/tangly1024/NotionNext/blob/main/themes/hexo/config_hexo.js) 中关闭。

**Comment by HelIwalker** [comment]
> Hi~ 此按钮功能是，点击后跳转到评论区，需要配置评论功能才有效。
> 
> 1. 配置评论在这 [blog.config.js](https://github.com/tangly1024/NotionNext/blob/main/blog.config.js) 2.`COMMENT_GISCUS_REPO`
> 2. 如果想隐藏按钮，可以在 [/config_hexo.js](https://github.com/tangly1024/NotionNext/blob/main/themes/hexo/config_hexo.js) 中关闭。

我配置了评论区，评论区功能正常，但是点评论按钮不会跳转，我试了大佬你的博客也是一样的不会跳转。

**Comment by tangly1024** [comment]
这就奇怪了，我的这个按钮点击一直是有效的。
可能 需要帮忙提供一下具体 信息 ，我跟踪一下 ：
1.  客户端类型、浏览器版本
2. 控制台错误日志
3. 复现这个问题的步骤

**Comment by HelIwalker** [comment]
1.Windows 10 专业版 21H2，浏览器Edge 100.0.1185.29 (正式版本) (64 位)
2.
![image](https://user-images.githubusercontent.com/19471848/161921057-dc48406f-4fdb-4cc4-b9ef-8631bf7bd85d.png)
3.复现的视频：「2022-04-06 15-33-33.mkv」https://www.aliyundrive.com/s/m9CoehWX3sh
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

**Comment by tangly1024** [comment]
感谢反馈，在你提供的条件和复现步骤中，重现了问题。
这边将着手修复这个bug
