### ISSUE TITLE
【文件上传】新上传的文件无法获取正确的下载链接

### ISSUE THREAD

**Issue by fatekey** [tangly1024/NotionNext#1501]
**描述bug**
之前上传的文件，下载域名为 https://file.notion.so/ 新上传的文件，下载域名为 https://prod-files-secure.s3.us-west-2.amazonaws.com/ 该链接无法正常下载文件
**复现步骤**
在博客页面上传任意文件并进行下载
**期望的正常结果**
可以正常下载文件
**截图**
![image](https://github.com/tangly1024/NotionNext/assets/32138014/f0447b1a-0e0a-4b81-a8d2-c3182f54b604)
![image](https://github.com/tangly1024/NotionNext/assets/32138014/eef83486-e4bb-4aaf-8337-03f29a49b8b9)
![image](https://github.com/tangly1024/NotionNext/assets/32138014/fe1d7978-3be8-41af-93b4-b2b5a79bb179)

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- NotionNext版本 [e.g. 3.13.6]
- 主题 [例如. hexo]

**补充说明**
已经更新到最新

**Comment by tangly1024** [comment]
Notion最近更新了api导致，此问题将在NotionNext的后续版本修复

**Comment by tangly1024** [comment]
新版本中修复：https://github.com/tangly1024/NotionNext/releases/tag/v4.0.15
