### ISSUE TITLE
【自定义】请问文章页面的页面宽度可以调整吗

### ISSUE THREAD

**Issue by zyzhou-saffron** [tangly1024/NotionNext#1512]
**描述遇到的问题**
您好，麻烦您了！我有目前三个问题！
1. 文章内容在block里的显示宽度可以调整吗？
2.侧边栏的最新发布没法显示成带文章封面图案的形式
3. 之前在next主题通过添加styl文件更改了背景图片，不知道在notionnextjs里是否可行？
**相应配置**
网站地址(https://notion-next-flame-ten.vercel.app/)

**截图**
希望减小显示宽度，显示类似于这样
<img width="934" alt="image" src="https://github.com/tangly1024/NotionNext/assets/119337328/1c24b19c-dbb9-4ec0-b1eb-b3e5da7c3909">

**环境**
- 操作系统: macOS
- 浏览器  chrome

谢谢您的解答和耐心！

**Comment by tangly1024** [comment]
可以参考此文 [《NotionNext开发指引》](https://docs.tangly1024.com/article/how-to-develop-with-notion-next)自定义背景图片，样式宽度等等
