### ISSUE TITLE
Bookmark 抓取不到图片

### ISSUE THREAD

**Issue by B3n-AI** [tangly1024/NotionNext#1516]
**描述bug**
Notion设置的bookmark，可以抓取网站封面，但是部署到notionnext抓取不到

**复现步骤**
如上

**期望的正常结果**
网页上和notion中效果一致

**截图**
Notion效果
<img width="881" alt="Shot 2023-09-09 at 11 51 30@2x" src="https://github.com/tangly1024/NotionNext/assets/129975925/b515dd96-6f67-4031-a6b2-28d809854b98">
网页效果
<img width="884" alt="Shot 2023-09-09 at 11 52 25@2x" src="https://github.com/tangly1024/NotionNext/assets/129975925/8932451e-8ebb-49b1-9a18-f1a682d8741e">

实测下来，4个主流浏览器均不显示

**环境**

- 操作系统: [macOS, windows]
- 浏览器 [chrome, safari, firefox, edge]
- NotionNext版本 [4.0.15]
- 主题 [next]

**补充说明**
暂无

**Comment by tangly1024** [comment]
最新版本中已修复

**Comment by niustark** [comment]
![screenshot-1706839784991](https://github.com/tangly1024/NotionNext/assets/28669447/854a9812-8b2f-46d2-ae0e-64def00529f9)
更新到4.2.2了 还是不行 书签在notion里编辑时正常显示图片，发布后博客里就是裂图
edge浏览器
