### ISSUE TITLE
【嵌入B站视频】B站嵌入视频无法在前端正常播放，油管视频可以

### ISSUE THREAD

**Issue by xiaozhiob** [tangly1024/NotionNext#1525]
B站嵌入视频无法在前端正常播放，油管视频可以

在notion里面可以播放B站视频，但是部署到vercel，前端网页不能播放

**Comment by RedhairHambagu** [comment]
b站要用player开头的链接。不能直接用浏览器访问的地址，参考 https://github.com/tangly1024/NotionNext/issues/1064
