### ISSUE TITLE
Command "npm run build" exited with 1 部署错误

### ISSUE THREAD

**Issue by Arturia169** [tangly1024/NotionNext#1528]
**描述遇到的问题**
近期在拉取最新的仓库进行Radeploy的过程中vercel出现了报错

**相应配置**
blog.tohsaka.me

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/69199123/d67c5889-23b1-4a05-bc44-60e906931d69)
![image](https://github.com/tangly1024/NotionNext/assets/69199123/a7789661-e3e6-4b21-aeba-fd85172002bc)
![image](https://github.com/tangly1024/NotionNext/assets/69199123/aafeeb9c-2139-49dd-b406-4b47654886e4)

**环境**

- 操作系统: [windows]
- 浏览器 [Edge]
- 版本 [e.g. 22]

**Comment by tangly1024** [comment]
请尝试更新版本，不确定新版中是否还有这个问题
