### ISSUE TITLE
【404页面】404页面暗黑模式错误

### ISSUE THREAD

**Issue by lifeafter619** [tangly1024/NotionNext#1549]
**描述bug**
heo主题，404页面暗黑模式下只有顶部栏暗黑，其它部分无效果

**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
白天的404页面，完全正常
![image](https://github.com/tangly1024/NotionNext/assets/65111206/2ef2784f-4401-4ec0-a67d-1d9326ee622a)
暗黑模式下，顶部文字颜色错误且无效果
![image](https://github.com/tangly1024/NotionNext/assets/65111206/7e6f3bde-b8c1-401c-9362-f647e28c0938)
下滑后，顶部出现预期正常效果，但页面仍无效果
![image](https://github.com/tangly1024/NotionNext/assets/65111206/198fe670-bca9-4d6c-b63f-462ffa431492)

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器：edge  [例如. chrome, safari, firefox]
- NotionNext版本：最新 [e.g. 3.13.6]
- 主题 ：heo [例如. hexo]

**补充说明**
与问题相关的其它说明

**Comment by jxpeng98** [comment]
404页面貌似没有做暗黑模式
