### ISSUE TITLE
[随机封面]建议加入自定义随机图片api的功能

### ISSUE THREAD

**Issue by 1130600015** [tangly1024/NotionNext#1552]
**为什么提出这个新的特性改动**
一个网站配图好看的与否都决定着这个网站是否美观，而每篇文章的配图我想使用随机图床的api，不想在notion配置固定的图片或者每次写文章都要挑图片上传

**描述一下你推荐的解决方案**
我自己写了一个随机图床的接口，我也在getNotionDate这个方法里改动代码调我自己的接口解析json从而配置每篇图片的url，但是我图片配置了腾讯云的cdn，同时加上了鉴权，url有效期，但是由于缓存以及生成了static，所以会导致我打开网站有时候显示的url上的时间戳表示这个url已经过期了，导致无法加载。我希望官方能提供这个相关的配置，比如支持配置随机图片api，希望官方提出随机图片api的接口响应标准，让开发者开发随机图片api时按这个标准来开发。同时希望加上鉴权相关配置和有效期等配置。

**Comment by acolasialiuliu** [comment]
我也想随机哈哈哈，然后发现notion就请求一次

**Comment by 1130600015** [comment]
> 我也想随机哈哈哈，然后发现notion就请求一次
我是改了 前端代码，用我自己的随机图片 api实现了随机图片功能。没用 notion 的随机图片

**Comment by tangly1024** [comment]
感谢反馈，此问题将被修复

**Comment by tangly1024** [comment]
修复随机图片之请求一次的bug


当在notion中将封面设置为一个随机api地址时，网站打开后封面是动态获取的；并且如果不同文章用的同一个随机api作为封面地址，封面也是随机不同的。


示例：

我将每个封面图设置为： https://source.unsplash.com/random  ； 这是unsplash提供的随机图片api，每次打开都会跳到不同的封面。
![b5e366b12293ef5421039400fc2f60f](https://github.com/tangly1024/NotionNext/assets/15920488/4e2aa9a4-9592-42b2-836d-86a2c81253d8)

在网站中看到的图片效果
![image](https://github.com/tangly1024/NotionNext/assets/15920488/48e6d330-a5a5-4f06-b2cb-5c766dbd7550)

刷新页面后

![image](https://github.com/tangly1024/NotionNext/assets/15920488/37390697-7cc6-4164-b6c9-db2a3524cd00)

除了unsplash的api，也支持任意随机图片的api，例如这个国人开发的[图片api](https://tuapi.eees.cc/)  https://tuapi.eees.cc/api.php?category=dongman&type=302 
将封面设置为图片api地址：
![image](https://github.com/tangly1024/NotionNext/assets/15920488/dbe72411-3d1f-4c06-98a1-afb0574f69b0)

效果l如下

![image](https://github.com/tangly1024/NotionNext/assets/15920488/13477f79-30af-4199-b637-242da8b82b00)

![image](https://github.com/tangly1024/NotionNext/assets/15920488/903ea53f-1ee4-437b-99a0-19ef4567e3a1)

**Comment by Angel0726** [comment]
这种方法，每次需要写图片的url。可以

**Comment by C-Plusone** [comment]
用的这个：https://tuapi.eees.cc/api.php?category=dongman&type=302 好像不行 
![466F2003-9AC4-46b4-9B93-E57527E66CD9](https://github.com/tangly1024/NotionNext/assets/97445906/2765244e-eee3-46c7-a140-f3108acae827)
https://source.unsplash.com/random 这个可以但是每篇文章都要设置，设置到站点背景，文章图片为空时获取站点背景做封面的是同一张
![1](https://github.com/tangly1024/NotionNext/assets/97445906/6020ff60-3df0-4b55-847f-2efb5f4365bd)

最好能实现文章为空时获取站点背景（随机图API）做封面且图片随机，这样就不用单独设置图片了
