### ISSUE TITLE
无法获取Notion数据，请检查Notion_ID： 当前 9e2ed496-ad9e-4c09-836c-7af776df5f44

### ISSUE THREAD

**Issue by phperfeng** [tangly1024/NotionNext#1564]
**描述遇到的问题**
无法获取Notion数据，请检查Notion_ID： 当前 9e2ed496-ad9e-4c09-836c-7af776df5f44

**相应配置**
相关的配置，例如notion_page_id；你的网站地址
nation外链：https://melted-blackbird-99c.notion.site/9e2ed496ad9e4c09836c7af776df5f44?pvs=4
nation_page_id:9e2ed496ad9e4c09836c7af776df5f44
自有域名:codepool.cn

**截图**
![微信截图_20231013114724](https://github.com/tangly1024/NotionNext/assets/8703874/11495d13-70a2-4cff-9097-af639d306c69)
![微信截图_20231013114715](https://github.com/tangly1024/NotionNext/assets/8703874/051b4512-ba75-47ef-ad09-b5c36c87ec9b)
![微信截图_20231013114645](https://github.com/tangly1024/NotionNext/assets/8703874/121b86a0-5ba7-48d6-8933-7817482d6fac)

**环境**
- 操作系统: windows
- 浏览器:chrome

**Comment by phperfeng** [comment]
看了下vercel的编译过程，出现这样的报错，因为对前端不了解，想问下是什么原因呢
![微信截图_20231014171307](https://github.com/tangly1024/NotionNext/assets/8703874/45665e96-329c-457f-bfab-b70af29809f1)

**Comment by jxpeng98** [comment]
把pageid中间的杠“-”全部去掉

**Comment by phperfeng** [comment]
已解决，必须要Duplicate项目主的页面代码才能正常编译，自己写的就会报楼上的错误
```Duplicate Template from  https://www.notion.so/tanghh/02ab3b8678004aa69e9e415905ef32a5```
自己写的内容无法正常解析，还是在项目主提供的模板页直接修改内容吧，结帖关闭issue

**Comment by WangKangAandy** [comment]
你好，我遇到了和你一样的问题，能帮我详细讲解下怎么解决这个问题的吗
