### ISSUE TITLE
图片不能加载出来

### ISSUE THREAD

**Issue by githubyangkai** [tangly1024/NotionNext#1567]
**描述bug**
在notion上面本地上传的图片可以正常显示，但是在notion next上面加载不出来，上面选择notion提供的无版权图片是可以正常显示的。

**复现步骤**
导入本地图片无法加载出来，感觉有一个月了吧
![微信截图_20231016202118](https://github.com/tangly1024/NotionNext/assets/121996502/56f25742-36ec-4bbb-989c-9e12a828f8fd)

结果就是这样了
![image](https://github.com/tangly1024/NotionNext/assets/121996502/6b934ef4-b944-4e12-a508-675a5b5fcc98)

**环境**

- 操作系统:  windows
- 浏览器 ：edge
- NotionNext版本 [3.16.0]

**Comment by tangly1024** [comment]
Notion近期升级接口，导致图片无法显示； 在最新的NotionNext4.0.16版本中已修复此问题，更新代码即可

https://github.com/tangly1024/NotionNext/issues/1506

https://github.com/tangly1024/NotionNext/issues/1492
