### ISSUE TITLE
评论按钮bug

### ISSUE THREAD

**Issue by HelIwalker** [tangly1024/NotionNext#158]
昨晚拉了3.0版本，评论按钮还是有BUG，点击评论按钮滚动到文章中间了，和昨天一点点往下蹭不一样了。

还是昨天的设备：
笔记本联想昭阳E42  14英寸，1920*1080分辨率，缩放与布局125%，win10 64位 专业版 21H2，Edge 最新版 100.0.1185.29 (正式版本) (64 位)
台式机 1920*1080，无缩放， win10 64位专业版 21H2，Edge 最新版 100.0.1185.29 (正式版本) (64 位)

**Comment by tangly1024** [comment]
收到

**Comment by tangly1024** [comment]
做了新的调整，这回应该可以了
