### ISSUE TITLE
hexo主题会把Logo标题半模糊

### ISSUE THREAD

**Issue by zuig** [tangly1024/NotionNext#1581]
**截图**
![image](https://github.com/tangly1024/NotionNext/assets/10735394/4be4784f-ced2-4c2c-ad34-69ef9706c4a2)

**环境**
- 浏览器 [ chrome ]
- NotionNext版本 NotionNext 4.0.16.
- 主题 [hexo]

**Comment by tangly1024** [comment]
设计如此的
