### ISSUE TITLE
[多级路径404] 更新到最新版本，所有文章点击文章跳转的时候全是

### ISSUE THREAD

**Issue by expoli** [tangly1024/NotionNext#1585]
**描述bug**
更新到最新版本，所有文章点击文章跳转的时候全是[404]
日志里面也只有404.没有其它的提示

**复现步骤**
预览分支
https://notion-next-2av0od915-expoli.vercel.app/

**期望的正常结果**
正确获取对应的页面

**截图**
https://notion-next-2av0od915-expoli.vercel.app/

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- NotionNext版本 [e.g. 3.13.6]
- 主题 [例如. hexo]

**补充说明**
与问题相关的其它说明

**Comment by expoli** [comment]
原来的版本：[NotionNext 3.13.5](https://github.com/tangly1024/NotionNext).
使用原始版本的网站：https://www.expoli.tech/

**Comment by expoli** [comment]
部分原因已经找到， 新版本在处理不同的列的时候会处理错误。具体404逻辑还不清楚。我的notion——pageid：74257aa9e9ec45feac0c616d9dc8bf4a
![图片](https://github.com/tangly1024/NotionNext/assets/31023767/a1bc6f85-40fe-4def-8b65-43fd32acea19)

**Comment by expoli** [comment]
![图片](https://github.com/tangly1024/NotionNext/assets/31023767/d4812974-f033-4d41-acb9-24acc80deb09)

**Comment by expoli** [comment]
随便点某个链接跳转的时候，都会触发404

**Comment by tarimoe** [comment]
我也遇到这个问题，请问解决了吗

**Comment by tarimoe** [comment]
@expoli 尝试回归版本
1. v.4.0.5 异常
2. 回退到 [v3.16.4](https://github.com/tangly1024/NotionNext/releases/tag/v3.16.4) 版本正常，

**Comment by tarimoe** [comment]
> @expoli 尝试回退版本
> 
> 1. v.4.0.5 异常
> 2. 回退到 [v3.16.4](https://github.com/tangly1024/NotionNext/releases/tag/v3.16.4) 版本正常，

用老版本又会有 https://github.com/tangly1024/NotionNext/issues/1567 这个bug，图片显示不了

**Comment by expoli** [comment]
> > @expoli 尝试回退版本
> > 
> > 1. v.4.0.5 异常
> > 2. 回退到 [v3.16.4](https://github.com/tangly1024/NotionNext/releases/tag/v3.16.4) 版本正常，
> 
> 用老版本又会有 #1567 这个bug，图片显示不了

我在使用我自己修改的版本，还可以 https://www.expoli.tech/ 3.13.x 版本

**Comment by expoli** [comment]
尝试看了一下源码，新版的逻辑理不清，放弃了

**Comment by tangly1024** [comment]
> 部分原因已经找到， 新版本在处理不同的列的时候会处理错误。具体404逻辑还不清楚。我的notion——pageid：74257aa9e9ec45feac0c616d9dc8bf4a ![图片](https://user-images.githubusercontent.com/31023767/277170262-a1bc6f85-40fe-4def-8b65-43fd32acea19.png)

感谢反馈问题，感谢提供NotionId等描述信息，这个错误是由于新版本中针对多级目录解析方式的改变导致；已提交补丁修复此问题. 

问题现象： 如果是  /about ， /article/about ，此类路径能正常访问，而 类似 /article/2023/10/29/test  （路径中的级数超过二就不支持。）
