### ISSUE TITLE
无法使用Menu/SubMenu功能，只能使用Page功能

### ISSUE THREAD

**Issue by LiWill188** [tangly1024/NotionNext#1588]
**描述bug**
哈喽，我是Will，刚通过NotionNext成功建站，有个问题现在还未解决，特来请教：检查过版本Github>Fork 没有要更新的提示，显示是最新版本，但菜单页面只有Page是正常的，Menu和SubMenu都没办法使用，请教下这个怎么处理解决呀？

**复现步骤**
网址：daxinex.com 

**期望的正常结果**
希望通过修改Notion里的数据库内容，能按照Menu/SubMenu来显示，而不是通过Page

**截图**
<img width="1516" alt="image" src="https://github.com/tangly1024/NotionNext/assets/148597868/7181ad85-b267-4f6f-875d-b9aa1c25e477">

**环境**

- 操作系统: [macOS]
- 浏览器 [chrome]
- NotionNext版本 [不知道在哪里查看，下图截图显示是最新版本]
- 主题 [next]
<img width="1858" alt="image" src="https://github.com/tangly1024/NotionNext/assets/148597868/a6d0c8e7-fc66-45f7-8a0e-d1b28d694bca">

**补充说明**
暂无

**Comment by tangly1024** [comment]
参考教程：

https://docs.tangly1024.com/article/notion-next-secondary-menu
