### ISSUE TITLE
[视频播放]notion近期新上传的视频无法在博客显示；（以前较早上传的视频现在可以正常播放）

### ISSUE THREAD

**Issue by AShanWang** [tangly1024/NotionNext#1590]
---
# bug图文描述详见博文链接    !*!*!*!*!*!*!*!*!*!*!
https://ashancbt.eu.org/article/qms
---

**描述bug**
notion近期新上传的视频无法在博客显示；（以前较早上传的视频现在可以正常播放）

**复现步骤**
将本地视频上传到notion里，无法在博客网页上正常播放！

**期望的正常结果**
从本地设备上传至notion的视频，可以正常在博客网页上播放。

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/129077870/cd24aaf0-f63f-4a75-a834-0ec8dd5b34f8)

**环境**
- 操作系统: iOS, Android, macOS, windows
- 浏览器 chrome
- NotionNext版本 最最新版（4.0.16）
- 主题 gitbook

**补充说明**
见此博文：https://ashancbt.eu.org/article/qms

**Comment by tangly1024** [comment]
在https://github.com/tangly1024/NotionNext/releases/tag/v4.0.17 版本中已修复视频播放的问题
