### ISSUE TITLE
【封面图无法显示】无法使用Notion自带的cover图片

### ISSUE THREAD

**Issue by Artificialimbecile** [tangly1024/NotionNext#1609]
**描述bug**
notion自带的cover图片的无法显示且文章标题显示出错

**复现步骤**
按照教程部署

**期望的正常结果**
notion自带的cover图片能够显示

**截图**
![1698853050614](https://github.com/tangly1024/NotionNext/assets/35124360/0d295fd7-5737-4089-9d1a-62987a8120d4)
![1698853021917](https://github.com/tangly1024/NotionNext/assets/35124360/d06b413a-1c4b-40ab-bce4-64c43e957302)
![1698853117063](https://github.com/tangly1024/NotionNext/assets/35124360/ad7ad60b-7231-4202-aafe-44c8471e08f4)

**环境**

- 操作系统: windows
- 浏览器 chrome
- NotionNext版本 4.0.17
- 主题 hexo

**补充说明**
与问题相关的其它说明

**Comment by expoli** [comment]
这个问题，应该是已经修复，更新到最新版本即可 https://github.com/tangly1024/NotionNext/pull/1600

**Comment by gitlayzer** [comment]
> 这个问题，应该是已经修复，更新到最新版本即可 #1600 不不不，我看还是没有修复，还是有问题

**Comment by DoiiarX** [comment]
erver failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:8dc2abed-c01e-0033-28df-0f904c000000
Time:2023-11-05T11:59:06.0194264Z
![image](https://github.com/tangly1024/NotionNext/assets/25550075/daed82db-9aff-4bc3-9098-5afe38966e8c)
![image](https://github.com/tangly1024/NotionNext/assets/25550075/1d002eed-0995-4613-936c-8a8428f7e20e)


我感觉是新问题啊

**Comment by gitlayzer** [comment]
> 服务器无法验证请求。确保授权标头的值格式正确，包括签名。 请求ID：8dc2abed-c01e-0033-28df-0f904c000000 时间：2023-11-05T11：59：06.0194264Z ![图像](https://user-images.githubusercontent.com/25550075/280524895-daed82db-9aff-4bc3-9098-5afe38966e8c.png) ![图像](https://user-images.githubusercontent.com/25550075/280524928-1d002eed-0995-4613-936c-8a8428f7e20e.png)
> 
> 我感觉是新问题啊

欸，看起来的确是新问题

**Comment by tangly1024** [comment]
感谢反馈，无法使用notion自带cover图片属于新bug，已经修复

**Comment by tangly1024** [comment]
@DoiiarX  这个错误，需要先更新至最新版，再做尝试；如果还是访问异常，请另外提交issue，附上详细信息。

> erver failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:8dc2abed-c01e-0033-28df-0f904c000000 Time:2023-11-05T11:59:06.0194264Z ![image](https://user-images.githubusercontent.com/25550075/280524895-daed82db-9aff-4bc3-9098-5afe38966e8c.png) ![image](https://user-images.githubusercontent.com/25550075/280524928-1d002eed-0995-4613-936c-8a8428f7e20e.png)
