### ISSUE TITLE
bug: 博客卡片高度问题

### ISSUE THREAD

**Issue by yuzhanglong** [tangly1024/NotionNext#162]
修复了上次图片高度的问题，貌似卡片左侧文本的高度又异常了。
我的建议是卡片固定高度，如果描述溢出则末尾追加省略号，图片高度和卡片一致，多余的裁剪。
<img width="955" alt="image" src="https://user-images.githubusercontent.com/56540811/162338723-f29ef521-27a5-4aa1-86a7-b554deb460de.png">

**Comment by tangly1024** [comment]
> 卡片固定高度，如果描述溢出则末尾追加省略号，图片高度和卡片一致，多余的裁剪

建议采纳
