### ISSUE TITLE
[随机图片统一配置] 博客图片支持随机图片 api 统一配置

### ISSUE THREAD

**Issue by jiashu1024** [tangly1024/NotionNext#1620]
**为什么提出这个新的特性改动**
关于随机图片 api 的配置，现有的方案是要在每一篇文章在 notion 的封面图设置一次 url，希望可以统一在一个地方配置。如果随机图片服务挂掉，或者跑路，又需要把所有文章的 url 全部重新配置一次。

**描述一下你推荐的解决方案**
建议在notion 的 database 里新添加一个 type 为 setting 的设置，从而设置全篇文章的随机图片 api
或者在blog.config.js配置文件里添加该支持也行。配置文件里随机图片地址为空才使用 notion 的配图
感谢支持🙏🙏🙏

**Comment by Angel0726** [comment]
同样的需求，不一样的解决方案。
建议设置10张图片，将网页地址进行哈希值计算，然后取10的余数，将相应的图片作为博客的封面。

**Comment by 1130600015** [comment]
已提交该功能的 pr

**Comment by Angel0726** [comment]
> 已提交该功能的 pr

这种方案需要在notion的datebase里面添加新的关键字吗

**Comment by jiashu1024** [comment]
> > 已提交该功能的 pr
> 
> 这种方案需要在notion的datebase里面添加新的关键字吗

我提交 pr 的时候还没有发 4.1.0 版本，而且我的 pr 没有合并

**Comment by Angel0726** [comment]
> > 已提交该功能的 pr
> 
> 这种方案需要在notion的datebase里面添加

> > > 已提交该功能的 pr
> > 
> > 
> > 这种方案需要在notion的datebase里面添加新的关键字吗
> 
> 我提交 pr 的时候还没有发 4.1.0 版本，而且我的 pr 没有合并

我看到了没有提交，我想问一下你的实现方法是不是需要设置关键字

**Comment by jiashu1024** [comment]
> 我看到了没有提交，我想问一下你的实现方法是不是需要设置关键字

umm.....不知道你说的设置关键字具体是什么意思。你可以去看我提交的pr，有具体的实现方法，以及实现代码

**Comment by tangly1024** [comment]
https://github.com/tangly1024/NotionNext/pull/1622

感谢您的issue
感谢您的提交

已经合并至最新版 [v4.1.1](https://github.com/tangly1024/NotionNext/releases/tag/v4.1.1)

**Comment by Angel0726** [comment]
如果之前没有配置过封面，那么怎么修改。可以给个范例吗？

**Comment by Angel0726** [comment]
没有设置封面（没有用notion封面，其他的封面也没有用）。


从 Windows 版邮件发送

发件人: ZhangJiashu
发送时间: 2023年11月24日 20:29
收件人: tangly1024/NotionNext
抄送: Angel0726; Comment
主题: Re: [tangly1024/NotionNext] [随机图片统一配置] 博客图片支持随机图片 api 统一配置 (Issue #1620)

如果之前没有配置过封面，那么怎么修改。可以给个范例吗？
什么意思，封面用的 notion 图床的图片吗，你随机图片 url 如果填写的话，则默认会将背景图片也会随机。

**Comment by touchsky-real** [comment]
看不大懂，我文章封面都用的 [https://random-image-pepebigotes.vercel.app/api/random-image](https://random-image-pepebigotes.vercel.app/api/random-image)在 **Notion配置中心** 里关键字写了random-image，url写了新的网址。为啥还是显示原来的图片？
