### ISSUE TITLE
配置中心文件无法读取，设置不生效

### ISSUE THREAD

**Issue by OrangeCatSleepless** [tangly1024/NotionNext#1625]
**描述bug**
最新版 v4.1.0 配置中心并不生效

![image](https://github.com/tangly1024/NotionNext/assets/58691431/d919bc12-d1e0-443a-8599-2254ccb5a24d)

为了避免冲突我是全新部署，但配置中心中的配置并不生效，看日志好像是没有正确找到配置中心文件？

**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
相关的页面，应该的结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- NotionNext版本 [e.g. 3.13.6]
- 主题 [例如. hexo]

**补充说明**
与问题相关的其它说明

**Comment by 1208nn** [comment]
可能由于`type`标签错误，应该为`CONFIG`，是全部大写的

页面内的数据库标题为`config-table`，表头为`启用``配置名``配置值`，否则无效

**Comment by 1208nn** [comment]
<https://github.com/tangly1024/NotionNext/blob/main/lib/notion/getNotionConfig.js#L27>

如有需要可以更改为
```js
return post && post?.type && (post?.type === 'CONFIG' || post?.type === 'config' || post?.type === 'Config');
```

**Comment by OrangeCatSleepless** [comment]
> 可能是`type`标签错误所导致的，应该为`CONFIG`，是全部大写的
> 
> 页面内的数据库标题为`config-table`，表头为`` 启用``配置名``配置值 ``，否则无效

好像是我使用了不支持的配置参数导致的，删除后就好了
