### ISSUE TITLE
[新增单页] 有没有什么方法可以增加一个友情链接页面

### ISSUE THREAD

**Issue by sorabug** [tangly1024/NotionNext#163]
有没有什么方法可以增加一个友情链接页面，如题

**Comment by tangly1024** [comment]
可以尝试notion中添加一个[友情链接页面](https://tanghh.notion.site/b9e5afa7db274aea95fb3fd5fcf81846)

**Comment by sorabug** [comment]
> 可以尝试notion中添加一个[友情链接页面](https://tanghh.notion.site/b9e5afa7db274aea95fb3fd5fcf81846)
> 
> 预览效果 https://preview.tangly1024.com/links
试过感觉有点不太美观

**Comment by tangly1024** [comment]
用notion原生页面主要好处是方便更新修改，美观的话就要单独设计，另外，有没有可以参考的样式提供一下

**Comment by sorabug** [comment]
> 用notion原生页面主要好处是方便更新修改，美观的话就要单独设计，另外，有没有可以参考的样式提供一下
如果要参考可以参考一下https://moechu.cn/links.html或者https://logi.im/about.html，但我想着也可以不用做，我干脆markdown写文字链接也行哈

**Comment by tangly1024** [comment]
> 如果要参考可以参考一下https://moechu.cn/links.html 或者 https://logi.im/about.html

相比之下，这两个参考页面确实样式更好看，不过短期内可能不会增加这个功能，我更偏向于在notion笔记中，根据自己的喜好排版出一个友情链接的功能。

> 但我想着也可以不用做，我干脆markdown写文字链接也行哈

或者文字加图片😁

**Comment by SkysCrystal** [comment]
> > 如果要参考可以参考一下https://moechu.cn/links.html 或者 https://logi.im/about.html
> 
> 相比之下，这两个参考页面确实样式更好看，不过短期内可能不会增加这个功能，我更偏向于在notion笔记中，根据自己的喜好排版出一个友情链接的功能。
> 
> > 但我想着也可以不用做，我干脆markdown写文字链接也行哈
> 
> 或者文字加图片😁

能渲染页面内数据库，让数据库标题可点击吗？
Notion页面
![Notion页面](https://raw.githubusercontent.com/SkysCrystal/Figurebed/master/img/20220606113047.png)
博客渲染
![博客Gallery不可点击](https://raw.githubusercontent.com/SkysCrystal/Figurebed/master/img/20220606113142.png)

在Notion中给页面标题复制带链接属性的文字，点击标题文字可以跳转网页。标题文字在渲染的博客页面不可点击。
![](https://raw.githubusercontent.com/SkysCrystal/Figurebed/master/img/20220606113354.png)

这样可以在Notion页面中调整友联内容和排版

**Comment by tangly1024** [comment]
> 能渲染页面内数据库，让数据库标题可点击吗？ 
> 在Notion中给页面标题复制带链接属性的文字，点击标题文字可以跳转网页。标题文字在渲染的博客页面不可点击。 
> 或者添加显示新条目： ![URL](https://raw.githubusercontent.com/SkysCrystal/Figurebed/master/img/20220606115028.png)
> 
> 这样设置的话，可以在Notion页面中调整友联内容和排版。


很好的提议，也许我可以试试

**Comment by tangly1024** [comment]
在V3.4.0版本中，增加了使用Gallery进行友情链接排班的可能性 。

预览效果: https://preview.tangly1024.com/links#9b54ef15cf074232b45cd91fbcff60e7

参考notion实现： https://www.notion.so/tanghh/b9e5afa7db274aea95fb3fd5fcf81846
