### ISSUE TITLE
【部署求助】发布时报错

### ISSUE THREAD

**Issue by Shadownc** [tangly1024/NotionNext#1630]
**描述bug**
部署时遇到报错

**复现步骤**
vercle部署

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/19424471/5f54bbe1-e9fd-493f-adb4-c0748417d4e4)

**环境**

- 操作系统: windows
- 浏览器 chrome
- 主题 hexo

**补充说明**

**Comment by AidenQianYu** [comment]
大大，想问一下，发生了和您图中一样的错误，是什么原因嘞？

**Comment by Shadownc** [comment]
感觉是升级了版本不兼容的问题 等待作者修复吧

**Comment by Shadownc** [comment]
> 大大，想问一下，发生了和您图中一样的错误，是什么原因嘞？
已解决 是未设置欢迎语的问题 你可以自己设置一个欢迎语或者修改源码

**Comment by tangly1024** [comment]
> 大大，想问一下，发生了和您图中一样的错误，是什么原因嘞？

可以提供一下具体日志 以便排查问题

**Comment by Shadownc** [comment]
> > 大大，想问一下，发生了和您图中一样的错误，是什么原因嘞？
> 
> 可以提供一下具体日志 以便排查问题

我的报错是由于未设置欢迎语导致代码报错引起的 不知道他的是不是一样
