### ISSUE TITLE
[Notion Config]代码框折叠失效 CODE_COLLAPSE

### ISSUE THREAD

**Issue by Ghlerrix** [tangly1024/NotionNext#1631]
**描述bug**
已升级4.1.0，在Notion的配置中心中添加`CODE_COLLAPSE`配置不生效，后去`blog.config.js`依旧不生效

**截图**
![图片](https://github.com/tangly1024/NotionNext/assets/114851291/633bd564-10bc-43eb-b09b-1807477e6e3e)
![图片](https://github.com/tangly1024/NotionNext/assets/114851291/507fdaa9-42d9-41c5-94d8-b8f8bcad2590)
![图片](https://github.com/tangly1024/NotionNext/assets/114851291/165ed51f-81ba-41fa-baf2-9b26dccb92e1)

**环境**

- 操作系统: windows
- 浏览器 firefox
- NotionNext版本 4.1.0
- 主题 hexo

**补充说明**
与问题相关的其它说明

**Comment by Ghlerrix** [comment]
目前发现，将Notion中的配置中心的字段删除，即可根据`blog.config.js`中的配置起作用。
配置中心的字段必须删除，取消勾选也不行

**Comment by tangly1024** [comment]
判断为 和 https://github.com/tangly1024/NotionNext/issues/1643 这个issue是同一个bug，原因是notionconfig在处理boolean类型的配置时会失效。

请更新至最新版即可修复。
