### ISSUE TITLE
[simple主题] 不显示notion自带的封面

### ISSUE THREAD

**Issue by SimFG** [tangly1024/NotionNext#1635]
**描述bug**
图片无法显示，打开控制台没有报错，有三个警告，展示出图片的url，与 https://github.com/tangly1024/NotionNext/issues/1609 类似

**复现步骤**
按照文档进行部署，无任何改动

**期望的正常结果**
正常封面显示

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/21985684/6e17ce47-bc5a-494a-9e0e-c9250924c683)

![image](https://github.com/tangly1024/NotionNext/assets/21985684/6ec638f0-80cf-47e1-9f44-1b4155c8d48e)

**环境**

- 操作系统 macOS
- 浏览器 chrome
- NotionNext版本 4.1.0-最新分支
- 主题 hexo

**补充说明**
无

**Comment by alanjustalan** [comment]
![image](https://github.com/tangly1024/NotionNext/assets/42884681/55a51a8f-e2d0-483d-92c6-be7284ece0e4)
这里的文字也变成这样了，想问下如何改回来？

**Comment by alanjustalan** [comment]
搞定了，是主题的问题，你换个主题就可以了

**Comment by SimFG** [comment]
@alanjustalan 你换了什么主题呀，参考下

**Comment by tangly1024** [comment]
notion自带的封面无法显示的问题 在另一个issue里解决了，可能需要更新试一下，https://github.com/tangly1024/NotionNext/issues/1609

当然也不排除，可能刚好simple这个主题单独有问题。

**Comment by SimFG** [comment]
@tangly1024 我当时提issue的时候，其实已经用的是最新的了

**Comment by tangly1024** [comment]
这样的话，有一种可能，这个simple主题设计的时候就没有放封面图😋 ，需要的话，我可以更新一个版本加入😋

**Comment by tangly1024** [comment]
> ![image](https://user-images.githubusercontent.com/42884681/282672074-55a51a8f-e2d0-483d-92c6-be7284ece0e4.png) 这里的文字也变成这样了，想问下如何改回来？

修改方式在主题里：


https://github.com/tangly1024/NotionNext/blob/60892530c61db78c43b5e433e3e8ecc99922bf53/themes/simple/config.js#L6C1-L7C1

```
  SIMPLE_LOGO_DESCRIPTION: process.env.NEXT_PUBLIC_THEME_SIMPLE_LOGO_DESCRIPTION || '<div>编程爱好者<br/>/互联网从业者<br/>/知识分享博主</div>',

```
