### ISSUE TITLE
没有找到文章

### ISSUE THREAD

**Issue by ByeYesterday** [tangly1024/NotionNext#164]
感谢您的项目，但我在尝试过程中遇到了问题

按照[快速开始](https://tangly1024.com/article/notion-next?theme=next)的方法进行部署，我只修改了`/blog.config.js`中的`process.env.NOTION_PAGE_ID`，并在部署时在vercel中也添加了一条`NOTION_PAGE_ID`环境变量，但是我部署好的博客显示“没有找到文章”。

这是我部署后的demo：https://myyy-bice.vercel.app/

这是我的notion页面：https://heliotrope-roarer-6d6.notion.site/6eb136d8df914f24b8b399ad9003abda?v=6094ea764fde4b1caa5ca83b6017877d

这是我fork后的repository：https://github.com/ByeYesterday/NotionNext

**Comment by tangly1024** [comment]
NOTION_PAGE_ID有误，需要修改  为 `6eb136d8df914f24b8b399ad9003abda`

**Comment by ByeYesterday** [comment]
好了，感谢解答
