### ISSUE TITLE
[Config配置中心]Notion-Config功能异常

### ISSUE THREAD

**Issue by scqy2000** [tangly1024/NotionNext#1643]
**描述bug**
NotionNext文档中提到Notion-Config可以在blog.config.js以及各个主题的config.js中找到可加入的配置，但是添加themes/hexo/config.js当中的字段HEXO_ARTICLE_COPYRIGHT并设置成false后，具体配置情况看下方截图，多次刷新后网页中依然显示版权信息。其他涉及到themes/hexo/config.js的字段也无法生效。
Notion-Config中其他仅涉及blog.config.js字段的功能完全正常(如截图中存在的樱花特效正常生效)。
又考虑到文档中提及并非所有配置都支持，因此不确定此状态是否为BUG。
**复现步骤**
重新部署后依然存在。

**期望的正常结果**
Notion-Config配置正常生效或者开发者确认themes/hexo/config.js字段无法被Notion-Config功能覆盖

**截图**
![copyright](https://github.com/tangly1024/NotionNext/assets/19802266/ceb656c4-5ba1-411a-b749-a7b92026f436)
![config](https://github.com/tangly1024/NotionNext/assets/19802266/b8d3c546-99bb-4e34-a18c-3f1ddd64758c)

**环境**

- NotionNext版本  4.1.0
- 主题 hexo
- 操作系统: windows
- 浏览器 chrome

**Comment by tangly1024** [comment]
感谢反馈! 确认是一个bug
