### ISSUE TITLE
[部署]无法获取Notion数据，请检查Notion_ID

### ISSUE THREAD

**Issue by luoliguang** [tangly1024/NotionNext#1656]
# 遇到的问题
1. 在最后部署时出现无法获取Notion数据
2. ❌暂时未配置自己的域名

# 相关的配置
notion_page_id：https://giluo.notion.site/0987600656074c92bc737459184d72cc?pvs=4
NOTION_PAGE_ID：0987600656074c92bc737459184d72cc

# 截图
![image](https://github.com/tangly1024/NotionNext/assets/74090098/cae44b33-364c-434d-b186-dc804cba0fad)
![image](https://github.com/tangly1024/NotionNext/assets/74090098/8c8f980e-0917-4375-87dc-f79f04c1864e)
![image](https://github.com/tangly1024/NotionNext/assets/74090098/bad943cc-cf41-46c0-b962-ef5592d59579)

# 环境
Windows 11
chrome 119.0.6045.160（正式版本） （64 位）

**Comment by tangly1024** [comment]
参考教程： https://docs.tangly1024.com/article/vercel-deploy-notion-next#3df829414795492bb41ec351eb6da84e

**Comment by luoliguang** [comment]
> 参考教程： https://docs.tangly1024.com/article/vercel-deploy-notion-next#3df829414795492bb41ec351eb6da84e

抱歉，我的问题，我duplicate我自己的页面啦。已解决谢谢大佬！
