### ISSUE TITLE
[代码块]部分语言代码块无法高亮

### ISSUE THREAD

**Issue by Issac-v** [tangly1024/NotionNext#166]
**Describe the bug**
C++和C#均无法高亮, 其他语言我测试了C, Bash, Go, Java, CSS均可正常高亮, 猜测为特殊符号`+`和`#`导致

**To Reproduce**
建立了一个[测试上述语言高亮的页面](https://blog.coldle.ml/article/42126509-1d29-4d39-82e0-9210422a04e6)
分别展示了notion中的高亮效果和网页高亮效果

**Expected behavior**
正常高亮

**Screenshots**
![image](https://user-images.githubusercontent.com/54757860/162598387-f92fc08f-57ac-429a-a5a8-cc1afeb85f84.png)
![image](https://user-images.githubusercontent.com/54757860/162598393-ed749e07-ad3e-4a05-9465-aa0ad806420f.png)

**Platform:**

- OS: Win11
- Browser Chrome
- Version 100.0.4896.75(64-bit)

**Additional context**

**Comment by tangly1024** [comment]
将添加 C++ 和C#语言的高亮

**Comment by tangly1024** [comment]
V3.2.2已修复问题

**Comment by wyih** [comment]
> V3.2.2已修复问题
> 
> 效果演示： https://preview.tangly1024.com/article/example-1#349808ed27944012a180f278295b7714

我的R代码也无法高亮

样本见：https://blog.yhong.wang/article/sd_tg_bot

Python和Shell代码高亮正常

**Comment by doing1024** [comment]
![image](https://github.com/tangly1024/NotionNext/assets/126306440/640db085-96c6-421a-8311-8f2537f51ed2)
c++无法高亮
