### ISSUE TITLE
[bug]几处样式问题及bug

### ISSUE THREAD

**Issue by HelIwalker** [tangly1024/NotionNext#167]
项目真的很不错，感谢大佬分享出来这么好的东西👍
我部署的实例 https://oblog.vercel.app/

这里技术分享和发布日期下面的虚线感觉有点违和，有没有考虑去掉它呢😁。
![屏幕截图 2022-04-10 162225](https://user-images.githubusercontent.com/19471848/162612151-6abfb978-786c-4b92-9b19-0a0006ad3590.png)

hexo主题下面页数翻到最后一页，下面页码会消失。
![屏幕截图 2022-04-10 162304](https://user-images.githubusercontent.com/19471848/162612153-8724c958-dcfc-4727-a793-26d7e9f0b319.png)

Next主题我开了显示首页大图，但是部署完是黑屏，好像没有读取/public/bg_image.jpg
![435435](https://user-images.githubusercontent.com/19471848/162612379-4b4d4b28-da38-465e-b34d-c584ace12f81.png)

fukasawa主题左边有搜索栏了，感觉归档下面那个搜索就不用做了吧，而且点击”搜索“这两个字之后会显示上下两排一样的文章。
![屏幕截图 2022-04-10 165214](https://user-images.githubusercontent.com/19471848/162612488-89b33ed4-86e3-4351-84ab-24fe2bef9d84.png)

**Comment by HelIwalker** [comment]
还有感觉手机版Next主题上面这块黑的太大了，把上下空出来的压缩到中间标题那么宽就好看了
![IMG_0121](https://user-images.githubusercontent.com/19471848/162614908-c1c5e161-f3f3-4a0b-bc31-e9004a77e171.png)

**Comment by tangly1024** [comment]
Hi， 感谢你的意见反馈~ 仔细看了你的描述，都是十分中肯的建议，我会按照你的建议进行调整
 1. > 去掉违和的虚线，虽然他们本意是告知用户可以点击，但似乎 没太大的必要 😂
 2. bug > Next首页大图的显示异常 
 3. > fukasawa 违和的搜索功能
 4. > Next主题上面这块黑色的高度

再次感谢你的意见😁，你真是我的宝藏用户了

**Comment by HelIwalker** [comment]
大佬客气了，没帮上什么大忙😂，幸苦大佬完善了。

Windows 10 专业版 21H2，浏览器Edge 100.0.1185.36 (正式版本) (64 位)，NotionNext 3.1.0

现在hexo主题主页 下面页数翻到最后一页，页码依然会消失。

NEXT主题夜间模式下目录这里字体颜色有点深，感觉看不太清
![屏幕截图 2022-04-11 150055](https://user-images.githubusercontent.com/19471848/162682650-f4eae8f7-f975-4bdd-ac2c-d07d1c40b582.png)

**Comment by tangly1024** [comment]
> 手机端，Next主题评论区这个笑脸歪了

这个问题似乎有些棘手，目前在PC端的safari浏览器也复现了此问题，需要花点时间来研究一下。
