### ISSUE TITLE
【音频播放】文章中插入MP3等音频文件前端无法播放（notion中可以播放）

### ISSUE THREAD

**Issue by cuiyanjie** [tangly1024/NotionNext#1670]
**描述bug**
写文章时无论拖入mp3文件还是/audio文件在notion中可以播放，在浏览器中不能播放，试过wav、m4a、aac等音频格式均如此（1MB左右的文件），但拖入mp4文件就一切正常。

**复现步骤**
随便新建文章，或者往现有文章里插入音频文件均会如此。

**期望的正常结果**
像正常拖入mp4文件可正常播放一样。

**截图**
![IMG_8007](https://github.com/tangly1024/NotionNext/assets/10110689/223ea271-a676-4930-95e3-b59112dc400a)

**环境**

- 【必填】NotionNext版本 [例如. 4.1.1]
- 【必填】主题 [例如. medium]
- 【可选】操作系统: iOS, Android, macOS, windows 均不行
- 【可选】edge. chrome, safari

**补充说明**
【可选】与问题相关的其它说明

**Comment by cuiyanjie** [comment]
看了前端页面，发现音频的preload=no，视频的preload=auto ， 不知道是不是这个问题造成

**Comment by tangly1024** [comment]
感谢反馈。

更新至4.1.4即可
https://github.com/tangly1024/NotionNext/releases/tag/v4.1.4
