### ISSUE TITLE
4.1.1还是有pdf的问题

### ISSUE THREAD

**Issue by dadaoerv** [tangly1024/NotionNext#1675]
**描述bug**
![image](https://github.com/tangly1024/NotionNext/assets/46274596/4324a2fa-a7dd-4529-bb6b-86bb8e9dc657)

**复现步骤**
怎么操作都是这样

**期望的正常结果**
正常显示pdf文件
**截图**
![image](https://github.com/tangly1024/NotionNext/assets/46274596/c4d4c082-ef19-4d17-8b5b-3021e5b64e14)

**环境**

- 【必填】NotionNext版本 4.1.1
- 【必填】主题 [例如. hexo]
- 【可选】操作系统: [windows]
- 【可选】浏览器 chrome,

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
4.2.0 已修复此问题
