### ISSUE TITLE
[或许算是bug]更新最新版本之后,页面出现闪烁  

### ISSUE THREAD

**Issue by laogou717** [tangly1024/NotionNext#1681]
**描述bug**
部署新版的notionnext后,部署日志未见错误,点击博文会出现闪动,然后延迟一两秒自动进入博文。

**复现步骤**
可进入网站随便点击一篇博文即可复现,暂未进行回滚操作。
https:laogou717.com

**期望的正常结果**
正常情况应该是点击博文-进入正文-加载博文,现在貌似变成了 点击博文-闪烁加载博文-进入正文

**截图**
无

**环境**

- 【必填】NotionNext版本 [例如. 4.1.1]
- 【必填】主题 [例如. heo]
- 
**补充说明**
暂无

**Comment by tangly1024** [comment]
> 点击博文会出现闪动,然后延迟一两秒自动进入博文。

显然这不应该是预期发生的现象，似乎是页面跳转过程中发生了一次主题切换导致的。


一个暂时的解决方法， 不使用Notion-Config指定主题，而是在blog.config.js 或者环境变量中指定主题为heo，也许这会奏效

**Comment by laogou717** [comment]
正如您说的，它奏效了
