### ISSUE TITLE
【修改配置】更改heo主题的配置后，vercel平台会报错部署错误

### ISSUE THREAD

**Issue by beilove** [tangly1024/NotionNext#1688]
**描述遇到的问题**
更改heo主题的配置后，vercel平台会报错部署错误
报错提示我HERO_TITLE_LINK的逗号有问题，但是我尝试更改多次依然无效，

**相应配置**
这是我目前更改的 [配置](https://github.com/beilove/NotionNext/blob/main/themes/heo/config.js)
网站地址为 [https://blog.owouo.me](https://blog.owouo.me)
部署在vercel平台上，使用heo主题

**截图**
我的配置
![image](https://github.com/tangly1024/NotionNext/assets/70726513/f1cc5f77-4479-426b-94c1-c3489666808a)
报错截图
![image](https://github.com/tangly1024/NotionNext/assets/70726513/356edf92-a80a-4aba-9264-5c5f9040ce82)

**环境**
- 操作系统: Windows 11 专业版 22H2 22621.2715
- 浏览器: Chrome
- 版本:119.0.6045.200

**Comment by tangly1024** [comment]
检查此处的6个逗号

https://github.com/beilove/NotionNext/blob/3bdf137ca636e92bfbf27f18a7816eb44f4504f8/themes/heo/config.js#L21-L23


- 用英文半角逗号，不要使用中文全角
","  而非  "，“

![image](https://github.com/tangly1024/NotionNext/assets/15920488/a6816a03-8e02-4203-ab2d-c29e34b16522)

**Comment by beilove** [comment]
谢谢，但是我并未改动这里的内容（em现在好了
