### ISSUE TITLE
【更新冲突】Regarding branch conflicts during Fork project synchronization

### ISSUE THREAD

**Issue by gitlayzer** [tangly1024/NotionNext#1690]
I hope there will be less branch conflict problems in the future.

![image](https://github.com/tangly1024/NotionNext/assets/77761224/dfb9a227-4a7c-4d33-be91-fddec16e3061)

**Comment by tangly1024** [comment]
1. 备份自己改动的配置文件 例如 blog.config.js ，以及主题 /themes/xx/config.js 
2. 然后点击放弃5次提交
3. 然后就可以正常更新
4. 更新后，按照之前备份的配置文件，重新配置

更多更新相关，访问此文获取帮助 https://docs.tangly1024.com/article/how-to-update-notionnext
