### ISSUE TITLE
【友情链接】友情链接互换 Elog

### ISSUE THREAD

**Issue by LetTTGACO** [tangly1024/NotionNext#1695]
[Elog](https://github.com/LetTTGACO/elog)是一个多平台 Markdown 批量导出工具、开放式跨平台博客解决方案，随意组合写作平台(语雀/Notion/FlowUs/飞书)和博客平台(Hexo/Vitepress/Halo/Confluence/WordPress等)，当然也非常适用于其他常见文档平台的 markdown 导出

但是 Elog 所支持的 Notion 格式仅限于 markdown 格式，无法适配更多格式。通常如果有小伙伴来问是否可以支持 Notion 更多格式，我会向他们推荐 NotionNext

也有一部分小伙伴在使用 NotionNext 的过程中，也同时使用 Elog 给 Notion 的文档做一层本地文件备份。也包括我[自己的博客](https://github.com/LetTTGACO/blog.1874.cool)，也是基于NotionNext博客管理Elog文档备份的个人博客

我这边已经加上了 NotionNext 项目地址，希望可以相互推广

**Comment by tangly1024** [comment]
ok 

https://github.com/tangly1024/NotionNext#-%E5%8F%8B%E6%83%85%E9%93%BE%E6%8E%A5
