### ISSUE TITLE
更新 4.1.1之后，RSS只能抓取标题和头图，且RSS名为 NotionNext blog

### ISSUE THREAD

**Issue by Miobowl** [tangly1024/NotionNext#1696]
**描述bug**
更新 4.1.1之后，RSS只能抓取标题和头图，且RSS名为 NotionNext blog

**复现步骤**
RSS: https://miobowl.com/rss/feed.xml

**期望的正常结果**
应该能正常抓取summary和全文，且RSS名为我的博客名

**截图**
【可选】相关的页面，应该的结果

**环境**

- 【必填】NotionNext版本 4.1.1
- 【必填】主题 fukasawa
- 【可选】操作系统: [例如. iOS, Android, macOS, windows]
- 【可选】浏览器 [例如. chrome, safari, firefox]

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
> 且RSS名为 NotionNext blog

此项需要再环境变量或在blog.config.js 中修改 title , 暂时不支持NotionConfig

https://github.com/tangly1024/NotionNext/blob/4d04e7de5d4550c0e9e21d3a513ef971bd562114/blog.config.js#L391
