### ISSUE TITLE
建站天数显示异常

### ISSUE THREAD

**Issue by LBEILC** [tangly1024/NotionNext#1719]
**描述遇到的问题**
建站天数的部分显示异常, 尝试修改notion中所有文章的时间, 但建站天数未改变, 查阅项目文档也未找到对应的修改方法

**相应配置**
网站地址: https://[blog.lubeiluchen.cc](https://blog.lubeiluchen.cc/)/

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/74463574/13c84622-3853-49ad-b212-48ad093382ce)
![image](https://github.com/tangly1024/NotionNext/assets/74463574/e11ce900-b2b4-461c-bb24-4630d26f69fa)

**环境**

- 操作系统: windows
- 浏览器: edge
- 版本: V4.1.2

**Comment by jxpeng98** [comment]
建站天数是自定义的。

你需要在你的heo主题配置文件[config.js](https://github.com/LBEILC/NotionNext/blob/16b7ba49320f4ccdf56a40f22da3b3999a8ae2bc/themes/heo/config.js#L4)中修改。

找到
```
HEO_SITE_CREATE_TIME: '2021-09-21', // 建站日期，用于计算网站运行的第几天
```

然后改成你想要的时间就可以了。

**Comment by LBEILC** [comment]
> 建站天数是自定义的。
> 
> 你需要在你的heo主题配置文件[config.js](https://github.com/LBEILC/NotionNext/blob/16b7ba49320f4ccdf56a40f22da3b3999a8ae2bc/themes/heo/config.js#L4)中修改。
> 
> 找到
> 
> ```
> HEO_SITE_CREATE_TIME: '2021-09-21', // 建站日期，用于计算网站运行的第几天
> ```
> 
> 然后改成你想要的时间就可以了。

感谢解惑
