### ISSUE TITLE
Fork后Vercel部署部分的环境变量不生效

### ISSUE THREAD

**Issue by SenLief** [tangly1024/NotionNext#174]
比如主题和备案这两个都不生效，那个切换主题的设为true也不生效。

**Comment by tangly1024** [comment]
奇怪的是，在我的[站点中](https://preview.tangly1024.com)配置是生效的。
请再确认一下环境变量的变量名、环境名：
<img width="792" alt="image" src="https://user-images.githubusercontent.com/15920488/163101324-90a480f9-8bf0-484b-a139-35971a9a4dec.png">

并重试一下部署。
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/15920488/163101361-ff2a7922-359f-4536-8101-dff959723771.png">

**Comment by SenLief** [comment]
我fork后部署的分支不是main，默认给我部署的好像是theme那个，难道是这个的问题？

发自我的iPhone

在 2022年4月13日，12:39，tangly1024 ***@***.***> 写道：

﻿

奇怪的是，在我的站点中<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpreview.tangly1024.com%2F&data=04%7C01%7C%7C292a1541046b46664c0a08da1d0797f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637854215693283669%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=u2WcVs6Z5pfTuw5AoluORUCl0ZsEOU2VwxKDdPyDmn0%3D&reserved=0>配置是生效的。
请再确认一下环境变量的变量名、环境名：
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F15920488%2F163101324-90a480f9-8bf0-484b-a139-35971a9a4dec.png&data=04%7C01%7C%7C292a1541046b46664c0a08da1d0797f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637854215693283669%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=e8wVFmqDT8z0JOLj06ZupzFW6AK4ZdJNLxz%2BUAmasgg%3D&reserved=0>

并重试一下部署。
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F15920488%2F163101361-ff2a7922-359f-4536-8101-dff959723771.png&data=04%7C01%7C%7C292a1541046b46664c0a08da1d0797f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637854215693283669%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=a9Y4V%2FyJygXsRXufO4I79V5I5jU6tira0nmUbJuZurY%3D&reserved=0>

**Comment by tangly1024** [comment]
> 我fork后部署的分支不是main，默认给我部署的好像是theme那个，难道是这个的问题？

可能就是这个导致的，需要部署main分支。

**Comment by SenLief** [comment]
确实是的，重新建立一个项目就可以了。
