### ISSUE TITLE
Notion 中添加音频后，网页无法播放

### ISSUE THREAD

**Issue by VamRed** [tangly1024/NotionNext#1753]
**Notion 中添加`音频`后，网页无法播放**

**Notion中通过`本地文件`的方式上传音频（notion界面可正常播放），网页端（不可播放）**

**网页端（可正常播放）**

**NotionNext `4.1.3`丨主题 `Heo`丨Windows丨Chrome**

注：

例如，notion文档中的直链为
https://file.notion.so/f/f/daa348b6-73fc-4c1b-bb35-d5622df32427/8793ccec-e394-404e-a2af-bc0cc3302ab3/7gm59KVXfG8wEAfN3Lv2Xu_(1).mp3?id=306ca9ae-01a8-483c-ba8f-e9ba6d5ea48b&table=block&spaceId=daa348b6-73fc-4c1b-bb35-d5622df32427&expirationTimestamp=1704787200000&signature=MhciOdNnyul2QDcrT36cbGr72_XDJBChgIUxuFBgcnI&downloadName=7gm59KVXfG8wEAfN3Lv2Xu+%281%29.mp3

但在博客源代码中，发现直链变成了
https://prod-files-secure.s3.us-west-2.amazonaws.com/daa348b6-73fc-4c1b-bb35-d5622df32427/8793ccec-e394-404e-a2af-bc0cc3302ab3/7gm59KVXfG8wEAfN3Lv2Xu_(1).mp3

@tangly1024 请问大佬该如何解决此问题QAQ

**Comment by tangly1024** [comment]
感谢反馈。

更新至4.1.4即可
https://github.com/tangly1024/NotionNext/releases/tag/v4.1.4
