### ISSUE TITLE
【如何备份文件】有没有博客备份的方法

### ISSUE THREAD

**Issue by MicroMatrixOrg** [tangly1024/NotionNext#1758]
**为什么提出这个新的特性改动**
希望博客能备份文章成markdown文件，notion自带的只能一个个的备份

**描述一下你推荐的解决方案**
如果能批量备份成markdown文件就不用当心博客文件丢失了

**描述一下你考虑过的其它替代解决方案**
我发现notion的每篇文章的url连接除了page那一块不变，只有p的参数改变了，大佬能否考虑下备份的功能

**补充说明**
补充与此特性相关的内容

**Comment by tangly1024** [comment]
可以参考一下这个： https://github.com/LetTTGACO/elog

**Comment by MicroMatrixOrg** [comment]
> 可以参考一下这个： https://github.com/LetTTGACO/elog

非常感谢，大佬，我完成了同步，这是个非常不错的项目。
