### ISSUE TITLE
【升级Twikoo】不知道是bug还是什么？twikoo版本问题

### ISSUE THREAD

**Issue by kuheg** [tangly1024/NotionNext#1770]
**描述遇到的问题**
无论怎么升级，所有的都尝试升级到最新版本，结果都是twikoo v1.6.17，twikoo的最新版为1.6.29
想升级到最新版本，最新版本新增验证码功能，能有效的防止垃圾评论。

请问该怎么解决问题
**截图**
![image](https://github.com/tangly1024/NotionNext/assets/130907071/5674bcba-bfb5-408f-ab4a-1864c2f74a66)

**环境**

- 操作系统:  windows
- 浏览器  chrome
- 版本 [ NotionNext 4.1.4]

**Comment by 1208nn** [comment]
twikoo不支持自动升级，需要自行升级前端 `COMMENT_TWIKOO_CDN_URL` 参见[配置入门](https://docs.tangly1024.com/article/how-to-config-notion-next)

<https://github.com/tangly1024/NotionNext/blob/main/blog.config.js#L247C74-L247C74>

**Comment by kuheg** [comment]
谢谢，终于找到解决方法
我找了很多方法，无论是twikoo还是NotionNext 都更新到最新版都是一样v1.6.17，还以为是自己出问题了

感谢大佬和作者大佬。解答了我的疑惑，非常棒的项目！
