### ISSUE TITLE
【目录】设置密码的文章目录无法显示，输入密码后，目录功能会失效

### ISSUE THREAD

**Issue by VamRed** [tangly1024/NotionNext#1772]
**heo主题下，上锁的文章，输入密码后，目录功能会失效（移动端会，电脑端未查看）**

**heo主题下，打开一篇上锁的文章，会发现无目录按钮及功能**

**上锁文章解锁后，同普通文章一样拥有目录，不影响读者阅读体验**

**环境：4.1.14丨HEO丨IOS丨Chrome**

QAQ多次修改代码无效，求救@tangly1024大佬
**注意：文章上锁这里，还有一个可以小优化的地方（不算bug,以后有机会可优化），文章开锁后，在输入密码时在移动端（主要是手机端）会缩放，每次都需要手动放大，影响体验，不知是跟浏览器设置相关，还是可以在代码中修改**

**Comment by tangly1024** [comment]
https://github.com/tangly1024/NotionNext/issues/1655
此issue和先前的[issue](https://github.com/tangly1024/NotionNext/issues/1655)内容重复，将在上一个issue中讨论。
