### ISSUE TITLE
支持clarity

### ISSUE THREAD

**Issue by DoiiarX** [tangly1024/NotionNext#1823]
**为什么提出这个新的特性改动**
支持clarity，能重放用户行为，更好的分析优化网站。

**描述一下你推荐的解决方案**
在这里引入clarity
https://clarity.microsoft.com/

**描述一下你考虑过的其它替代解决方案**
无。这是微软新特性。

**补充说明**
无

**Comment by tangly1024** [comment]
已添加，在 blog.config.js 中配置CLARITY_ID即可，ID来自这里：
![image](https://github.com/tangly1024/NotionNext/assets/15920488/195dc8f1-298e-4278-aae2-ac9c5365233d)

![image](https://github.com/tangly1024/NotionNext/assets/15920488/bce855c5-3aeb-4063-9616-3db9eba4f8e6)

添加后，基本上马上就能在微软的后台看到实时动作视频：

![image](https://github.com/tangly1024/NotionNext/assets/15920488/2edaba0b-9134-4441-bced-06bfcfbcf874)
