### ISSUE TITLE
【文章丢失】A分类增加一篇文章，B分类就会减少一篇文章

### ISSUE THREAD

**Issue by Oliverwqcwrw** [tangly1024/NotionNext#1824]
**描述bug**
【此项必填】简单说明bug的现象、相关的错误提示、日志等

A分类增加一篇文章，B分类就会减少一篇文章
<img width="907" alt="image" src="https://github.com/tangly1024/NotionNext/assets/31796988/94c3aeaa-0531-472d-853d-87e165bf1956">
如图
技术分享增加一篇，Java八股文分类就减少一篇，总数卡到86不变(已经写了120篇文章左右了，一直是86)

**复现步骤**
【此项必填】出现这个bug的操作步骤

新增一篇技术分享分类的文章

**期望的正常结果**
【此项必填】希望按这个步骤，正常操作结果是什么

文章数量统计没有问题

**截图**
【可选】相关的页面，应该的结果

**环境**

- 【必填】NotionNext版本 [例如. 4.0.18] 4.1.4
- 【必填】主题 [例如. hexo] hexo
- 【可选】操作系统: [例如. iOS, Android, macOS, windows] macOS
- 【可选】浏览器 [例如. chrome, safari, firefox] chrome

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
请尝试升级最新版本，验证此问题

**Comment by Oliverwqcwrw** [comment]
升级最新版本之后，统计没有问题了， 膜拜大佬
