### ISSUE TITLE
vercel部署出现Error: Command "npm run build" exited with 1

### ISSUE THREAD

**Issue by steady298** [tangly1024/NotionNext#1832]
**描述遇到的问题**
严格按照网站上部署的打野50秒左右报错

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/115759238/661f00f3-d331-4f1d-9b08-5ec33cd48ed0)

**Comment by tangly1024** [comment]
似乎是上午更新的代码有问题，稍等我检查一下

**Comment by tangly1024** [comment]
已修复 更新代码版本即可

**Comment by steady298** [comment]
> 已修复 更新代码版本即可

正常了 谢谢大佬
