### ISSUE TITLE
【图片封面】更新最新版本后所有的文章列表预览图都变成了封面图

### ISSUE THREAD

**Issue by Shadownc** [tangly1024/NotionNext#1838]
**描述bug**
【此项必填】更新最新版本后所有的文章列表预览图都变成了封面图

**复现步骤**
【此项必填】所有的主题都一样

**期望的正常结果**
【此项必填】恢复文章自带的列表图

**环境**

- 【必填】NotionNext版本 最新版
- 【必填】主题 所有主题包含列表图的
- 【可选】操作系统: iOS, Android, macOS, windows
- 【可选】浏览器 chrome, safari, firefox

**Comment by tangly1024** [comment]
已解决，此issue重复 https://github.com/tangly1024/NotionNext/issues/1833
