### ISSUE TITLE
【cloudflare不会同步文章】但每次在notion更新内容后，pages上的网站不会更新

### ISSUE THREAD

**Issue by shadowstar2023** [tangly1024/NotionNext#1839]
**描述遇到的问题**
同时在vercel和cloudflare部署了网站，但每次在notion更新内容后，vercel部署的网站会更新，但pages上的网站不会更新

**相应配置**
使用的同一个notion_id,如果想让pages上部署的网站也更新内容的话，必须要重新部署一下才可以，就算把域名的缓存清除了也无用

**截图**
无

**环境**

- 操作系统: [windows]
- 浏览器 [ chrome]
- 版本 [e.g. 22]

**Comment by tangly1024** [comment]
CloudFlare Pages 是导出静态文件，不支持实时更新.实时更新请使用Vercel\Netlify\Zeabur\VPS部署方案

**Comment by shadowstar2023** [comment]
OK
