### ISSUE TITLE
【nav主题】post类型数据能否在slug中添加链接直接跳转置顶网址

### ISSUE THREAD

**Issue by laogou718** [tangly1024/NotionNext#1848]
**作为一个导航主题页面，如果支持无中间页跳转就更好了**
『打算做一个工具合集，也就是导航站，并不需要大段文章来介绍每个网站的功能，只需在summary中做简短介绍就行』

**描述一下你推荐的解决方案**
暂无

**描述一下你考虑过的其它替代解决方案**
我看了您的博客的所有教程，没有找到关于这个的描述 。

**补充说明**
现在是这样的情况，我在notion种这样设置的   下图
![image](https://github.com/tangly1024/NotionNext/assets/139377884/7fcf2856-8fae-49bd-bb89-eb0f9bc989cb)

然后我在主页点击它，本希望可以直接跳转到我填写的网站种，但是现在是下面这样 
![image](https://github.com/tangly1024/NotionNext/assets/139377884/ff2bf46f-ae54-4603-9c1e-4e58d6aabb7e)
![image](https://github.com/tangly1024/NotionNext/assets/139377884/2525af8f-b13f-4ec3-bbf4-2b0241b5e97c)

**Comment by tangly1024** [comment]
支持的 , https://ct.ued.cat/? 这个导航网站就是用这种方式。
 
检查一下url ， 把 https:/linux.do/t/topic/1051.html 换成  https://linux.do/t/topic/1051.html 试试(后者在：后面多了一个/ )

**Comment by laogou718** [comment]
> 支持的 , https://ct.ued.cat/? 这个导航网站就是用这种方式。
> 
> 检查一下url ， 把 https:/linux.do/t/topic/1051.html 换成 https://linux.do/t/topic/1051.html 试试(后者在：后面多了一个/ )

## 我遇到的似乎是一个网址重定向的问题，可能是我描述和操作上有误。
- 具体来说，当我尝试在slug中填写正确的URL并点击时，它并未正常重定向，而是错误地将动作解析为打开博文。
- 例如，我输入的URL是 https://XXX，但在点击后，网址变成了 www.我的域名.com/https:/XXX，这显然不是我预期的结果。

我注意到您分享的链接点击后会有一个重定向的动作，这让我思考可能是我的某些配置出了问题。我不确定是哪个环节出现了问题，所以我想向您寻求一些建议。

如果您对此有任何思路或建议，我将非常感激。

**Comment by laogou718** [comment]
> > 支持的 , https://ct.ued.cat/? 这个导航网站就是用这种方式。
> > 检查一下url ， 把 https:/linux.do/t/topic/1051.html 换成 https://linux.do/t/topic/1051.html 试试(后者在：后面多了一个/ )
> 
> ## 我遇到的似乎是一个网址重定向的问题，可能是我描述和操作上有误。
> * 具体来说，当我尝试在slug中填写正确的URL并点击时，它并未正常重定向，而是错误地将动作解析为打开博文。
> * 例如，我输入的URL是 [https://XXX，但在点击后，网址变成了](https://XXX%EF%BC%8C%E4%BD%86%E5%9C%A8%E7%82%B9%E5%87%BB%E5%90%8E%EF%BC%8C%E7%BD%91%E5%9D%80%E5%8F%98%E6%88%90%E4%BA%86) [www.我的域名.com/https:/XXX，这显然不是我预期的结果。](http://www.%E6%88%91%E7%9A%84%E5%9F%9F%E5%90%8D.com/https:/XXX%EF%BC%8C%E8%BF%99%E6%98%BE%E7%84%B6%E4%B8%8D%E6%98%AF%E6%88%91%E9%A2%84%E6%9C%9F%E7%9A%84%E7%BB%93%E6%9E%9C%E3%80%82)
> 
> 我注意到您分享的链接点击后会有一个重定向的动作，这让我思考可能是我的某些配置出了问题。我不确定是哪个环节出现了问题，所以我想向您寻求一些建议。
> 
> 如果您对此有任何思路或建议，我将非常感激。

<img width="1225" alt="image" src="https://github.com/tangly1024/NotionNext/assets/139377884/76da55eb-19d7-4409-ac5d-5e3b70e31734">

**Comment by tangly1024** [comment]
了解了，这似乎是一个bug，我会修复一下
