### ISSUE TITLE
【nav主题】 报错 a client-side exception

### ISSUE THREAD

**Issue by tammyxx** [tangly1024/NotionNext#1853]
**描述bug**
【此项必填】当默认主题为nav主题时，会出现报错。notion内容不会显示。Uncaught TypeError: Cannot destructure property 'filteredNavPages' of '(0 , l.useNavGlobal)(...)' as it is undefined.     at t.default (35400.53ad126b7f69527b.js:1:20995)     at ak (framework-ce11a3e4adbecdb7.js:9:60903)     at i (framework-ce11a3e4adbecdb7.js:9:119424)     at oD (framework-ce11a3e4adbecdb7.js:9:99077)     at framework-ce11a3e4adbecdb7.js:9:98944     at oO (framework-ce11a3e4adbecdb7.js:9:98951)     at oP (framework-ce11a3e4adbecdb7.js:9:96037)     at r8 (framework-ce11a3e4adbecdb7.js:9:44813)     at oV (framework-ce11a3e4adbecdb7.js:9:113296)     at o (framework-ce11a3e4adbecdb7.js:9:107711)

**复现步骤**
【此项必填】当在notion的配置文件里主题设置为nav

**期望的正常结果**
【此项必填】没有报错，可以正常显示内容

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/67304472/1887b8cd-0f33-4467-b082-546f9a9ef9c0)

**环境**

- 【必填】NotionNext版本  4.2.2
- 【必填】主题 nav
- 【可选】操作系统:windows
- 【可选】浏览器chrome

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
无法复现此问题 ， 需提供访问网址，以及对应的NOTION_PAGE_ID

**Comment by Phillweston** [comment]
https://github.com/tangly1024/NotionNext/pull/2417
