### ISSUE TITLE
[Zeabur部署] 无法访问博文、点击头像,自动跳转/404页面;以及slug为外链情况处理

### ISSUE THREAD

**Issue by laogou718** [tangly1024/NotionNext#1861]
**描述bug**
【此项必填】点击头像或者访问博文bug就会访问识别并且自动跳转/404页面,但描述图片显示正常。
<img width="2558" alt="image" src="https://github.com/tangly1024/NotionNext/assets/139377884/68b11e19-d825-4c2e-ba89-2e0be296c14a">

**复现步骤**
## 大佬可以在下面链接里查看
- 网站:https://nva.zeabur.app/
- fork地址:https://github.com/laogou718/nav
- notion共享页面及ID:https://efficient-crop-f9b.notion.site/7d4fe76137e1499796c535ea773c1c30?v=fec883153e4648f990b7c46ca6c5fb42&pvs=4
**期望的正常结果**
略

**截图**
[未做任何操作时]
<img width="2555" alt="image" src="https://github.com/tangly1024/NotionNext/assets/139377884/ec0d6b20-d159-4ce9-afa2-284b7a419fbe">
[点击头像或者侧边栏的副标题后]
<img width="2553" alt="image" src="https://github.com/tangly1024/NotionNext/assets/139377884/1e82c9fc-d224-4fd0-aaa0-84b8c5a5b2ec">

**环境**

- 【必填】NotionNext版本 [例如. 4.2.2]
- 【必填】主题 [例如. nav、heo均有此问题]
- 【可选】操作系统: [macOS, windows]
- 【可选】浏览器 [chrome, safari, arc]

**补充说明**
## 基本情况
昨天，我在 GitHub 的 [issues/1848](https://github.com/tangly1024/NotionNext/issues/1848) 上反馈了关于 `nav` 主题重定向的问题。然而，今天我收到消息，我的博客所有文章都无法打开，尽管文章封面和描述都正常显示。
## 猜测可能的原因
- 我目前部署了两个 NotionNext 项目，一个使用 `heo` 主题作为博客页面，另一个则是部署了 `nav` 主题。它们都使用同一个 Notion 账号中的不同数据表和 ID。此外，变量有相同的是google ads [这个还没有配置,只是把变量先加了上去]。
- 在向您反馈之前，我尝试创建了一个新的 Notion 账号，并将原有数据表复制过去，但问题依旧存在。我还查阅了过往的 issues，未能找到类似问题的解决方法。
## 已采取的措施
为了解决这个问题，我尝试将项目恢复到之前正常运行的状态，但问题依然没有解决。
我非常重视和喜欢这个项目，并希望能尽快解决这个问题。如果您能提供任何建议或解决方案，我将不胜感激。
最后谢谢您抽出宝贵时间阅读我的问题，期待您的回复。祝好.

**Comment by tangly1024** [comment]
已收到反馈，我排查一下

**Comment by tangly1024** [comment]
# 部署方式问题
可能和您目前是用的 zeabur 部署方案有关系。


## 1. 进行bug复现的测试
我刚尝试拉取您的代码，在本地进行部署，链接您的Notion_ID进行搭建网站，一切访问都是正常的。我没有在zeabur中部署测试。

## 2.导致bug的直接原因
> 点击头像或者访问博文bug就会访问识别并且自动跳转/404页面,但描述图片显示正常。
在点击头像或者博文时，页面会请求响应的数据文件，通常他会放回一个json格式的数据包。但是在您的页面上，请求数据返回的内容是异常的。

- 点击头像的异常数据地址：
  https://nva.zeabur.app/_next/data/SDIyTVkPEh37nprHmZHdp/index.json

- 点击【访问测试】这篇文章返回的异常数据地址：
  https://nva.zeabur.app/_next/data/SDIyTVkPEh37nprHmZHdp/LG/717.json?prefix=LG&slug=717

xx/_next/data/xxx.json 这个目录是专门用于请求页面数据的，但是在您的网页中都失效了。

# 使用Vercel部署或Cloudflare部署

## 正常的数据示例

- 我的首页json数据
  https://blog.tangly1024.com/_next/data/Vstn5NatLZSn7SGahCkUy/index.json

- 我的文章页json数据
  https://blog.tangly1024.com/_next/data/Vstn5NatLZSn7SGahCkUy/article/habits.json?prefix=article&slug=habits

可能需要花时间研究一下zeabur的机制，求助一下对方的技术人员。或者切换成vercel或者netlify等其他部署

**Comment by laogou718** [comment]
原因不明,但我换了账号清除了之前的更改,已经解决。
感谢开发者的耐心回复,祝好。

**Comment by laogou718** [comment]
## 在使用 NotionNext 项目并进行多次测试后，我观察到了一个可能的规律

### 问题描述
我在进行多账号测试时发现了一个可能的小 Bug，这个问题在我的环境中可以百分之百复现。具体来说，问题出现在我的 NotionNext 项目中，与 `post` 文件的 `slug` 字段相关。

### 重现步骤
1. 当我在 `post` 文件的 `slug` 中添加了链接时，项目构建过程中会出现错误。
2. 为了解决这个问题，我尝试了以下步骤：
   - 首先，对比了多个账号的表格发现部署成功的数据库无一例外,它们的post文件的slug都没有填写外部链接。
   - 我隐藏了所有 `slug` 字段为链接的 `post` 表格。然后，我成功地部署了项目。
   - 最后，在 Notion 中将之前隐藏的 `post` 重新设为可见，这样做之后，链接可以正常识别。
   - 基于这些观察，我得出一个初步的结论,尽管它可能不是绝对准确的：Notion 数据库中 post 数据的 slug 字段若写入外部链接，可能会在项目的第一次部署时导致构建问题。这个问题对于后续的项目更新似乎没有影响。

### 补充
我希望能获得您的帮助以确认这是否为一个普遍存在的问题，以及是否有更有效的解决方法。希望这个发现有可能对改善 NotionNext 项目有所帮助。

**Comment by tangly1024** [comment]
## 是一个普遍存在的bug
感谢您详细的内容描述，如您所见 ，当post的slug为外链时会影响打包编译，这是一个以前未考虑的到问题。 往常外链只作用于菜单栏，例如 Menu或者Page这种类型。

## 此bug出现的原因
后续加入Nav主题后，才有此特性：允许post的地址是一个外链，方便直接导航。
这个特性还有很多未知的风险，需要检测并且修复。

## 目前的想法
先解决打包编译的问题；在打包时，检查Post是否是外部文章，若是，则跳过编译此文章的内容。

**Comment by tangly1024** [comment]
修复此打包问题的代码已经提交 https://github.com/tangly1024/NotionNext/pull/1865

**Comment by betears** [comment]
slug为中文的时候，就访问不了，出现404，slug为英文的时候，就能正常访问。

**Comment by tangly1024** [comment]
> slug为中文的时候，就访问不了，出现404，slug为英文的时候，就能正常访问。

4.2.4 中解决了中文slug无法访问的问题: 相关issue： https://github.com/tangly1024/NotionNext/issues/1864#issuecomment-1922764194
