### ISSUE TITLE
【网页Title】浏览器标签中的内容无法正确显示

### ISSUE THREAD

**Issue by lainbo** [tangly1024/NotionNext#1862]
**描述bug**
浏览器的标签内容, 也就是document.title的内容缺少了文章标题或者页面标题
![image](https://github.com/tangly1024/NotionNext/assets/46062895/a4bfd868-ea26-4c03-96c0-a2d04b4eb333)

**复现步骤**
打开官方作者的blog https://blog.tangly1024.com/article/habits 即可观察到这个现象

**期望的正常结果**
应当有当前页面的标题

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/46062895/8f400a35-c8d7-4bc1-9e82-8e6d277904fb)

**环境**

- 【必填】NotionNext版本 4.0.22
- 【必填】gitbook、next
- 【必填】vps
- 【可选】Windows
- 【可选】chrome

**补充说明**

**Comment by tangly1024** [comment]
收到反馈，bug已修复
