### ISSUE TITLE
【404】当url为中文时页面丢失，文章分类横幅点击跳转页面数据丢失

### ISSUE THREAD

**Issue by TA961215** [tangly1024/NotionNext#1864]
**描述bug**
点击【文章分类横幅-技术分享】跳转到页面所有分类不显示，重新刷新当前页面则又正常显示
![image](https://github.com/tangly1024/NotionNext/assets/48305781/5ddfe266-b5f2-4144-906b-e56ea119aa44)
![image](https://github.com/tangly1024/NotionNext/assets/48305781/cfde2771-2750-4cbf-92a6-dc1c174a4450)

**复现步骤**
网站地址:https://blog-hellolbz-bug.vercel.app/?theme=heo
fork地址:https://github.com/TA961215/NotionNext
notion共享页面及ID:https://voracious-sycamore-efa.notion.site/417350174ba64363bf5c6d41d28f956c?v=d0c393db3b2e47d1a541687141eed59e&pvs=4

**期望的正常结果**
分类正常显示

**截图**

**环境**

- 【必填】NotionNext版本 [4.2.2]
- 【必填】主题 [HEO]
- 【必填】部署方案 [Vercel]
- 【可选】操作系统: [windows]
- 【可选】浏览器 [chrome]

**补充说明**
本地部署启动测试是正常的

**Comment by tangly1024** [comment]
## 令人头疼
这个bug有点玄乎，数据正常，部署正常。
同时除了heo主题，观察后发现，其它主题的分类文章也丢失了，因此排除了主题样式问题，而是编译的数据问题。
![image](https://github.com/tangly1024/NotionNext/assets/15920488/8a1f0988-9fc5-4f94-83fb-62012b4ad9b5)


## 建议
先这样，今天提交了几个编译数据相关的补丁，可能会导致这个bug，请先尝试拉取最新代码试一下，如果问题还存在，我再跟进。

**Comment by zangguojun** [comment]
想问后续如果next最新版修复了此bug，会升级到最新版本吗？14版本的一些新东西还是挺好玩的

**Comment by lxw15337674** [comment]
https://github.com/vercel/next.js/issues/33470#issuecomment-1018732126 
@tangly1024 看下这个解决方法
