### ISSUE TITLE
[站点地图]谷歌seo无法抓取站点地图

### ISSUE THREAD

**Issue by lxw15337674** [tangly1024/NotionNext#1875]
**描述bug**
谷歌seo无法抓取站点地图。我用的是vercel默认分配的域名，难道必须要独立的域名才能抓取吗？还是需要做哪些配置？

**复现步骤**
【此项必填】出现这个bug的操作步骤

**期望的正常结果**
【此项必填】希望按这个步骤，正常操作结果是什么
谷歌seo正常抓取站点地图
**截图**
【可选】相关的页面，应该的结果
![image](https://github.com/tangly1024/NotionNext/assets/19898669/0acfc24e-280a-420e-bf77-bff0aceb0292)

**环境**
- 【必填】NotionNext版本 [例如. 4.0.18]
- 【必填】主题 [例如. hexo]
- 【必填】部署方案 [例如. vercel]
- 【可选】操作系统: [例如. iOS, Android, macOS, windows]
- 【可选】浏览器 [例如. chrome, safari, firefox]

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
可能是sitemap生成失败  重复提交试一下

**Comment by lxw15337674** [comment]
> 可能是sitemap生成失败 重复提交试一下
没有生成失败，我通过url可以直接访问到
![image](https://github.com/tangly1024/NotionNext/assets/19898669/b185f3c3-e016-422b-8097-5e2ef481801c)

**Comment by sun510001** [comment]
可能是谷歌的问题, 相同地址的情况下 bing 可以抓取站点地图, 但是 google 就显示抓取失败.

**Comment by tangly1024** [comment]
猜测可能是google 偶然的抓取失败；或者google对于vercel.app这个域名抓取的限制
 
1. 也许可以多试几次，因为只要这个sitemap.xml文件存在，总是能抓取到
2. 换个域名

**Comment by fatekey** [comment]
这个问题困扰我一年多了，别的搜索引擎都能抓取，就谷歌报这个错误。

**Comment by lxw15337674** [comment]
结论：确实是只有谷歌会报这个错误。

**Comment by ominipcba** [comment]
> 结论：确实是只有谷歌会报这个错误。

请问这个问题最后解决了吗？我也遇到同样的问题，bing正常，google提示无法抓取sitemap

**Comment by IhaveBB** [comment]
检查一下生成的sitemap.xml文件里面，是否存在报错。可以看看这个https://github.com/typecho-fans/plugins/issues/151
