### ISSUE TITLE
【公告中因GalleryView报错】突然无法在Heo主题下的公告中使用GalleryView且会导致编译部署错误

### ISSUE THREAD

**Issue by qixing-jk** [tangly1024/NotionNext#1881]
**描述bug**
具体报错信息为：
- 在部署的预渲染阶段出现（可正常获取页面数据和配置数据库）
TypeError:Cannot read properties of undefined (reading '72eef94f-e219-4eb0-ab19-35c8e99e36bc')
排查结果为：
公告界面，因含有**GalleryView视图**而导致报错，删除后再次部署成功，但部署成功后**恢复原有内容，再次导致报错，且报错信息一致**
![Clip_20240206_214535](https://github.com/tangly1024/NotionNext/assets/125447674/05ea2e86-ccc8-4068-8639-7c29cac44603)
**复现步骤**
Heo主题，在公告界面配置一个GalleryView的数据库视图

**期望的正常结果**
可以正常渲染，在先前版本是可以正常渲染的（出现问题时的提交为 https://github.com/qixing-jk/Notion-Website/commit/1184d08b4984f10948eb001c03af1c6f1752040c ）

**环境**

- 【必填】版本 NotionNext版本 4.2.4（合并 main分支的01620a0ee8b733b621d20c4561ee139eeebd30e8提交后）
- 【必填】主题 heo
- 【必填】部署环境 Vercel
- 【可选】操作系统 windows
- 【可选】浏览器 chrome

**补充说明**
具体情况没有调查，因能力不足以了解整个项目的更改情况，根据错误可知是在Notion渲染部分的第三方包报错的，但也可能是本项目的调用方式改变或第三方包的版本升级等原因导致

**Comment by tangly1024** [comment]
感谢反馈！
已定位到问题，并将修复
