### ISSUE TITLE
【vercel部署】2月6日update branch后更新部署失败

### ISSUE THREAD

**Issue by yoghurtlee-thu** [tangly1024/NotionNext#1883]
**描述遇到的问题**
如题，在合并2月6日的提交后，vercel发生了部署失败，错误为400 Bad Request，但是我直到今晚才发现。

**相应配置**
网站地址：https://yoghurtlee.com
主题：Hexo（更改为matery失败）
Notion pageID：dc9aea5a7990498384a208b79b5f0757

**截图**
Github相关信息：
<img width="1313" alt="image" src="https://github.com/tangly1024/NotionNext/assets/146422759/e6eb641d-586e-43e3-b90c-b0d99f9f1c34">
Vercel相关信息：
<img width="1409" alt="image" src="https://github.com/tangly1024/NotionNext/assets/146422759/ad26846d-c35f-463e-8ce0-62bb210cc559">

**环境**

- 操作系统: macOS
- 浏览器 edge
- 版本 NotionNext 4.2.4，edge 121.0.2277.106 (正式版本) (arm64)

**Comment by tangly1024** [comment]
你好，
Vercel部署失败，指的是代码重新编译异常。这部分日志，需要在vercel的deployment 面板中找到。
![image](https://github.com/tangly1024/NotionNext/assets/15920488/defeb712-64f3-45f9-b659-5f50249da39e)


你截图中的内容是网站中运行时的警告提示，并不影响站点运行。

**Comment by yoghurtlee-thu** [comment]
开发大大您好，目前发生的的确是部署错误，造成Github和Notion的任何更改都无法成功更新。

这是报错截图和相关错误信息，希望能得到您的帮助，不胜感激。

TypeError [ERR_INVALID_URL]: Invalid URL
--
13:12:14.606 | at new NodeError (node:internal/errors:405:5)
13:12:14.606 | at new URL (node:internal/url:637:13)
13:12:14.606 | at compressImage (/vercel/path0/.next/server/chunks/4925.js:2002:20)
13:12:14.607 | at mapImgUrl (/vercel/path0/.next/server/chunks/4925.js:1977:15)
13:12:14.607 | at getPageProperties (/vercel/path0/.next/server/chunks/3151.js:1087:89)
13:12:14.607 | at getDataBaseInfoByNotionAPI (/vercel/path0/.next/server/chunks/3151.js:897:105)
13:12:14.607 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
13:12:14.608 | at async getNotionPageData (/vercel/path0/.next/server/chunks/3151.js:661:16)
13:12:14.608 | at async getGlobalData (/vercel/path0/.next/server/chunks/3151.js:584:18)
13:12:14.608 | at async getStaticPaths (/vercel/path0/.next/server/pages/[prefix]/[slug]/[...suffix].js:61:27) {
13:12:14.608 | input: 'https%3A%2F%2Fooo.0x0.ooo%2F2024%2F02%2F05%2FOvGavx.webp?t=2eeb553a-de8c-49e2-85c2-dcb7ce74541e',
13:12:14.609 | code: 'ERR_INVALID_URL'
13:12:14.609 | }
13:12:14.609 |  
13:12:14.610 | > Build error occurred
13:12:14.612 | Error: Failed to collect page data for /[prefix]/[slug]/[...suffix]
13:12:14.612 | at /vercel/path0/node_modules/next/dist/build/utils.js:1130:15
13:12:14.613 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
13:12:14.613 | type: 'Error'
13:12:14.613 | }
13:12:14.715 | error Command failed with exit code 1.
13:12:14.715 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
13:12:14.739 | Error: Command "yarn run build" exited with 1



<img width="1328" alt="image" src="https://github.com/tangly1024/NotionNext/assets/146422759/2f8265f1-ce96-4f57-817c-77de473cb126">

**Comment by yoghurtlee-thu** [comment]
目前问题已经找到了（通过猜报错信息的含义），可能是我的一个图床坏掉了导致的无效URL，改掉就可以了。很抱歉耽误您的时间了，祝您新年快乐(\*^▽^\*)
