### ISSUE TITLE
[Notion文章导入] notion 中有一些其他文章如何导入到博客中

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#190]

**Comment by tangly1024** [comment]
将文章复制并粘贴到博客列表中即可。

**Comment by tangly1024** [comment]
> 是否可以去支持链接的文章

也许是个不错的提议

**Comment by tangly1024** [comment]
然而技术上无法实现这种引用。

在Notion的数据格式中，链接的文章无法直接取到标题的，而需要调用接口单独查询此页面的数据信息。
这样的结果是，访问博客列表时需要额外查询每个外链的博客信息，对性能有损耗。

**Comment by tangly1024** [comment]
非常感谢你的提议，我在这里解释一下NotionNext（NNext）的工作原理，并描述一下我的考虑，

1.NNext在编译部署时，会请求notion中的所有页面信息，并将数据打包到server中，输出成静态，从而达到最快的访问速度。

2.然而项目在线上时访问文章表时，NNext还是会重新请求一次Notion，来同步博客列表，以确保已有文章信息的标题、描述等更新信息，同时抓取到最新的博文。此时如果文章有引用的外部页面，就需要为这个页面单独请求一次接口，仅仅只是为了获取此Notion页面的标题。

3. NNext在真正访问每个文章详情时，首先会在打包的静态资源中查找数据、其次在内存缓存中查找、最后都找不到的情况会请求Notion数据。

**Comment by tangly1024** [comment]
如果你理解到了我所提的这块问题，我能想到的一种解决方式，就是需要在表格中加入一个新字段来支持```引用文章```功能
如图：在原有属性不变的情况下，引用文章单独加入了一个 realate 属性
<img width="1021" alt="图片" src="https://user-images.githubusercontent.com/15920488/168197516-63be77e2-c1f4-4b1d-af54-04b65096846f.png">

**Comment by lhuafmaof** [comment]
刚好遇到同样的问题，发现可以用notion的同步块来解决，不用折腾了。

**Comment by lhuafmaof** [comment]
> > 刚好遇到同样的问题，发现可以用notion的同步块来解决，不用折腾了。
> 
> Hi，借助‘同步块’如何解决此问题，可以描述一下吗😁

我目前的情况是这样的：
文章a：是我原本撰写好的，比较系统性的文章。
文章b：是我放到你框架里面，准备发布的文章。
之前的办法是复制，但是文章a我会不断的更新，所以同步是个问题。

现在的步骤：
1、在文章a中添加一个同步块。
2、然后把文章a中需要同步的内容放到块内。
3、然后再把这个同步块放到你的框架的那篇文章b中。
就实现了需要的效果。

具体如下：
![image](https://user-images.githubusercontent.com/33141484/172785793-6e1692a7-a788-4e35-adc6-25954e1d9693.png)
![image](https://user-images.githubusercontent.com/33141484/172785950-6817fa5a-92f8-486d-ad4e-7d0da40ab66a.png)
![image](https://user-images.githubusercontent.com/33141484/172786077-ad3d5931-1038-43da-a751-95ea20474c6d.png)
![image](https://user-images.githubusercontent.com/33141484/172786167-ce68a757-6d7b-4b2d-8e86-088abdfe5d06.png)

**Comment by lhuafmaof** [comment]
顺便说声谢谢，你做个这个东西的确好，将写博客的成本降到了最低，是我喜爱的产品，这种代码才是有意义的。

**Comment by tangly1024** [comment]
感谢你提供的创意：“用同步块导入文章”的做法着实巧妙👏👏。

很荣幸此项目能得到你的喜爱，我也同样感谢你以及每一位参与体验与反馈NotionNext的用户。是你们共同造就的此项目，我不过是借助Notion的功能和众多前辈们的力量，站在巨人的肩膀上，尽了自己的举手之劳😁。

**Comment by An-Jhon** [comment]
> 

非常感谢，这个方法很实用。顺便提一下，要使用同步块需要原notion页面也要开启分享功能。
