### ISSUE TITLE
【部署问题】Failed to load next.config.js

### ISSUE THREAD

**Issue by likemuuxi** [tangly1024/NotionNext#1900]
**描述遇到的问题**
从3.x版本更新到最新版本，vercel部署出现错误error - Failed to load next.config.js，仅修改blog.config.js

**相应配置**
notion_page_id：2ad48e3ddfcd42e7b8555a72cb0ec42e
你的网站地址：www.muuxi.cn

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/85612715/f38657ae-3b1a-4bde-baa8-4567923e03a0)
![image](https://github.com/tangly1024/NotionNext/assets/85612715/40ad900e-4e08-4bd9-9e3b-fd6999f6217a)

**环境**

- 操作系统: [windows]
- 浏览器 [edge]
- 版本 [4.2.4]

**Comment by tangly1024** [comment]
blog.config.js 第16行，需要将中文逗号改为英文逗号：

![image](https://github.com/tangly1024/NotionNext/assets/15920488/528b37e4-8a77-43a8-9f23-9afedbeaeb84)

https://github.com/likemuuxi/NotionNext/edit/main/blog.config.js

**Comment by likemuuxi** [comment]
修改后出现了新的问题
<html>
<body>



14:42:34.592 |  
14:42:34.593 | Error occurred prerendering page "/article". Read more: https://nextjs.org/docs/messages/prerender-error
14:42:34.593 | Error: The provided export path '/article' doesn't match the '/[prefix]/[slug]' page.
14:42:34.593 | Read more: https://nextjs.org/docs/messages/export-path-mismatch
14:42:34.593 | at /vercel/path0/node_modules/next/dist/export/worker.js:164:27
14:42:34.593 | at Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:97:26)
14:42:34.593 | at Object.exportPage (/vercel/path0/node_modules/next/dist/export/worker.js:107:27)
14:42:34.593 | at execFunction (/vercel/path0/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2828)
14:42:34.593 | at execHelper (/vercel/path0/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2486)
14:42:34.593 | at execMethod (/vercel/path0/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2574)
14:42:34.593 | at process.messageListener (/vercel/path0/node_modules/next/dist/compiled/jest-worker/processChild.js:1:1284)
14:42:34.593 | at process.emit (node:events:517:28)
14:42:34.593 | at emit (node:internal/child_process:944:14)
14:42:34.593 | at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
14:42:34.598 | [API<<--缓存] from:category-page-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:34.623 | info  - Generating static pages (74/99)
14:42:34.627 | [API<<--缓存] from:category-page-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:34.652 | [API<<--缓存] from:category-page-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:34.677 | [API<<--缓存] from:page-2 root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:34.703 | [API<<--缓存] from:page-3 root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:34.726 | [API<<--缓存] from:page-4 root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:34.752 | [API<<--缓存] from:page-5 root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:34.776 | [API<<--缓存] from:search-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:34.847 | [API<<--缓存] from:search-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:34.886 | [API<<--缓存] from:tag-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:34.925 | [API<<--缓存] from:tag-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:34.967 | [API<<--缓存] from:tag-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:34.991 | [API<<--缓存] from:tag-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:35.012 | [API<<--缓存] from:tag-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:35.032 | [API<<--缓存] from:tag-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:35.054 | [API<<--缓存] from:tag-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:35.076 | [API<<--缓存] from:tag-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:35.098 | [API<<--缓存] from:tag-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:35.120 | [API<<--缓存] from:tag-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:35.143 | [API<<--缓存] from:tag-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:35.162 | [API<<--缓存] from:tag-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:35.183 | [API<<--缓存] from:tag-page-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:35.207 | [API<<--缓存] from:tag-page-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:35.229 | [API<<--缓存] from:tag-page-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:35.251 | [API<<--缓存] from:tag-page-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:35.277 | [API<<--缓存] from:tag-page-props root-page-id:2ad48e3ddfcd42e7b8555a72cb0ec42e
14:42:35.293 | info  - Generating static pages (99/99)
14:42:35.297 |  
14:42:35.297 | > Export encountered errors on following paths:
14:42:35.298 | /[prefix]/[slug]: /article
14:42:35.353 | error Command failed with exit code 1.
14:42:35.357 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
14:42:35.376 | Error: Command "yarn run build" exited with 1
14:42:35.810

<br class="Apple-interchange-newline">
</body>
</html>
