### ISSUE TITLE
无法加载next.config.js

### ISSUE THREAD

**Issue by rumian0** [tangly1024/NotionNext#1908]
**描述bug**
【此项必填】简单说明bug的现象、相关的错误提示、日志等
![image](https://github.com/tangly1024/NotionNext/assets/117440588/a5331b6b-d816-4014-b5e8-181ad9345117)
**复现步骤**
【此项必填】出现这个bug的操作步骤
更改完blog.config.js就出现这样了，不知道为什么，博客能正常运行，正常打开，但是我选用的主题为heo，修改了主题里的config.js，但是被修改的地方没有改变，翻了日志就是这样，不知道为什么，请求解答谢谢~
**期望的正常结果**
【此项必填】希望按这个步骤，正常操作结果是什么
可以正常显示主题被修改的结果
**截图**
【可选】相关的页面，应该的结果

**环境**

- 【必填】NotionNext4.2.4 [例如. 4.0.18]
- 【必填】heo [例如. hexo]
- 【必填】vercel] [例如. vercel]
- 【可选】windows: [例如. iOS, Android, macOS, windows]
- 【可选】edge [例如. chrome, safari, firefox]

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
flase 改为false即可
