### ISSUE TITLE
无法解析“@theme-components”

### ISSUE THREAD

**Issue by rumian0** [tangly1024/NotionNext#1909]
**描述遇到的问题**
简单说明你遇到的问题，相关的日志、错误信息
![image](https://github.com/tangly1024/NotionNext/assets/117440588/637ab52a-d3c1-47eb-bf60-feecd01d8bc5)
这个错误不知道怎么回事~
找不到模块：无法解析“@theme-components”

**相应配置**
相关的配置，例如notion_page_id；你的网站地址
使用vercel部署，采用heo主题
**截图**
相关的页面，应该用结果
这个是日志
![image](https://github.com/tangly1024/NotionNext/assets/117440588/4eb5192f-5644-4e3c-842e-af5f07dce8c6)

**环境**

- 操作系统: windows
- 浏览器 edge
- 版本 [e.g. 22]

**Comment by tangly1024** [comment]
HEO 改为 heo
