### ISSUE TITLE
[公式块]化学方程式显示问题

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#191]
**Describe the bug**

浏览器中公式显示错误

**To Reproduce**

**Expected behavior**
Notion中的页面
![image](https://user-images.githubusercontent.com/32816780/164237318-acdfbcf9-542d-4ef3-8ddf-c88f72b4e2d6.png)

**Screenshots**
浏览器中的页面
![image](https://user-images.githubusercontent.com/32816780/164236933-aa253c38-b1ab-4171-80bb-c36d66bcebab.jpeg)

**Platform:**

- OS: [e.g. iOS, Android]
- Version [e.g. 3.2.1]

**Additional context**
Add any other context about the problem here

**Comment by tangly1024** [comment]
[问题重复]：这个BUG已经在另一个issues中提到，目前暂时无法解决：https://github.com/tangly1024/NotionNext/issues/145
