### ISSUE TITLE
[ BUG ] Vercel 部署 使用 yarn export 有概率失败

### ISSUE THREAD

**Issue by W4ddl3** [tangly1024/NotionNext#1920]
**描述bug**
- Vercel 部署
- 使用 yarn export
- 有概率失败
- 但是重新部署（啥也没改），又能成功
- 属于偶发现象，估计和 Vercel 有关？
- 但是不知道作者您能否优化一下？（不优化也无所谓）

**复现步骤**
- 我初步判断的复现情况
- 每次再修改了代码后的第一次部署，就会报这个错误，但是二次部署就没问题了

**期望的正常结果**
不失败

**截图**
![Shot 2024-02-26 at 21 50 40@2x](https://github.com/tangly1024/NotionNext/assets/141616559/6ef54dd9-67ae-409d-b0c2-960d8a32e6eb)

![Shot 2024-02-26 at 21 48 02@2x](https://github.com/tangly1024/NotionNext/assets/141616559/420e8f90-121d-4077-b12a-619a1cc7078a)

**环境**

- 【必填】NotionNext版本 [最新版]
- 【必填】部署方案 [vercel]

**补充说明**

**Comment by tangly1024** [comment]
![image](https://github.com/tangly1024/NotionNext/assets/15920488/e1d85dcf-1342-4794-9814-75af59392c21)

这个错误的内容应该是某个主题的编码格式有误；请问使用的是哪个主题呢？

**Comment by W4ddl3** [comment]
> ![image](https://private-user-images.githubusercontent.com/15920488/308100940-e1d85dcf-1342-4794-9814-75af59392c21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwOTgxNDAsIm5iZiI6MTcwOTA5Nzg0MCwicGF0aCI6Ii8xNTkyMDQ4OC8zMDgxMDA5NDAtZTFkODVkY2YtMTM0Mi00Nzk0LTk4MTQtNzVhZjU5MzkyYzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA1MjQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NzgzN2VlMGI0ODkzMjBkMjNjNmQwOTc2ZTFmYWJmMTVkM2IzMmJhMmZmN2RiN2NhYmI1ZjFhYWI4NWE4MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2wxFcmQ7BRoykYUnj-PsxFIWYm9O8HxJRpOXvXVFA6c)
> 
> 这个错误的内容应该是某个主题的编码格式有误；请问使用的是哪个主题呢？

哦？还和主题有关啊。
用的是 nav 主题
