### ISSUE TITLE
【HEXO】默认HEXO主题，点击首页文章分类跳转错误页面

### ISSUE THREAD

**Issue by Yohann0617** [tangly1024/NotionNext#1925]
**描述bug**
默认HEXO主题，点击首页文章分类跳转错误页面

**复现步骤**
默认HEXO主题，点击首页文章分类跳转错误页面（NotionNext BLOG），重新刷新页面又恢复正常。

**期望的正常结果**
默认HEXO主题，点击首页文章分类跳转到指定页面。

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/75626191/f1387654-129d-4dc6-88d2-9992ee7ac3e4)
![image](https://github.com/tangly1024/NotionNext/assets/75626191/dd969798-ecef-43e4-8c98-4d5b33f467fb)

**环境**

- 【必填】NotionNext版本 [例如. 4.3.0]
- 【必填】主题 [ hexo]
- 【必填】部署方案 [vercel]
- 【可选】操作系统: [windows]
- 【可选】浏览器 [chrome]

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
缓存导致
