### ISSUE TITLE
[更新代码] Fetch upstream 失败

### ISSUE THREAD

**Issue by Mr-CD** [tangly1024/NotionNext#193]
![image](https://user-images.githubusercontent.com/29009710/164450865-7f287fcb-caeb-40f5-bcfb-824d97bff34b.png)

![image](https://user-images.githubusercontent.com/29009710/164450723-55c11837-51cb-41ff-9604-7394e9a7e207.png)

**Comment by tangly1024** [comment]
最新版本有改动到 blog.config.js 文件，需要在Open  pull request中解决合并冲突。

或者是单独备份一下配置文件，重新fork代码

**Comment by tangly1024** [comment]
相关的Fetch upstream失败说明，已更新在文档介绍中。
