### ISSUE TITLE
bug: 代码展示异常

### ISSUE THREAD

**Issue by yuzhanglong** [tangly1024/NotionNext#197]
如下图所示，代码会重复出现两次：
<img width="844" alt="image" src="https://user-images.githubusercontent.com/56540811/164933222-09e0bcd7-2843-4699-8703-4a113b40516a.png">

**Comment by yuzhanglong** [comment]
复现方法：随便找到一篇有代码的文章，进入后重新刷新就可以复现。

**Comment by yuzhanglong** [comment]
哈喽，这个修复进展如何了，感觉影响到正常使用了~

**Comment by tangly1024** [comment]
Bug已修复😁 请更新V3.2.2

**Comment by yuzhanglong** [comment]
> Bug已修复😁 请更新V3.2.2

谢谢~
