### ISSUE TITLE
block并行显示有问题

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#198]
**Describe the bug**

notion中的block是并行显示的。但是在博客中会显示不完全。博客的链接https://coolnext.vercel.app/article/ff815669-355e-4ea5-96f2-640c11572806
![image](https://user-images.githubusercontent.com/32816780/164960557-21873c5e-5aad-40ad-afc2-51f0997a80ee.png)
![image](https://user-images.githubusercontent.com/32816780/164960578-352130bf-3bbf-4ce2-9c61-e8ca2a0c9ba5.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform:**

- OS: win10
- Browser chrome
- Version 3.2.1

**Additional context**

**Comment by tangly1024** [comment]
我无法重现此问题，尝试再检查一下你的notion页面。

https://preview.tangly1024.com/article/example-1#037e3be90f264d7c8e01bf94ec06b58d

对应notion页面： https://www.notion.so/tanghh/a6271da06b8f47a39735e8fa770f1d9f#037e3be90f264d7c8e01bf94ec06b58d

**Comment by Angel0726** [comment]
> 我无法重现此问题，尝试再检查一下你的notion页面。
> 
> https://preview.tangly1024.com/article/example-1#037e3be90f264d7c8e01bf94ec06b58d
> 
> 对应notion页面： https://www.notion.so/tanghh/a6271da06b8f47a39735e8fa770f1d9f#037e3be90f264d7c8e01bf94ec06b58d

https://preview.tangly1024.com/article/example-1#037e3be90f264d7c8e01bf94ec06b58dhttps://www.notion.so/tanghh/a6271da06b8f47a39735e8fa770f1d9f#037e3be90f264d7c8e01bf94ec06b58d这两个页面是没有问题的。在我的博客中也没有问题。但是我发的页面就有问题

**Comment by tangly1024** [comment]
我看到你的notion笔记中此处就是空白😂

https://coolnext.vercel.app/article/ff815669-355e-4ea5-96f2-640c11572806
<img width="914" alt="图片" src="https://user-images.githubusercontent.com/15920488/165231849-f3b38ba5-2601-48b8-b37a-fcfca40cb330.png">


https://jeweled-trilby-556.notion.site/windows-ff815669355e4ea596f2640c11572806
<img width="928" alt="图片" src="https://user-images.githubusercontent.com/15920488/165231985-32117020-7c5f-40df-ba52-54b23e109040.png">
