### ISSUE TITLE
在notion中插入notion链接。发布博客的时候希望能够自动变成博客的链接

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#199]
**Is your feature request related to a problem? Please describe.**
在写博客的时候经常会遇到，插入本博客中博文的链接。但是在notion中插入notion的link之后，在博文中点击链接会挑战到notion

![image](https://user-images.githubusercontent.com/32816780/164960723-eb8a3025-7448-4f6f-8bf6-f45b4be6edcf.png)
点击安装过程会跳转 https://www.notion.so/windows-5226a88e2be94a81a9bc88e55815ea99
![image](https://user-images.githubusercontent.com/32816780/164960780-b2146059-61db-4cdf-86fd-beb27bf10ffb.png)
我希望跳转到  https://coolnext.vercel.app/article/5226a88e-2be9-4a81-a9bc-88e55815ea99
![image](https://user-images.githubusercontent.com/32816780/164960807-17d9ac62-577a-441a-b3f0-019570e00ff2.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tangly1024** [comment]
参考此处文章：[内部文章的引用问题](https://preview.tangly1024.com/article/example-1#2a4f7d7357254ac3b2ae4e661d0bc6a8)

要注意的是，只适用于notion的page-link，你截图中的书签类型是不会被自动替换成博客内链接，如果一定要插入书签，建议是在博客站点中复制博文的地址，再插入到notion。

- ❌不适用于书签

<img width="278" alt="图片" src="https://user-images.githubusercontent.com/15920488/165051253-d59d22d7-bc5e-4604-8f1c-e12d10bf5894.png">

- ✅ 可以用PageLink

<img width="656" alt="图片" src="https://user-images.githubusercontent.com/15920488/165051914-b63d18d4-d2cf-4287-bddb-ca1a0f6af6e0.png">
