### ISSUE TITLE
[配置问题] 本地部署的时候遇到这个错误，该怎么解决

### ISSUE THREAD

**Issue by wper-golo** [tangly1024/NotionNext#211]
root@554df75cf6cc:/home/NotionNext-main# yarn run build
yarn run v1.22.18
$ next build && next-sitemap --config next-sitemap.config.js
info  - Checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data ...[请求API]: from:category-paths id:xxxxxxxxxxxxxxxxxxxxxxxx
info  - Collecting page data ..[请求成功] from:category-paths id:xxxxxxxxxxxxxxxxxxxxxxxx

> Build error occurred
TypeError: Cannot read properties of undefined (reading 'value')
    at getPageRecordMapByNotionAPI (/home/NotionNext-main/.next/server/chunks/499.js:620:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getNotionPageData (/home/NotionNext-main/.next/server/chunks/499.js:495:27)
    at async getGlobalNotionData (/home/NotionNext-main/.next/server/chunks/499.js:413:28)
    at async getStaticPaths (/home/NotionNext-main/.next/server/pages/category/[category].js:72:29)
    at async buildStaticPaths (/home/NotionNext-main/node_modules/next/dist/build/utils.js:491:31)
    at async /home/NotionNext-main/node_modules/next/dist/build/utils.js:632:119
    at async Span.traceAsyncFn (/home/NotionNext-main/node_modules/next/dist/trace/trace.js:79:20) {
  type: 'TypeError'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
求求，大佬们帮帮

**Comment by tangly1024** [comment]
根据你的提供的日志，只知道在getNotionPageData方法中，读取某个对象的 xx.value 值时遇到空指针错误。
建议解决方法：
1. 清理项目中的`.next`文件夹，再重试编译
2. 检查你的notion_page_id是否配置正确

---
或者提供我你的page-id，我进行编译测试

**Comment by wper-golo** [comment]
这是我的分享链接 https://golowper.notion.site/golowper-s-blog-1-3b8da3b02e244815a89274a88eac510c
用3b8da3b02e244815a89274a88eac510c这个id会报错
：
>info - Creating an optimized production build... 
13:16:50.649 info - Compiled successfully 
13:16:50.649 info - Collecting page data... 
13:16:51.365 [请求API]: from:slug-paths id:3b8da3b02e244815a89274a88eac510c
13:16:51.385 [请求API]: from:slug-paths id:3b8da3b02e244815a89274a88eac510c
13:16:51.421 [请求API]: from:category-paths id:3b8da3b02e244815a89274a88eac510c
13:16:52.129 [请求成功] from:slug-paths id:3b8da3b02e244815a89274a88eac510c
13:16:52.131 pageId "3b8da3b02e244815a89274a88eac510c" is not a database 
13:16:52.131 [请求API]: from:slug-paths id:undefined 
13:16:52.131 [请求失败] from:slug-paths id:undefined error:Error: invalid notion pageId "undefined" 
13:16:52.132 [重试请求] from:slug-paths id:undefined 剩余次数:3 
13:16:52.132 [请求API]: from:slug-paths id:undefined 
13:16:52.132 [请求失败] from:slug-paths id:undefined error:Error: invalid notion pageId "undefined" 
13:16:52.132 [重试请求] from:slug-paths id:undefined 剩余次数:2 
13:16:52.132 [请求API]: from:slug-paths id:undefined 
13:16:52.132 [请求失败] from:slug-paths id:undefined error:Error: invalid notion pageId "undefined" 
13:16:52.132 [重试请求] from:slug-paths id:undefined 剩余次数:1 
13:16:52.132 [请求API]: from:slug-paths id:undefined 
13:16:52.133 [请求失败] from:slug-paths id:undefined error:Error: invalid notion pageId "undefined" 
13:16:52.133  
13:16:52.134 > Build error occurred 
13:16:52.136 TypeError: Cannot read property 'tagOptions' of null 
13:16:52.136 at getGlobalNotionData (/vercel/path0/.next/server/chunks/499.js:421:39) 
13:16:52.136 at processTicksAndRejections (internal/process/task_queues.js:95:5) 
13:16:52.136 at async getStaticPaths (/vercel/path0/.next/server/pages/article/[slug].js:145:27) 
13:16:52.136 at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:491:31) 
13:16:52.137 at async /vercel/path0/node_modules/next/dist/build/utils.js:632:119 
13:16:52.137 at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) { 
13:16:52.13


golowper-s-blog-1-3b8da3b02e244815a89274a88eac510c这个也会
>yarn run v1.22.18
$ next build && next-sitemap --config next-sitemap.config.js
info - Checking validity of types
info - Creating an optimized production build
info - Compiled successfully
info - Collecting page data ...[请求API]: from:category-paths id:xxxxxxxxxxxxxxxxxxxxxxxx
info - Collecting page data ..[请求成功] from:category-paths id:xxxxxxxxxxxxxxxxxxxxxxxx
Build error occurred
TypeError: Cannot read properties of undefined (reading 'value')
at getPageRecordMapByNotionAPI (/home/NotionNext-main/.next/server/chunks/499.js:620:39)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async getNotionPageData (/home/NotionNext-main/.next/server/chunks/499.js:495:27)
at async getGlobalNotionData (/home/NotionNext-main/.next/server/chunks/499.js:413:28)
at async getStaticPaths (/home/NotionNext-main/.next/server/pages/category/[category].js:72:29)
at async buildStaticPaths (/home/NotionNext-main/node_modules/next/dist/build/utils.js:491:31)
at async /home/NotionNext-main/node_modules/next/dist/build/utils.js:632:119
at async Span.traceAsyncFn (/home/NotionNext-main/node_modules/next/dist/trace/trace.js:79:20) {
type: 'TypeError'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by tangly1024** [comment]
hi， 很遗憾，你的notion页面不可以作为notionnext的数据源哦，需要复制此[Notion模板](https://www.notion.so/tanghh/02ab3b8678004aa69e9e415905ef32a5?v=b7eb215720224ca5827bfaa5ef82cf2d)，并将复制后的模板作为数据源。

详情参考此说明： [NotionNext配置notion页面](https://tangly1024.com/article/notion-next#41e8440e1a8443279951134d230d1ace)

**Comment by wper-golo** [comment]
谢谢大佬我可以了
