### ISSUE TITLE
[部署失败] Fetch upstream 后部署失败

### ISSUE THREAD

**Issue by thedavidweng** [tangly1024/NotionNext#216]
以下是 Vercel 的 log

Error occurred prerendering page "/[slug]". Read more: https://nextjs.org/docs/messages/prerender-error
--
17:22:28.047 | TypeError: Cannot read property 'description' of undefined
17:22:28.048 | at AsideLeft (/vercel/path0/.next/server/chunks/399.js:3502:30)
17:22:28.048 | at d (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
17:22:28.048 | at bb (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
17:22:28.048 | at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
17:22:28.049 | at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
17:22:28.049 | at Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
17:22:28.049 | at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:789:45)
17:22:28.050 | at Object.defaultGetInitialProps (/vercel/path0/node_modules/next/dist/server/render.js:393:51)
17:22:28.050 | at Function.getInitialProps (/vercel/path0/.next/server/chunks/859.js:547:20)
17:22:28.050 | at Function.getInitialProps (/vercel/path0/.next/server/pages/_document.js:153:61)

问题出在 Notion Database 的 Slug 吗，但是找不到问题所在

**Comment by tangly1024** [comment]
是Fukasawa主题下的编译问题，已经提交了一个版本补丁： https://github.com/tangly1024/NotionNext/pull/217
更新再试一下

**Comment by thedavidweng** [comment]
部署成功了，但是主题切换按钮关不掉，已经确认了config和vercel的环境变量都是false

**Comment by tangly1024** [comment]
> 解决了 这是 bug 吗

配置设置为false可能会无效，除非删除这一配置项。也可以算是一个bug，新版本中也修补了这个问题
