### ISSUE TITLE
【fukasawa主题】点击文章卡的图片无法打开文章、只能点击标题打开

### ISSUE THREAD

**Issue by DeeepMind** [tangly1024/NotionNext#2198]
**描述bug**
fukasawa主题下点击文章卡中的封面图片无法打开文章，控制台报错live2d.min.js中Cannot read properties of undefined，
关闭宠物显示后控制台无报错产生，但是仍然无法打开文章

**复现步骤**
正常部署

**期望的正常结果**
打开文章内容

**环境**
- 【必填】NotionNext版本 4.4.0
- 【必填】主题 fukasawa
- 【必填】部署方案 vps部署
- 【可选】操作系统:  windows
- 【可选】浏览器 chrome

**Comment by DeeepMind** [comment]
![屏幕截图 2024-03-20 134853](https://github.com/tangly1024/NotionNext/assets/79368955/8c143ad7-ca42-492d-ba66-1531e2b50924)

**Comment by tangly1024** [comment]
感谢反馈，图片忘记做点击跳转了，只能通过标题打开
