### ISSUE TITLE
movie主题 上传notion的多个视频没有实现聚合功能

### ISSUE THREAD

**Issue by ypfstu** [tangly1024/NotionNext#2208]
**描述bug**
在使用movie主题聚合功能时，**自己上传**notion的多个视频**没有实现聚合功能**。
通过测试仅仅只有是借助dplayer播放器嵌入notion的视频才能实现聚合。
借助dplayer播放器嵌入notion
**复现步骤**
在notion中直接上传多个视频，使用聚合功能。

**期望的正常结果**
直接在notion上传的视频也可以实现聚合功能

**截图**
![屏幕截图 2024-03-23 170126](https://github.com/tangly1024/NotionNext/assets/164488815/dfb723df-c2d3-4fef-96a5-b350f380fa71)

**环境**

- 【必填】NotionNext版本4.4.0
- 【必填】主题movie
- 【必填】部署方案 vercel
- 【可选】操作系统:windows
- 【可选】浏览器 chrome

**Comment by tangly1024** [comment]
本地支持notion上传视频聚合

<img width="796" alt="image" src="https://github.com/tangly1024/NotionNext/assets/15920488/6e9d27a0-0299-4d53-b67c-cc333ba85624">

<img width="1368" alt="image" src="https://github.com/tangly1024/NotionNext/assets/15920488/7ffd914c-7e78-43a8-a738-9baa7c03c948">


可以提供一下网站和相关notion页面

**Comment by ypfstu** [comment]
刚看了一下，现在可以了
