### ISSUE TITLE
components/GlobalHead.js文件中，这里应该多了两个}号

### ISSUE THREAD

**Issue by yunzhongci** [tangly1024/NotionNext#2217]
**描述bug**

components/GlobalHead.js文件中，这里应该多了两个}号，导致在点击相应页面的时候，浏览器标签显示中出现了 多余的 **|| ''}**

<img width="778" alt="image" src="https://github.com/tangly1024/NotionNext/assets/49399931/066a5b71-0180-4e08-a332-2527b3cf05d9">

**Comment by tangly1024** [comment]
感谢反馈，已确认问题
