### ISSUE TITLE
博客的个人简介模块被挤下来了

### ISSUE THREAD

**Issue by eliaszon** [tangly1024/NotionNext#223]
**描述bug**
博客的个人简介模块被挤下来了，如图所示

我要把网页缩放比例调成90%才能正常显示

**复现步骤**
正常打开网页

**期望的正常结果**
![image](https://user-images.githubusercontent.com/73749474/167073487-9a7beb04-d564-4e63-9fe8-381bd4015b2b.png)

**截图**
![image](https://user-images.githubusercontent.com/73749474/167073427-da75f04e-36ec-419b-bd35-45bc2fb6c71f.png)

**环境**

- 操作系统:  windows
- 浏览器 edge
- 版本 [e.g. 22] 101.0.1210.32 (正式版本) (64 位)

**补充说明**
与问题相关的其它说明

**Comment by eliaszon** [comment]
另外：我启用了edge的垂直标签页，左边会占一栏的宽度。不过不是很多，我刚用chrome试了一下发现正常显示。大佬能否稍微再调整一下宽度，用百分比宽度比固定宽度应该会更好

**Comment by tangly1024** [comment]
> 另外：我启用了edge的垂直标签页，左边会占一栏的宽度。不过不是很多，我刚用chrome试了一下发现正常显示。大佬能否稍微再调整一下宽度，用百分比宽度比固定宽度应该会更好

感谢你的反馈😁，这样的排版确实不太恰当，我调整一下
