### ISSUE TITLE
访问文章时，显示Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by Fosvcat** [tangly1024/NotionNext#2232]
**描述bug**
在vercel部署完成后能够抓取到文章，但是文章无法打开，提示Application error: a client-side exception has occurred (see the browser console for more information).
换用Netlify部署，打开文章时闪了一下文章内容，随后白屏没有任何提示

**复现步骤**
Github复制最新代码后在vercel建立新项目并部署

**期望的正常结果**
应该按新的链接正常打开文章

**截图**
![屏幕截图 2024-03-27 155229](https://github.com/tangly1024/NotionNext/assets/83565161/803f62db-60b0-4140-aeb3-a6e49062b39a)
![屏幕截图 2024-03-28 232725](https://github.com/tangly1024/NotionNext/assets/83565161/abcb3551-0bfb-4bf1-b4f9-0da3d95eb691)

**环境**

NotionNext版本 4.4.2
主题 heo
部署方案 vercel
操作系统: windows
浏览器 Edge

**补充说明**
网站地址：https://www.fosvcat.top/
问题发生后尝试重新部署，但使用原本的页面ID-788992b650e943e592546c3ddd9ccc5c显示部署失败（vercel和Netlify），复制了新的页面模板后使用新的ID后部署正常，随后访问网站出现文章无法打开问题。

我把所有的步骤都是按照官方教程重新来了一遍，清除浏览器缓存建立全新的项目和网站，但依然存在问题。

**Comment by Fosvcat** [comment]
OK，问题的原因是我在编辑heo主题的config时，文件换行策略从CRLF无意中变成了LF，设置回来就一切正常了。

**Comment by DFBlowing** [comment]
我也出现了上述的报错问题，可是无法通过上面的方式解决，我将自己问题的几个解决方法分享在了我的博客上： [博客链接](https://www.xiaoyuezhou.us.kg/error-1) ，应该对大家有帮助
