### ISSUE TITLE
【配置】NEXT_SINCE 配置不生效

### ISSUE THREAD

**Issue by Oliverwqcwrw** [tangly1024/NotionNext#2243]
**描述bug**
【此项必填】简单说明bug的现象、相关的错误提示、日志等

配置NEXT_SINCE环境变量为2023之后，还是2021

**复现步骤**
【此项必填】出现这个bug的操作步骤

配置NEXT_SINCE环境变量为2023

**期望的正常结果**
【此项必填】希望按这个步骤，正常操作结果是什么

页面展示为2023-2024

**截图**
【可选】相关的页面，应该的结果

<img width="260" alt="image" src="https://github.com/tangly1024/NotionNext/assets/31796988/57dfa866-2dd4-46ef-bccc-c29c55c0e4b3">

**环境**

- 【必填】NotionNext版本 [例如. 4.0.18] 4.2.1
- 【必填】主题 [例如. hexo] hexo
- 【必填】部署方案 [例如. vercel] vercel
- 【可选】操作系统: [例如. iOS, Android, macOS, windows] macOS
- 【可选】浏览器 [例如. chrome, safari, firefox] chrome

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
感谢反馈；
解决如下，更新到最新版，后任选一种方案：

1.环境变量名 改为： NEXT_PUBLIC_SINCE
2.或者加一个Notion_Config即可：

![image](https://github.com/tangly1024/NotionNext/assets/15920488/1f05b803-b191-41e9-beb1-e37516047b4f)
