### ISSUE TITLE
sitemap站点地图生成问题

### ISSUE THREAD

**Issue by doing1024** [tangly1024/NotionNext#2252]
**描述bug**
【此项必填】网站可正常访问，但是sitemap中每一条网址的域名都是https://tangly1024.com

**复现步骤**
正常部署，打开sitemap.xml，发现了每一条url都是以https://tangly1024.com开头

**期望的正常结果**
希望可以让每一条的开头都为notion配置中心中配置的域名

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/126306440/146781f2-2471-44c6-b462-927dfb6b27e7)

**环境**

- 【必填】NotionNext版本：4.2.4
- 【必填】主题：Next
- 【必填】部署方案 Vercel
- 【可选】操作系统: Windows11
- 【可选】浏览器 Microsoft Edge

**补充说明**
【可选】与问题相关的其它说明

**Comment by doing1024** [comment]
已解决，修改blog.config.js即可

**Comment by MicroMatrixOrg** [comment]
同样的问题，上面的sitemap没有网站前缀。我已经在vercel的环境变量中配置了NEXT_PUBLIC_LINK。之前是有的，现在没有导致链接快全掉完了

【必填】NotionNext版本：4.7.11
【必填】主题：Next
【必填】部署方案 Vercel
【可选】操作系统: Windows11
【可选】浏览器 Microsoft Edge
补充说明
【可选】与问题相关的其它说明
