### ISSUE TITLE
【控制台报错】Uncaught TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by ymh0000123** [tangly1024/NotionNext#2265]
**描述bug**
【此项必填】
点击头像出现报错
```
live2d.min.js:1 
 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at r.hitTestSimpleCustom (live2d.min.js:1:5284)
    at o.hitTestCustom (live2d.min.js:1:146877)
    at o.tapEvent (live2d.min.js:1:137689)
    at p (live2d.min.js:1:22319)
    at g (live2d.min.js:1:22887)
```
**复现步骤**
【此项必填】heo主题点击右侧的头像

**期望的正常结果**
【此项必填】不知道正常情况下的样子

**环境**

- 【必填】4.4.2 [a429684](https://github.com/tangly1024/NotionNext/commit/a4296844cf2ecb2c174d2de47371a2b2abfd4019)
- 【必填】主题 heo
- 【必填】部署方案 netlify
- 【可选】操作系统: windows
- 【可选】浏览器 edge

**Comment by tangly1024** [comment]
live2d 挂件的问题，因为不是用的完整版引入，官方推荐的是用autoloader引入，这样支持宠物换装、交互动画、文字对话等功能。

https://github.com/stevenjoezhang/live2d-widget



不过我这里舍掉了其它丰富的功能，只保留宠物本身，因此会有此bug，后面会处理掉。
