### ISSUE TITLE
Notion 直接通过 ctrl+v 粘贴的图片，无法通过 notion next 访问

### ISSUE THREAD

**Issue by PeterChen1997** [tangly1024/NotionNext#2267]
感谢作者提供优秀的站点生成工具

**描述bug**
【此项必填】简单说明bug的现象、相关的错误提示、日志等

notion next 网站，无法直接查看 notion 中可查看的图片，找了一圈 issues，好像没看到解决方案

https://aws.peterchen97.cn/article/foundamentals
![image](https://github.com/tangly1024/NotionNext/assets/21072589/9cc2576c-fcae-44ac-9cba-27034d0deb31)

原版 notion 站点：https://peterchen97.notion.site/02-Foundamentals-cbb5675f9b36431c920bfa674e7b877b

repo链接：https://github.com/PeterChen1997/NotionNext

**复现步骤**
【此项必填】出现这个bug的操作步骤

直接访问就可复现

**期望的正常结果**
【此项必填】希望按这个步骤，正常操作结果是什么

能够正常看到图片

**截图**
【可选】相关的页面，应该的结果

**环境**

- 【必填】NotionNext版本 [例如. 4.0.18]
- 【必填】主题 [例如. hexo]
- 【必填】部署方案 [例如. vercel]
- 【可选】操作系统: [例如. iOS, Android, macOS, windows]
- 【可选】浏览器 [例如. chrome, safari, firefox]

最新版 macos

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
# 建议
撤销之前的配置更改，还原代码，或者升级到目前的最新版本试一下。

# 关于问题复现

您好，检查了Notion模板后，确认数据是正常的 ctrl+v的方式使用图片并不会产生此影响。


另外，我用您的数据库本地开启调试也是正常显示了图片：

![image](https://github.com/tangly1024/NotionNext/assets/15920488/f5348b5b-b268-43a4-b147-370cbec9bdc3)

您提供的仓库地址 无法访问，我无法确定是否某处代码修改导致了此问题。 


# 原因推断
## 异常的图片地址 
在您的站点中，图片都是未经安全加密的路径，不知道是什么原因导致您的项目无法正常调用加密函数。
`https://prod-files-secure.s3.us-west-2.amazonaws.com/0822feeb-f958-45bf-b162-f03675176e08/b8b54828-10ae-431a-bd78-10046c720709/Untitled.png`
![image](https://github.com/tangly1024/NotionNext/assets/15920488/a95dc84f-f06e-4400-9ac9-ad84523f1d32)

## 预期的图片地址
在正常的NotionNext站点中，notion的网页图片会被迦密成以下可访问的安全链接：
`https://www.notion.so/image/https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2F0822feeb-f958-45bf-b162-f03675176e08%2F738c2cd5-494d-4b61-ae74-e5985235dfc3%2FUntitled.png?table=block&id=86aca519-e721-47a0-ad1a-c6bad5e3fc83&t=86aca519-e721-47a0-ad1a-c6bad5e3fc83&width=432.98614501953125&cache=v2`

**Comment by PeterChen1997** [comment]
感谢回复，我尝试了一下，应该是我粘贴的时候，使用了粘贴同步的功能，导致这个 block 的图片和没 public 的图片绑定了，所以可能链接是安全链接

我重新尝试上传后 ok 了，感谢大佬！

**Comment by PeterChen1997** [comment]
重新从头配置后 ok，怀疑是图片不能现在 private 的 notion page 中粘贴，然后再复制到 public page 里

**Comment by hanrongMan** [comment]
我也遇到了这个问题，挺奇怪的。之前的博文可以，但是近期的就有这个问题了，原来的配置并没有改变过。
