### ISSUE TITLE
4.4.3新版本有些元数据的问题

### ISSUE THREAD

**Issue by laye0619** [tangly1024/NotionNext#2283]
**描述bug**
几个我自己修改的地方：
- blog的logo，我在notion页面里面修改了database的图标
<img width="227" alt="image" src="https://github.com/tangly1024/NotionNext/assets/9484313/8d9b29bb-bc74-4344-9e76-dba8abadd063">

- 在public目录中，使用自己的图标替换了favicon.ico和favicon.svg
- 在notion“配置中心”中修改了AUTHOR，BIO，TITLE和DESCRIPTION
<img width="432" alt="image" src="https://github.com/tangly1024/NotionNext/assets/9484313/ea1e4fbf-2915-4504-8a30-4edff43073ad">

在4.4.2版本一切正常，blog的logo，描述等。升级到了4.4.3中，网站title和描述变成了“NotionNext BLOG | 这是一个由NotionNext生成的站点”。另外logo也还原成了默认的样子：
<img width="80" alt="image" src="https://github.com/tangly1024/NotionNext/assets/9484313/6f2273a1-1436-46b3-98e7-1bbd896aa274">

另外我看到我的网站会自动跳转到/en，这可能是我操作系统是英文版导致的。但是我不知道上述问题和这个有没有关系。就算我手工删掉/en，回车后还是会跳转到/en

**期望的正常结果**
希望和4.4.2一样

**复现步骤**
【此项必填】你的操作步骤，按此步骤理应在我的开发环境出现一样的bug。

**环境**

- 【必填】NotionNext版本 [例如. 4.0.18]：4.4.3
- 【必填】主题 [例如. hexo]：heo
- 【必填】部署方案 [例如. vercel]：vercel
- 【可选】操作系统: [例如. iOS, Android, macOS, windows]
- 【可选】浏览器 [例如. chrome, safari, firefox]：safari

**补充说明**
【可选】与问题相关的其它说明

**Comment by laye0619** [comment]
> **描述bug** 几个我自己修改的地方：
> 
> * blog的logo，我在notion页面里面修改了database的图标
> 
> <img alt="image" width="227" src="https://private-user-images.githubusercontent.com/9484313/321903357-8d9b29bb-bc74-4344-9e76-dba8abadd063.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDkyNjcsIm5iZiI6MTcxMjkwODk2NywicGF0aCI6Ii85NDg0MzEzLzMyMTkwMzM1Ny04ZDliMjliYi1iYzc0LTQzNDQtOWU3Ni1kYmE4YWJhZGQwNjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMDgwMjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDMxNDllODY5ZGJkNTdlYzU1OGU5ZjRkM2U1MDkxZDExOTJhYzQyODAxMWU5NDU5MTEzZWI3MzlhM2UwOTg4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fDY6bPAI-e-Iqq2QxLKwvsHt_Cl6U0LFbJcCOMuNBEE">
> * 在public目录中，使用自己的图标替换了favicon.ico和favicon.svg
> * 在notion“配置中心”中修改了AUTHOR，BIO，TITLE和DESCRIPTION
> 
> <img alt="image" width="432" src="https://private-user-images.githubusercontent.com/9484313/321903817-ea1e4fbf-2915-4504-8a30-4edff43073ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDkyNjcsIm5iZiI6MTcxMjkwODk2NywicGF0aCI6Ii85NDg0MzEzLzMyMTkwMzgxNy1lYTFlNGZiZi0yOTE1LTQ1MDQtOGEzMC00ZWRmZjQzMDczYWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMDgwMjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzQxNTZiMDNkYTI2ZjQ3NTIyZjNmMTcxOTBiZmI0YjhkNzRlZWIwZDBjZGRmNTA5MjkyN2UwYzIyMTg0NjUwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e00VzfugjyfyOBTfpkc4_D_V97HoMMNAeU3vOpOOtiY">
> 在4.4.2版本一切正常，blog的logo，描述等。升级到了4.4.3中，网站title和描述变成了“NotionNext BLOG | 这是一个由NotionNext生成的站点”。另外logo也还原成了默认的样子： <img alt="image" width="80" src="https://private-user-images.githubusercontent.com/9484313/321904467-6f2273a1-1436-46b3-98e7-1bbd896aa274.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDkyNjcsIm5iZiI6MTcxMjkwODk2NywicGF0aCI6Ii85NDg0MzEzLzMyMTkwNDQ2Ny02ZjIyNzNhMS0xNDM2LTQ2YjMtOThlNy0xYmJkODk2YWEyNzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMDgwMjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWIyNmUyYzAzOTI2OWI0ODAyNjBmNTFiMDU5ZWU0NGJmODY0NDZmMmRlZjQxMTNjMjYyZmE0MjA0ZjdlYzMwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BPepu96t5JoNcPoQsvQN2axWDRJFwY-_NfgMR9WZOJI">
> 
> 另外我看到我的网站会自动跳转到/en，这可能是我操作系统是英文版导致的。但是我不知道上述问题和这个有没有关系。就算我手工删掉/en，回车后还是会跳转到/en
> 
> **期望的正常结果** 希望和4.4.2一样
> 
> **复现步骤** 【此项必填】你的操作步骤，按此步骤理应在我的开发环境出现一样的bug。
> 
> **环境**
> 
> * 【必填】NotionNext版本 [例如. 4.0.18]：4.4.3
> * 【必填】主题 [例如. hexo]：heo
> * 【必填】部署方案 [例如. vercel]：vercel
> * 【可选】操作系统: [例如. iOS, Android, macOS, windows]
> * 【可选】浏览器 [例如. chrome, safari, firefox]：safari
> 
> **补充说明** 【可选】与问题相关的其它说明

回滚到4.4.2一切正常

**Comment by dongzhenye** [comment]
> 另外我看到我的网站会自动跳转到/en，这可能是我操作系统是英文版导致的。但是我不知道上述问题和这个有没有关系。就算我手工删掉/en，回车后还是会跳转到/en

我也有类似的困扰，我的网站会自动跳转到/en，虽然我没有为en配置独立的Database。希望在下一个版本解决问题，谢谢!
