### ISSUE TITLE
更新版本4.4.3后文章和公告字体变成默认字体了

### ISSUE THREAD

**Issue by 88lin** [tangly1024/NotionNext#2292]
**描述bug**
更新版本4.4.3后文章和公告字体变成默认字体了，其他的字体正常，我设置的字体是LXGW WenKai字体。附上博客链接：https://yyyy.gay/article/27

**期望的正常结果**
字体恢复正常

**复现步骤**
【此项必填】你的操作步骤，按此步骤理应在我的开发环境出现一样的bug。

**环境**

- 【必填】NotionNext版本 [4.4.3]
- 【必填】主题 [heo]
- 【必填】部署方案 [vercel]
- 【可选】操作系统: [Android,  windows]
- 【可选】浏览器 [chrome, edge, firefox]

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
已修复
