### ISSUE TITLE
【FONT_URL】为什么没有使用镜像地址呢，导致访问的时候很慢。

### ISSUE THREAD

**Issue by handbye** [tangly1024/NotionNext#2300]
![image](https://github.com/tangly1024/NotionNext/assets/26617058/f1479bf4-0ad8-4b6f-b6ec-4fc3dc06e906)
另外这里能否支持从vercel的环境变量中配置镜像地址呢，方便更新。

关联 ：
#384 
#380

**Comment by tangly1024** [comment]
感谢反馈，我将提交一个新功能，使 FONT_URL 支持在NOTION_CONFIG中配置。

- 直接添加一个 FONT_URL 配置即可覆盖，便于自行配置web字体的路径。
- 同时，如果要自定义别除了 noto-sans 或 noto-serif 之外的字体，建议在GLOBAL_CSS 中配置 font-family的CSS样式，如下图。

![image](https://github.com/tangly1024/NotionNext/assets/15920488/5049e28c-9b10-4368-a0df-e6c4fe5a1d3a)
