### ISSUE TITLE
Notion-Config中的分享图标配置(POST_SHARE_SERVICES不生效

### ISSUE THREAD

**Issue by dongzhenye** [tangly1024/NotionNext#2304]
**描述bug**
在Notion配置文件中设置分享图标范围无法生效

**期望的正常结果**
期望按照配置的范围，更新分享图标列表。

**复现步骤**
步骤1：在Notion配置文件中增加如下配置并启用：
POST_SHARE_SERVICES = 'link,wechat,weibo,email,facebook,twitter,telegram,whatsapp'
步骤2：在Vercel重新部署并刷新页面，无法看到分享图标发生变化，仍然为默认的列表。

**环境**

- 【必填】NotionNext版本 v4.4.3
- 【必填】主题 Hexo
- 【必填】部署方案 Vercel
- 【可选】操作系统 Wndows
- 【可选】浏览器 Edge

**补充说明**
我做了初步排查：
1、经验证，配置文件已生效，比如配置的GREETING_WORDS在首页已看到效果
2、经验证，环境变量中的POST_SHARE_SERVICES可以正常生效

故怀疑是Notion-Config对这个配置解析有某种问题，希望作者或朋友们分享思路或协助解决，谢谢！

**Comment by tangly1024** [comment]
# 试一下
> POST_SHARE_SERVICES = 'link,wechat,weibo,email,facebook,twitter,telegram,whatsapp'

改成 `POSTS_SHARE_SERVICES`，即`POST` 后面加个S

**Comment by dongzhenye** [comment]
@tangly1024 经测试，改成 `POSTS_SHARE_SERVICES`，即可恢复生效。

**Comment by dongzhenye** [comment]
问题已解决，相关同学可以参考
