### ISSUE TITLE
HEO主题的英雄区（首页顶部大卡），点击链接无法修改

### ISSUE THREAD

**Issue by zuilintan** [tangly1024/NotionNext#2315]
**描述bug**
![image](https://github.com/tangly1024/NotionNext/assets/34953840/81a973be-5963-43e3-8576-a6487aa359a0)
此处点击链接无法通过HEO_HERO_TITLE_LINK修改替换
![image](https://github.com/tangly1024/NotionNext/assets/34953840/68d3e8f1-8164-4904-a91e-5c313f1a1572)
![image](https://github.com/tangly1024/NotionNext/assets/34953840/efeb4d23-d948-4f0a-91c8-2dc3237e846c)

**期望的正常结果**
正常替换

- 【必填】NotionNext版本 4.4.3
- 【必填】主题 heo
- 【必填】部署方案 vercel
- 【可选】操作系统 windows
- 【可选】浏览器 chrome

**Comment by tangly1024** [comment]
感谢反馈，bug已修复
