### ISSUE TITLE
【评论插件】页底红字：Utterance

### ISSUE THREAD

**Issue by 1985312383** [tangly1024/NotionNext#2320]
**描述bug**
【此项必填】简单说明目前出现的现象、相关的错误提示、日志等、截图
![image](https://github.com/tangly1024/NotionNext/assets/56398475/055898e3-5b00-430f-8f12-37cf8aa8090b)

**期望的正常结果**
没有这个红色的Utterance

**复现步骤**
我在某一次2.几到3. 的更新后，全覆盖分支更新，然后修改了相应的主json的参数，其他的没更改

**环境**

- 【必填】NotionNext版本 [3.15]
- 【必填】所有
- 【必填】vercel

**Comment by tangly1024** [comment]
现在版本，至少要有两个及两个以上的评论插件，才会显示此红字，用于引导在不同评论间切换。
只有一个就不会显示这个红字。

相关代码 : https://github.com/tangly1024/NotionNext/blob/2dd9be95d883634c8572e79111a84c66ea9e03f0/components/Tabs.js#L20


```
 {!(validChildren.length === 1 && siteConfig('COMMENT_HIDE_SINGLE_TAB')) && (
      .l..
      )}
```

**Comment by 1985312383** [comment]
> 现在版本，至少要有两个及两个以上的评论插件，才会显示此红字，用于引导在不同评论间切换。 只有一个就不会显示这个红字。
> 
> 相关代码 :
> 
> https://github.com/tangly1024/NotionNext/blob/2dd9be95d883634c8572e79111a84c66ea9e03f0/components/Tabs.js#L20
> 
> ```
>  {!(validChildren.length === 1 && siteConfig('COMMENT_HIDE_SINGLE_TAB')) && (
>       .l..
>       )}
> ```

感谢作者大大的回复，原来在主json设置里新更新的有个和这个代码对应的true false选项
