### ISSUE TITLE
[部署及性能问题] 一改文件就部署出错

### ISSUE THREAD

**Issue by xinkeji** [tangly1024/NotionNext#237]
**描述遇到的问题**
一改文件就部署出错，环境变量只有NOTION_PAGE_ID可以改，其他都改不了，一改就出错，感觉应该是我github操作有问题，希望提示下解决方法，

警告“gitalk > react-flip-move@2.9.14”具有不正确的对等依赖关系“react@0.13.x \|\|0.14.x \|\|15.x.x”。
--
18:47:02.368 | 警告 “gitalk > react-flip-move@2.9.14” 具有不正确的对等依赖关系 “react-dom@0.13.x \|\|0.14.x \|\|15.x.x”。
18:47:02.369 | 警告“react-facebook > react-spinner-children@1.0.8”具有不正确的对等依赖关系“react@15.x \|\|16.x”。
18:47:02.369 | 警告“> react-messenger-customer-chat@0.8.0”具有不正确的对等依赖关系“react@^0.14.0 \|\|^15.0.0-0 \|\|^16.0.0-0”。
18:47:02.370 | 警告“react-notion-x > react-image@4.0.3”具有未满足的对等依赖关系“@babel/runtime@>=7”。
18:47:02.370 | 警告 “react-notion-x > react-lazy-images@1.1.0” 具有不正确的对等依赖关系 “react@^15 \|\|^16”。
18:47:02.371 | 警告 “react-notion-x > react-lazy-images@1.1.0” 具有不正确的对等依赖关系 “react-dom@^15 \|\|^16”。
18:47:02.371 | 警告 “react-notion-x > react-pdf > file-loader@6.2.0” 具有未满足的对等依赖关系 “webpack@^4.0.0 \|\|^5.0.0”。
18:47:02.375 | 警告 “eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.21.0” 具有未满足的对等依赖项 “typescript@>=2.8.0 \|\|>= 3.2.0-开发\|\|>= 3.3.0-开发\|\|>= 3.4.0-开发\|\|>= 3.5.0-开发\|\|>= 3.6.0-开发\|\|>= 3.6.0-贝塔\|\|> = 3.7.0-开发\|\|>= 3.7.0-beta”。

**相应配置**
相关的配置，例如notion_page_id；你的网站地址

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**Comment by tangly1024** [comment]
hi，你提供的这部分日志信息不能看出部署错误的原因。

请提供更详细的 日志 ，尤其是包含```error``` 的部分

**Comment by xinkeji** [comment]
已经解决了，但是仍然不知道哪里出了问题，我是fork了fork您项目人的项目，目前已经解决，目前可以搭建了，感谢您这么晚还回复我，洗希望这个项目越来越好，辛苦！！

**Comment by xinkeji** [comment]
啊，好像不行，什么数据改了都没用，我重新部署下，提下错误

**Comment by tangly1024** [comment]
Hi ， 感谢你详细的问题反馈;

报错的原因应该是主题名字配置有误，导致找不到对应文件，修改一下主题名就可以了。

**Comment by tangly1024** [comment]
😂我尝试访问你的站点 https://xinkejicf-pdh00ximl-xinkeji.vercel.app/ ，看起来一切正常，网站问题现在已经解决了吗

**Comment by xinkeji** [comment]
是的，已经解决了，您费心了，不过我又发现了新的问题，就是网站更新很慢
，其实imgix很拖速度，也就是您的外链图片还有个就是，我专门访问了您的网站，加载速度48秒，这就很恐怖了，当然这是您外链图的原因，不过我试着访问我刚建立的网站外链也换了，但是加载仍要3秒，如果加上一些文章速度可能会更慢，这对于静态网站真的难以想象，不知道能不能优化下

**Comment by tangly1024** [comment]
很感谢你的反馈，我一直很看重网站的性能，并热衷于对NotionNext这个项目的速度优化。我仔细阅读了你的问题描述，并引用你的文字作出6点回应：

## 1.  `网站更新很慢`
- 若这里指的是Notion的信息同步到站点的速度，那其实是正常的，页面有做缓存，理论上在数十秒左右，刷新几次页面即可更新数据。

## 2. ` imgix很拖速度 `
-  图片是由Notion托管的，加载的速度将由你的网络访问Notion的速度决定，这个没有什么办法优化，只能在上传图片前进行适当的压缩。

## 3. ` 我专门访问了您的网站，加载速度48秒，这就很恐怖了`
- 除了图片还加入了一些站点统计、广告统计之类的脚本，确实非常拖慢网站速度。这个我要好好反省一下

## 4. ` 不过我试着访问我刚建立的网站外链也换了，但是加载仍要3秒`
- 禁用缓存的情况下首次访问3秒，这个问题我会持续跟进，目前看来貌似是字体文件、和Vercel程序的执行偶尔会有影响。

## 5. ` 如果加上一些文章速度可能会更慢`
- 理论文章的数量并不会影响加载的速度，毕竟页面是静态的。除非更多的文章意味着更多的图片。

## 6. 我的测试结果与你有些出入
我平时用的是GTMetrix进行网站性能的测试，其实测试的结果数据还是不错：
<img width="1349" alt="图片" src="https://user-images.githubusercontent.com/15920488/168216261-e74bbc95-2043-4700-abc2-979a7ddb30a2.png">

### 主要影响性能的还是引用的字体服务
<img width="1043" alt="图片" src="https://user-images.githubusercontent.com/15920488/168216659-9623abba-ad88-4263-8d62-e86740e64e1a.png">


### 我在自己的电脑上访问你的网站也只需要765ms，这到底是哪里出问题了😂
<img width="1618" alt="图片" src="https://user-images.githubusercontent.com/15920488/168216180-29def6fe-44a1-4c67-b56b-58bf9b2a06a7.png">

最后，关于站点性能的问题，希望能与你有更多的交流！

**Comment by xinkeji** [comment]
首先很感谢作者您这么用心的回答，我这边也引用您的问题进行答复

**1. 若这里指的是Notion的信息同步到站点的速度，那其实是正常的，页面有做缓存，理论上在数十秒左右，刷新几次页面即可更新数据。**
这个我刚找到原因了，挂着v更新，貌似就不同步，但是我用您借鉴的哪个框架测试是不影响的，不过这应该不算大问题

**2.图片是由Notion托管的，加载的速度将由你的网络访问Notion的速度决定，这个没有什么办法优化，只能在上传图片前进行适当的压缩。**
这个我也不太清楚但是为什么我的图片链接不是这个而且速度很快https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fe56f2fa1-9328-43cb-96d3-f3faf977b108%2Frb48xg.jpg?table=block&id=3e220e80-9739-4107-80fc-237dc7e9470b&cache=v2
刚去测试了一下，速度突然都变快了，可能我测的时候，网络刚好抽风吧！

刚好写了,我最后在提一提意见和问下问题
1.可以用js和css 用   jsdelivr+github（也不知道您知不知道，反正我提一下）
2.希望有些内容可以自己生成，比如摘要和页面链接（slug）, 日期可以默认当天
以及这个 type，status,可不可以像 password 那样没有填就默认 文章和发布 
3.网站首页的最新文章，确实有点鸡肋，毕竟首页的应该都是最新文章吧，去掉可以增加速度，或者换成热度文章
4.hexo模板确实好看，但是他的开屏图片对于我来说略显鸡肋，想问下能不能加个控制开关
5.想请问下增加database 的 properties（notion数据表）对网站有什么影响，能不能更改顺序，因为我刚试过了，换了个
notion页面自己手动添加，没有成功， 想问下有什么需要注意的，另外notion数据表属性修改名称的话在网站代码里哪里修改

**Comment by tangly1024** [comment]
网络环境 难免 会有抽风的时候 ，哈哈~

感谢你的意见；
1.jsdlivr+github的方案也 尝试一下对比一下 加载 速度。
2.自己 生成数据  ，或许可以用一下Notin自带 的模板功能，就是New按钮 右边的小箭头，很方便。
<img width="1002" alt="图片" src="https://user-images.githubusercontent.com/15920488/168292366-68edf4eb-9723-4bdb-8318-e40214feda2a.png">
slug参数默认是可以不填写的 ，摘要功能最好 还是 自己 总结；另外可以在[blog.config.js的这行代码](https://github.com/tangly1024/NotionNext/blob/a3f2494f5639f37558538cc6d90260248b6542d4/blog.config.js#L35)中 开启预览模式，这样会在列表中将 文章的部分段落展示 为 摘要。 

3. 因为我自己是 手动 排序的首页文章 ，不一定 都是最新的；所以才有 了 最新文章 板块 。也许有的 用户希望首页 默认展示 最新 列表  ，而在 侧边展示 热度文章 ，这是另一种方案了 。可能 我会在后续版本中加入 这种支持，另外 ,在 [blog.config.js的此行代码 ](https://github.com/tangly1024/NotionNext/blob/a3f2494f5639f37558538cc6d90260248b6542d4/blog.config.js#L39)中 可以 修改 首页的 排序方式为按时间 ，或者 按照 notion手动排序。
4. 开屏图片 关闭在 [config_hexo.js的此行代码 ](https://github.com/tangly1024/NotionNext/blob/a3f2494f5639f37558538cc6d90260248b6542d4/themes/hexo/config_hexo.js#L2)配置为 false即可。
5. 增加properties不会有影响 ，可以更改顺序 。目前没有适配过其他自己 添加的notion页面，如果你有觉得更好的模板方式欢迎与我 分享，我将在代码里进行兼容。

最后 ，再次感谢你认真的评论！

**Comment by xinkeji** [comment]
好的非常感谢，不过我去试过了不出意外改文件又出错拉，不知道为啥，我怀疑又是挂V的问题

**Comment by tangly1024** [comment]
改文件就会出错嘛，真是让人头疼的问题😅；可以看看vercel后台的日志错误、找找错误原因

**Comment by xinkeji** [comment]
全部退回了，能成功部署了，但是改下环境变量，重新部署又出错，真的太难了

**Comment by xinkeji** [comment]
NotionAPI 集合查询错误 02ab3b8678004aa69e9e415905ef32a5 响应代码 504（网关超时

**Comment by xinkeji** [comment]
哈哈哈

**Comment by xinkeji** [comment]
为什么换了个页面就用不了啊 我都一比一还原了。https://www.notion.so/xinkeji/e50b8daaa6d24f3c92fea5af4c0b9f94?v=407118027d614dcaa086c01bd4b2721b

**Comment by tangly1024** [comment]
Hi，看来目前是卡在了修改文件这一步，你可以说明一下需求是要改成什么样，我可以为你提供配置文件的修改。


---
关于其他问题的一一答复：

1. > 好的非常感谢，不过我去试过了不出意外改文件又出错拉，不知道为啥，我怀疑又是挂V的问题

- 这个问题需要提供的vercel编译日志才好确认，改动文件时一个英文符号的错误也可能导致编译出错。




2. > NotionAPI 集合查询错误 02ab3b8678004aa69e9e415905ef32a5 响应代码 504（网关超时

- 这个错误提示是哪里的，我记得代码中没有抛出这个提示语



3. > 为什么换了个页面就用不了啊 我都一比一还原了。https://www.notion.so/xinkeji/e50b8daaa6d24f3c92fea5af4c0b9f94?v=407118027d614dcaa086c01bd4b2721b

- 由于很多潜在的格式问题，除了复制[该模板](https://www.notion.so/tanghh/02ab3b8678004aa69e9e415905ef32a5?v=b7eb215720224ca5827bfaa5ef82cf2d)的页面有经过验证可用，其他自创建的Notion页面我无法保证可以使用😂。

**Comment by xinkeji** [comment]
是这样的，我找个一个可以rss添加notion文章的方法，只不过他是单独生成的一页数据～我就想着能不能直接把咱们的网站直接用这个页面的数据对接～

**Comment by tangly1024** [comment]
> RSS添加Notion文章

你指的是类似https://notion-feed.com/ 这个吗😂

**Comment by xinkeji** [comment]
是的

**Comment by tangly1024** [comment]
如果是这样，程序要做一些兼容处理才可以，此功能也许会在未来的版本中添加支持。
