### ISSUE TITLE
【nav 主题】修改代码文件后部署失败，结果是Vercel抽风

### ISSUE THREAD

**Issue by uniech** [tangly1024/NotionNext#2373]
**描述bug**
<img width="424" alt="image" src="https://github.com/tangly1024/NotionNext/assets/131935550/918c08a8-adb9-471d-bcf3-1b7d954cbf90">
我只是稍微修改一个 css 就会部署报错
我看了原文件 nav 主题的index.js / style.js 都处于报错状态
并且在 notion 中更改 css 好像也无法应用在这个主题中

**期望的正常结果**
可以正常对 nav 主题进行修改

**复现步骤**
只需在 nav 主题中的 style.js 更改任意样式就会部署报错

**环境**
NotionNext版本  [4.4.6]
主题  [nav]
部署方案  [vercel]
操作系统  [macOS]
 浏览器  [chrome]

**补充说明**
无

**Comment by 88lin** [comment]
报错信息是什么

**Comment by uniech** [comment]
> 报错信息是什么

抱歉我今天又尝试了一下，已经正常了，之前貌似是 vercel 抽风了
