### ISSUE TITLE
【vercel部署】vercel部署时报错

### ISSUE THREAD

**Issue by lifeafter619** [tangly1024/NotionNext#2379]
**描述遇到的问题**
更新代码后vercel出现报错，疑似和翻译有关？

**相应配置**

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/65111206/7bba55b3-bac2-4e2e-a4c4-a7d03099ff5d)
![image](https://github.com/tangly1024/NotionNext/assets/65111206/8f3afcf2-7f84-46e1-911f-770b3875ddbb)
![image](https://github.com/tangly1024/NotionNext/assets/65111206/20133e68-5f24-4acd-83e8-aca2b6f9ed7d)

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**Comment by Yanyutin753** [comment]
加1

**Comment by tangly1024** [comment]
新版已修复

**Comment by lifeafter619** [comment]
已更新至最新版本 该问题仍然复现
![image](https://github.com/tangly1024/NotionNext/assets/65111206/0e2a4404-a9fd-4c4f-b004-4d4da1e81853)
![image](https://github.com/tangly1024/NotionNext/assets/65111206/99f3b251-3173-4c07-8312-08c77449ce43)
