### ISSUE TITLE
【Matery主题】标签和分类显示不正常

### ISSUE THREAD

**Issue by Couslever** [tangly1024/NotionNext#2380]
**描述bug**
matery主题的顶部导航栏似乎会遮挡标签（tag）和分类（category）页面的内容。以我的网站的分类页为例：
matery下
![image](https://github.com/tangly1024/NotionNext/assets/165126705/b19f2117-df33-4edd-b4d9-6a3894d9166d)
simple下
![image](https://github.com/tangly1024/NotionNext/assets/165126705/20d9f9e2-1ae2-40fd-b3fb-ecbcc1cae1d5)

以作者博客的标签页为例：
matery下
![image](https://github.com/tangly1024/NotionNext/assets/165126705/2cec2f45-01a5-4a3e-a77c-1d5c5af7c014)
hexo下
![image](https://github.com/tangly1024/NotionNext/assets/165126705/82867a0f-93a6-4ef5-82e4-84a29a3b2cb5)

**期望的正常结果**
【此项必填】按这个步骤，预期出现的现象应该是什么

**复现步骤**
【此项必填】你的操作步骤，按此步骤理应在我的开发环境出现一样的bug。

**环境**

- 【必填】NotionNext版本 [4.4.6]
- 【必填】主题 [matery]
- 【必填】部署方案 [vercel]
- 【可选】操作系统: [ windows]
- 【可选】浏览器 [edge]

**Comment by tangly1024** [comment]
已在最新版修复
