### ISSUE TITLE
【修改代码】求助blog最下面的 powered by NotionNext 4.**怎么修改？

### ISSUE THREAD

**Issue by Blackxuan6** [tangly1024/NotionNext#2386]
**描述遇到的问题**

求助blog最下面的 powered by NotionNext 4.x怎么修改成其他链接？

**环境**

- 操作系统: [例如. iOS, Android, macOS,  #windows]
- 浏览器 [例如. chrome, safari, [firefox]]
- 版本 [4.x]

**Comment by tangly1024** [comment]
只能改动对应主题的源码，如果没有开发经验请谨慎尝试，可能会导致编译失败

 以example主题为例，powered版权信息在Footer（页脚组件中）；
位置是： `/themes/example/components/Footer.js` 
相关代码：
https://github.com/tangly1024/NotionNext/blob/4bda12d0f5d5e2b273a3d3d04df0b5d0b32f5ce4/themes/example/components/Footer.js#L19-L22

**Comment by Blackxuan6** [comment]
非常感谢帮助，有一丢丢对开发的认识，这行代码的意思是a标签里面加了一个超链接，然后起了个名字叫做notionNext，不知道理解的对不对，后面那个Version我看联系上面的代码，好像是查询备案号地址的官网，为啥会显示成安装的notionNext的版本号，还是我没有理解对。
     那个我修改了超链接内容后，跳转成功了，但是后面的版本还是4.4.6，不知道这个版本号是在哪里获取并修改。

**Comment by Blackxuan6** [comment]
###   非常感谢帮助

 
   有一丢丢对开发的认识，这行代码的意思是a标签里面加了一个超链接，然后起了个名字叫做notionNext，不知道理解的对不对，后面那个Version我看联系上面的代码，好像是查询备案号地址的官网，为啥会显示成安装的notionNext的版本号，还是我没有理解对。
 那个我修改了超链接内容后，跳转成功了，但是后面的版本还是4.4.6，不知道这个版本号是在哪里获取并修改。那个我修改了超链接内容后，跳转成功了，但是后面的版本还是4.4.6，不知道这个版本号是在哪里获取并修改。

**Comment by tangly1024** [comment]
siteConfig('VERSION')

此函数会读取 blog.config.js 中的VERSION配置；

而blog.config.js中的配置，会被项目根目录的  .env.local （环境变量） 覆盖

![image](https://github.com/tangly1024/NotionNext/assets/15920488/dc85c2ff-2698-4ac3-b074-3729ca887e61)

**Comment by Blackxuan6** [comment]
终于明白了，再次感谢解答，会持续关注.
