### ISSUE TITLE
【画册视图】大图点击bug，图片缩放尺寸位置错误

### ISSUE THREAD

**Issue by PrainLopez** [tangly1024/NotionNext#2388]
**描述bug**
配置 `process.env.NEXT_PUBLIC_POST_DISABLE_GALLERY_CLICK || true` 后，图片点击缩放尺寸位置错误
![image](https://github.com/tangly1024/NotionNext/assets/61592725/67fbbc35-f657-4d00-b2b6-333610867e18)

**期望的正常结果**
【此项必填】按这个步骤，预期出现的现象应该是什么
点开居中查看大图

**复现步骤**
【此项必填】你的操作步骤，按此步骤理应在我的开发环境出现一样的bug。
我自己优化的图片源，在notion中上传时直接使用压缩过的.webp格式。不知是否和新版本自带的图片压缩有冲突

**环境**

- 【必填】NotionNext版本 [例如. 4.0.18] main 分支 4bda12d commit: Merge pull request tangly1024#2383 from Vixcity/wx
- 【必填】主题 fukasawa
- 【必填】部署方案 Vercel
- 【可选】操作系统: iOS Chrome, Windows Chrome均发生
- 【可选】浏览器 见上

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
已提交修复补丁 https://github.com/tangly1024/NotionNext/commit/dc17c1e533a5e7876cee2a19b0e0c86da1f30440
