### ISSUE TITLE
【netlify部署】打包时不生成rss文件

### ISSUE THREAD

**Issue by ymh0000123** [tangly1024/NotionNext#2402]
**描述bug**
rss文件不存在  

**期望的正常结果**
rss正常生成

**复现步骤**
![image](https://github.com/tangly1024/NotionNext/assets/107793048/5a7bf277-ab04-4080-aec0-f77dc713511c)

**环境**

- 【必填】NotionNext版本 4.5.1
- 【必填】主题 heo
- 【必填】部署方案 netlify
- 【可选】操作系统: windows
- 【可选】浏览器 edg   
node版本 18.x

**补充说明**
【可选】与问题相关的其它说明
![image](https://github.com/tangly1024/NotionNext/assets/107793048/52fe541c-830c-4f1b-9522-38c84ed0d2ce)  
我的 [博客rss](https://xiaofeishu-boke.netlify.app/rss/feed.xml)

**Comment by ymh0000123** [comment]
发现报错
```
8:23:05 AM: [RSS订阅] 生成/rss/feed.xml
8:23:05 AM: Warning: data for page "/search" is 129 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
8:23:05 AM: See more info here: https://nextjs.org/docs/messages/large-page-data
```

**Comment by tangly1024** [comment]
属于警告，不影响rss生成
