### ISSUE TITLE
[ Gitbook 主题 ] 文档自动分组排序功能使用，siteConfig无效

### ISSUE THREAD

**Issue by W4ddl3** [tangly1024/NotionNext#2412]
**描述bug**

NEXT_PUBLIC_GITBOOK_AUTO_SORT 设置为 false 时不起作用
https://github.com/tangly1024/NotionNext/blob/f037a41c7a3e5aef6ae4db8a12d4dd7770d9bb91/themes/gitbook/config.js#L4

如下图是我的 Notion 列表
![Shot 2024-05-14 at 12 04 17](https://github.com/tangly1024/NotionNext/assets/141616559/b4fc9bde-e08c-46ab-90f7-3657f981a58e)

可以看到理论排序应该是
`快速了解`
`产品定价`
`部署指南`
`页面介绍`
`联系我们`

如下图是实际部署的效果
![Shot 2024-05-14 at 12 06 09](https://github.com/tangly1024/NotionNext/assets/141616559/0bb88014-dc84-4dd9-b6a3-87f646838921)

可以看到实际排序是
`快速了解`
`产品定价`
`联系我们`
`部署指南`
`页面介绍`

也就是它和 NEXT_PUBLIC_GITBOOK_AUTO_SORT 设置为 true 时 一样，把分类的放到最下面，单页放到最上面

即，NEXT_PUBLIC_GITBOOK_AUTO_SORT 这个参数设置为 false 时已失效

**期望的正常结果**
无须多言

**复现步骤**
半个月前的版本是没问题的，前几天我更新了一下代码，就不起作用了

**环境**

- 【必填】NotionNext版本 [ 4.5.2 ]
- 【必填】主题 [ Gitbook ]
- 【必填】部署方案 [ Vercel ]

**Comment by W4ddl3** [comment]
奥，我想起来。是这个变量本来就没用

我之前是把这里的 true 改成 false 才达到目的的
https://github.com/tangly1024/NotionNext/blob/f037a41c7a3e5aef6ae4db8a12d4dd7770d9bb91/themes/gitbook/components/NavPostList.js#L115

**Comment by tangly1024** [comment]
感谢反馈，经过代码排查确实发现配置无效，并且顺藤摸瓜发现一个影响范围比较广的重大bug。很快会提交补丁修复

**Comment by W4ddl3** [comment]
> 感谢反馈，经过代码排查确实发现配置无效，并且顺藤摸瓜发现一个影响范围比较广的重大bug。很快会提交补丁修复
> 
> 更新代码后，可使用环境变量`NEXT_PUBLIC_GITBOOK_AUTO_SORT`或者在Notion中添加Config-`GITBOOK_AUTO_SORT`实现：
> 
> ![image](https://private-user-images.githubusercontent.com/15920488/330693656-f0d323fc-baac-4251-a74e-1938d4063dad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODUyNDIsIm5iZiI6MTcxNTc4NDk0MiwicGF0aCI6Ii8xNTkyMDQ4OC8zMzA2OTM2NTYtZjBkMzIzZmMtYmFhYy00MjUxLWE3NGUtMTkzOGQ0MDYzZGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE0NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZTg2Y2QzMjJkNjY3M2E3ZmJkMWE2M2VlZWIwZTAwNmVhNzE5OGY1ZWQyNzI2Yjc4ZTI3NmMxN2FlMjEzNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S39KCnOBU9x-ObnAA4xIwon2iW4WQ_ubWeAT9mqoK_o)

感谢您的回复。


但是我更新了最新版本的代码，我所反馈的 NEXT_PUBLIC_GITBOOK_AUTO_SORT 变量仍然没有起作用
我要实现 **不自动按分类名 归组排序文章**
按道理来讲，将 NEXT_PUBLIC_GITBOOK_AUTO_SORT = false 即可
但是这么设置了没用

我只能把，这里的 true 改成 false 才能实现
https://github.com/tangly1024/NotionNext/blob/f037a41c7a3e5aef6ae4db8a12d4dd7770d9bb91/themes/gitbook/components/NavPostList.js#L115
