### ISSUE TITLE
没法生成RSS

### ISSUE THREAD

**Issue by Winner365-China** [tangly1024/NotionNext#2418]
**描述遇到的问题**
没法生成RSS了

**相应配置**
[网站地址](https://blog.365sites.top/rss/feed.xml)

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/133582008/17c1d1c1-3c76-406e-8fe0-2d3f2d1ecb06)

**环境**

- 操作系统: windows
- 浏览器 edge
- 版本 124.0.2478.97 (正式版本) (64 位)

**Comment by tangly1024** [comment]
已在最新[提交](https://github.com/tangly1024/NotionNext/commit/89d385855f0c028d859c02f805dc03cc5b0ddfe2)中修复，请更新
