### ISSUE TITLE
feat: 更灵活的 page 配置

### ISSUE THREAD

**Issue by yuzhanglong** [tangly1024/NotionNext#244]
如下图，配置为 page 类型的 notion 文档会自动展示在右上角，但有些我不太想展示在右上角，只希望用户能够通过链接访问（例如一些非博客文章，如一些自己写的工具的使用文档啥的）

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/56540811/168329673-59ff9f51-1978-406c-85a2-183a97856590.png">

建议：notion 表格增加一列配置，例如 showTitleInHeaderForPage 表示是否以标题链接的形式展示在博客首页header

**Comment by tangly1024** [comment]
hi，有趣的提议 ~
我将在新分支 [feature-page-visible-in-menu](https://github.com/tangly1024/NotionNext/tree/feature-page-visible-in-menu) 中开发这项功能。

出于使用便捷度、以及表格列 的复用度考虑，我不会考虑新增一个列单独 解决是否在标题栏 展示 的 问题。
相对的，我采用的方案是 在原有的`Status`字段 中进行 扩展，新增一个 类型`Invisible`表示页面已发布，但在博客中不可见，只能通过链接访问，除了单页，博文列表也同样有效。

<img width="1041" alt="图片" src="https://user-images.githubusercontent.com/15920488/168406058-c9bcbcbc-4663-4116-bddd-c23279827fba.png">

**Comment by yuzhanglong** [comment]
> hi，有趣的提议 ~ 我将在新分支 [feature-page-visible-in-menu](https://github.com/tangly1024/NotionNext/tree/feature-page-visible-in-menu) 中开发这项功能。
> 
> 出于使用便捷度、以及表格列 的复用度考虑，我不会考虑新增一个列单独 解决是否在标题栏 展示 的 问题。 相对的，我采用的方案是 在原有的`Status`字段 中进行 扩展，新增一个 类型`Invisible`表示页面已发布，但在博客中不可见，只能通过链接访问，除了单页，博文列表也同样有效。
> 
> <img alt="图片" width="1041" src="https://user-images.githubusercontent.com/15920488/168406058-c9bcbcbc-4663-4116-bddd-c23279827fba.png">

好，感谢！

**Comment by tangly1024** [comment]
- 已发布，[v3.3.6](https://github.com/tangly1024/NotionNext/releases/tag/v3.3.6)
- 
- 预览效果：
https://preview.tangly1024.com/example-3
