### ISSUE TITLE
[Bookmark] 在bookmark中 无法显示封面图 og : image 自定义选项

### ISSUE THREAD

**Issue by eddiehe99** [tangly1024/NotionNext#247]
**为什么提出这个新的特性改动**

喜欢在 Notion 把网页保存为 bookmark。保存为 bookmark 时，Notion 会抓取 og : image 作为图片嵌入到 Notion 页面中。

目前具体的 blog 页面如果有 cover，则会以 cover 作为 og : image。但是在 blog 的主页，似乎无法获取，保存为 bookmark 之后显示的是空白的图片。

**描述一下你推荐的解决方案**

发现在 components/CommonHead.js 中有定义 og : image，但是 blog 主页似乎不起作用。希望在 blog.config.js 中加入 image 自定义链接选项。

**描述一下你考虑过的其它替代解决方案**

以 public/bg_image.jpg 为 og : image。

**Comment by tangly1024** [comment]
> 发现在 components/CommonHead.js 中有定义 og : image，但是 blog 主页似乎不起作用。

# 此bug在我的博客中没有出现
正如你所发现的，网站已经定义了og:image，而且它在我的站点上起了作用。如下图：

<img width="943" alt="图片" src="https://user-images.githubusercontent.com/15920488/168969352-bc4ee13a-e911-4793-a4d0-7a84fdd48e97.png">

显然的是，你的站点封面图却不翼而飞。

# 问题的原因比较诡异

在浏览器中查看你的站点源码得知，封面图是一张notion自带的图片，这应该就是你的Notion数据库的Page_cover
<img width="762" alt="图片" src="https://user-images.githubusercontent.com/15920488/168969839-8b36f7d2-4817-4100-af45-2a68a5513040.png">

这张图片是可以打开的，但是在Bookmark中区却是一个空白：
https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F4012dae2-19ac-4073-a171-6ce8536cf585%2Fbearwinterhouse1920x1200.jpg?table=block&id=f2e4fc1a-7e4b-4718-b52f-195e97eac2a6&cache=v2

# 可能可以解决问题的尝试
试着手动重新上传封面图片，修改一下此项即可：
<img width="1365" alt="图片" src="https://user-images.githubusercontent.com/15920488/168969714-89f13e98-ce53-4f00-a0fa-d289875ffd0c.png">

另外，附上我的封面图：
https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F10eb466a-599b-4513-bcbf-2331cf88078d%2Fpexels-photo-546819.webp?table=block&id=bee1fccf-a3bd-47a1-a7be-83cc71372d83&cache=v2

**Comment by eddiehe49** [comment]
无法解决，不知道什么原因。试过删库重新 Fork，仍然不能解决。

无论使用 Notion 自带的 Gallery 中的图片、Upload 的图片、通过 Link 导入的图片还是 bg_image.jpg，保存为 bookmark 的时候都是空白的。

查看了我空白 bookmark 的源码，奇怪的是，src="data:image/gif;base64,R0lGOD......"，似乎会把图片进行一次编解码？

而且发现一个不同的地方，你的图片链接为“https://www.notion.so/**image**/......”而无论我使用 Gallery、Upload、Link，最后在 blog 看 og : image 的链接都是“https://www.notion.so/**images**/......”。不知有没有影响？

**Comment by tangly1024** [comment]
- 嗨，我的建议是：不要用Notion自带的这张图作为封面，将他替换成别的图后再尝试一下。
<img width="555" alt="图片" src="https://user-images.githubusercontent.com/15920488/172747034-c80c0978-99b4-4ca2-8fe7-6db2de78a741.png">

- 理由，我尝试将你网站中的多个页面添加为notion书签，其中有两个页面是无法抓取到封面的，而这两个封面的共同点是 ‘用了上面这个图片作为封面’ 。
<img width="595" alt="图片" src="https://user-images.githubusercontent.com/15920488/172747222-fe2089fc-1ea7-4ad5-99bd-8b0591b25cdc.png">

- 我想这应该是notion本身bookmark抓取封面的问题，至少我在微信中分享你的主页时，是可以抓取到封面的：
<img width="276" alt="图片" src="https://user-images.githubusercontent.com/15920488/172747361-3b0d09c5-5c97-47c4-a382-4a817f50a644.png">

**Comment by eddiehe99** [comment]
感谢回复！最近重新折腾了一下，发现可能是缓存的问题。之前都是 Fetch and merge 你的更新，这样的更新还会存在我说的问题，前几天发现重新手动在 Vercel Deploy 一次就解决了，谢谢！
&nbsp;
&nbsp;
------------------ Original ------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Jun 9, 2022 09:54 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [tangly1024/NotionNext] [Bookmark] 在bookmark中 无法显示封面图 og : image 自定义选项 (Issue #247)

&nbsp;



  
嗨，我的建议是：不要用Notion自带的这张图作为封面，将他替换成别的图后再尝试一下。
  

  
理由，我尝试将你网站中的多个页面添加为notion书签，其中有两个页面是无法抓取到封面的，而这两个封面的共同点是 ‘用了上面这个图片作为封面’ 。
  

  
我想这应该是notion本身bookmark抓取封面的问题，至少我在微信中分享你的主页时，是可以抓取到封面的：
