### ISSUE TITLE
【自动多语言开关】网页链接会多一个“/en/”

### ISSUE THREAD

**Issue by hprandom** [tangly1024/NotionNext#2471]
**描述bug**
【此项必填】

在网站文章链接中，会多一个"/en/"，所有文章的链接都是这样。
网站已经在vercel那里设置了"zh-CN“，没有设置网站英文版的链接。

**期望的正常结果**
【此项必填】
能否把链接中的这个"/en/"去掉，看着真的很别扭。
我不知道怎么会多这个东西除了的。

**复现步骤**
【此项必填】你的操作步骤，按此步骤理应在我的开发环境出现一样的bug。

**环境**

- 【必填】NotionNext版本 最新版也是如此
- 【必填】主题 [ hexo]
- 【必填】部署方案 [vercel]
- 【可选】操作系统: 网站链接，和浏览的系统无关
- 【可选】浏览器 同上

**补充说明**
【可选】与问题相关的其它说明
![1](https://github.com/tangly1024/NotionNext/assets/48062021/597fe248-e8ed-44f6-8131-1d9261332119)
如图，打开主页就会有"/en"这个尾巴

![2](https://github.com/tangly1024/NotionNext/assets/48062021/7c8952fe-8abf-4af0-8cd9-53c56c5354b9)
文章链接也是如此

**Comment by tangly1024** [comment]
如果你的浏览器偏好是英文，则会自动跳转。感谢反馈，我在最新版默认关闭此特性，如需打开请在Notion_CONFIG中配置 REDIRECT_LANG = true即可。

默认语言取自用户浏览器中的偏好语言(window.navigator.language)
例如用户的浏览器默认语言如果是英文 ， 则会跳转到 /en目录；否则就不会自动跳转，当然用户可以选择从菜单栏自行选择切换语言。

![Untitled](https://github.com/tangly1024/NotionNext/assets/15920488/dc1320a4-3d0d-457f-9498-9a4390943387)
