### ISSUE TITLE
【樱花特效】无法显示，配置不生效

### ISSUE THREAD

**Issue by LxAnC** [tangly1024/NotionNext#2477]
**描述bug**
配置了樱花掉落的动效，无法显示

**期望的正常结果**
应该能够正常显示

**复现步骤**
由于notion.config没有这个选项，我去blog.config,js修改，保存之后一直没有效果

**环境**

- 【必填】NotionNext版本最新
- 【必填】hexo
- 【必填】vercel+自定义域名
- 【可选】ma c
- 【可选】chrome

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
感谢反馈，樱花特效的问题，已经修复。
