### ISSUE TITLE
RSS生成订阅失败

### ISSUE THREAD

**Issue by kitety** [tangly1024/NotionNext#2490]
**描述bug**
访问生成的rss但是没结果
<img width="1319" alt="image" src="https://github.com/tangly1024/NotionNext/assets/22906933/c5cf38b9-d425-4afd-9b44-07d64ca8fc34">
<img width="1131" alt="image" src="https://github.com/tangly1024/NotionNext/assets/22906933/bf99062a-634f-4db8-9b3e-5ad25eeee10e">

地址：[https://www.kitety.com/rss/feed.xml](https://www.kitety.com/rss/feed.xml)
**期望的正常结果**
希望可以正确的返回订阅内容

**复现步骤**
vercel部署出现，但是本地是OK的
<img width="944" alt="image" src="https://github.com/tangly1024/NotionNext/assets/22906933/72dbfd43-1707-4dd0-9c61-32af7d8168f8">

**环境**

- 【必填】NotionNext版本 
4.5.4.
- 【必填】主题 
hexo
- 【必填】部署方案 
vercel
- 【可选】操作系统: 
macOS
- 【可选】浏览器 
chrome

**补充说明**
【可选】与问题相关的其它说明
无

**Comment by sakuraee** [comment]
无法复现

**Comment by kitety** [comment]
但是部署的网页确实是有问题的啊 奇怪

**Comment by kitety** [comment]
是否还需要我提供别的一些参数

**Comment by kitety** [comment]
会不会因为我底部的footer 有修改会导致这个问题？
[Poetry.js](https://github.com/kitety/NotionNext/blob/main/themes/hexo/components/Poetry.js)

**Comment by sakuraee** [comment]
你fork的那个部署上去就有问题么，如果是的话我可以看下那个

**Comment by kitety** [comment]
我部署的就是我fork的，就有点奇怪，我

1.pull部署下

2.再注释那一句试试

**Comment by kitety** [comment]
重新pull 4.6.0 https://kitety-blog-546lfgbaz-aizaizuoris-projects.vercel.app/

**Comment by kitety** [comment]
删除古诗compoennt https://kitety-blog-m2l5ndyb0-aizaizuoris-projects.vercel.app/

**Comment by kitety** [comment]
> 你fork的那个部署上去就有问题么，如果是的话我可以看下那个

是的，我都部署了。我感觉我需要重新切一个分支来试试，用原始的NotionNext最新

**Comment by sakuraee** [comment]
你是自定义主题的么

**Comment by kitety** [comment]
目前已经解决，方案如下：重新pull为master的最新代码，vercel去除所有环境变量，只楼下pageId和link，这样就可以了。
先关闭吧。
