### ISSUE TITLE
[个性化配置]修改头像问题

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#250]
在public添加了头像文件。并在config文件中修改了头像文件的位置。结果博客中头像并未改变
**描述遇到的问题**
简单说明你遇到的问题，相关的日志、错误信息

**相应配置**
相关的配置，例如notion_page_id；你的网站地址

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**Comment by tangly1024** [comment]
新版本中 头像会读取notion模板的icon，当icon为空时将读取blog.config.js中的图片。

建议点击notion模板的左上角的页面icon， 直接上传头像即可。

**Comment by Angel0726** [comment]
谢谢
