### ISSUE TITLE
开启伪静态后 从文章页点击首页跳转后 网址路径错误

### ISSUE THREAD

**Issue by wensley** [tangly1024/NotionNext#2502]
**描述bug**
【此项必填】开启伪静态后，从文章页点击首页跳转后 首页网址路径错误

**期望的正常结果**
【此项必填】正常返回首页

**复现步骤**
【此项必填】
例如从 https://blog.zhcn.xyz/article/choosing-the-right-development-tools ，点击首页后跳转的网址是 https://blog.zhcn.xyz/.html

**环境**
- 【必填】NotionNext版本 4.5.4
- 【必填】主题  hexo
- 【必填】部署方案  vercel
- 【可选】操作系统: windows
- 【可选】浏览器  chrome, firefox

**Comment by vicacheung** [comment]
开伪静态不是 https://blog.zhcn.xyz/article/choosing-the-right-development-tools.html 吗？咋没有后缀了
