### ISSUE TITLE
不对svg格式图片缩放

### ISSUE THREAD

**Issue by flt6** [tangly1024/NotionNext#2519]
**描述bug**
上传notion图床和配置后的自定义图床中，svg图片被赋予"?xx=xx&width=400"等质量调整，无法执行，图像无法显示
![image](https://github.com/tangly1024/NotionNext/assets/42725841/60c76ab4-8f71-4ce7-a4b0-9f4676047802)

**期望的正常结果**
判断为svg时，跳过所有压缩

**复现步骤**
在一个页面内创建图片，用notion图床或支持了oss process的图床上传svg图片，渲染打开。

**环境**

- 【必填】NotionNext版本 实时同步，目前在[96d5e2e](https://github.com/tangly1024/NotionNext/commit/96d5e2ebee0f89a224730ba6949a4f313c3b26ab)
- 【必填】主题 hexo
- 【必填】部署方案 vercel，VPS
- 【可选】操作系统: windows
- 【可选】浏览器 chrome

**补充说明**
已修复：#2518

**Comment by tangly1024** [comment]
在此提交中修复 ： https://github.com/tangly1024/NotionNext/pull/2518
