### ISSUE TITLE
【HEO主题】修改主题配置代码后，编译失败

### ISSUE THREAD

**Issue by ichenc** [tangly1024/NotionNext#2528]
**描述遇到的问题**
Running build in Washington, D.C., USA (East) – iad1
Failed to compile.
Cloning completed: 1.755s
./themes/heo/config.js
Error: 
Vercel CLI 34.2.7
    ,-[
yarn install v1.22.19
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1
Detected Next.js version: 14.2.4
Running "yarn run build"
yarn run v1.22.19
$ next build
  ▲ Next.js 14.2.4
  - Environments: .env.local
  - Experiments (use with caution):
    · scrollRestoration
   Linting and checking validity of types ...
   Creating an optimized production build ...
[默认主题] /vercel/path0/themes/simple
Failed to compile.
./themes/heo/config.js
Error: 
  x Unexpected character '，'
    ,-[/vercel/path0/themes/heo/config.js:23:1]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1

**相应配置**
[相关的配置，例如notion_page_id；你的网站地址https://blog.ichenc.xyz/

**截图**
相关的页面，应该用结果

**环境**
windows，chrome
- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**Comment by tangly1024** [comment]
推荐在Notion_Config或环境变量中修改。

报错是因为引用了中文符号


![image](https://github.com/tangly1024/NotionNext/assets/15920488/61438403-ee30-4714-85c5-65c9a9ebe2d6)


我已经向你提交了补丁 https://github.com/ichenc/NotionNext/pull/1  ， 请点击同意合并即可自动更新代码并自动部署。

**Comment by ichenc** [comment]
非常感谢
