### ISSUE TITLE
[数据库Block] 网页无法打开

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#253]
**描述bug**
简单说明bug的现象、相关的错误提示、日志等
- 博客网址：[排序算法](https://coolnext.vercel.app/article/54525291-ef16-462f-8c45-43b56cbaaaba)这个网址无法打开，只有这篇博客有问题。不知道是不是这边博客中含有database的原因
- 对应的原始notion界面https://jeweled-trilby-556.notion.site/54525291ef16462f8c4543b56cbaaaba
- 打开博客显示
![image](https://user-images.githubusercontent.com/32816780/168993428-0a5bd93d-0fa6-46bf-94d6-95f0479b2713.png)

**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么
![image](https://user-images.githubusercontent.com/32816780/168993935-c3c00efe-ccbb-49f4-82ed-114c659e64ee.png)

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. windows]
- 浏览器 [例如. chrome,]
- 版本 [e.g. 3.3.5]

**补充说明**
其他博客没有问题，只有排序这篇博客有这个问题

**Comment by thedavidweng** [comment]
对应 notion 链接打不开，是不是页面权限问题？

**Comment by Angel0726** [comment]
> 对应 notion 链接打不开，是不是页面权限问题？你再试一试。

**Comment by tangly1024** [comment]
1.打开提示错误：
```Application error: a client-side exception has occurred (see the browser console for more information).```

2.页面提示请求数据超时：
```An error occurred with your deployment
FUNCTION_INVOCATION_TIMEOUT

```
3. 浏览器控制台提示：
```
Uncaught (in promise) Error: Failed to load static props
```

**Comment by tangly1024** [comment]
可以去掉数据库块试一下。

网络请求是正常的，但是渲染超过10秒导致请求中断🤔，这个问题要再观察一下。

**Comment by tangly1024** [comment]
普通的数据库是可以渲染的：示例： https://preview.tangly1024.com/article/example-1#32a7b6a9e1ba44a5982fa055f5b01366

问题的原因也许是你的数据库涉及的一些无法被正常渲染的字段、可以修改 一下试试

**Comment by Angel0726** [comment]
> 普通的数据库是可以渲染的：示例： https://preview.tangly1024.com/article/example-1#32a7b6a9e1ba44a5982fa055f5b01366
> 
> 问题的原因也许是你的数据库涉及的一些无法被正常渲染的字段、可以修改 一下试试

你用的不是数据库是表格。数据库无法渲染，表格是可以的
