### ISSUE TITLE
【example主题】添加目录功能

### ISSUE THREAD

**Issue by Le1a** [tangly1024/NotionNext#2532]
**描述bug**
【此项必填】example主题没有目录功能吗？

**期望的正常结果**
【此项必填】有其他主题一样的目录功能，例如
<img width="1046" alt="image" src="https://github.com/tangly1024/NotionNext/assets/97610822/fac226e7-d3d5-44e0-8168-8edd3d5fa1e0">

**复现步骤**
【此项必填】你的操作步骤，按此步骤理应在我的开发环境出现一样的bug。

**环境**

- 【必填】NotionNext版本 4.6.0
- 【必填】主题 example
- 【必填】部署方案  vercel 
- 【可选】操作系统: macOS
- 【可选】浏览器 chrome

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
确实没有，不过刚添加了
