### ISSUE TITLE
【Url访问bug】点击第2页之后的文章，url路径多了/page导致路径错误

### ISSUE THREAD

**Issue by Yohann0617** [tangly1024/NotionNext#2533]
**描述bug**
![image](https://github.com/tangly1024/NotionNext/assets/75626191/820ca49c-6a9d-4351-9856-7eea78fe3c14)

**期望的正常结果**
去掉/page则正常

**复现步骤**
![image](https://github.com/tangly1024/NotionNext/assets/75626191/bed0236f-4228-41a0-a5fd-a27697c04988)

**环境**

- NotionNext版本：[4.6.0]
- 主题 [hexo]
- 部署方案 [vercel]

**补充说明**
【可选】与问题相关的其它说明

**Comment by Yohann0617** [comment]
第一页的文章不存在这个问题

**Comment by Yohann0617** [comment]
![image](https://github.com/tangly1024/NotionNext/assets/75626191/e594f05a-7c2a-48fe-ab61-31a21e211c10)
第2页之后的文章路径都会加上/page导致路径错误

**Comment by LiFulian** [comment]
我也出现了，而且notion-next自己的文档也是第2个页面会404

**Comment by Yohann0617** [comment]
> 我也出现了，而且notion-next自己的文档也是第2个页面会404

notion-next自己的文档都没有第2页

**Comment by tangly1024** [comment]
感谢反馈，已修复
