### ISSUE TITLE
【URL】右键菜单默认配置问题

### ISSUE THREAD

**Issue by luras-oil** [tangly1024/NotionNext#2534]
**描述bug**

Category && Tag 的属性没有在 blog.config.js 里被修改前，在 notion 里配置完的 url 会导向原来的 category 和 tag 指向的 menu 界面（即默认的 notion 模版的 menu 界面，数据源是新的）

```
  CUSTOM_RIGHT_CLICK_CONTEXT_MENU_CATEGORY:
    process.env.NEXT_PUBLIC_CUSTOM_RIGHT_CLICK_CONTEXT_MENU_CATEGORY || true, // 是否显示分类
  CUSTOM_RIGHT_CLICK_CONTEXT_MENU_TAG:
    process.env.NEXT_PUBLIC_CUSTOM_RIGHT_CLICK_CONTEXT_MENU_THEME_TAG || true, // 是否显示标签
```

当 blog.config.js 里的这两个值被修改之后，url 才会导向正确的 menu 界面。

**期望的正常结果**

无需修改这两个值，就导向 notion 里所配置的 menu 界面。

**复现步骤**
1.在 notion 模版里增加一个 menu type 的 config。
2.点击页面的 往期整理->文章分类（文章标签）
3.新增的 menu type 会消失

**环境**

- NotionNext版本 [v4.6.0]
- 主题 [simple] (没试过其他主题)
- 部署方案 [vercel]
- 操作系统: [macOS]
- 浏览器 [chrome]

**Comment by tangly1024** [comment]
根据你的描述，这两个配置是用来开关右键菜单中的内容：

```
CUSTOM_RIGHT_CLICK_CONTEXT_MENU_CATEGORY:
    process.env.NEXT_PUBLIC_CUSTOM_RIGHT_CLICK_CONTEXT_MENU_CATEGORY || true, // 是否显示分类
  CUSTOM_RIGHT_CLICK_CONTEXT_MENU_TAG:
    process.env.NEXT_PUBLIC_CUSTOM_RIGHT_CLICK_CONTEXT_MENU_THEME_TAG || true, // 是否显示标签
```

默认是开启，右键菜单中，会显示出分类和标签两个入口。
![image](https://github.com/tangly1024/NotionNext/assets/15920488/3d375946-c1ff-4226-9548-13e970a7dfc0)
