### ISSUE TITLE
[页面渲染]引用中含有代码块不显示

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#254]
**描述bug**
简单说明bug的现象、相关的错误提示、日志等
当引用块中包含代码块时，代码块不显示。

**复现步骤**
出现这个bug的操作步骤
[博客网址](https://coolnext.vercel.app/article/1e5bbfd50f2f4562839549742c456516#5d95203efaec4b179b5e16fcd10c7945)
![image](https://user-images.githubusercontent.com/32816780/169185682-82609ee7-d332-4fb6-9a8c-38fb94729634.png)

[share网址](https://jeweled-trilby-556.notion.site/1e5bbfd50f2f4562839549742c456516)
![image](https://user-images.githubusercontent.com/32816780/169185875-65dd6128-4d86-462d-bb82-abacd101f15f.png)

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
https://github.com/tangly1024/NotionNext/pull/442

在最新版本提交中已经修复此问题，更新即可体验
<img width="864" alt="图片" src="https://user-images.githubusercontent.com/15920488/201509802-f0dcbe53-61dc-4d2d-8297-72cc8cb3d926.png">
