### ISSUE TITLE
[配置文件] 如何在vercel中添加pageid

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#255]
**描述遇到的问题**
简单说明你遇到的问题，相关的日志、错误信息
我想把blog.config.js 文件中的pageid迁移到vercel中。是这样操作吗？
- blog.config.js文件中的pageid部分应该如何操作，需要删除吗？，如下图所示：
  ![image](https://user-images.githubusercontent.com/32816780/169191555-0c3bdb7a-6bf8-4b5a-9a84-097120c71123.png)

- vercel中修改的位置
  ![image](https://user-images.githubusercontent.com/32816780/169191384-fac5a6d1-9b4d-41d2-8883-a4daf3d7ee85.png)

**相应配置**
相关的配置，例如notion_page_id；你的网站地址

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**Comment by tangly1024** [comment]
- 配置解释
```
NOTION_PAGE_ID: process.env.NOTION_PAGE_ID || 'xxxx'
```

表示优先会读取Vercel中的配置，若vercel中没有，则会读取blog.config.js中`||`后面的值，即上面的 'xxxx'。


> 需要删除吗？

- 可以删除或填写任意值。
