### ISSUE TITLE
[Duplicate]  ipad 博客显示太边缘

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#258]
**描述bug**
简单说明bug的现象、相关的错误提示、日志等
![image](https://user-images.githubusercontent.com/32816780/169433425-d46d0c42-be80-4275-bfe0-bf1a0c82b975.png)
**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. iOS]
- 浏览器 [例如. chrome, safari]
- 版本 [e.g. 22]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
请提供一下ipad型号，和网页访问的地址。

**Comment by Angel0726** [comment]
> 请提供一下ipad型号，和网页访问的地址。

ipad 2017。 使用chrome, safari。

**Comment by tangly1024** [comment]
此问题已修复：在之前的issues https://github.com/tangly1024/NotionNext/issues/196  中已经反馈并解决了此问题。

升级 到最新的V3.3.6版本即可体验 。

**Comment by Angel0726** [comment]
> 此问题已修复：在之前的issues #196 中已经反馈并解决了此问题。
> 
> 对应的代码提交： #201
> 
> 升级 到最新的V3.3.6版本即可体验 。

https://github.com/tangly1024/NotionNext/issues/196有留意到，升级到了3.3.5之前的页面有所改善。但是问题并未修复。

**Comment by tangly1024** [comment]
将对此问题进一步改善
