### ISSUE TITLE
[页面渲染] 无法渲染mermaid

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#260]
无法渲染mermaid的代码块。
notion原网址：https://jeweled-trilby-556.notion.site/d6413f5c6ee44f799ce7fed0488cf594
博客网址：https://coolnext.vercel.app/article/d6413f5c-6ee4-4f79-9ce7-fed0488cf594#e72f195b498645ab901e7e6ccb409de4
![image](https://user-images.githubusercontent.com/32816780/169644828-eef9a934-ee1e-48a1-bb9e-1485a4002094.png)

**描述bug**
简单说明bug的现象、相关的错误提示、日志等

**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
感谢你的提议. 
NotionNext使用 `react-notion-x`  项目来渲染Notion中的内容. Mermaid并不是默认支持的格式；

在`react-notion-x`项目中，这个问题也暂时未被解决。
ref: [NotionX/react-notion-x#188](https://github.com/NotionX/react-notion-x/issues/188)

期待有更厉害的开发者能协助解决此问题。
https://github.com/PrismJS/prism/pull/3050
https://github.com/PrismJS/prism/issues/2852

**Comment by Angel0726** [comment]
> 感谢你的提议. 
> NotionNext使用 `react-notion-x`  项目来渲染Notion中的内容. Mermaid并不是默认支持的格式；
> 
> 在`react-notion-x`项目中，这个问题也暂时未被解决。
> ref: [NotionX/react-notion-x#188](https://github.com/NotionX/react-notion-x/issues/188)
> 
> Mermaid我之前从未接触过，期待有更厉害的开发者能协助解决此问题。
> https://github.com/PrismJS/prism/pull/3050
> https://github.com/PrismJS/prism/issues/2852
> 
> 建议是：或许能用图片形式代替？

不太清楚。不过我知道hexo是可以渲染的

**Comment by tangly1024** [comment]
功能已更新
https://github.com/tangly1024/NotionNext/releases/tag/v3.6.0

**Comment by Angel0726** [comment]
> 博客网址：https://coolnext.vercel.app/article/d6413f5c-6ee4-4f79-9ce7-fed0488cf594#e72f195b498645ab901e7e6ccb409de4

我更新了你的最新分支
<img width="954" alt="image" src="https://user-images.githubusercontent.com/32816780/204288220-f1ea9290-3407-4340-8d43-cbaa2e61bcfe.png">
但是博客还是现示3.4.2，且mermaid还是不能进行渲染。是因为没有更新成功吗？

**Comment by tangly1024** [comment]
hi 
不知道是出于什么原因，你的vercel 发布版本状态是inactive， 最新的代码只是以preview模式发布，而非正式的production版本

## 建议
尝试在后台 您的发布历史列表中 点击右边的“三点按钮” 并选择 Promote to Production

<img width="1407" alt="204288692-d4340418-e30b-4cff-8067-887e20d7ef49" src="https://user-images.githubusercontent.com/15920488/206214126-5c27837e-deed-4b71-bf0f-596143ea6607.png">

**Comment by Angel0726** [comment]
> hi 不知道是出于什么原因，你的vercel 发布版本状态是inactive， 最新的代码只是以preview模式发布，而非正式的production版本
> 
> ## 建议
> 尝试在后台 您的发布历史列表中 点击右边的“三点按钮” 并选择 Promote to Production
> 
> <img alt="204288692-d4340418-e30b-4cff-8067-887e20d7ef49" width="1407" src="https://user-images.githubusercontent.com/15920488/206214126-5c27837e-deed-4b71-bf0f-596143ea6607.png">

Promote to Production之后，博客显示成了你的内容。有办法进行回滚操作吗
