### ISSUE TITLE
网页中不包含database，网页同样无法显示

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#261]
‘
https://coolnext.vercel.app/article/45912d39-2973-41ab-8420-1fc29159ee1b

https://jeweled-trilby-556.notion.site/45912d39297341ab84201fc29159ee1b
![image](https://user-images.githubusercontent.com/32816780/169692998-0e73bc73-56c8-4127-8478-800b9f6c2b69.png)

**描述bug**
简单说明bug的现象、相关的错误提示、日志等

**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
根据日志显示请求超时，无法打开。 

这个页面究竟经历了什么，改动了何处🤔

> [请求API] from:slug id:45912d39-2973-41ab-8420-1fc29159ee1b 2022-05-23T09:29:47.520Z 73f53e30-1c84-4032-a8b1-edbdf6268b3a Task timed out after 10.02 seconds

**Comment by Angel0726** [comment]
> 根据日志显示请求超时，无法打开。 
> 
> 这个页面究竟经历了什么，改动了何处🤔
> 
> > [请求API] from:slug id:45912d39-2973-41ab-8420-1fc29159ee1b 2022-05-23T09:29:47.520Z 73f53e30-1c84-4032-a8b1-edbdf6268b3a Task timed out after 10.02 seconds

怎么把日志给你

**Comment by tangly1024** [comment]
很奇怪，我将你的页面完整复制到我的Notion中，访问是正常的。
- 我的Notion地址 https://www.notion.so/tanghh/a12925ce35fc45aeab48e9ea1b08de9b
- 预览效果  https://notionnext-tlyong1992.vercel.app/article/a12925ce-35fc-45ae-ab48-e9ea1b08de9b

有个建议：
尝试将这个页面的内容重新复制导入一下。

**Comment by Angel0726** [comment]
好的

**Comment by Angel0726** [comment]
> 很奇怪，我将你的页面完整复制到我的Notion中，访问是正常的。
> - 我的Notion地址 https://www.notion.so/tanghh/a12925ce35fc45aeab48e9ea1b08de9b
> - 预览效果  https://notionnext-tlyong1992.vercel.app/article/a12925ce-35fc-45ae-ab48-e9ea1b08de9b
> 
> 有个建议：
> 尝试将这个页面的内容重新复制导入一下。

我有个问题，notion无法支持h6标题。以后会支持吗？还是不会

**Comment by tangly1024** [comment]
如果你指的是Heading的话，Notion 貌似只支持3级标题吧

<img width="372" alt="图片" src="https://user-images.githubusercontent.com/15920488/170392742-b6eb19c0-8263-44f1-af7c-5d18e15df9db.png">
