### ISSUE TITLE
【主题刷新】gitbook切换文章一直是全页面刷新

### ISSUE THREAD

**Issue by littlesusu** [tangly1024/NotionNext#2647]
**描述bug**
在gitbook 主题下，点击目录切换文章，会全页面刷新。
当前定位的目录会收起再展开，

**期望的正常结果**
同[官方](https://docs.tangly1024.com/about) 一致，可以局部刷新文章内容

**复现步骤**
无

**环境**

- 【必填】NotionNext版本 [ 4.6.1]
- 【必填】主题： gitbook]
- 【必填】部署方案： vercel
- 【可选】操作系统：windows
- 【可选】浏览器 ：edge

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
需要在环境变量中配置： NEXT_PUBLIC_THEME = gitbook
或者在blog.config.js 中，将主题写死为 gitbook;

然后关闭掉Notion笔记中NOTION_CONFIG的主题配置即可
