### ISSUE TITLE
[页面渲染] 代码块复制按钮定位出错

### ISSUE THREAD

**Issue by ycloong** [tangly1024/NotionNext#266]
**描述bug**
当代码过长时，滑动代码，代码复制按钮停留在中央，而不是在代码块右上角

**复现步骤**
显示长代码时，滑动代码就会浮现

**期望的正常结果**
希望左右滑动代码时，代码复制按钮能始终保持在代码块的右上角

**截图**
![image](https://user-images.githubusercontent.com/83064739/170257654-5d978467-6b54-414f-a520-cce4b56f3275.png)

**环境**

- 操作系统: [ windows]
- 浏览器 [ chrome,]

**补充说明**
附上博文地址;
[1-STM32工程文件配置](https://ycloong.top/article/116a2df3-9673-4910-8052-46a9ffc58bdf#e00a2f86976d4ddbaf1780c96af847b7)

**Comment by tangly1024** [comment]
功能已更新
https://github.com/tangly1024/NotionNext/releases/tag/v3.6.0
