### ISSUE TITLE
【多语言】设置网站语言默认en，网址自动转向 zh，能不能把 zh 改过来，或者把 en/zh 都去掉？

### ISSUE THREAD

**Issue by leaflyingl** [tangly1024/NotionNext#2664]
**描述bug**
网站默认设置语言是 en-US, 但是输入网址出来自动导向 example.com/zh，能不能把zh改过来，或者干脆把zh或者en都去掉？这个功能对搜索引擎有影响，而且对文档的访问位置有影响。

**期望的正常结果**
希望尽快修复

**复现步骤**
【此项必填】你的操作步骤，按此步骤理应在我的开发环境出现一样的bug。

**环境**

- 【必填】NotionNext版本 [例如. 4.6.1]
- 【必填】主题 [hexo]
- 【必填】部署方案 [vercel]
- 【可选】操作系统: [windows]
- 【可选】浏览器 [例如. chrome irefox]

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
最新版本已修复
