### ISSUE TITLE
[ BUG ] sitemap.xml 页面不存在了，作者本人的网站也是！

### ISSUE THREAD

**Issue by bbb3n** [tangly1024/NotionNext#2679]
- 现在只有 https://preview.tangly1024.com/sitemap.xml 存在网站地图
![Shot 2024-08-28 at 22 41 55@2x](https://github.com/user-attachments/assets/006cfb34-3303-43f9-8efa-9ae5a88e6a00)

- 其余网站均不存在，下方是作者的两个网站作为示例
- https://docs.tangly1024.com/sitemap.xml
![Shot 2024-08-28 at 22 42 48@2x](https://github.com/user-attachments/assets/63b73f2b-ef85-4c5f-8d16-f4157cf7fda1)

- https://blog.tangly1024.com/sitemap.xml
![Shot 2024-08-28 at 22 42 56@2x](https://github.com/user-attachments/assets/5367fe4e-fa71-41d5-8850-74e4e2a8730c)

- 我本人部署的所有网站，sitemap.xml 也是不存在了，今天检查 Google Search Console 时才发现网站地图功能没了

**Comment by moreoronce** [comment]
我也出现了相同情况, 使用的是export方式

**Comment by Phillweston** [comment]
看下这个commit呢？我这边自己的博客以及作者的博客点击链接能正常显示sitemap.xml
[https://github.com/tangly1024/NotionNext/commit/053fc6576be00c09360a91ad29bbd74aaf9632b9](https://github.com/tangly1024/NotionNext/commit/053fc6576be00c09360a91ad29bbd74aaf9632b9)

**Comment by tangly1024** [comment]
感谢反馈，这个问题昨天刚刚提交了补丁修复，更新即可修复

**Comment by moreoronce** [comment]
当前版本的sitemap会把站外链接通过和本站域名拼接的方式展示出来，类似这种：
`https://www.dolingou.com/https://github.com/tangly1024/NotionNext`

我尝试用Cursor修改了一下lib/sitemap.xml.js：

`  // 循环页面生成
  allPages?.forEach(post => {
    const slugWithoutLeadingSlash = post?.slug?.startsWith('/') ? post?.slug?.slice(1) : post.slug
    const url = `${BLOG.LINK}/${slugWithoutLeadingSlash}`
    
    // 检查是否为外部链接或以 http 开头的链接
    if (url.startsWith(BLOG.LINK) && !slugWithoutLeadingSlash.startsWith('http')) {
      urls.push({
        loc: url,
        lastmod: new Date(post?.publishDay).toISOString().split('T')[0],
        changefreq: 'daily'
      })
    }
  })
  const xml = createSitemapXml(urls)
  try {
    fs.writeFileSync('sitemap.xml', xml)
    fs.writeFileSync('./public/sitemap.xml', xml)
  } catch (error) {
    console.warn('无法写入文件', error)
  }
}`

**Comment by AllenRay456** [comment]
> 当前版本的sitemap会把站外链接通过和本站域名拼接的方式展示出来，类似这种： `https://www.dolingou.com/https://github.com/tangly1024/NotionNext`
> 
> 我尝试用Cursor修改了一下lib/sitemap.xml.js：
> 
> ```
>   // 循环页面生成
>   allPages?.forEach(post => {
>     const slugWithoutLeadingSlash = post?.slug?.startsWith('/') ? post?.slug?.slice(1) : post.slug
>     const url = `${BLOG.LINK}/${slugWithoutLeadingSlash}`
>     
>     // 检查是否为外部链接或以 https 开头的链接
>     if (url.startsWith(BLOG.LINK) && !slugWithoutLeadingSlash.startsWith('https')) {
>       urls.push({
>         loc: url,
>         lastmod: new Date(post?.publishDay).toISOString().split('T')[0],
>         changefreq: 'daily'
>       })
>     }
>   })
>   const xml = createSitemapXml(urls)
>   try {
>     fs.writeFileSync('sitemap.xml', xml)
>     fs.writeFileSync('./public/sitemap.xml', xml)
>   } catch (error) {
>     console.warn('无法写入文件', error)
>   }
> }
> ```

我的sitemap 也是有这个情况，同时 google 抓取站点地图一直失败，不知道跟这个链接有关系没？

@tangly1024 链接这个情况需要修复下。
