### ISSUE TITLE
[文章卡在Loading] 新的文章能够在首页显示标题但是无法打开，一直显示loading中。

### ISSUE THREAD

**Issue by shengyu-meng** [tangly1024/NotionNext#2746]
**描述bug**
新的文章能够在首页显示标题但是无法打开，打开后一直显示loading中；以前的文章能够正常显示。

**期望的正常结果**
希望和以前一样正常显示。

**复现步骤**
问题文章链接：
https://shengyu.me/article/Boundless-Intelligence
https://shengyu.me/article/renature

**环境**
- 【必填】NotionNext版本 4.7.2
- 【必填】主题 Hexo
- 【必填】部署方案 Vercel
- 【可选】操作系统:  Android windows]
- 【可选】浏览器  chrome， firefox, IE

**补充说明**
Vercel后台log:
![image](https://github.com/user-attachments/assets/691b4491-f634-49dc-beb7-c1927288475e)

**Comment by tangly1024** [comment]
你好；

我这边看似乎正常访问：https://shengyu.me/article/renature
![image](https://github.com/user-attachments/assets/f9f19973-051a-40f3-bfc9-24e5d93885a1)

另外
https://shengyu.me/article/Boundless-Intelligence 这篇也重指向了-> 《无界智能这篇文章》https://shengyu.me/article/mixintelligence

是已经解决了吗

**Comment by shengyu-meng** [comment]
好像是缓存的问题，过了24个小时好像已经解决了😂谢谢
