### ISSUE TITLE
[blog.config.js配置] 修改配置文件后，项目部署失败

### ISSUE THREAD

**Issue by leaflyingl** [tangly1024/NotionNext#2751]
**描述遇到的问题**
用 sync 更新到4.7.2最新版，但是更新后出现 CUSTOM_MENU: process.env.NEXT_PUBLIC_CUSTOM_MENU 错误，无论设置 false 还是 true，都报错，无法更新代码。

**相应配置**
notion_page_id: leaflying；网站地址: https://www.goldenbuds.online

**截图**
<img width="994" alt="1726914050145" src="https://github.com/user-attachments/assets/1f7483ff-2d4d-4f34-a182-bf9a8c67e5d7">

**环境**

- 操作系统: [windows]
- 浏览器 [chrome, yandex, firefox]
- 版本 [yandex 24.7.3.1160 beta (64-bit)]

**Comment by tangly1024** [comment]
配置错误导致：
https://github.com/leaflyingl/NotionNext/compare/main...tangly1024:NotionNext:patch-3

建议在NOTION_CONFIG中配置，否则可能会出现类似上述的代码格式异常，导致编译失败

**Comment by leaflyingl** [comment]
谢谢！搞定了！

> 配置错误导致： [leaflyingl/NotionNext@main...tangly1024:NotionNext:patch-3](https://github.com/leaflyingl/NotionNext/compare/main...tangly1024:NotionNext:patch-3)
> 
> 建议在NOTION_CONFIG中配置，否则可能会出现类似上述的代码格式异常，导致编译失败

**Comment by zsr-lukezhang** [comment]
> 谢谢！搞定了！
> 
> > 配置错误导致： [leaflyingl/NotionNext@main...tangly1024:NotionNext:patch-3](https://github.com/leaflyingl/NotionNext/compare/main...tangly1024:NotionNext:patch-3)
> > 建议在NOTION_CONFIG中配置，否则可能会出现类似上述的代码格式异常，导致编译失败

那就`Close`一下`Issue`吧
