### ISSUE TITLE
【帮助】画廊视图，Description字段如何显示多行？(借助Notion_Config轻松调整样式)

### ISSUE THREAD

**Issue by tanglyqq** [tangly1024/NotionNext#2759]
# 现象
description字段内容很多，但是这里只显示了一行

![图片](https://github.com/user-attachments/assets/f0bcf0a6-3e2d-4db7-87ce-821ab446da34)

# 原理
description描述字段默认只展示一行，但用户可以自行调整样式

# 解决

需要修改样式实现多行显示，效果如下：

![图片](https://github.com/user-attachments/assets/19407b3a-6d62-48da-9c90-9a3dfafa81bc)

# 修改方法：
在您的Notion_Config页面中添加一个 GLOBAL_CSS配置，内容如下即可：
```
.notion-property-text {
  white-space: normal;
}
```
配置示例：
![图片](https://github.com/user-attachments/assets/9d5e85be-2f8e-4c16-86db-64fb81ac66df)

**Comment by dexon9109** [comment]
谢谢 我成功啦

**Comment by StoksY** [comment]
> 谢谢 我成功啦 https://www.qiuqiubaba.com/%E7%BE%8E%E9%A3%9F/food1

你好，请问一下您的description和小标签怎么配置让他显示出来的呀？我也是hexo主题，是用的tag吗

**Comment by dexon9109** [comment]
> > 谢谢 我成功啦 https://www.qiuqiubaba.com/%E7%BE%8E%E9%A3%9F/food1
> 
> 你好，请问一下您的description和小标签怎么配置让他显示出来的呀？我也是hexo主题，是用的tag吗
> 
> @see #2760

可以在notion的视图窗口的Property里面进行更改默认展示的内容和顺序。这个是notion的视图窗口自带的功能。但是我现在遇到了新的问题

**Comment by StoksY** [comment]
好的好的，蟹蟹您



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年09月26日 14:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [tangly1024/NotionNext] 【帮助】画廊视图，Description字段如何显示多行？(借助Notion_Config轻松调整样式) (Issue #2759) |

谢谢 我成功啦 https://www.qiuqiubaba.com/%E7%BE%8E%E9%A3%9F/food1

你好，请问一下您的description和小标签怎么配置让他显示出来的呀？我也是hexo主题，是用的tag吗

@see#2760

可以在notion的视图窗口的Property里面进行更改默认展示的内容和顺序。这个是notion的视图窗口自带的功能。但是我现在遇到了新的问题
