### ISSUE TITLE
[更新内容] 看可以大概写下嘛，一直在关注，但是不知道你更新的什么

### ISSUE THREAD

**Issue by xinkeji** [tangly1024/NotionNext#277]
**为什么提出这个新的特性改动**
简要说明此特性解决的问题，例如，『博客站点的读者互动性不够强，和读者无法建立紧密的联系...』

**描述一下你推荐的解决方案**
简要说明你的解决方案建议，例如，『Giscus评论插件功能更加强大，用户只需留言既可在你的邮箱收到通知。。。』

**描述一下你考虑过的其它替代解决方案**
简要说明你所有想过的有可能解决此问题的方案。

**补充说明**
补充与此特性相关的内容

**Comment by xinkeji** [comment]
已经知道怎么看了，另外发现咱们这个貌似没有个国内能用的评论系统

**Comment by tangly1024** [comment]
为什么说国内不能用呢，我测试的话这几个插件在国内都是可以正常访问的：
<img width="758" alt="图片" src="https://user-images.githubusercontent.com/15920488/170911539-1d7ee2b8-975b-4eb8-ac8e-77359a7644d9.png">


更新内容一般都是小的功能性优化和修复BUG，这次的更新主要是新增了评论插件，对应的安装方法参考：https://tangly1024.com/article/notionnext-valine

更新太频繁了，以至于更新文档都没怎么完善，哎

**Comment by xinkeji** [comment]
好的懂了，请问什么时候弄rss啊

**Comment by xinkeji** [comment]
因为事实上，所有能做起来的网站都必须要要有个批量增加内容的方法，没有文章堆砌，就没有权重，没有自然流量的网站基本上就是自娱自乐～当然，也不是全盘否定自己写的东西，不可否认，自己网站一定要有自己的内容，但是不可否认的是所有高权重的网站都是成百上千个文章页面堆砌出来的，rss虽然对被收录也同样不太友好，但这可能是咱们这个体系唯一增加内容的方式了。

**Comment by xinkeji** [comment]
因为事实上，所有能做起来的网站都必须要要有个批量增加内容的方法，没有文章堆砌，就没有权重，没有自然流量的网站基本上就是自娱自乐～当然，也不是全盘否定自己写的东西，不可否认，自己网站一定要有自己的内容，但是不可否认的是所有高权重的网站都是成百上千个文章页面堆砌出来的，rss虽然对被收录也同样不太友好，但这可能是咱们这个体系唯一增加内容的方式了。

**Comment by xinkeji** [comment]
对了既然讲到了seo，也正好想给您一些seo的建议，由于我只是搭建了，但是并没有写内容，所以就经常看您的网站，也总结了几个问题。
1.文章最新内容后置，以至于之前认为您没有更新，第一篇文章仍是2021年的，我知道可以手动调整，但是能不能默认新增文章放首页（最重要）
2.看了您网站的百度收录，其实说实话不太不太理想的7个月了，好几个网站加起来只有60多个百度收录.没有任何权重。
这说明seo,肯定是又些问题的，我粗略的看了下，大概有这几个问题：
（1）没有任何有关seo的设置例如：sitemap生成，robots.txt，文章自动提交设置
（2）收录中没有任何分类收录和关键词收录（emm,这样显得关键词这个设置毫无意义）
（3）rss其实严格意义上不利于收录,如果可以的有个采集系统是最好的（例如火车头采集接口，采集规则可以让站长自己写）
以上只是我的浅见，并没有完整看过您的代码，如果您已经写过相关代码，请忽略我的问题~

**Comment by tangly1024** [comment]
嗨，感谢您认真的提议，正如你所说这个网站本身是出于自娱自乐所搭建的，访问的流量主要来自Google自然流量以及外部引流。（事实上我已经基本放弃了百度🤣，比起优化百度的SEO、也许开一个“百家号”效果会更直观）

像RSS这样批量导入文章内容的方式也不并不是NotionNext的初衷，相反的，我提倡个人写作的过程中不断思考总结而产生的价值。

关于重要的SEO部分，
1. robots.txt  和 sitemap.xml 都是自动生成，无法配置的， https://tangly1024.com/robots.txt
2. blog.config.js 中的关键词表示整个站点的关键词，但每偏文章在渲染站点时会把标签作为网页的关键词。
3. 如果只是为了采集、做一个内容农场的话，可能wordpress会更加合适

对了，近期暂时没有计划做rss的功能

**Comment by xinkeji** [comment]
好的吧~

**Comment by xinkeji** [comment]
如果可能的希望可以做个rss功能，一直再等，wp网站我有，国内服务器的，权重4左右，但是主要有个域名没有备案~，不想空着~

**Comment by tangly1024** [comment]
关于RSS订阅功能，我另起项目做了一个Demo版本（还有很大的优化空间），适配了RSS抓取文章。

- 此项目是独立的代码残酷： https://github.com/tangly1024/NotionNextRss  ，部署方式和NotionNext类似。

- 预览地址： https://notion-next-1bv421vcq-tlyong1992.vercel.app/
- NotionFeed页面： https://tanghh.notion.site/NotionFeed-Template-1dc036b6937645c4a8cb00519e939989
- 文章列表： https://www.notion.so/tanghh/888e1581351948b4874e528ed8549e45?v=5f6294d86b634294b866682ab1312d85
