### ISSUE TITLE
[Docker 部署 ] docker如何修改文件，我用SH进入修改blogconfig.js文件以后重启没有作用

### ISSUE THREAD

**Issue by lesnolie** [tangly1024/NotionNext#278]
**docker如何修改标题等**
我想用docker部署，但是通过修改config.js等文件，重启后并没有效果，例如改变主题等。

请问docker如何修改呢？十分感谢。

**Comment by tangly1024** [comment]
请确认你所执行的Docker脚本，如果是使用如下旧版脚本运行docker可能导致无法修改主题。

```
docker run -p 3000:3000 -e NOTION_PAGE_ID="02ab3b8678004aa69e9e415905ef32a5" tangly1024/notionnext:2.8.1
```

## 解决
请使用以下脚本进行部署 当前最新版本3.3.9

```
docker run -p 3000:3000 -e NEXT_PUBLIC_THEME="next" -e NOTION_PAGE_ID="02ab3b8678004aa69e9e415905ef32a5" tangly1024/notionnext:3.3.9
```

**Comment by k-ying** [comment]
@tangly1024 您好，我用最新的docker镜像部署也遇到了相同的问题，无论是用-v来挂载容器内/app/blog.config.js到宿主机、还是直接sh进容器内vi修改blog.config.js，都不起作用。（因为直接挂载文件比较方便设置以及保存）
后来尝试了部署时添加变量的方式-e NEXT_PUBLIC_THEME="next"，也不起作用。
附启动代码：
`
docker run
  -d
  --name='NotionNext'
  --net='bridge'
  --privileged=true
  -e TZ="Asia/Shanghai"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="NotionNext"
  -l net.unraid.docker.managed=dockerman
  -p '3888:3000/tcp'
  -e NEXT_PUBLIC_THEME="next" 'ghcr.nju.edu.cn/tangly1024/notionnext:latest'
7609bf1cf9eedac74f17f52a5886729d83c2fef349f17111ec19042f89824464
`
_（unraid部署所自动生成的，镜像下载使用了nju缓存加速，实际上还是ghcr.io/tangly1024/notionnext:latest）_

**Comment by k-ying** [comment]
@tangly1024 您好，我用最新的docker镜像部署也遇到了相同的问题，无论是用-v来挂载容器内/app/blog.config.js到宿主机、还是直接sh进容器内vi修改blog.config.js，都不起作用。（因为直接挂载文件比较方便设置以及保存）
后来尝试了部署时添加变量的方式-e NEXT_PUBLIC_THEME="next"，也不起作用；只能修改NOTION_PAGE_ID。
附启动代码：
```bash
docker run -d --name='NotionNext' --net='bridge' --privileged=true -e TZ="Asia/Shanghai" -e HOST_OS="Unraid" -e HOST_HOSTNAME="Tower" -e HOST_CONTAINERNAME="NotionNext" -l net.unraid.docker.managed=dockerman -p '3888:3000/tcp' -e NEXT_PUBLIC_THEME="next" 'ghcr.nju.edu.cn/tangly1024/notionnext:latest' 7609bf1cf9eedac74f17f52a5886729d83c2fef349f17111ec19042f89824464
```
_（unraid部署所自动生成的，镜像下载使用了nju缓存加速，实际上还是ghcr.io/tangly1024/notionnext:latest）_
