### ISSUE TITLE
notion数据库字段名修为中文后，菜单与子菜单不能正常显示

### ISSUE THREAD

**Issue by laoma2053** [tangly1024/NotionNext#2780]
**描述bug**
【此项必填】
// 自定义配置notion数据库字段名，配置截图如下：
![image](https://github.com/user-attachments/assets/bf5086ff-0ccc-4b13-a027-f057e32ae0bb)

notion文档里，类型设置截图如下：
![image](https://github.com/user-attachments/assets/66fabb7a-b292-417c-bdf8-e9089788e7f8)

网页前端展示，如下：
![image](https://github.com/user-attachments/assets/5bda4de7-e869-4eb1-ae72-a8a2b58241d9)

菜单与子菜单的内容只显示一个图标，文字和链接显示不出来
其他中文的公告、文章、单页都能正常显示

**期望的正常结果**
【此项必填】
设置菜单和子菜单，能正常设置显示

**复现步骤**

**环境**

- 【必填】NotionNext版本 4.7.3
- 【必填】主题 heo
- 【必填】部署方案vercel
- 【可选】操作系统:  windows]
- 【可选】浏览器 chrome

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
感谢反馈，此bug已修复
