### ISSUE TITLE
Heo主题英雄面板中，Skill Icon悬浮在文字上方（而不是下面）

### ISSUE THREAD

**Issue by OtakuSquirrel** [tangly1024/NotionNext#2803]
icon遮挡文字。应当在文字下方。

![image](https://github.com/user-attachments/assets/766de1e0-9dcc-4c81-a335-87c131b1e658)

环境
NotionNext版本 4.7.4
主题 Heo
部署方案 Vercel
操作系统 Windows
浏览器 Edge

**Comment by leaflyingl** [comment]
我想把这个图标删掉好像还不行，用//注销和只留空，都报错，不知道是不是哪里的问题

**Comment by tangly1024** [comment]
已修复 https://github.com/tangly1024/NotionNext/pull/2833
