### ISSUE TITLE
[多语言] 翻页后会错误跳转语言，Hexo模板

### ISSUE THREAD

**Issue by shengyu-meng** [tangly1024/NotionNext#2809]
**描述bug**
网站部署了zh和en两个版本，在打开[en版本](https://shengyu.me/en)时，翻动下一页后，会[错误跳转回中文页面](https://shengyu.me/en/page/2)（但是看起来网址路径并没有错）。

**期望的正常结果**
在[en首页](https://shengyu.me/en)[翻动到下一页](https://shengyu.me/en/page/2)时，正常显示英文数据库的内容。

**复现步骤**
使用hexo主题部署了[zh](https://shengyu.me/)和[en](https://shengyu.me/en)两个数据库，默认为zh，设定语言为随浏览器语言自动跳转。

**环境**

- 【必填】4.7.3
- 【必填】Hexo
- 【必填】Vercel
- 【可选】windows
- 【可选】chrome + safari + IE

**Comment by tangly1024** [comment]
已修复：https://github.com/tangly1024/NotionNext/pull/2832
