### ISSUE TITLE
在英文版网站中的文章显示中文文章tag

### ISSUE THREAD

**Issue by shengyu-meng** [tangly1024/NotionNext#2810]
**描述bug**
网站部署了zh和en两个版本，在打开[en版本](https://shengyu.me/en)时，英文文章会显示中文文章的tag（但是在英文数据库的文章中并没有设置这些tag）。
![image](https://github.com/user-attachments/assets/511f3df4-d511-4119-85f3-5e1cad660753)
![image](https://github.com/user-attachments/assets/c3d58b49-f3cc-42b5-ac12-69ecd9725305)

**期望的正常结果**
在[en版本](https://shengyu.me/en)中的文章，只显示英文tag。

**复现步骤**
使用hexo主题部署了[zh](https://shengyu.me/)和[en](https://shengyu.me/en)两个数据库，默认为zh，设定语言为随浏览器语言自动跳转。
在站点建设时，先完成了zh库的建设，然后将zh库中的post直接在notion中批量复制到了en库中（复制后en库中的文章原有中文tag全部自动丢失），然后手动将每篇复制到英文库中的中文post重新翻译成英文，并添加英文tag后重新发布。

**环境**
- 【必填】4.7.3
- 【必填】Hexo
- 【必填】Vercel
- 【可选】windows
- 【可选】chrome + safari + IE

**Comment by tangly1024** [comment]
已修复：https://github.com/tangly1024/NotionNext/pull/2831
