### ISSUE TITLE
求助：4.7.5 英雄区左侧“随便逛逛”改英文后怎么改字体大小

### ISSUE THREAD

**Issue by leaflyingl** [tangly1024/NotionNext#2848]
**描述遇到的问题**
4.7.5英雄区左侧 随便逛逛 四个字改英文后字体会变大， 原来是在  components 里面知道怎么改字体大小，但是新版移位置后不知道怎么调整字体大小了，想改成4号字

**相应配置**
相关的配置，例如notion_page_id；你的网站地址

**截图**
在电脑上不好截图

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**Comment by Hyphen-H** [comment]
> 在电脑上不好截图

老兄你认真的？你懒得描述问题，别人就懒得解决你的问题
