### ISSUE TITLE
图片设置标题后无法完全显示

### ISSUE THREAD

**Issue by SkysCrystal** [tangly1024/NotionNext#285]
**描述bug**
在Notion页中给原宽度的图片创建标题，原图大小在博客页面中无法显示图片上部。
Notion原图添加标题
![Notion原图](https://raw.githubusercontent.com/SkysCrystal/Figurebed/master/img/202206041626552.png)
页中图片上部被裁切
![页面上部裁切](https://raw.githubusercontent.com/SkysCrystal/Figurebed/master/img/202206041618299.png)
当我在notion中缩小图片宽度后，博客页面图片缩小后显示出来。
图片宽度缩小
![图片宽度缩小](https://raw.githubusercontent.com/SkysCrystal/Figurebed/master/img/202206041621311.png)

**复现步骤**
不调节插入图片的宽度，给图片在Notion中添加标题，观察博客页面。

**期望的正常结果**
在不修改图片在notion中宽度的情况下，在博客页面显示完全。

**截图**
相关截图在描述bug中

**环境**
- windows，
- chrome，
- 版本 102.0.5005.63（正式版本）

**补充说明**
暂无

**Comment by tangly1024** [comment]
v3.4.0版本中已修复此问题
