### ISSUE TITLE
夜间模式导致代码块叠加

### ISSUE THREAD

**Issue by Issac-v** [tangly1024/NotionNext#286]
**描述bug**
切换为夜间模式时代码块会叠加一次

**复现步骤**
复现网址: https://preview.tangly1024.com/article/example-1  
切换为夜间模式即可复现

**期望的正常结果**
代码块正常显示

**截图**
叠加效果
![image](https://user-images.githubusercontent.com/54757860/172035902-582d2c03-5615-45e2-86d5-fbd5e2ac0635.png)

**环境**

- 操作系统: WIN11
- 浏览器 chrome 
- 版本 102.0.5005.63（正式版本） （64 位）

**Comment by tangly1024** [comment]
3.4.0版本修复此问题
