### ISSUE TITLE
部署错误

### ISSUE THREAD

**Issue by 44maker** [tangly1024/NotionNext#288]
**2022年6月7日今天更改基本信息上传github，vercel显示一直报错无法部署**
所以我就重新fork，还是没有用
报错部分信息：Error occurred prerendering page "/archive". Read more: https://nextjs.org/docs/messages/prerender-error

**相应配置**
notion_page_id；https://44maker.notion.site/061f9eb9858a4f14b85a81171e95b4ad?v=2247d002fe00413ca6a30d8de74595ce
网站现在没了。。。

**截图**
![image](https://user-images.githubusercontent.com/101875427/172405630-1ea1c8d3-d1ef-4138-925c-fa2c3dd55503.png)

**环境**

- 操作系统: windows
- 浏览器 chrome
- 版本 102.0.5005.63

**Comment by tangly1024** [comment]
Hi 部署错误的原因应该是某篇文章没有设置发布日期导致的 。将date为空的 文章 设置 一下日期即可。

另外 这个问题在另一个issue中也已经提到，参考：https://github.com/tangly1024/NotionNext/issues/287

此漏洞 将很快 被修复。

**Comment by 44maker** [comment]
第一次写issue，这么快得到答复，您还紧急更新补丁修复，难以言说我对您的感激之情，希望您能事业顺利，阖家欢乐，祝Notion-Next越来越好！！！！！！！
