### ISSUE TITLE
【BUG】HEXO主题的备案信息未居中显示

### ISSUE THREAD

**Issue by Yohann0617** [tangly1024/NotionNext#2901]
**描述bug**
HEXO主题的备案信息未居中显示，如图：
![image](https://github.com/user-attachments/assets/a8e31ee3-4182-4ef3-b351-b5207a0c5c6c)

**期望的正常结果**
居中显示

**复现步骤**
无

**环境**

- 【必填】NotionNext版本 4.7.5
- 【必填】主题 hexo
- 【必填】部署方案 vercel
- 【可选】操作系统: windows
- 【可选】浏览器 chrome

**Comment by tangly1024** [comment]
感谢反馈，已修复 https://github.com/tangly1024/NotionNext/commit/f4f0acd13a36b7e8675142183964b65738a2fda1
