### ISSUE TITLE
【heo主题】目录和社群卡片固定

### ISSUE THREAD

**Issue by carwlyjoe** [tangly1024/NotionNext#2932]
**为什么提出这个新的特性改动**
前几天还是固定的，但是突然发现在最近的更新中被取消了。目录固定可以让用户浏览文章的时候不用一直往前翻反复回顾文章整体内容，替身用户体验

**描述一下你推荐的解决方案**
像之前一样固定目录和社群卡片

**描述一下你考虑过的其它替代解决方案**
固定目录

**补充说明**
固定卡片谢谢

**Comment by tangly1024** [comment]
感谢反馈，问题马上将被修复
