### ISSUE TITLE
【starter主题】nav导航栏，点击搜索后未出现搜索框

### ISSUE THREAD

**Issue by KaterinaJiang** [tangly1024/NotionNext#2934]
**描述bug**
![image](https://github.com/user-attachments/assets/cd2439cc-f6f6-4dd2-acb4-14d1471b0a4b)

**期望的正常结果**
搜索后出现正常的操作框

**复现步骤**
点击搜索

**环境**

NotionNext版本 [4.7.5]
主题 [starter]
部署方案 [notion]
操作系统: [windows]
浏览器 [chrome]

**补充说明**
【可选】与问题相关的其它说明

**Comment by KaterinaJiang** [comment]
还有两个问题麻烦大神们解答一下，十分感谢！！
1: starter主题怎么关闭顶部的nav导航栏？试过在notion上修改成draft但是依旧还是显示
2:怎么取消右键的切换主题？

**Comment by tangly1024** [comment]
Starter主题没有设计Search页面，没有设计搜索功能。
因此如果访问 domain.com/search 页面将是空白，新版本将加入此功能。
