### ISSUE TITLE
notion中的公式是居中的，博客中向左对齐

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#295]
notion：https://jeweled-trilby-556.notion.site/Bloom-Filter-08c0e3797ca44d9fadaf89668685634b
博客：https://coolnext.vercel.app/article/08c0e379-7ca4-4d9f-adaf-89668685634b
博客中的公式是左对齐，能不能居中对齐
![image](https://user-images.githubusercontent.com/32816780/173107005-28615001-2adb-415f-9f61-20b1a49aeacc.png)

**为什么提出这个新的特性改动**
简要说明此特性解决的问题，例如，『博客站点的读者互动性不够强，和读者无法建立紧密的联系...』

**描述一下你推荐的解决方案**
简要说明你的解决方案建议，例如，『Giscus评论插件功能更加强大，用户只需留言既可在你的邮箱收到通知。。。』

**描述一下你考虑过的其它替代解决方案**
简要说明你所有想过的有可能解决此问题的方案。

**补充说明**
补充与此特性相关的内容

**Comment by tangly1024** [comment]
可以✅ 近期版本会更新此特性

**Comment by tangly1024** [comment]
在最新的补丁 #297  中已修复此问题，更新可体验。
