### ISSUE TITLE
[页面渲染] md2notion导入的文章目录索引顺序有问题

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#296]
最大深度、最小深度应该在深度目录下面
https://coolnext.vercel.app/article/e7a8100b-c54e-43d2-83c0-d34bd0907926#d07d912568394586a118b9034e8d1a78
![image](https://user-images.githubusercontent.com/32816780/173197019-e8474fae-dd47-4eae-a63f-af7e36ed76a7.png)

**描述bug**
简单说明bug的现象、相关的错误提示、日志等

**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
Hi， 在排查此bug的过程中我遇到了一些问题：

我在Notion中创建了相同的页面结构，但并没有复现此Bug：

![图片](https://user-images.githubusercontent.com/15920488/173301117-c9edbe56-2b08-497f-835e-41f75edf254d.png)


具体导致“并排展示的Heading标题无法显示”的问题，我想还需要更多时间排查，比如你是怎么编写这篇文章的，流程是咋样，可以在另一篇文章中复现这个bug吗？

**Comment by Angel0726** [comment]
> Hi， 在排查此bug的过程中我遇到了一些问题：
> 
> 我在Notion中创建了相同的页面结构，但并没有复现此Bug：
> 
> ![图片](https://user-images.githubusercontent.com/15920488/173301117-c9edbe56-2b08-497f-835e-41f75edf254d.png)
> 
> 具体导致“并排展示的Heading标题无法显示”的问题，我想还需要更多时间排查，比如你是怎么编写这篇文章的，流程是咋样，可以在另一篇文章中复现这个bug吗？
> 
> 这是我测试的Notion页面和站点：
> 
> * https://www.notion.so/tanghh/4a5baa286ead4dd3a526f086ea35024d#6284e3ab91204fd4b5965a806d275745
> * https://notionnext-tlyong1992.vercel.app/article/example-1#6284e3ab91204fd4b5965a806d275745

我是把本地的markdown文件利用md2notion上传到notion中（记文件page1）。在notion中博客无法显示，所以我创建了一个新文件page2，并将page1中的内容逐次复制到page2中。博客能够打开，但是出现了目录的问题。
page2文件的具体编辑流程。我是把内容编辑好之后，在修改的并排内容。也就是说写了平衡二叉树、树的路径等问题之后，才将最大深度最小深度进行的并排

**Comment by tangly1024** [comment]
这个流程要复现有点复杂，在你的页面中也只有最大深度和最小深度这两项出现此问题，我只能将此bug定为一个小概率偶然事件。

很遗憾的是这里并没有什么api可以获取到目录，生成目录的函数是由@[transitive-bullshit](https://github.com/transitive-bullshit)编写的[get-page-table-of-contents](https://github.com/NotionX/react-notion-x/blob/master/packages/notion-utils/src/get-page-table-of-contents.ts)方法。如果可能的话，我需要重写这个方法来兼容你的页面格式。

**Comment by Angel0726** [comment]
> 这个流程要复现有点复杂，在你的页面中也只有最大深度和最小深度这两项出现此问题，我只能将此bug定为一个小概率偶然事件。
> 
> 很遗憾的是这里并没有什么api可以获取到目录，生成目录的函数是由@[transitive-bullshit](https://github.com/transitive-bullshit)编写的[get-page-table-of-contents](https://github.com/NotionX/react-notion-x/blob/master/packages/notion-utils/src/get-page-table-of-contents.ts)方法。如果可能的话，我需要重写这个方法来兼容你的页面格式。

嗯嗯，为什么有的无法显示，只有重新写一遍才能显示。例如md2notion导入的就无法显示

**Comment by tangly1024** [comment]
我并没有用过md2notion这个工具，目前看来，md2notion导入的文章似乎存在格式兼容的问题😂

**Comment by Angel0726** [comment]
> 我并没有用过md2notion这个工具，目前看来，md2notion导入的文章似乎存在格式兼容的问题😂

notion中显示没有问题！但是在博客中就无法显示

**Comment by tangly1024** [comment]
能否提供一个使用md2notion导入的文章样例呢，我测试一下

**Comment by Angel0726** [comment]
> 能否提供一个使用md2notion导入的文章样例呢，我测试一下

好，但是需要晚些时候，因为最近事情比较多

**Comment by tangly1024** [comment]
ok

**Comment by Angel0726** [comment]
> ok

跟缓存有关系吗？可以清除一下缓存吗？

**Comment by tangly1024** [comment]
缓存也有可能影响，要清理缓存的话，只需要多刷新几次页面就可以

**Comment by Angel0726** [comment]
> 缓存也有可能影响，要清理缓存的话，只需要多刷新几次页面就可以

vercel中有静态页面的缓存吗？

**Comment by Angel0726** [comment]
> 缓存也有可能影响，要清理缓存的话，只需要多刷新几次页面就可以



> 这个流程要复现有点复杂，在你的页面中也只有最大深度和最小深度这两项出现此问题，我只能将此bug定为一个小概率偶然事件。
> 
> 很遗憾的是这里并没有什么api可以获取到目录，生成目录的函数是由@[transitive-bullshit](https://github.com/transitive-bullshit)编写的[get-page-table-of-contents](https://github.com/NotionX/react-notion-x/blob/master/packages/notion-utils/src/get-page-table-of-contents.ts)方法。如果可能的话，我需要重写这个方法来兼容你的页面格式。

楼主是怎么做复制的

**Comment by Angel0726** [comment]
> CloudFlare的域名服务有做CDN缓存，另外为了提高性能Vercel有做部分缓存。

这个vercel缓存怎么清除一下呀

**Comment by tangly1024** [comment]
刷新几次页面缓存就没了，不用特意清除。

提供一下你的Notion页面地址，并且开启Allow Duplicate as template，我这边就可以复制你的页面
<img width="757" alt="图片" src="https://user-images.githubusercontent.com/15920488/174202438-d70bd4c8-994a-4312-b02d-2ebb3a494037.png">

**Comment by Angel0726** [comment]
> 刷新几次页面缓存就没了，不用特意清除。
> 
> 提供一下你的Notion页面地址，并且开启Allow Duplicate as template，我这边就可以复制你的页面 <img alt="图片" width="757" src="https://user-images.githubusercontent.com/15920488/174202438-d70bd4c8-994a-4312-b02d-2ebb3a494037.png">

https://jeweled-trilby-556.notion.site/a53a7aa0575a4c3c9885094407f38b40

**Comment by Angel0726** [comment]
这个解决了吗

**Comment by Angel0726** [comment]
这个解决了吗

**Comment by Angel0726** [comment]
> 这个解决了吗

更新到3.8.2之后解决
