### ISSUE TITLE
【部署报错】Error serializing .customNav[0].name returned from getStaticProps in "/[prefix]/[slug]".

### ISSUE THREAD

**Issue by moerjie** [tangly1024/NotionNext#2962]
**描述遇到的问题**
在vervel部署时报错如下：
Error occurred prerendering page "/zh/article/ducsimulate". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Error serializing `.customNav[0].name` returned from `getStaticProps` in "/[prefix]/[slug]".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
    at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:446)
    at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:683
    at Array.every (<anonymous>)
    at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:580)
    at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:820
    at Array.every (<anonymous>)
    at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:807)
    at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:683
    at Array.every (<anonymous>)
    at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:580)

**相应配置**
网站地址为：[blog.sawenmoerjie.top](https://blog.sawenmoerjie.top/)

**截图**
![image](https://github.com/user-attachments/assets/43d1a942-4396-41fc-84f3-96e38c3b36ab)

**环境**

- 操作系统:windows
- 浏览器 edge
- 版本 4.7.8

**Comment by tangly1024** [comment]
## 分析
报错是因为编译读取菜单时，读取不到菜单的标题。导致此错误的原因可能是 Notion数据库的列名修改导致、或者修改了环境变量和代码都可能影响菜单标题的读取。

默认的标题那一列的列名是 'title'。

![image](https://github.com/user-attachments/assets/339ae660-4409-4493-8adb-d650de743b92)

## 建议
至于改动了哪里导致此问题不好排查。
建议是将可能影响的配置都改回来。

## 主动的解决方案
当然我这边会同时给出兼容性更强的解决方案。
我会在下个版本中提交代码，读取菜单失败也不报错影响编译。

git fetch origin
git checkout fix/deploy-custom-nav-name

**Comment by tangly1024** [comment]
相关代码已提交

https://github.com/tangly1024/NotionNext/commit/c3d229e8eb28df3fdc354b9502225edebf25a01c
