### ISSUE TITLE
代码块显示不全问题

### ISSUE THREAD

**Issue by sunnydongbowen** [tangly1024/NotionNext#298]
**描述遇到的问题**
在notion中编辑好文章，其中有代码块，是常用的Linux命令，同步到博客后，发现有命令并没有在博客的代码中显示出来或者显示了一半，但是点击copy后再粘贴出来其实是全的，也就是代码块里命令显示不全。

**相应配置**
例如  https://bovan.vercel.app/article/b2120e39-91e0-4775-ba1f-dc2ffcd49cf6
**截图**
notion里的：
![image](https://user-images.githubusercontent.com/46588976/173310937-72d80cb2-faa2-40c6-8ece-6b15b9e9546e.png)
博客里的
![image](https://user-images.githubusercontent.com/46588976/173311074-15719894-45f4-43d1-a902-87f2ccb10f40.png)

**环境**

- 操作系统:  windows
- 浏览器      chrome,
- 版本          3.4.0

**Comment by tangly1024** [comment]
已确认bug，最新版本提交 #299 中已修复此问题， 更新即可体验。
