### ISSUE TITLE
【求助】更新代码后，博客文章标题文字消失

### ISSUE THREAD

**Issue by moerjie** [tangly1024/NotionNext#2980]
**描述遇到的问题**
更新GitHub仓库的代码后博客中的标题文字全部消失

**相应配置**
https://notionnext-pnamxg2zf-moerjies-projects.vercel.app/

**截图**
![image](https://github.com/user-attachments/assets/165e4cad-7237-4d2b-8a3e-ab4c20bce4e0)

**环境**

- 操作系统:Windows
- 浏览器 edge
- 版本 latest

**Comment by tangly1024** [comment]
代码应该是正常，我的预览站点也是正常的：

![image](https://github.com/user-attachments/assets/289e1b86-e6c8-4390-870a-c88add2d7349)


# 解决
我觉得可以检查一下你的Notion数据库，对比一下和原本的模板 是不是修改了什么字段的名字

> 原模板地址： https://tanghh.notion.site/02ab3b8678004aa69e9e415905ef32a5

![image](https://github.com/user-attachments/assets/337d849d-bd48-46da-b1c9-0b9025127b5f)
