### ISSUE TITLE
[nobelium 主题] 评论区无法正常显示

### ISSUE THREAD

**Issue by M24VC** [tangly1024/NotionNext#3002]
**描述bug**
nobelium 主题中 评论区无法正常显示，重新刷新会跳出来让后马上不见

**期望的正常结果**
评论区显示且可以使用

**复现步骤**
在 Cusdis 取得 id 并在 vercel 的环境变数中新增 NEXT_PUBLIC_COMMENT_CUSDIS_APP_ID 并填入 id

**环境**

- 【必填】NotionNext版本 4.7.10
- 【必填】nobelium 
- 【必填】vercel
- 【可选】Android,windows
- 【可选】chrome

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
似乎无法复现，在我的环境中按照以下操作，评论区正常显示：

"  Cusdis 取得 id 并在 vercel 的环境变数中新增 NEXT_PUBLIC_COMMENT_CUSDIS_APP_ID 并填入 id

" 重新刷新会跳出来让后马上不见

![image](https://github.com/user-attachments/assets/c848edf3-9337-4f90-903a-434691c7ca7b)

**Comment by M24VC** [comment]
> 似乎无法复现，在我的环境中按照以下操作，评论区正常显示：
> 
> "  Cusdis 取得 id 并在 vercel 的环境变数中新增 NEXT_PUBLIC_COMMENT_CUSDIS_APP_ID 并填入 id
> 
> " 重新刷新会跳出来让后马上不见
> 
> ![image](https://github.com/user-attachments/assets/c848edf3-9337-4f90-903a-434691c7ca7b)
> 

😭
