### ISSUE TITLE
[页面渲染] 部分公式无法显示 - EquationBlock

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#302]
博客地址：https://coolnext.vercel.app/article/58cc0d89-2518-4275-8de1-fb12663c58c8
原始内容：https://jeweled-trilby-556.notion.site/58cc0d89251842758de1fb12663c58c8
![image](https://user-images.githubusercontent.com/32816780/173614561-9b198326-0b3e-4055-bf93-ee7744e63a51.png)

**描述bug**
简单说明bug的现象、相关的错误提示、日志等

**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
与问题相关的其它说明

**Comment by An-Jhon** [comment]
我也遇到这个问题，我换了一种对齐方式就可以正常渲染了。我是把\begin{align}……\end{align}换成了\begin{aligned}……\end{aligned}

**Comment by Angel0726** [comment]
> 我也遇到这个问题，我换了一种对齐方式就可以正常渲染了。我是把\begin{align}……\end{align}换成了\begin{aligned}……\end{aligned}

好的我试试

**Comment by tangly1024** [comment]
嗨，这里是方程式语法的问题，需要将`\begin{align*}……\end{align*}`换成`\begin{aligned}……\end{aligned}`即可

示例效果：
https://preview.tangly1024.com/article/example-1#7de9f2bb6e8b4a0db12662148de95bd5
noiton页面：
https://tanghh.notion.site/a6271da06b8f47a39735e8fa770f1d9f#7de9f2bb6e8b4a0db12662148de95bd5
