### ISSUE TITLE
【严重】标签和分类全数失效

### ISSUE THREAD

**Issue by M24VC** [tangly1024/NotionNext#3021]
**描述bug**
11/24我更新到最新4.7.11后，Movie 主题的 标签和分类失效，前往该页面无法显示，已尝试过重新部署和创建新项目

（16：44更新）
目前发现所有的标签和分类全数失效😭

https://m24vc.vercel.app/tag

https://m24vc.vercel.app/category

https://m24vc-movie.vercel.app/category

https://m24vc-movie.vercel.app/tag

**期望的正常结果**
出现tag和分类的选项

**复现步骤**
点击选单前往分类和表签

**环境**

- 【必填】NotionNext版本 [4.7.11]
- 【必填】主题 [Movie,hexo]
- 【必填】部署方案 [ vercel]
- 【可选】操作系统: [Android, windows]
- 【可选】浏览器 [chrome]

**补充说明**
【可选】与问题相关的其它说明

**Comment by Cloud-OG** [comment]
我也遇到了这种问题，我的分类是正常的，但是tag不见了，插个眼👀

**Comment by M24VC** [comment]
> 我也遇到了这种问题，我的分类是正常的，但是tag不见了，插个眼👀

建议你也回报一个

**Comment by dxs1256** [comment]
俺也一样

**Comment by Cloud-OG** [comment]
我不太记得是什么时候更新的了，只是最近才注意到tag不显示的问题，大概是在4.7.9版本左右

**Comment by Cloud-OG** [comment]
@dxs1256 你这头像好幽默

**Comment by moreoronce** [comment]
medium 主题也出现了相同的情况
