### ISSUE TITLE
【sitemap异常】没有网站前缀

### ISSUE THREAD

**Issue by FreeServiceSource** [tangly1024/NotionNext#3023]
**描述bug**
![企业微信截图_17325112547498](https://github.com/user-attachments/assets/f04b6216-a6ec-4455-bad4-4c3ba4a6e536)

上面的sitemap没有网站前缀。我已经在vercel的环境变量中配置了NEXT_PUBLIC_LINK。之前是有的，现在没有导致链接快全掉完了

**期望的正常结果**
【此项必填】按这个步骤，预期出现的现象应该是什么
地址那里带上我设置的网站地址
**复现步骤**
【此项必填】你的操作步骤，按此步骤理应在我的开发环境出现一样的bug。

**环境**

【必填】NotionNext版本：4.7.11
【必填】主题：Next
【必填】部署方案 Vercel
【可选】操作系统: Windows11
【可选】浏览器 Microsoft Edge
补充说明
【可选】与问题相关的其它说明

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
https://github.com/tangly1024/NotionNext/commit/439cebdbe6cf8c4afa1d72c7a4ca07f1e43f4fd3

已修复
