### ISSUE TITLE
【sitemap 报错】 Google search console 收录 sitemap.xml 报错

### ISSUE THREAD

**Issue by OHeroJ** [tangly1024/NotionNext#3025]
![image](https://github.com/user-attachments/assets/e7f112e8-a980-47f5-a961-9e9283dbb77f)

然后我的站点是：https://flutter.oldbird.run
sitemap.xml:  https://flutter.oldbird.run/sitemap.xml

**Comment by wuyuhanzijin** [comment]
我的站点也有同样的错误，同问

**Comment by tangly1024** [comment]
访问sitemap 缺失了 站点url

https://flutter.oldbird.run/sitemap.xml

新提交的代码做了相关调整，更新试一下一下

**Comment by tangly1024** [comment]
已修复
