### ISSUE TITLE
【无法部署】r2.cnpmjs.org 官方证书不自动续期，导致今天(2024.12.6) 8 点后没人能在 Vercel (重新)部署 Notion-Next

### ISSUE THREAD

**Issue by W4ddl3** [tangly1024/NotionNext#3043]
![Safari浏览器 2024-12-06 08 32 44](https://github.com/user-attachments/assets/1714bb55-e9a8-4082-99a2-da96933ef394)
![Shot 2024-12-06 at 08 38 40@2x](https://github.com/user-attachments/assets/99eb33a1-52da-402c-8125-376eade33044)

看到这个就立刻想到前几天的苹果音乐事件，真是服了，无语子。
为啥作者不用官方的包呢？

**Comment by Boyue1988** [comment]
Vercel 部署失败。报错了，error An unexpected error occurred: "https://r2.cnpmjs.org/glob-to-regexp/-/glob-to-regexp-0.4.1.tgz: certificate has expired".  **主要是证书过期问题。**

**Comment by zzhangblog** [comment]
同样问题，我说怎么今天更新失败呢，希望尽快解决，要不然只能换其他部署方式了

**Comment by neoshui** [comment]
同样的问题

**Comment by Cloud-OG** [comment]
![image](https://github.com/user-attachments/assets/fd3d249e-5358-49f7-93a2-8b5e341275e1)
同样的问题，看到你们也有问题，我就放心了🥲

**Comment by darkbluesoul** [comment]
我也是，刚今天想着把hugo换成NotionNext

**Comment by qopo1233** [comment]
貌似已经迁到这个域名了 https://npmmirror.com/

**Comment by Timeink88** [comment]
一样的问题

**Comment by zhangxuanrui2023** [comment]
同上
