### ISSUE TITLE
【部署异常】CNPM证书异常，导致一直部署失败

### ISSUE THREAD

**Issue by LxhNolan** [tangly1024/NotionNext#3045]
**描述bug**
自从更新到最新版后，每到Vercel上部署就出错。就算是删掉再重新Fork也是一个结果
![屏幕截图 2024-12-07 002443](https://github.com/user-attachments/assets/d98ed339-0fcf-4f00-9e69-7c0cba070b4d)

**期望的正常结果**
能成功部署

**复现步骤**
【此项必填】你的操作步骤，按此步骤理应在我的开发环境出现一样的bug。

**环境**

- 【必填】NotionNext版本 [4.7.11]
- 【必填】主题 [例如. next]
- 【必填】部署方案 [例如. vercel]
- 【可选】操作系统: [例如.Android, windows]
- 【可选】浏览器 [例如. Edge]

**补充说明**
【可选】与问题相关的其它说明

**Comment by tangly1024** [comment]
已提交修复，更新最新版本即可

https://github.com/tangly1024/NotionNext/issues/3043
https://github.com/tangly1024/NotionNext/pull/3046
