### ISSUE TITLE
【菜单】菜单自定义排序问题

### ISSUE THREAD

**Issue by imnxg** [tangly1024/NotionNext#3048]
**描述bug**
【此项必填】简单说明目前出现的现象、相关的错误提示、日志等、截图
![image](https://github.com/user-attachments/assets/bf1f50e3-7dde-4635-a800-f966d279dba7)
notion配置：
![image](https://github.com/user-attachments/assets/c401a786-f863-4c11-81c0-6455d42bdf82)

**期望的正常结果**

希望是可以自定义菜单顺序，比如想要这样的：首页、导航、归档、友链、关于我，而不是这样的顺序：
首页、友链、导航、归档、关于我。

**复现步骤**
在notion配置中调整菜单顺序是无效的，尝试在vercel中重新部署，但是还是这样的效果，顺序始终无法改变，有时增加新的菜单，还会把菜单顺序弄乱。

**环境**

- 【必填】NotionNext版本 [4.7.11]
- 【必填】主题 [hexo]
- 【必填】部署方案 [ vercel]
- 【可选】操作系统: [windows]
- 【可选】浏览器 [chrome, safari, firefox]

**补充说明**

**Comment by imnxg** [comment]
突然悟了，需要在table 列表下，想要的导航栏，拖拽到指定的菜单下，页面渲染就是什么样的顺序了
![image](https://github.com/user-attachments/assets/b7eef201-bcfe-49a9-9efc-521bfb17c4e3)
回头再看一遍，确实是上图那样的，现在再看才醒悟，哎
![image](https://github.com/user-attachments/assets/607937d6-fe28-4afd-b696-0c3d288e9a80)

效果：
![image](https://github.com/user-attachments/assets/2065b2eb-2c5b-4f59-a98b-2f21379fa712)

**Comment by jinhuili-lab** [comment]
现在好像是根据list表来排序的
