### ISSUE TITLE
无法显示头像

### ISSUE THREAD

**Issue by SsageParuders** [tangly1024/NotionNext#3058]
**描述bug**
Version:4.7.10 ,无法显示上传到Notion的头像到网站，网站头像显示空白

**期望的正常结果**
出现Notion同步的网站头像

**复现步骤**
https://blog.hongqing.online

F12错误日志
Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
<img width="564" alt="image" src="https://github.com/user-attachments/assets/c7bdac49-4c77-4a60-86bf-da4359a1674f" />

**环境**

- 【必填】NotionNext版本 : 4.7.10
- 【必填】主题: 全系主题
- 【必填】部署方案: vercel

**补充说明**
【可选】与问题相关的其它说明

**Comment by SsageParuders** [comment]
已解决
添加头像图标的时候
不要勾选同步到工作空间表情

**Comment by Jiaheliu137** [comment]
> 已解决 添加头像图标的时候 不要勾选同步到工作空间表情
多谢，自己盯了半天，看到你这恍然大悟
帮忙给后面的人说清楚一点：
在自己的notion里面添加自定义图片的时候，不要勾选“添加到工作空间表情符号库”
