### ISSUE TITLE
【主题功能】点击宠物不切换主题

### ISSUE THREAD

**Issue by hiyaabai** [tangly1024/NotionNext#3067]
**描述bug**
设置NEXT_PUBLIC_WIDGET_PET为false，无效。

**期望的正常结果**
设置NEXT_PUBLIC_WIDGET_PET为false，点击宠物不切换主题。

**环境**

- 【必填】NotionNext版本：4.7.11
- 【必填】所有带宠物的主题
- 【必填】vercel

**补充说明**
【可选】版本更新前可用；

**Comment by qixing-jk** [comment]
这个才是切换主题的啊
WIDGET_PET_SWITCH_THEME: process.env.NEXT_PUBLIC_WIDGET_PET_SWITCH_THEME || true, // 点击宠物挂件切换博客主题

**Comment by hiyaabai** [comment]
> 这个才是切换主题的啊 WIDGET_PET_SWITCH_THEME: process.env.NEXT_PUBLIC_WIDGET_PET_SWITCH_THEME || true, // 点击宠物挂件切换博客主题

我就是想实现点击宠物不切换主题

**Comment by qixing-jk** [comment]
看你想写Notion还是Vercel里面了，WIDGET_PET_SWITCH_THEME这是Notion的，NEXT_PUBLIC_WIDGET_PET_SWITCH_THEME这是Vercel的

**Comment by hiyaabai** [comment]
> 看你想写Notion还是Vercel里面了，WIDGET_PET_SWITCH_THEME这是Notion的，NEXT_PUBLIC_WIDGET_PET_SWITCH_THEME这是Vercel的

已经解决了，没有注意区分Notion变量和Vercel变量，感谢。
