### ISSUE TITLE
【图片加载】当notion封面图片为来自link时，notion封面正常，但是博客封面加载不出来

### ISSUE THREAD

**Issue by sunnydongbowen** [tangly1024/NotionNext#322]
**描述bug**
notion封面正常，但是博客封面加载不出来

**复现步骤**
notion写博客，封面图片设置为link方式
![image](https://user-images.githubusercontent.com/46588976/174622527-cccbe273-3777-473b-a36c-61755a53459d.png)

同步博客后，发现博客封面显示空白，无法同步，观察12小时后，依然没有同步。
![image](https://user-images.githubusercontent.com/46588976/174622901-3c9752fd-512f-4e1b-a069-8f25d309394b.png)

link测试网址: 
https://gimg2.baidu.com/image_search/src=http%3A%2F%2Ftop.embedu.org%2Fuploads%2Fallimg%2F170712%2F13-1FG2152I2353.jpg&refer=http%3A%2F%2Ftop.embedu.org&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1658325868&t=5d2b649850e4416d22c49f9f880b6dc7

**期望的正常结果**
正常同步notion中设置的封面。
**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
猜测可能与图片格式或者是图片url有关。此现象已遇到多次

**Comment by sunnydongbowen** [comment]
此bug可以通过将图片下载下来，上传notion封面规避，暂时放一放，建议先修改代码块加载不全问题

**Comment by SwwweetOrange** [comment]
bug是由于封面拿到的链接地址被notion添加了前缀'https://www.notion.so/image/'，通过对链接地址去除前缀并decode，可以获得正确链接

**Comment by tangly1024** [comment]
感谢 @SwwweetOrange  修复此问题，此issue关闭。
