### ISSUE TITLE
【博客分页】建议当从标签入口进入博客时，也增加分页功能

### ISSUE THREAD

**Issue by sunnydongbowen** [tangly1024/NotionNext#323]
**为什么提出这个新的特性改动**
某一标签下的博客很多，采用滚动加载的方式会很不方便，会一直往下拉，建议可以和从首页进去一样，可以进行按页码翻页，这样用户体验好很多
**描述一下你推荐的解决方案**
建议
**描述一下你考虑过的其它替代解决方案**

**补充说明**

**Comment by tangly1024** [comment]
https://github.com/tangly1024/NotionNext/pull/438

最新提交中已新增此特性，更新即可体验
