### ISSUE TITLE
[CloudFlare部署 ]请求能否撰写基于Cloudflare部署的流程

### ISSUE THREAD

**Issue by xJoyLu** [tangly1024/NotionNext#329]
**描述遇到的问题**
Cloudflare 更新 「Pages」功能，类似于 Vercel , 我按照部署流程进行部署，设置 None 环境提示是无法打开，填写 Next.js 环境则无法正常构建版本

**相应配置**
基于Cloudflare「pages」功能部署

**截图**
![image](https://user-images.githubusercontent.com/74151622/176992296-bd247401-96a3-4e96-a49c-359f6a5c5af1.png)
![image](https://user-images.githubusercontent.com/74151622/176992342-ebe495cd-3bab-4cc5-8afb-6d359762b76d.png)

**环境**

- 操作系统: [macOS]
- 浏览器 [Brave]
- 版本 [1.40]

**Comment by lxxself** [comment]
同问

**Comment by haixin1225** [comment]
我做些了修改, 成功部署到Cloudflare上去了. 
[https://haixin.io/article/notion-next-on-cf](https://haixin.io/article/notion-next-on-cf)

**Comment by tangly1024** [comment]
> 我做些了修改, 成功部署到Cloudflare上去了. https://haixin.io/article/notion-next-on-cf @lxxself @xJoyLu

厉害了 大神！

**Comment by lxxself** [comment]
> 我做些了修改, 成功部署到Cloudflare上去了. https://haixin.io/article/notion-next-on-cf @lxxself @xJoyLu

大佬 nb，已部署成功
