### ISSUE TITLE
可不可以允许用户自定义NOTION属性名称，或者使用中文属性名称？

### ISSUE THREAD

**Issue by majw88** [tangly1024/NotionNext#331]
**为什么提出这个新的特性改动**
现在如果想要NotionNext在部署时能够正确识别到NOTION中的数据库属性，必须按照NotionNext的演示模板那样来给每个属性都用固定的英文命名，比如category tags等，对于刚创建NOTION的用户来说还好，老老实实按照这个做就行。但是对于已有NOTION并且做的很完善丰富的用户来说，他们可能有相当一部分使用的是自定义的属性名，如果是英文还好，但像我这样会使用中文属性名的用户，而且不是按照最传统的“分类”“标签”这种固定命名法，而是根据性质的不同来定义不同的属性名。比如如果是文章，我可能把分类叫做“体裁”，如果是商品，可能会叫“品类”，在这种情况下，部署时就会失败，或者内容压根显示不出来，无法被读取和识别。

**描述一下你推荐的解决方案**
建议增加一个配置页面，在这个页面下可以定义相应属性的名称，比如：我在这个页面中，将tags这个功能对应的属性名设置为：标签，这时，只要我的NOTION中，属性名字有叫“标签”的，就会被识别为tags功能，从而正确的识别。而不需要我强制使用固定的英文属性名。并且，在定义时应该可以定义多个词汇。例如：我手动定义了A/B/C，这3种都可以被识别成category。

**描述一下你考虑过的其它替代解决方案**
直接定义一套固定的中文标签名。比如category对应分类/类别；tags对应标签/关键词等。但没有上述方案人性化。

**补充说明**
没有别的意思，只是觉得强制使用固定的英文属性名，用起来不是很舒服，尤其是我的NOTION页面，所有的数据库属性均用的中文名，要把它们全改了，跟我页面的内容也确实显得格格不入，很是别扭。

**Comment by l782993610** [comment]
可以新建一个 Notion 视图来着，不影响的。如果要改属性名称，会很复杂，因为这个名称是硬编码在文章信息读取代码里头的，要改起来很麻烦。

**Comment by tangly1024** [comment]
一个很好的想法，不过实现起来相当复杂😂 以后再考虑

**Comment by majw88** [comment]
> 可以新建一个 Notion 视图来着，不影响的。如果要改属性名称，会很复杂，因为这个名称是硬编码在文章信息读取代码里头的，要改起来很麻烦。

你NOTION如果数据量很大，有很多数据库，而且都已经定义好了相关属性的名称，你去适配这个，猜猜工作量有多大？不光是中文改英文，还需要匹配标签，比如有些你自定义的属性这里边没有，你怎么办？基本上数据量大的完全没法用。我自己就是。

**Comment by tangly1024** [comment]
功能已开发：
在[V3.4.5](https://github.com/tangly1024/NotionNext/releases/tag/V3.4.5) 的版本中，[Jenson](https://github.com/JensonMiao)大大实现了字段名自定义的功能。

相关提交： https://github.com/tangly1024/NotionNext/pull/366/files#diff-fe65cc92b3f2cc4cfc35bc5276c35d7d4ff2e7e7fed5e8dd2af8e45df93e559e

在 `blog.config.js` 中 定义`NOTION_PROPERTY_NAME`的映射配置，即可实现自定义配置notion数据库字段名
```
// 自定义配置notion数据库字段名
NOTION_PROPERTY_NAME: {
    password: '密码',
    type: '类型',
    title: '标题',
    status: '状态',
    summary: '摘要',
    slug: '链接',
    category: '分类',
    date: '日期',
    tags: '标签',
    icon: '图标'
  },
```
