### ISSUE TITLE
[页面渲染] 在 vercel 部署后，打开时页面卡死无响应

### ISSUE THREAD

**Issue by sheng-di** [tangly1024/NotionNext#333]
**描述遇到的问题**
在 vercel 部署后，打开页面后页面卡死无响应，标签页也无法关闭。

**相应配置**
相关的配置，例如notion_page_id；你的网站地址

地址为：
[notion-next-5pcdmfs8m-sheng-di.vercel.app](https://vercel.com/sheng-di/notion-next/62JWsxvYYhf3ds3m568ZpHz6kHV8)

**截图**
![image](https://user-images.githubusercontent.com/13643746/178089264-10bdf632-fb79-4099-9ce9-8d44880a0ea1.png)

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows] → 所有的操作系统
- 浏览器 [例如. chrome, safari, firefox] → 所有的浏览器，包括 chrome  和 safari
- 版本 [e.g. 22]

推测是在部署后触发了死循环？因为本地起 server 是没问题的。

**Comment by sheng-di** [comment]
Update: 本地开发也不行，也会卡死，而且没法通过 Performance 面板调试。
只有通过 Github Codespaces 启动可以，其他场景都不行。

**Comment by mccrena** [comment]
同问题，等一个解决办法

**Comment by sheng-di** [comment]
奇怪的事情来了，执行 `yarn dev` Serve 出来的页面没有问题，如果先 build 再 start，就会卡死。

**Comment by sheng-di** [comment]
> 同问题，等一个解决办法

解决了，PReact 的问题，在 dev 时使用的是 React，部署的时候使用的是 PReact，而 PReact 肯定没有 React 稳定啊，导致卡死了。

解决办法：
next.config.js 文件中，注释掉下面的替换逻辑：
![image](https://user-images.githubusercontent.com/13643746/178095664-953a06bd-342b-42e4-95b4-4096be1ae9d3.png)
