### ISSUE TITLE
[部署问题] 最新main 0ded976 部署后网页卡死

### ISSUE THREAD

**Issue by lxxself** [tangly1024/NotionNext#334]
**描述bug**
fork后的仓库同步了上游最新main代码，vercel部署后发现vercel部署成功但没截图，打开网页巨慢，且可能卡死浏览器标签页，页面无法难以点击一直转圈。（浏览器cpu会满载）使用新的fork最新main发现问题依然，排除合并修改造成的问题。
<img width="945" alt="image" src="https://user-images.githubusercontent.com/8406766/178115979-c7047f89-3f05-4e70-a938-a0918691e531.png">
![image](https://user-images.githubusercontent.com/8406766/178115987-02c6b04c-fa2c-4b76-a7d1-cbeadd3f56b4.png)
![image](https://user-images.githubusercontent.com/8406766/178115995-72a0b953-d432-4854-9c47-8ed451009e2a.png)

**复现步骤**
可尝试打开部署的测试网站，直接fork了最新main 0ded976然后没有做任何修改直接vercel，地址：https://nn-test-rust.vercel.app/

**期望的正常结果**
加载正常不卡死

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [ iOS, Android, macOS]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
如果是我哪里操作有问题导致请指出并关闭issue，谢谢

**Comment by LoveMyself546** [comment]
> **描述bug** fork后的仓库同步了上游最新main代码，vercel部署后发现vercel部署成功但没截图，打开网页巨慢，且可能卡死浏览器标签页，页面无法难以点击一直转圈。（浏览器cpu会满载）使用新的fork最新main发现问题依然，排除合并修改造成的问题。 <img alt="image" width="945" src="https://user-images.githubusercontent.com/8406766/178115979-c7047f89-3f05-4e70-a938-a0918691e531.png"> ![image](https://user-images.githubusercontent.com/8406766/178115987-02c6b04c-fa2c-4b76-a7d1-cbeadd3f56b4.png) ![image](https://user-images.githubusercontent.com/8406766/178115995-72a0b953-d432-4854-9c47-8ed451009e2a.png)
> 
> **复现步骤** 可尝试打开部署的测试网站，直接fork了最新main 0ded976然后没有做任何修改直接vercel，地址：https://nn-test-rust.vercel.app/
> 
> **期望的正常结果** 加载正常不卡死
> 
> **截图** 相关的页面，应该用结果
> 
> **环境**
> 
> * 操作系统: [ iOS, Android, macOS]
> * 浏览器 [例如. chrome, safari, firefox]
> * 版本 [e.g. 22]
> 
> **补充说明** 如果是我哪里操作有问题导致请指出并关闭issue，谢谢

我也遇到了同样的问题，但是我在本地部署同样的代码是正常的，怀疑是不是Vercel的问题

**Comment by v2wy** [comment]
遇到了同样的问题

**Comment by nagongze** [comment]
感覺是Vercel的問題，我也卡死了。

**Comment by kyeo-hub** [comment]
遇到了同样的问题，docker部署就很好，但是docker的版本还在3.3.9，并且我不知道docker版本怎么才能**更新**，不会每次都需要重新部署一次才能更新吧？

**Comment by tangly1024** [comment]
感谢各位用户及时、热情的反馈；经过定位排查，目前此问题已得到解决。

## 问题原因：

1. 2天前Vercel官方发布了最新版本[next 12.2.2](https://www.npmjs.com/package/next)，然而此版本与NotionNext存在兼容性问题，导致正常编译部署后的项目访问后卡死。（这也许是官方的一个BUG）
2. NotionNext项目中设置的默认next版本是 ``` "next": "^12.0.5"```，既版本号大于12.0.5的*最新版* 。当在Vercel生产环境中部署时，Vercel默认会使用最新版本的12.2.2版本Nextjs进行打包编译。因此如果是之前已有的   开发/生产 环境部署不会出现此问题， 而这两天刚开始首次部署的用户会遇到此问题。

<img width="1227" alt="图片" src="https://user-images.githubusercontent.com/15920488/178188741-97d360e8-c760-4f0f-bd9b-66c66f062346.png"/>

## 代码中的调整
目前是在package.json 中限定了nextjs版本为  ```"next": "12.1.6"```

**Comment by kyeo-hub** [comment]
> 感谢各位用户及时、热情的反馈；经过定位排查，目前此问题已得到解决。
> 
> ## 问题原因：
> 1. 2天前Vercel官方发布了最新版本[next 12.2.2](https://www.npmjs.com/package/next)，然而此版本与NotionNext存在兼容性问题，导致项目正常部署运行后，出现访问后卡死的现象。（这也许是官方的一个BUG）
> 2. NotionNext项目中设置的默认next版本是 ` "next": "^12.0.5"`，既版本号大于12.0.5的_最新版_ 。当在Vercel生产环境中部署时，Vercel默认会使用最新版本的12.2.2版本Nextjs进行打包编译。因此如果是之前已有的   开发/生产 环境部署不会出现此问题， 而这两天刚开始首次部署的用户会遇到此问题。
> 
> <img alt="图片" width="1227" src="https://user-images.githubusercontent.com/15920488/178188741-97d360e8-c760-4f0f-bd9b-66c66f062346.png">
> 
> ## 代码中的调整
> 目前是在package.json 中限定了nextjs版本为 `"next": "12.1.6"` 相关commit： [6e3904f](https://github.com/tangly1024/NotionNext/commit/6e3904ff60cb468511d0760da1063ef85bd3b071)
> 
> ## 解决方式
> 更新代码至最新版即可。

非常感谢，问题完美解决，建议可以关闭issue

**Comment by lxxself** [comment]
感谢开发者，已部署正常
