### ISSUE TITLE
在 /Toggle 下创建 /code 块内容显示超出页面

### ISSUE THREAD

**Issue by SkysCrystal** [tangly1024/NotionNext#339]
**描述bug**
在 /toggle 下创建 /code 块。填入内容后，博客对应部分展开没有底部滚动条，内容显示超出页面。

**复现步骤**
在Toggle下Code块内填入内容。

**期望的正常结果**
内容可以滚动显示，或者自动换行。

**截图**
![](https://raw.githubusercontent.com/SkysCrystal/Figurebed/master/img/20220719173218.png)

**环境**
windows chrome 版本 103.0.5060.114（正式版本） （64 位）

**补充说明**
很奇怪，这个页面一个折叠代码可以滚动阅读，一个不行。
正常显示：https://www.dsuper.xyz/article/waline-setting#176fbae8af2c4baaa859630477637154
不能滚动：https://www.dsuper.xyz/article/waline-setting#1a7bb0a02ee44c13abcc557e6ce9cee9

**Comment by tangly1024** [comment]
感谢反馈，问题已确认，并将尽快修复。
