### ISSUE TITLE
分享的複製連結無法顯示圖標

### ISSUE THREAD

**Issue by nagongze** [tangly1024/NotionNext#340]
**描述bug**
如標題描述。

**复现步骤**
使用的是next主題

**期望的正常结果**
顯示圖標

**截图**
![image](https://user-images.githubusercontent.com/68653451/180133197-7819fa00-5bdc-4959-8151-e0bcf227fb00.png)
![image](https://user-images.githubusercontent.com/68653451/180133307-0055014e-a15d-4110-a631-9497cb2a85eb.png)

**环境**
- 操作系统:  windows
- 浏览器:  chrome

**补充说明**
可以正常複製，但就是空白一塊在那裡。

**Comment by tangly1024** [comment]
嗨~感谢你的使用和反馈；

## 问题的原因：
此空白处正常需要展示一个图标如下：
<img width="89" alt="图片" src="https://user-images.githubusercontent.com/15920488/180177185-2c6272ec-1d0e-461b-bc8e-956b305dbede.png">

但因为图标名称错误导致无法显示。【正确的名称是`fas fa-link` 而非 `fab fa-link` ，依据[Fontawesome官方说明](https://fontawesome.com/v5/icons/link?s=solid)】


## 问题解决：
我已在代码的main分支[提交代码](https://github.com/tangly1024/NotionNext/commit/3a4c1d3890d8b074ba15d6c4fdbddb88afab1eba)并修复了此问题。

你可以按我的方式将你代码的[`ShareBar.js`](https://github.com/nagongze/NotionNext/blob/13c60036d950be698cf187039a5ba490148b758b/themes/next_nagongze/components/ShareBar.js#L64
)文件的`fab fa-link` 修改为`fas fa-link`，或任意你喜欢的[icon](https://fontawesome.com/v5/icons)。
<img width="1846" alt="图片" src="https://user-images.githubusercontent.com/15920488/180176508-8a59e7fc-e5b2-4328-9ce0-dffd54cb62f2.png">
