### ISSUE TITLE
Next主題右下方按鈕重疊

### ISSUE THREAD

**Issue by nagongze** [tangly1024/NotionNext#343]
**描述bug**
如果同時使用了Messenger的氣泡，按鈕會被覆蓋。

**期望的正常结果**
希望可以新增設定將按鈕切換至左側，或者將按扭上移

**截图**
![image](https://user-images.githubusercontent.com/68653451/180190131-9a912a9c-77e5-4424-aa34-efd1784d987c.png)

**Comment by tangly1024** [comment]
将在下一版本修复问题

**Comment by tangly1024** [comment]
问题已修复，当识别到 Messenger气泡，按钮位置将上移。 更新最新版即可体验。
