### ISSUE TITLE
【笔记同步】Notion笔记没有同步更新

### ISSUE THREAD

**Issue by pan52yu** [tangly1024/NotionNext#344]
**描述遇到的问题**
Notion笔记没有同步更新

**相应配置**
https://notion-next2-r5o7x1taf-pan52yu.vercel.app/

**截图**
![image](https://user-images.githubusercontent.com/76894844/180413517-15c93a23-7dc0-4198-93e2-1814f321fcec.png)

**环境**

- 操作系统: [ Android, windows]
- 浏览器 [chrome]
- 版本 [chrome 103.0.5060.114]

**Comment by LITTLESITE** [comment]
要到你的Vercel部署页面点"Redepoly
<img width="1010" alt="示例" src="https://user-images.githubusercontent.com/108331059/180910251-eb65bcf7-1984-4b00-b557-87f30fb2eec4.png">
"

**Comment by pan52yu** [comment]
> 如果立即更新要到你的部署页面点“否则 等一会会重新自动更新” <img alt="示例" width="1010" src="https://user-images.githubusercontent.com/108331059/180910251-eb65bcf7-1984-4b00-b557-87f30fb2eec4.png">

应该是我notion笔记操作失误的问题 并没有解决问题

**Comment by wyih** [comment]
> 如果要立即更新要到你的Vercel部署页面点"Redepoly <img alt="示例" width="1010" src="https://user-images.githubusercontent.com/108331059/180910251-eb65bcf7-1984-4b00-b557-87f30fb2eec4.png"> "否则等一会才会自动更新

一般我笔记保存之后需要等多久会自动更新呢？

**Comment by pan52yu** [comment]
> > 如果立即更新要到你的部署页面点“否则<img alt="示例" width="1010" src="https://user-images.githubusercontent.com/108331059/180910251-eb65bcf7-1984-4b00-b557-87f30fb2eec4.png">等一会会重新自动更新”
> 
> 一般我的笔记保存之后需要等多久自动更新呢？

好的 谢谢啦

**Comment by LITTLESITE** [comment]
试了下,Page是立刻更新,Post要自己重新部署

**Comment by pan52yu** [comment]
> 

okok
