### ISSUE TITLE
Build时Http 400错误

### ISSUE THREAD

**Issue by wyih** [tangly1024/NotionNext#349]
**Build总出错**
重试了好几次了，错误如下

[响应异常]: HTTPError: Response code 400 (Bad Request)
--
11:47:46.860 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
11:47:46.860 | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11:47:46.860 | code: 'ERR_NON_2XX_3XX_RESPONSE',
11:47:46.860 | timings: {
11:47:46.861 | start: 1659498466706,
11:47:46.861 | socket: 1659498466711,
11:47:46.861 | lookup: 1659498466713,
11:47:46.861 | connect: 1659498466715,
11:47:46.861 | secureConnect: 1659498466722,
11:47:46.861 | upload: 1659498466723,
11:47:46.862 | response: 1659498466848,
11:47:46.862 | end: 1659498466852,
11:47:46.862 | error: undefined,
11:47:46.862 | abort: undefined,
11:47:46.862 | phases: {
11:47:46.862 | wait: 5,
11:47:46.862 | dns: 2,
11:47:46.863 | tcp: 2,
11:47:46.863 | tls: 7,
11:47:46.863 | request: 1,
11:47:46.863 | firstByte: 125,
11:47:46.863 | download: 4,
11:47:46.863 | total: 146
11:47:46.863 | }
11:47:46.864 | }
11:47:46.864 | }
11:47:46.866 | [响应异常]: HTTPError: Response code 400 (Bad Request)
11:47:46.866 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
11:47:46.866 | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11:47:46.866 | code: 'ERR_NON_2XX_3XX_RESPONSE',
11:47:46.867 | timings: {
11:47:46.867 | start: 1659498466731,
11:47:46.867 | socket: 1659498466735,
11:47:46.867 | lookup: 1659498466737,
11:47:46.867 | connect: 1659498466738,
11:47:46.867 | secureConnect: 1659498466742,
11:47:46.867 | upload: 1659498466743,
11:47:46.868 | response: 1659498466855,
11:47:46.868 | end: 1659498466860,
11:47:46.868 | error: undefined,
11:47:46.868 | abort: undefined,
11:47:46.868 | phases: {
11:47:46.868 | wait: 4,
11:47:46.868 | dns: 2,
11:47:46.868 | tcp: 1,
11:47:46.869 | tls: 4,
11:47:46.869 | request: 1,
11:47:46.869 | firstByte: 112,
11:47:46.869 | download: 5,
11:47:46.869 | total: 129
11:47:46.869 | }
11:47:46.869 | }
11:47:46.869 | }
11:47:46.913 | [响应异常]: HTTPError: Response code 400 (Bad Request)
11:47:46.913 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
11:47:46.913 | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11:47:46.914 | code: 'ERR_NON_2XX_3XX_RESPONSE',
11:47:46.914 | timings: {
11:47:46.914 | start: 1659498466733,
11:47:46.914 | socket: 1659498466736,
11:47:46.915 | lookup: 1659498466738,
11:47:46.915 | connect: 1659498466739,
11:47:46.915 | secureConnect: 1659498466747,
11:47:46.915 | upload: 1659498466747,
11:47:46.915 | response: 1659498466878,
11:47:46.916 | end: 1659498466882,
11:47:46.916 | error: undefined,
11:47:46.916 | abort: undefined,
11:47:46.916 | phases: {
11:47:46.916 | wait: 3,
11:47:46.916 | dns: 2,
11:47:46.916 | tcp: 1,
11:47:46.917 | tls: 8,
11:47:46.917 | request: 0,
11:47:46.917 | firstByte: 131,
11:47:46.917 | download: 4,
11:47:46.917 | total: 149
11:47:46.917 | }
11:47:46.917 | }
11:47:46.917 | }
11:47:47.862 | [请求API] from:slug-paths id:2a657ce47ece4b7a8291da48354d8f23 剩余重试次数:2
11:47:47.868 | [请求API] from:category-paths id:2a657ce47ece4b7a8291da48354d8f23 剩余重试次数:2
11:47:47.892 | [请求API] from:slug-paths id:2a657ce47ece4b7a8291da48354d8f23 剩余重试次数:2
11:47:47.986 | [响应异常]: HTTPError: Response code 400 (Bad Request)
11:47:47.986 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
11:47:47.986 | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11:47:47.986 | code: 'ERR_NON_2XX_3XX_RESPONSE',
11:47:47.986 | timings: {
11:47:47.986 | start: 1659498467864,
11:47:47.986 | socket: 1659498467864,
11:47:47.986 | lookup: 1659498467864,
11:47:47.987 | connect: 1659498467866,
11:47:47.987 | secureConnect: 1659498467868,
11:47:47.987 | upload: 1659498467868,
11:47:47.987 | response: 1659498467984,
11:47:47.987 | end: 1659498467984,
11:47:47.987 | error: undefined,
11:47:47.987 | abort: undefined,
11:47:47.987 | phases: {
11:47:47.987 | wait: 0,
11:47:47.987 | dns: 0,
11:47:47.987 | tcp: 2,
11:47:47.987 | tls: 2,
11:47:47.987 | request: 0,
11:47:47.987 | firstByte: 116,
11:47:47.987 | download: 0,
11:47:47.987 | total: 120
11:47:47.987 | }
11:47:47.987 | }
11:47:47.987 | }
11:47:48.007 | [响应异常]: HTTPError: Response code 400 (Bad Request)
11:47:48.007 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
11:47:48.007 | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11:47:48.007 | code: 'ERR_NON_2XX_3XX_RESPONSE',
11:47:48.007 | timings: {
11:47:48.007 | start: 1659498467870,
11:47:48.008 | socket: 1659498467870,
11:47:48.008 | lookup: 1659498467871,
11:47:48.008 | connect: 1659498467872,
11:47:48.008 | secureConnect: 1659498467874,
11:47:48.008 | upload: 1659498467874,
11:47:48.008 | response: 1659498468005,
11:47:48.008 | end: 1659498468005,
11:47:48.008 | error: undefined,
11:47:48.008 | abort: undefined,
11:47:48.009 | phases: {
11:47:48.009 | wait: 0,
11:47:48.009 | dns: 1,
11:47:48.009 | tcp: 1,
11:47:48.009 | tls: 2,
11:47:48.009 | request: 0,
11:47:48.009 | firstByte: 131,
11:47:48.009 | download: 0,
11:47:48.009 | total: 135
11:47:48.009 | }
11:47:48.009 | }
11:47:48.010 | }
11:47:48.011 | [响应异常]: HTTPError: Response code 400 (Bad Request)
11:47:48.011 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
11:47:48.011 | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11:47:48.012 | code: 'ERR_NON_2XX_3XX_RESPONSE',
11:47:48.012 | timings: {
11:47:48.012 | start: 1659498467894,
11:47:48.012 | socket: 1659498467894,
11:47:48.012 | lookup: 1659498467894,
11:47:48.012 | connect: 1659498467896,
11:47:48.012 | secureConnect: 1659498467898,
11:47:48.012 | upload: 1659498467898,
11:47:48.013 | response: 1659498468009,
11:47:48.013 | end: 1659498468010,
11:47:48.013 | error: undefined,
11:47:48.013 | abort: undefined,
11:47:48.013 | phases: {
11:47:48.014 | wait: 0,
11:47:48.014 | dns: 0,
11:47:48.014 | tcp: 2,
11:47:48.014 | tls: 2,
11:47:48.015 | request: 0,
11:47:48.015 | firstByte: 111,
11:47:48.015 | download: 1,
11:47:48.015 | total: 116
11:47:48.015 | }
11:47:48.015 | }
11:47:48.015 | }
11:47:48.987 | [请求API] from:slug-paths id:2a657ce47ece4b7a8291da48354d8f23 剩余重试次数:1
11:47:49.008 | [请求API] from:category-paths id:2a657ce47ece4b7a8291da48354d8f23 剩余重试次数:1
11:47:49.012 | [请求API] from:slug-paths id:2a657ce47ece4b7a8291da48354d8f23 剩余重试次数:1
11:47:49.132 | [响应异常]: HTTPError: Response code 400 (Bad Request)
11:47:49.132 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
11:47:49.132 | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11:47:49.132 | code: 'ERR_NON_2XX_3XX_RESPONSE',
11:47:49.133 | timings: {
11:47:49.133 | start: 1659498469014,
11:47:49.133 | socket: 1659498469014,
11:47:49.133 | lookup: 1659498469014,
11:47:49.133 | connect: 1659498469015,
11:47:49.133 | secureConnect: 1659498469017,
11:47:49.133 | upload: 1659498469017,
11:47:49.133 | response: 1659498469130,
11:47:49.133 | end: 1659498469131,
11:47:49.133 | error: undefined,
11:47:49.134 | abort: undefined,
11:47:49.134 | phases: {
11:47:49.134 | wait: 0,
11:47:49.134 | dns: 0,
11:47:49.134 | tcp: 1,
11:47:49.134 | tls: 2,
11:47:49.134 | request: 0,
11:47:49.134 | firstByte: 113,
11:47:49.134 | download: 1,
11:47:49.134 | total: 117
11:47:49.134 | }
11:47:49.135 | }
11:47:49.135 | }
11:47:49.135 | [响应异常]: HTTPError: Response code 400 (Bad Request)
11:47:49.135 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
11:47:49.135 | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11:47:49.135 | code: 'ERR_NON_2XX_3XX_RESPONSE',
11:47:49.135 | timings: {
11:47:49.135 | start: 1659498469010,
11:47:49.135 | socket: 1659498469010,
11:47:49.136 | lookup: 1659498469010,
11:47:49.136 | connect: 1659498469012,
11:47:49.136 | secureConnect: 1659498469014,
11:47:49.136 | upload: 1659498469014,
11:47:49.136 | response: 1659498469132,
11:47:49.136 | end: 1659498469132,
11:47:49.136 | error: undefined,
11:47:49.136 | abort: undefined,
11:47:49.136 | phases: {
11:47:49.136 | wait: 0,
11:47:49.136 | dns: 0,
11:47:49.137 | tcp: 2,
11:47:49.137 | tls: 2,
11:47:49.137 | request: 0,
11:47:49.137 | firstByte: 118,
11:47:49.137 | download: 0,
11:47:49.137 | total: 122
11:47:49.137 | }
11:47:49.137 | }
11:47:49.137 | }
11:47:49.145 | [响应异常]: HTTPError: Response code 400 (Bad Request)
11:47:49.145 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
11:47:49.145 | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11:47:49.145 | code: 'ERR_NON_2XX_3XX_RESPONSE',
11:47:49.145 | timings: {
11:47:49.145 | start: 1659498468988,
11:47:49.146 | socket: 1659498468989,
11:47:49.146 | lookup: 1659498468989,
11:47:49.146 | connect: 1659498468990,
11:47:49.146 | secureConnect: 1659498468992,
11:47:49.146 | upload: 1659498468992,
11:47:49.146 | response: 1659498469143,
11:47:49.146 | end: 1659498469144,
11:47:49.147 | error: undefined,
11:47:49.147 | abort: undefined,
11:47:49.147 | phases: {
11:47:49.147 | wait: 1,
11:47:49.147 | dns: 0,
11:47:49.147 | tcp: 1,
11:47:49.148 | tls: 2,
11:47:49.148 | request: 0,
11:47:49.148 | firstByte: 151,
11:47:49.148 | download: 1,
11:47:49.148 | total: 156
11:47:49.148 | }
11:47:49.148 | }
11:47:49.148 | }
11:47:50.133 | [请求失败]: from:slug-paths id:2a657ce47ece4b7a8291da48354d8f23
11:47:50.134 | [API耗时] 3422ms
11:47:50.137 |  
11:47:50.137 | > Build error occurred
11:47:50.140 | TypeError: Cannot read properties of undefined (reading 'map')
11:47:50.141 | at getStaticPaths (/vercel/path0/.next/server/pages/article/[slug].js:146:25)
11:47:50.141 | at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:491:31)
11:47:50.141 | at async /vercel/path0/node_modules/next/dist/build/utils.js:632:119
11:47:50.141 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) {
11:47:50.141 | type: 'TypeError'
11:47:50.142 | }
11:47:50.214 | error Command failed with exit code 1.

[响应异常]: HTTPError: Response code 400 (Bad Request)
11:47:46.860	    at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
11:47:46.860	    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11:47:46.860	  code: 'ERR_NON_2XX_3XX_RESPONSE',
11:47:46.860	  timings: {
11:47:46.861	    start: [1659498466706](tel:1659498466706),
11:47:46.861	    socket: [1659498466711](tel:1659498466711),
11:47:46.861	    lookup: [1659498466713](tel:1659498466713),
11:47:46.861	    connect: [1659498466715](tel:1659498466715),
11:47:46.861	    secureConnect: [1659498466722](tel:1659498466722),
11:47:46.861	    upload: 1659498466723,
11:47:46.862	    response: [1659498466848](tel:1659498466848),
11:47:46.862	    end: 1659498466852,
11:47:46.862	    error: undefined,
11:47:46.862	    abort: undefined,
11:47:46.862	    phases: {
11:47:46.862	      wait: 5,
11:47:46.862	      dns: 2,
11:47:46.863	      tcp: 2,
11:47:46.863	      tls: 7,
11:47:46.863	      request: 1,
11:47:46.863	      firstByte: 125,
11:47:46.863	      download: 4,
11:47:46.863	      total: 146
11:47:46.863	    }
11:47:46.864	  }
11:47:46.864	}
11:47:46.866	[响应异常]: HTTPError: Response code 400 (Bad Request)
11:47:46.866	    at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
11:47:46.866	    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11:47:46.866	  code: 'ERR_NON_2XX_3XX_RESPONSE',
11:47:46.867	  timings: {
11:47:46.867	    start: [1659498466731](tel:1659498466731),
11:47:46.867	    socket: [1659498466735](tel:1659498466735),
11:47:46.867	    lookup: [1659498466737](tel:1659498466737),
11:47:46.867	    connect: 1659498466738,
11:47:46.867	    secureConnect: [1659498466742](tel:1659498466742),
11:47:46.867	    upload: 1659498466743,
11:47:46.868	    response: [1659498466855](tel:1659498466855),
11:47:46.868	    end: 1659498466860,
11:47:46.868	    error: undefined,
11:47:46.868	    abort: undefined,
11:47:46.868	    phases: {
11:47:46.868	      wait: 4,
11:47:46.868	      dns: 2,
11:47:46.868	      tcp: 1,
11:47:46.869	      tls: 4,
11:47:46.869	      request: 1,
11:47:46.869	      firstByte: 112,
11:47:46.869	      download: 5,
11:47:46.869	      total: 129
11:47:46.869	    }
11:47:46.869	  }
11:47:46.869	}
11:47:46.913	[响应异常]: HTTPError: Response code 400 (Bad Request)
11:47:46.913	    at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
11:47:46.913	    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11:47:46.914	  code: 'ERR_NON_2XX_3XX_RESPONSE',
11:47:46.914	  timings: {
11:47:46.914	    start: [1659498466733](tel:1659498466733),
11:47:46.914	    socket: [1659498466736](tel:1659498466736),
11:47:46.915	    lookup: 1659498466738,
11:47:46.915	    connect: [1659498466739](tel:1659498466739),
11:47:46.915	    secureConnect: [1659498466747](tel:1659498466747),
11:47:46.915	    upload: 1659498466747,
11:47:46.915	    response: [1659498466878](tel:1659498466878),
11:47:46.916	    end: 1659498466882,
11:47:46.916	    error: undefined,
11:47:46.916	    abort: undefined,
11:47:46.916	    phases: {
11:47:46.916	      wait: 3,
11:47:46.916	      dns: 2,
11:47:46.916	      tcp: 1,
11:47:46.917	      tls: 8,
11:47:46.917	      request: 0,
11:47:46.917	      firstByte: 131,
11:47:46.917	      download: 4,
11:47:46.917	      total: 149
11:47:46.917	    }
11:47:46.917	  }
11:47:46.917	}
11:47:47.862	[请求API] from:slug-paths id:2a657ce47ece4b7a8291da48354d8f23 剩余重试次数:2
11:47:47.868	[请求API] from:category-paths id:2a657ce47ece4b7a8291da48354d8f23 剩余重试次数:2
11:47:47.892	[请求API] from:slug-paths id:2a657ce47ece4b7a8291da48354d8f23 剩余重试次数:2
11:47:47.986	[响应异常]: HTTPError: Response code 400 (Bad Request)
11:47:47.986	    at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
11:47:47.986	    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11:47:47.986	  code: 'ERR_NON_2XX_3XX_RESPONSE',
11:47:47.986	  timings: {
11:47:47.986	    start: [1659498467864](tel:1659498467864),
11:47:47.986	    socket: [1659498467864](tel:1659498467864),
11:47:47.986	    lookup: [1659498467864](tel:1659498467864),
11:47:47.987	    connect: [1659498467866](tel:1659498467866),
11:47:47.987	    secureConnect: [1659498467868](tel:1659498467868),
11:47:47.987	    upload: 1659498467868,
11:47:47.987	    response: [1659498467984](tel:1659498467984),
11:47:47.987	    end: 1659498467984,
11:47:47.987	    error: undefined,
11:47:47.987	    abort: undefined,
11:47:47.987	    phases: {
11:47:47.987	      wait: 0,
11:47:47.987	      dns: 0,
11:47:47.987	      tcp: 2,
11:47:47.987	      tls: 2,
11:47:47.987	      request: 0,
11:47:47.987	      firstByte: 116,
11:47:47.987	      download: 0,
11:47:47.987	      total: 120
11:47:47.987	    }
11:47:47.987	  }
11:47:47.987	}
11:47:48.007	[响应异常]: HTTPError: Response code 400 (Bad Request)
11:47:48.007	    at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
11:47:48.007	    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11:47:48.007	  code: 'ERR_NON_2XX_3XX_RESPONSE',
11:47:48.007	  timings: {
11:47:48.007	    start: [1659498467870](tel:1659498467870),
11:47:48.008	    socket: [1659498467870](tel:1659498467870),
11:47:48.008	    lookup: [1659498467871](tel:1659498467871),
11:47:48.008	    connect: 1659498467872,
11:47:48.008	    secureConnect: [1659498467874](tel:1659498467874),
11:47:48.008	    upload: 1659498467874,
11:47:48.008	    response: [1659498468005](tel:1659498468005),
11:47:48.008	    end: 1659498468005,
11:47:48.008	    error: undefined,
11:47:48.008	    abort: undefined,
11:47:48.009	    phases: {
11:47:48.009	      wait: 0,
11:47:48.009	      dns: 1,
11:47:48.009	      tcp: 1,
11:47:48.009	      tls: 2,
11:47:48.009	      request: 0,
11:47:48.009	      firstByte: 131,
11:47:48.009	      download: 0,
11:47:48.009	      total: 135
11:47:48.009	    }
11:47:48.009	  }
11:47:48.010	}
11:47:48.011	[响应异常]: HTTPError: Response code 400 (Bad Request)
11:47:48.011	    at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
11:47:48.011	    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11:47:48.012	  code: 'ERR_NON_2XX_3XX_RESPONSE',
11:47:48.012	  timings: {
11:47:48.012	    start: [1659498467894](tel:1659498467894),
11:47:48.012	    socket: [1659498467894](tel:1659498467894),
11:47:48.012	    lookup: [1659498467894](tel:1659498467894),
11:47:48.012	    connect: 1659498467896,
11:47:48.012	    secureConnect: [1659498467898](tel:1659498467898),
11:47:48.012	    upload: 1659498467898,
11:47:48.013	    response: [1659498468009](tel:1659498468009),
11:47:48.013	    end: 1659498468010,
11:47:48.013	    error: undefined,
11:47:48.013	    abort: undefined,
11:47:48.013	    phases: {
11:47:48.014	      wait: 0,
11:47:48.014	      dns: 0,
11:47:48.014	      tcp: 2,
11:47:48.014	      tls: 2,
11:47:48.015	      request: 0,
11:47:48.015	      firstByte: 111,
11:47:48.015	      download: 1,
11:47:48.015	      total: 116
11:47:48.015	    }
11:47:48.015	  }
11:47:48.015	}
11:47:48.987	[请求API] from:slug-paths id:2a657ce47ece4b7a8291da48354d8f23 剩余重试次数:1
11:47:49.008	[请求API] from:category-paths id:2a657ce47ece4b7a8291da48354d8f23 剩余重试次数:1
11:47:49.012	[请求API] from:slug-paths id:2a657ce47ece4b7a8291da48354d8f23 剩余重试次数:1
11:47:49.132	[响应异常]: HTTPError: Response code 400 (Bad Request)
11:47:49.132	    at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
11:47:49.132	    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11:47:49.132	  code: 'ERR_NON_2XX_3XX_RESPONSE',
11:47:49.133	  timings: {
11:47:49.133	    start: [1659498469014](tel:1659498469014),
11:47:49.133	    socket: [1659498469014](tel:1659498469014),
11:47:49.133	    lookup: [1659498469014](tel:1659498469014),
11:47:49.133	    connect: [1659498469015](tel:1659498469015),
11:47:49.133	    secureConnect: [1659498469017](tel:1659498469017),
11:47:49.133	    upload: 1659498469017,
11:47:49.133	    response: [1659498469130](tel:1659498469130),
11:47:49.133	    end: 1659498469131,
11:47:49.133	    error: undefined,
11:47:49.134	    abort: undefined,
11:47:49.134	    phases: {
11:47:49.134	      wait: 0,
11:47:49.134	      dns: 0,
11:47:49.134	      tcp: 1,
11:47:49.134	      tls: 2,
11:47:49.134	      request: 0,
11:47:49.134	      firstByte: 113,
11:47:49.134	      download: 1,
11:47:49.134	      total: 117
11:47:49.134	    }
11:47:49.135	  }
11:47:49.135	}
11:47:49.135	[响应异常]: HTTPError: Response code 400 (Bad Request)
11:47:49.135	    at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
11:47:49.135	    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11:47:49.135	  code: 'ERR_NON_2XX_3XX_RESPONSE',
11:47:49.135	  timings: {
11:47:49.135	    start: [1659498469010](tel:1659498469010),
11:47:49.135	    socket: [1659498469010](tel:1659498469010),
11:47:49.136	    lookup: [1659498469010](tel:1659498469010),
11:47:49.136	    connect: 1659498469012,
11:47:49.136	    secureConnect: [1659498469014](tel:1659498469014),
11:47:49.136	    upload: 1659498469014,
11:47:49.136	    response: [1659498469132](tel:1659498469132),
11:47:49.136	    end: 1659498469132,
11:47:49.136	    error: undefined,
11:47:49.136	    abort: undefined,
11:47:49.136	    phases: {
11:47:49.136	      wait: 0,
11:47:49.136	      dns: 0,
11:47:49.137	      tcp: 2,
11:47:49.137	      tls: 2,
11:47:49.137	      request: 0,
11:47:49.137	      firstByte: 118,
11:47:49.137	      download: 0,
11:47:49.137	      total: 122
11:47:49.137	    }
11:47:49.137	  }
11:47:49.137	}
11:47:49.145	[响应异常]: HTTPError: Response code 400 (Bad Request)
11:47:49.145	    at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
11:47:49.145	    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11:47:49.145	  code: 'ERR_NON_2XX_3XX_RESPONSE',
11:47:49.145	  timings: {
11:47:49.145	    start: [1659498468988](tel:1659498468988),
11:47:49.146	    socket: [1659498468989](tel:1659498468989),
11:47:49.146	    lookup: [1659498468989](tel:1659498468989),
11:47:49.146	    connect: [1659498468990](tel:1659498468990),
11:47:49.146	    secureConnect: 1659498468992,
11:47:49.146	    upload: 1659498468992,
11:47:49.146	    response: [1659498469143](tel:1659498469143),
11:47:49.146	    end: 1659498469144,
11:47:49.147	    error: undefined,
11:47:49.147	    abort: undefined,
11:47:49.147	    phases: {
11:47:49.147	      wait: 1,
11:47:49.147	      dns: 0,
11:47:49.147	      tcp: 1,
11:47:49.148	      tls: 2,
11:47:49.148	      request: 0,
11:47:49.148	      firstByte: 151,
11:47:49.148	      download: 1,
11:47:49.148	      total: 156
11:47:49.148	    }
11:47:49.148	  }
11:47:49.148	}
11:47:50.133	[请求失败]: from:slug-paths id:2a657ce47ece4b7a8291da48354d8f23
11:47:50.134	[API耗时] 3422ms
11:47:50.137	
11:47:50.137	> Build error occurred
11:47:50.140	TypeError: Cannot read properties of undefined (reading 'map')
11:47:50.141	    at getStaticPaths (/vercel/path0/.next/server/pages/article/[slug].js:146:25)
11:47:50.141	    at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:491:31)
11:47:50.141	    at async /vercel/path0/node_modules/next/dist/build/utils.js:632:119
11:47:50.141	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) {
11:47:50.141	  type: 'TypeError'
11:47:50.142	}
11:47:50.214	error Command failed with exit code 1.

**相应配置**
notion_page_id；2a657ce47ece4b7a8291da48354d8f23

https://wyihac.notion.site/4015efcd15b84d7ea5c17f9d27b0ef8a?v=2a657ce47ece4b7a8291da48354d8f23

**Comment by tangly1024** [comment]
notion_page_id 错误： 正确应填写： 4015efcd15b84d7ea5c17f9d27b0ef8a

v=2a657ce47ece4b7a8291da48354d8f23 此值表示，你的此页面改动历史的版本号。
