### ISSUE TITLE
【夜间模式适配】Waline\Utterance暗黑模式支持

### ISSUE THREAD

**Issue by JesseJeson** [tangly1024/NotionNext#351]
**为什么提出这个新的特性改动**
开启暗黑模式后waline的输入框仍然保持亮色

**描述一下你推荐的解决方案**
可能改一下waline的前端引入配置就行了

**描述一下你考虑过的其它替代解决方案**
无

**补充说明**
无

**Comment by tangly1024** [comment]
收到反馈，将在下一版本中加入功能

**Comment by lifeafter619** [comment]
Utterance暗黑模式下输入框也是亮色，而Giscus则正常
![1](https://user-images.githubusercontent.com/65111206/199223193-5e18d183-acb5-42ef-9cac-6f5b57d051e8.png)
