### ISSUE TITLE
【Vercel部署日志】在vercel中部署遇到一些waring and errors 

### ISSUE THREAD

**Issue by aron-xx** [tangly1024/NotionNext#357]
**描述遇到的问题**
这些errors是什么原因导致的呢
我应该怎么做来消除这些errors

**相应配置**
配置设置正确

**截图**
 
![chrome_CDANnv3rqY](https://user-images.githubusercontent.com/52649364/185422342-6fe83c0e-9b9a-4de7-9f02-915df79b680a.png)

![chrome_nDYNJ26d4v](https://user-images.githubusercontent.com/52649364/185422471-dee01897-57ee-4d2a-b004-68fa7425536d.png)
![chrome_lKeiZ0DHFu](https://user-images.githubusercontent.com/52649364/185422482-3104079c-c98d-4926-874d-0b1b8a0954b7.png)

**环境**

- 操作系统: Windows
- 浏览器: chrome
- 版本 [e.g. 22]

**Comment by tangly1024** [comment]
## 问题
- 黄色warning无关紧要
   由于某些组件版本依赖比较旧的警告，它不影响使用可以忽略不计。（盲目更新到最新的组件反而会不稳定）
- 红色error要视情况而定
   图中你的错误源影是请求Notion的API时，出现了网络超时的问题 504(Gateway Time-out)

## 解决
- 可能是Notion的网络抽风了，重新尝试编译可以修复此问题；
- 可能是部分文章的内容太大了，导致请求数据超时，需要检查一下有没有文章的文字过多，适当优化一下内容，进行精减或拆分即可

**Comment by aron-xx** [comment]
谢谢了
