### ISSUE TITLE
【缓存问题】搜索功能搜索到了文章，但是点进去后404，事实上文章是存在的。

### ISSUE THREAD

**Issue by sunnydongbowen** [tangly1024/NotionNext#359]
**描述bug**
登录博客页面，在输入框中搜索，例如我直接发链接 https://bovan.vercel.app/，

在搜索框中输入panic关键字，可以搜索出文章，但是点文章后是404，事实上文章是存在的。是不是由于我修改了slug这个属性导致url失效？但是已经很长时间了，按理说应该更新过来了。后来我试了一下，带slug的搜索的时候都是404，从主页翻页能进去，这是为何？
![image](https://user-images.githubusercontent.com/46588976/185914463-d493072f-7e22-4e56-b502-40192f1eccfa.png)

**复现步骤**

**期望的正常结果**
登录博客页面，在输入框中搜索，可以搜索出文章，点进文章可以查看文章。

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
需更新至最新版本，已验证此问题
