### ISSUE TITLE
vercel.js 在部署时报错

### ISSUE THREAD

**Issue by fanhua-manhua** [tangly1024/NotionNext#363]
**描述遇到的问题**
正在修改文件的时候突然无法正常更新了，以为是自己修改的原因，全部删除后导入原版（一模一样除了page ID）但是还是一直报错    [Vercel.js](https://github.com/fanhua-manhua/NotionNext/blob/main/components/Vercel.js) 
vercel.js 内容完全一样依旧报错
**相应配置**
Notion_page_id : 4218d3d5d93647b7a6c26213f4021215
网站地址：[fanhua.vercel.app](https://fanhua.vercel.app/)
**截图**
<img width="910" alt="image" src="https://user-images.githubusercontent.com/110377680/188261491-63f88480-20ea-47f7-a05a-9edfa39ad40e.png">
**环境**
操作系统: Windows
浏览器：chrome
浏览器版本：105.0.5195.53

**Comment by asdqwd1** [comment]
今天下午两点我还能部署成功，现在也出现了同样的error

**Comment by Thinker91** [comment]
同样的错误，昨天晚上遇到，现在还是无法解决

**Comment by tangly1024** [comment]
似乎是 `vercel.js` 这一组件的问题，此组件的功能是展示一个Vercel的svg图标，此图标在新的版本中已经不再使用。

我在新的3.4.4版本中直接删除了该组件，更新代码即可避免此问题。
