### ISSUE TITLE
Deployment error 

### ISSUE THREAD

**Issue by Thinker91** [tangly1024/NotionNext#364]
**描述遇到的问题**

Failed to compile.
--
09:25:15.841 |  
09:25:15.841 | ./components/Vercel.js
09:25:15.841 | 19:13  Error: Invalid property 'fill' found on tag 'path', but it is only allowed on: svg  react/no-unknown-property
09:25:15.841 | 23:13  Error: Invalid property 'fill' found on tag 'path', but it is only allowed on: svg  react/no-unknown-property
09:25:15.841 | 27:13  Error: Invalid property 'fill' found on tag 'path', but it is only allowed on: svg  react/no-unknown-property
09:25:15.841 | 33:47  Error: Invalid property 'fill' found on tag 'rect', but it is only allowed on: svg  react/no-unknown-property
09:25:15.841 |  
09:25:15.842 | info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
09:25:15.861 | error Command failed with exit code 1.
09:25:15.861 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
09:25:15.873 | Error: Command "yarn run build" exited with 1

**截图**
相关的页面，应该用结果

**环境**
macOS chrome e.g.22

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**Comment by tangly1024** [comment]
duplicate as https://github.com/tangly1024/NotionNext/issues/364
