### ISSUE TITLE
【SEO】在 google 搜索博客标题，搜索内容不正确

### ISSUE THREAD

**Issue by yizhimuzhuozi** [tangly1024/NotionNext#370]
![CleanShot 2022-09-15 at 12 38 24@2x](https://user-images.githubusercontent.com/31234254/190315903-e9f235ee-ca30-4370-adb1-86f07aaa0262.png)

**Comment by tangly1024** [comment]
1. 这里并非程序bug导致。而是google搜索引擎的特性导致.
2. google选择展示了你分页列表中的第二页，而非文章详情页、具体原因在结尾说明 。而在NotionNext中，分页列表（即 http://xx.com/page/2） 的标题是你的 `${页码}|Page-${站点名字}`，不包括文章标题，如下：https://00000520.xyz/page/2
<img width="790" alt="图片" src="https://user-images.githubusercontent.com/15920488/196203040-30691362-9148-42c3-91e4-c3bccec9e8cb.png">

3.我想要想让你的文章主页面被google摘录，需要从SEO的策略上着手解决，增加文章详情的内容丰富度。一些建议，在google中此关键词竞争太过激烈，基本已经被其他已有的高权重的优质文章占据，可以考虑优化文章内容、更新文章新颖性、**差异化**你的关键词，而非在标题摘要中堆砌关键词。

相关图片：

尝试在google中搜索此关键词，发现大量相似的文章关键词：
<img width="513" alt="图片" src="https://user-images.githubusercontent.com/15920488/196200296-024396a7-5eed-4856-a90a-7969f9db95ab.png">

<img width="938" alt="图片" src="https://user-images.githubusercontent.com/15920488/196200382-43ecafce-3694-406b-a7d0-61f487cab467.png">
