### ISSUE TITLE
当文章数量超过120的时候会导致新文章无法在首页被显示

### ISSUE THREAD

**Issue by De4tsh** [tangly1024/NotionNext#373]
**描述遇到的问题**
当文章写到120篇以后，后续的文章再无法显示到博客网站的首页上（首页的侧边栏最新文章处也没有显示），但是却可以在博客网站中的文章一栏中看到（文章一栏中的侧边栏处却有新的文章），但问题依旧存在在于即使看见了有些文章打开了也会显示404无法找到，问题截图如下：

![WeChat Screenshot_20220918101633](https://raw.githubusercontent.com/De4tsh/typoraPhoto/main/img/202209181040439.png)

![WeChat Screenshot_20220918101742](https://raw.githubusercontent.com/De4tsh/typoraPhoto/main/img/202209181021019.png)

在排错的时候由于对源码不了解，所以只能根据现象排错，第一想到了可能是因为`tag`/`category`种类分的太多了（因为通过观察网页的分类/标签一栏发现许多自己加的在网站中并没有显示），遂删掉了许多标签/分类，并保持其数量与作者您的网站的标签/分类数量保持一致，但发现并没有用处

于是尝试在`Vercel`中`Redeploy`项目，但一直是以失败告终，在`Building Log`中没有最后确切的报错日志，但却一直在报如下图所示400的小错误

![WeChat Screenshot_20220918102255](https://raw.githubusercontent.com/De4tsh/typoraPhoto/main/img/202209181023979.png)

![WeChat Screenshot_20220918102308](https://raw.githubusercontent.com/De4tsh/typoraPhoto/main/img/202209181023207.png)

实在找不到原因，所以向您求助，感激不尽

期间曾尝试重新`Fork`，每次都是使用您的`notion ID`构建可成功，换成我的`notion ID`便无法`Building`

**相应配置**
**notion_page_id：**`05fd40f5b96441c99c3a5f784d88e06b`

**网站URL：**`www.shtwo.top`

**完整notion Link：**`https://eufit.notion.site/05fd40f5b96441c99c3a5f784d88e06b?v=bedee4f8df9b4ff28c9e1f177049f97a`

**notion后端截图：**

![WeChat Screenshot_20220918102755](https://raw.githubusercontent.com/De4tsh/typoraPhoto/main/img/202209181040059.png)

**截图**
已在上面贴出

**环境**

- 操作系统: Windows Notion

**Comment by tangly1024** [comment]
Hi, 感谢你的认真反馈;
我在对你的Notion_Id进行编译时也遇到了类似的问题，最后编译提示超时，但我想这不是由于文章数量过多而导致，而是由于部分页面的网络响应过慢，从而出发了NextJS的超时限制 。

例如 ，我在编译过程中的错误提示: 在编译Rev27这篇文章时，尝试3次都是请求超时。。
```
> Build error occurred
Error: Static page generation for /article/Rev27 is still timing out after 3 attempts. See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
    at onRestart (/Users/tangly/Documents/WorkSpace/temp/NotionNext-New/node_modules/next/dist/build/index.js:507:35)
    at Worker.exportPage (/Users/tangly/Documents/WorkSpace/temp/NotionNext-New/node_modules/next/dist/lib/worker.js:49:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/tangly/Documents/WorkSpace/temp/NotionNext-New/node_modules/next/dist/export/index.js:311:32
    at async Span.traceAsyncFn (/Users/tangly/Documents/WorkSpace/temp/NotionNext-New/node_modules/next/dist/trace/trace.js:79:20)
    at async Promise.all (index 29)
    at async /Users/tangly/Documents/WorkSpace/temp/NotionNext-New/node_modules/next/dist/export/index.js:306:9
    at async Span.traceAsyncFn (/Users/tangly/Documents/WorkSpace/temp/NotionNext-New/node_modules/next/dist/trace/trace.js:79:20)
    at async /Users/tangly/Documents/WorkSpace/temp/NotionNext-New/node_modules/next/dist/build/index.js:1034:21
    at async Span.traceAsyncFn (/Users/tangly/Documents/WorkSpace/temp/NotionNext-New/node_modules/next/dist/trace/trace.js:79:20)
```



同时，在日志中，注意看[API耗时]这一项, 当请求的时间大于2000毫秒、甚至3000ms的时候，就应该考虑优化这个文章的内容体积了。（或者期待Notion官方能够提升一下接口的响应速度）
```
[API耗时] 2027ms
```


以Rev27这篇文章作为切入点的话，我认为过多的额代码 Block会影响notion的接口速度，可以尝试优化一下。

祝好
