### ISSUE TITLE
文章页面下一页的部分没有右侧箭头

### ISSUE THREAD

**Issue by mouyase** [tangly1024/NotionNext#378]
**描述bug**
文章页面下一页的部分没有右侧箭头

**复现步骤**
无

**期望的正常结果**
应该有右侧箭头

**截图**
![image](https://user-images.githubusercontent.com/7844572/193392496-414d8dca-4d9f-4fd2-af98-adbdd8ab4bc2.png)

**环境**

- 操作系统: Windows 10
- 浏览器: Edge
- 版本 -

**补充说明**
查看源码发现是class写错了

**Comment by tangly1024** [comment]
https://github.com/tangly1024/NotionNext/pull/379

感谢您的贡献！
