### ISSUE TITLE
【自定义字体】如何无伤修改字体

### ISSUE THREAD

**Issue by mouyase** [tangly1024/NotionNext#380]
现在如果需要修改字体，似乎要修改部分源代码，这可能会导致后续更新时与新代码产生冲突。是否有一种更优雅的方式来修改字体和样式呢？

**Comment by tangly1024** [comment]
字体的修改确实不够优雅，后续版本将考虑将字体的配置相关也完全移到配置文件中

**Comment by tangly1024** [comment]
hi
现已支持完全在[blog.config.js 28至37行](https://github.com/tangly1024/NotionNext/blob/df64a7ca2e3a59c6142c9e184a5c7ce5e820bd1d/blog.config.js#L28-L37)中配置GoogleFont字体：

## 相关代码
```
  // 字体相关
  FONT: 'font-sans', // 预设三种文章字体 ['font-sans', 'font-serif', 'font-mono'] @see /lib/font.js https://www.tailwindcss.cn/docs/font-family
  FONT_URL: 'https://fonts.font.im/css2?family=Noto+Serif+SC&display=swap', // 谷歌字体中国站镜像;对应的国际站地址：https://fonts.googleapis.com/css2?family=Noto+Serif+SC&display=swap
  FONT_CUSTOM: ['-apple-system', 'BlinkMacSystemFont', '"Apple Color Emoji"', '"Segoe UI Emoji"', '"Segoe UI Symbol"', '"Segoe UI"', '"PingFang SC"', 'HarmonyOS_Regular', '"Hiragino Sans GB"', '"Microsoft YaHei"', '"Helvetica Neue"', 'Helvetica', '"Source Han Sans SC"', '"Noto Sans CJK SC"', '"WenQuanYi Micro Hei"', 'Arial', 'sans-serif'],

  // 自定义google字体示例： 请先将FONT 改为  'font-custom'， 并将FONT_URL改为你的字体地址，同时在FONT_CUSTOM中指定你的 fontfamily
  // 以下是示例：
  //FONT: 'font-custom',
  //FONT_URL: 'https://fonts.font.im/css2?family=Ma+Shan+Zheng&display=swap',
  //FONT_CUSTOM_FAMILY: ['"Times New Roman"', 'Ma Shan Zheng'],
```

## 使用参考
参考配置文件 [blog.config.js 35-37行](https://github.com/tangly1024/NotionNext/blob/b34efecd37b37cb2eac227722823d40200b28ac5/blog.config.js#L35-L37)

参考预览效果
https://tangly1024.com/

**Comment by handbye** [comment]
> hi 现已支持完全在[blog.config.js 28至37行](https://github.com/tangly1024/NotionNext/blob/df64a7ca2e3a59c6142c9e184a5c7ce5e820bd1d/blog.config.js#L28-L37)中配置GoogleFont字体：
> 
> ## 相关代码
> ```
>   // 字体相关
>   FONT: 'font-sans', // 预设三种文章字体 ['font-sans', 'font-serif', 'font-mono'] @see /lib/font.js https://www.tailwindcss.cn/docs/font-family
>   FONT_URL: 'https://fonts.font.im/css2?family=Noto+Serif+SC&display=swap', // 谷歌字体中国站镜像;对应的国际站地址：https://fonts.googleapis.com/css2?family=Noto+Serif+SC&display=swap
>   FONT_CUSTOM: ['-apple-system', 'BlinkMacSystemFont', '"Apple Color Emoji"', '"Segoe UI Emoji"', '"Segoe UI Symbol"', '"Segoe UI"', '"PingFang SC"', 'HarmonyOS_Regular', '"Hiragino Sans GB"', '"Microsoft YaHei"', '"Helvetica Neue"', 'Helvetica', '"Source Han Sans SC"', '"Noto Sans CJK SC"', '"WenQuanYi Micro Hei"', 'Arial', 'sans-serif'],
> 
>   // 自定义google字体示例： 请先将FONT 改为  'font-custom'， 并将FONT_URL改为你的字体地址，同时在FONT_CUSTOM中指定你的 fontfamily
>   // 以下是示例：
>   //FONT: 'font-custom',
>   //FONT_URL: 'https://fonts.font.im/css2?family=Ma+Shan+Zheng&display=swap',
>   //FONT_CUSTOM_FAMILY: ['"Times New Roman"', 'Ma Shan Zheng'],
> ```
> 
> ## 使用参考
> 参考配置文件 [blog.config.js 35-37行](https://github.com/tangly1024/NotionNext/blob/b34efecd37b37cb2eac227722823d40200b28ac5/blog.config.js#L35-L37)
> 
> 参考预览效果 https://tangly1024.com/

为什么main分支中的blog.config.js没有更改呢。
