### ISSUE TITLE
【自定义博客前缀路径】建议支持 Post 自定义父路径配置以实现博客无缝迁移

### ISSUE THREAD

**Issue by zjs1224522500** [tangly1024/NotionNext#381]
**为什么提出这个新的特性改动**
- 如果以前搭建过静态页面的博客，就会涉及到博客迁移的问题，但是以往的博客文章可能已经部分被搜索引擎检索，如果想在不影响搜索引擎检索的情况下完成无缝的博客迁移，就需要保持博客对应的链接完全一致。

- 现在的博客文章 Post 类型，仿佛无法自定义网页的父路径信息，默认是 /article/xxx，而以往的很多博客是 /post/xxx。

- 所以希望可以支持自定义的路径的设置，实现博客无缝迁移。

**描述一下你推荐的解决方案**
- 支持在配置文件中自定义配置网站路径，比如针对 /article 的配置，但仿佛 article 是文件夹的名称，对于前端不太了解，不知道有没有什么比较优雅的解决方案。

**Comment by tangly1024** [comment]
不错的提议；我将此新特性列入下一个大版本的开发计划中。

我的设想是，在notion中笔记中增加一个 `folder`(文件夹)的属性，以便于用户自定义文章的页面路径。例如配置为`/post`后，路径则为 /post/xxx，如果配置为空则路径为  /xxx。

另外， 原先的 `type(类型)`属性(=`page`或=`post`)本意是用于区分文章的类型，从而实现文章显示在列表，单页显示在菜单栏的情况。

**Comment by tangly1024** [comment]
https://github.com/tangly1024/NotionNext/blob/1956d17d9a066b3c5288ac922a13d018f4dfb9e9/blog.config.js#L35

hi， 在V3.5.0版本中已经支持配置路径，修改方法为修改  'article' 为 'post'即可。
```
POST_URL_PREFIX: process.env.NEXT_PUBLIC_POST_URL_PREFIX || 'post', // POST类型文章的默认路径前缀，例如默认POST类型的路径是  /article/[slug]
```

**Comment by zjs1224522500** [comment]
使用新版本的部署到 vercel 后，仿佛在 notion 中设置为 invisible 的 post 在文章归档中变得可见了。

Notion 数据维护如下：
![image](https://user-images.githubusercontent.com/17877010/196626974-286054b7-c1af-4557-b42c-42d8cc95a415.png)

Blog 地址：https://notion.shunzi.tech/
![image](https://user-images.githubusercontent.com/17877010/196627272-a8f0e221-e4d8-42c0-a3d3-2dba09d79a3c.png)

**Comment by tangly1024** [comment]
> 使用新版本的部署到 vercel 后，仿佛在 notion 中设置为 invisible 的 post 在文章归档中变得可见了。
> 
> Notion 数据维护如下： ![image](https://user-images.githubusercontent.com/17877010/196626974-286054b7-c1af-4557-b42c-42d8cc95a415.png)
> 
> Blog 地址：https://notion.shunzi.tech/ ![image](https://user-images.githubusercontent.com/17877010/196627272-a8f0e221-e4d8-42c0-a3d3-2dba09d79a3c.png)

已收到反馈，[最新版本](https://github.com/tangly1024/NotionNext/commit/cd233f506035778c5694aabae320a297d466854b)中刚刚已修复此bug，更新即可体验~
