### ISSUE TITLE
【样式渲染】二号标题和三号标题排版出错，number list无法渲染层级关系

### ISSUE THREAD

**Issue by hortonyyx** [tangly1024/NotionNext#383]
**描述bug**
1. 当二号标题下为三号标题时，渲染结果为二号标题与三号标题在同一行，无法实现分行顺序排列
2. 在notion里使用number list进行层级嵌套时，渲染结果的序号都为123的序号模式（无法实现notion中次级序号分别为abc，i、ii、iii的格式）

**复现步骤**
正常notion编辑

**期望的正常结果**
1. 标题分行渲染输出
2. number list层级嵌套可以沿用notion的分级格式

**截图**
博客效果
![image](https://user-images.githubusercontent.com/65713218/194736933-4b62d6d9-b3fb-4807-beef-70b2a9228f41.png)
notion效果
![image](https://user-images.githubusercontent.com/65713218/194736947-cd5f5e50-659a-4374-a4c6-106ac56e4a96.png)

**环境**

- 操作系统: windows
- 浏览器：chrome

**补充说明**
博客地址：[hortonyyx.com](https://www.hortonyyx.com/article/public-philosophy0#a28069b6e2614cae92c09187cb25ef8b)

感谢作者的辛勤付出，非常有价值有意义的博客程序！！

**Comment by tangly1024** [comment]
已收到bug反馈，将在后续版本中修复此问题

**Comment by hortonyyx** [comment]
> 已收到bug反馈，将在后续版本中修复此问题

大佬，可否在list嵌套中增加第三级为i，ii，iii的渲染格式。如果作者有时间愿意做的话非常感谢，不做也没关系，谢谢谢谢！！

**Comment by tangly1024** [comment]
> > 已收到bug反馈，将在后续版本中修复此问题
> 
> 大佬，可否在list嵌套中增加第三级为i，ii，iii的渲染格式。如果作者有时间愿意做的话非常感谢，不做也没关系，谢谢谢谢！！


已收到反馈，此功能也已刚刚提交，第三级的列表 渲染为小写罗马字(i，ii，iii)， 更新至最新版即可体验。
