### ISSUE TITLE
【页面渲染】无法正确渲染 Equation Block  中的  \tag{行标}

### ISSUE THREAD

**Issue by kchen0x** [tangly1024/NotionNext#388]
**描述bug**
无法正确渲染 Equation Block

**复现步骤**
在Notion中使用 Equation Block，无法在NotionNext中正确渲染。

**期望的正常结果**
<img width="571" alt="image" src="https://user-images.githubusercontent.com/9739009/196016354-a90de53c-eda6-46aa-a469-c84434f057df.png">

**截图**
<img width="726" alt="image" src="https://user-images.githubusercontent.com/9739009/196016374-b5850eb9-78b0-45de-b808-0d555ac52025.png">

**环境**

- 操作系统: macos
- 浏览器 edge
- 版本 all

**补充说明**

**Comment by kchen0x** [comment]
#302

**Comment by An-Jhon** [comment]
我也遇到了这个问题，我的解决方法是矩阵括号不要用  \left[  和  \right] ，我换成\begin{bmatrix}...\end{bmatrix}之后就可以正常渲染了

**Comment by tangly1024** [comment]
经测试，似乎是由于 \tag{行号} 不受支持导致的渲染失败：
如果去掉行号，则可以正常显示
`f\left(\left[\frac{1+\{x, y\}}{\left(\frac{x}{y}+\frac{y}{x}\right)(u+1)}+a\right]^{3 / 2}\right)`

源notion页面
https://www.notion.so/tanghh/a6271da06b8f47a39735e8fa770f1d9f#7de9f2bb6e8b4a0db12662148de95bd5

效果页面
https://www.notion.so/tanghh/a6271da06b8f47a39735e8fa770f1d9f#7de9f2bb6e8b4a0db12662148de95bd5

**Comment by zfhxi** [comment]
> 经测试，似乎是由于 \tag{行标} 不受支持导致的渲染失败： `f\left(\left[\frac{1+\{x, y\}}{\left(\frac{x}{y}+\frac{y}{x}\right)(u+1)}+a\right]^{3 / 2}\right) \tag{行标}` 如果去掉 行标(\tag{x})，则可以正常显示 `f\left(\left[\frac{1+\{x, y\}}{\left(\frac{x}{y}+\frac{y}{x}\right)(u+1)}+a\right]^{3 / 2}\right)`
> 
> 源notion页面 https://www.notion.so/tanghh/a6271da06b8f47a39735e8fa770f1d9f#7de9f2bb6e8b4a0db12662148de95bd5
> 
> 效果页面 https://preview.tangly1024.com/article/example-1#7de9f2bb6e8b4a0db12662148de95bd5
> 
> 要修复这个bug似乎比较棘手

我发现将react-notion-x降级为4.11.0可以解决，最新版为啥不行的原因暂不知道:joy:

**Comment by tangly1024** [comment]
> 我发现将react-notion-x降级为4.11.0可以解决，最新版为啥不行的原因暂不知道😂

感谢您的反馈，根据这个思路我进行了调试：

这个错误是由Katex 直接导致的错误：
错误原因是 : ParseError: KaTeX parse error: \tag works only in display equations
![image](https://user-images.githubusercontent.com/15920488/217450543-b7101251-c87a-4397-b5a7-ce25f43a57cc.png)

## 推测原因
版本不同导致
- [katex](https://www.npmjs.com/package/katex) 目前最新版本的katex是**0.16.4**
- 而 [react-notion-x](https://github.com/NotionX/react-notion-x/blob/master/packages/react-notion-x/package.json) 使用的是 [matejmazur/react-katex组件](https://www.npmjs.com/package/@matejmazur/react-katex) 这是一个3年前的项目，其Katex内核为 ^0.15.x 对应版本**0.15.6**。

## 最后解决

剖析了 react-notion-x 、 matejmazur/react-katex 、 katex 的源码后发现：错误原因是 displayMode 参数设置的问题；
```

**Comment by tangly1024** [comment]
更新至[3.6.4](https://github.com/tangly1024/NotionNext/releases/tag/v3.9.4) 版本即可解决此问题。

**Comment by zfhxi** [comment]
大佬，我也最近在研究如何解决这个问题。没学过nodejs，捣鼓了好久，从<https://github.com/NotionX/react-notion-x/issues/301>才研究出解决方案<https://github.com/zfhxi/NotionNext/commit/99c6173a9262c8544bdd5fd01f3708817e5de3ab>，但还是没大佬的优雅:joy:
