### ISSUE TITLE
【页面渲染】有换行的引用块显示不完整

### ISSUE THREAD

**Issue by MarcusPierce** [tangly1024/NotionNext#391]
**描述bug**
有换行的引用块显示不完整

**复现步骤**
在引用块中使用换行

**期望的正常结果**
显示完整的引用块内容

**截图**
![notion](https://user-images.githubusercontent.com/30462393/196235657-d6e4a7d0-85c1-4af8-8aa3-6f003561ee65.png)
![notionnext](https://user-images.githubusercontent.com/30462393/196235683-6da39d16-03d1-4600-8409-3caa9f48b5c9.png)
**环境**

- 操作系统: WEB
- 浏览器：Web
- 版本：Latest

**补充说明**
[Notion链接](https://thedavidweng.notion.site/zu1k-IPFS-bf82d9c7ae7b4360aa344044ed7a6f9a)
[网站链接](https://blog.davidweng.tk/article/zu1ksviewonipfs)

**Comment by tangly1024** [comment]
最新版本已修复此问题
