### ISSUE TITLE
【部署相关】考虑一下本地生成博客项目

### ISSUE THREAD

**Issue by xanqan** [tangly1024/NotionNext#403]
想部署在自己国内的服务器上，手动同步也可以

**Comment by tangly1024** [comment]
## 结论
项目是支持本地生成博客的。

NotionNext可以部署在任意服务器上，选择Vercel、CloudFlarePage、或其他Serverless服务商中，是因为他们提供了免费的具有NodeJs环境的托管平台，而且文章数据是托管在你的Notion笔记中的，所以私有服务器其实是一个非必要的选项。

## 私有服务器部署
在自己的服务器上部署运行NotionNext有两种方式。一是正常安装NodeJs环境部署，二是使用Docker容器。好消息是这几种部署方式也是支持自动实时同步的，得益于NotionNext开发使用的NextJS框架特性。

## 一、 NodeJs原生 部署
```bash 
git clone https://github.com/tangly1024/NotionNext.git     # 下载代码
curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash - && sudo yum install -y nodejs         # 安装nodejs环境
cd NotionNext/ && npm --registry https://registry.npm.taobao.org install --force && npm run build   # 安装依赖并编译

npm run start  # 运行页面
 ```
启动后浏览器通过 http://localhost:3000/ 即可访问


##  二、Docker容器部署
```
docker pull ghcr.io/tangly1024/notionnext:main # 下载镜像
docker run -p=3000:3000 ghcr.io/tangly1024/notionnext:main # 运行镜像
```
可以用环境变量或者外挂blog.config.js的方式来 管理配置文件。


# 扩展
除以上方法之外，NotionNext还支持导出纯静态Html，放在诸如Nginx\Apache等web容器中运行。
参考此[Issue](https://github.com/tangly1024/NotionNext/issues/116)

**Comment by xiebaiyuan** [comment]
很赞~
