### ISSUE TITLE
vercel部署出错

### ISSUE THREAD

**Issue by lifeafter619** [tangly1024/NotionNext#404]
**描述遇到的问题**
大大，今天早上更新的时候discard了，只能重新修改[blog.config.js](https://github.com/lifeafter619/NotionNext/commit/ea1216ebb6e82ca6781e8f504dd7e8f036eafd33)
但是在vercel重新deploy的时候直接报错了，无法deploy

**相应配置**
notion_page_id :b2dc0cd4bc7d4f3c96425a0223229c6a
其它配置应该没问题

**截图**
![1](https://user-images.githubusercontent.com/65111206/196840995-8cd61b38-a574-426f-b86c-2bc06da07acc.png)

**环境**

- 操作系统: windows 10
- 浏览器 edge
- 版本 [e.g. 22]

**Comment by eddiehe99** [comment]
我遇到了相同的问题。

**Comment by tangly1024** [comment]
感谢反馈，应该是代码错误导致，将马上修复此问题

**Comment by tangly1024** [comment]
在main分支的最新代码中已修复此问题，更新代码即可解决。
