### ISSUE TITLE
【表格排版】部署之后notion中的表格排版被拉伸

### ISSUE THREAD

**Issue by An-Jhon** [tangly1024/NotionNext#406]
**描述遇到的问题**
notion内容部署之后表格排版被拉伸，详情见下图。尝试多个浏览器结果相同

**相应配置**
内容详见：https://notion-next-opal-ten.vercel.app/article/de1317b2-0590-437e-bd9a-3bf563425e0d

**截图**
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/44490800/196970713-f483cd2b-90b6-4848-8bc8-93c639138da4.png">
<img width="961" alt="image" src="https://user-images.githubusercontent.com/44490800/196970929-debb83cb-1bbf-4da1-a929-4e486e5618d6.png">

**环境**

- 操作系统: macOS
- 浏览器 chrome,
- 版本

**Comment by tangly1024** [comment]
功能已更新
https://github.com/tangly1024/NotionNext/releases/tag/v3.6.0
