### ISSUE TITLE
【组件渲染】Next主題的按鈕消失及佈局不正常

### ISSUE THREAD

**Issue by nagongze** [tangly1024/NotionNext#407]
**描述bug**
更新了新版之後，右下角的按鈕只剩下messenger了
而且本來的三欄佈局變成了兩欄

**截图**
<img width="588" alt="CleanShot 2022-10-21 at 09 44 29" src="https://user-images.githubusercontent.com/68653451/197091725-fd8a7646-78b9-4448-9c11-2923281d08dc.png">
<img width="400" alt="CleanShot 2022-10-21 at 09 45 45" src="https://user-images.githubusercontent.com/68653451/197091882-c419225c-b68b-424b-ad73-cf8da2fb5a69.png">

**环境**
- 操作系统: macOS
- 浏览器: chrome, safari

**Comment by tangly1024** [comment]
> 右下角的按鈕只剩下messenger了

按钮问题[已修复](https://github.com/tangly1024/NotionNext/commit/2acd5cc58a7ce04de40c8bf18153e872f7245eb0)，更新代码即可。


> 本來的三欄佈局變成了兩欄

😂奇怪，我默认设置RIGHT_BAR的值为`true`，页面应该是三栏。请检查是你的[config_next.js](https://github.com/nagongze/NotionNext/commit/ea2af98717da3b6585368244f18c3969d0a5ebaa#diff-10a027574edd9a1bfda4c214b7a4b1f05637d756bb94a35b404da9c1c7ed2af8)配置错误导致的。

**Comment by nagongze** [comment]
怪的是我也是true
前面的版本我有改成兩欄過
但再改也改不回三欄

**Comment by tangly1024** [comment]
在我这边看，现在看就是三栏：
<img width="1453" alt="图片" src="https://user-images.githubusercontent.com/15920488/197157382-641d0971-5f62-419d-83e4-6e97c77ffbc9.png">

<img width="1483" alt="图片" src="https://user-images.githubusercontent.com/15920488/197157407-305ea36f-985f-4289-83cd-6b8a8e33b2cb.png">

https://www.nagongze.me/article/ray-shader-video-tutorial-1

是不是你的浏览器窗口太小，导致最右侧的那栏被动态隐藏了？（在小窗口或是移动端的小屏幕中，右侧栏是动态隐藏的）

**Comment by nagongze** [comment]
還真是太小了 所以不見了 謝謝XD
