### ISSUE TITLE
【单页建议】单页中的文章推荐和署名建议删除

### ISSUE THREAD

**Issue by An-Jhon** [tangly1024/NotionNext#410]
**为什么提出这个新的特性改动**
新增的单页在结尾处还会有文章推荐和署名

**描述一下你推荐的解决方案**
如果可以，建议在单页中屏蔽或删除这部分内容

**描述一下你考虑过的其它替代解决方案**
![image](https://user-images.githubusercontent.com/44490800/197160667-ffc80863-f43c-4e1b-966d-7e4b0db19e9b.png)

**补充说明**
无

**Comment by tangly1024** [comment]
最新的提交更新中，已经隐藏了“文章推荐和署名”元素
