### ISSUE TITLE
【链接外部Notion】

### ISSUE THREAD

**Issue by tangly1024** [tangly1024/NotionNext#411]
**为什么提出这个新的特性改动**
来自评论区 horton留言的问题，在此做一个链接：

> 作者大大好，请问有办法实现文章的嵌套吗？
> 因为我自己的内容很多都是按数据库建立多个page来组织的，但是博客页面好像并不能实现嵌套页面的打开，如果是一个个把文章单独拷贝一份的话有点太麻烦了，而且感觉不好组织
> 请问支持文章嵌套的功能方便增加吗？或者有别的办法可以实现该需求？
> 谢谢作者大大！！！
> 

**解决方案**

存在这种情况: 你的文章不是全都放在NotionNext指定的数据库中，而是已经放在了Notion笔记的其他任意位置，这时候你可以用`page-link`的方式将它作为嵌套页面放置在博客中。

但是前提条件是：被引用的页面需要Share to web（开启共享），否则网站无权访问。
<img width="1044" alt="图片" src="https://user-images.githubusercontent.com/15920488/197169376-4cfb2908-eb4b-463f-8272-64815812707a.png">

实现效果
[示例演示页面](https://preview.tangly1024.com/article/example-1#ff69326a6d684e878195d3abe3c938bc)

对应的Notion页面：
包含内嵌的页面：
https://www.notion.so/tanghh/a6271da06b8f47a39735e8fa770f1d9f#ff69326a6d684e878195d3abe3c938bc
被用于内嵌的外部页面
https://www.notion.so/b458be50052940db9039f907ee69e524

注意：链接打开的功能

**描述一下你考虑过的其它替代解决方案**
页面的内嵌已经可以实现，但是点击跳转此页面的逻辑需要开发

**补充说明**
补充与此特性相关的内容

**Comment by An-Jhon** [comment]
这个功能超赞，幸苦作者

**Comment by hortonyyx** [comment]
明白了，相当于把引用的其他notion页面作为外部网页链接插入到分享的博文里。这样跳转之后是notion分享页面的组织方式，感觉也不错，非常感谢

**Comment by tangly1024** [comment]
功能已更新
https://github.com/tangly1024/NotionNext/releases/tag/v3.6.0

**Comment by kufx** [comment]
能不能粘贴其他作者公开的notion页面链接为mention的时候，也渲染成本站页面的样式呀！
因为我发现如果我mention到其他作者的notion公开页面，虽然显示错误404，但是打开源码，里面显示的内容就是mention到的外部notion页面的内容，所以我觉得这个可行呀！
不知道tangly大佬有空研究一下吗？谢谢！
