### ISSUE TITLE
文章前綴路徑留空後無法正常使用

### ISSUE THREAD

**Issue by nagongze** [tangly1024/NotionNext#412]
**描述bug**
<img width="1038" alt="CleanShot 2022-10-24 at 14 11 12" src="https://user-images.githubusercontent.com/68653451/197459293-93b47530-c102-4377-835e-72746f94c852.png">

**复现步骤**
<img width="977" alt="CleanShot 2022-10-24 at 14 12 32" src="https://user-images.githubusercontent.com/68653451/197459370-4b9c8407-ed5a-4be8-93ff-9a76fd541ddc.png">

**期望的正常结果**
因為只要mention頁面都會被加上文章的前綴路徑，導致頁面會無法訪問，所以才會留空，結果留空之後就出錯了。

**Comment by mouyase** [comment]
#414

**Comment by tangly1024** [comment]
感谢 @mouyase 修复了此问题
