### ISSUE TITLE
【画廊和附件】添加画廊视图后,文章的附件就会无法打开、并且嵌入式PDF将不显示

### ISSUE THREAD

**Issue by 274802235** [tangly1024/NotionNext#421]
**描述bug**
在添加画廊视图后,文章的附件就会无法打开（点击了没反应）并且嵌入式PDF模块将不显示的问题

**复现步骤**
1.在NOTION添加一篇正常的文章并插入一个XXX.PDF附件后,去BLOG看文章是可以点开这个附件的。见图1
2.在NOTION添加一个画廊视图后，刷新BLOG文章，文章的附件将无法打开（点了没反应） 嵌入式PDF模块也不显示了。见图2
3.发生此问题后，再回去删除画廊视图并不能解决问题故障依旧。
**期望的正常结果**
希望按这个步骤，正常操作结果是什么
希望能够解决添加画廊视图后出现的问题。
**截图**
![image](https://user-images.githubusercontent.com/82162031/198870469-8c2edc74-a1e7-4979-b6b0-14ca2adea0c7.png)
![image](https://user-images.githubusercontent.com/82162031/198870665-e1842d85-1d89-4667-9b27-e3f1eae5c46f.png)

**环境**
windows chrome，Android

**补充说明**
与问题相关的其它说明

**Comment by 274802235** [comment]
测试页面：https://d32d.vercel.app/
Notion：fb2804e3054847809932e5a35a4087e2

**Comment by sh2288** [comment]
这个嵌入附件是notion的自带功能,web可能并不能抓取或读取这个附件,这里只是读取到了你的附件文字渲染成了网页而已,所以个人觉得这个应该不算bug

**Comment by SenLief** [comment]
我看了下附件是没有被渲染到链接的，只是文字。

**Comment by 274802235** [comment]
> 你这个嵌入是notion的自带功能，web可能并抓取附件或读取这个，这里可以读取到的附件渲染成网页，所以觉得这个应该不算bug

正常情况下，附件链接是可以点击打开的。 在notion端添加了画廊视图后 文章里的附件就变成不能打开了。

**Comment by tangly1024** [comment]
最新版本已经没有这个bug；可以帮忙验证一下；

https://preview.tangly1024.com/article/example-1#46e007896d6a4635aac3433bba79a5df

**Comment by 274802235** [comment]
你好 测试过了  确实没有这个bug了，感谢修复！

**Comment by 274802235** [comment]
> 最新版本已经没有这个bug；可以帮忙验证一下；
> 
> * 演示页面
>   https://preview.tangly1024.com/article/example-1#75cd9f2882de41f7a5f2af4e0055aaf1
> * 源notion页面
>   https://www.notion.so/tanghh/Test1-a6271da06b8f47a39735e8fa770f1d9f#75cd9f2882de41f7a5f2af4e0055aaf1

你好 测试过了 确实没有这个bug了，感谢修复！
