### ISSUE TITLE
【PDF渲染】关于PDF模块不会从第一页开始显示的问题

### ISSUE THREAD

**Issue by 274802235** [tangly1024/NotionNext#422]
**描述bug**
PDF模块的内容不是从第一页开始显示。

**复现步骤**
添加一个测试PDF,内容为1-5的数字，在notion里显示正常从第一页1开始（见图1）
从blog文章查看PDF模块，页面不是从第一页开始显示，25页的PDF只显示13页（见图2）

**期望的正常结果**
希望可以像在notion一样正常显示

**截图**
![image](https://user-images.githubusercontent.com/82162031/198871784-22345235-1bec-4937-b9fa-62ea1c84af6f.png)
![image](https://user-images.githubusercontent.com/82162031/198871799-971cdea1-ff9e-437b-adae-d7c5aa3afa65.png)

**环境**
windows，chrome， Android

**补充说明**
BOLG测试页面：https://pdf-weld-ten.vercel.app/article/49169d94-791d-4c48-9398-0d13b00d33bf
notion：180cf989b9df4586abd9b2943a95a1e4

**Comment by tangly1024** [comment]
> 这个bug是由于NotionNext依赖的react-notion-x导致的，react-notion-x对于PDF文件的样式设置出现了错误，所以只能看到第一页的内容，我提了一个[PR](https://github.com/NotionX/react-notion-x/pull/412)来解决这个问题，等他们合完代码发布新版本就可以用了。

感谢你发现了问题的根源，当react-notion-x项目修复此补丁后，NotionNext也会相应更新。

不过好消息是，我们不需要等到对方更新，在NotionNext中也可以修复此问题,

只需要在notion.css 中简单地修改样式即可：https://github.com/tangly1024/NotionNext/commit/69124a9275cee309cb1237e80047afb5db1a935a
