### ISSUE TITLE
【页面404】POST类型文章的默认路径前缀更改后出错、Fontawesome图标版本

### ISSUE THREAD

**Issue by lifeafter619** [tangly1024/NotionNext#423]
**描述bug**
POST类型文章的默认路径前缀更改后出错

**复现步骤**
bug1.修改[blog.config.js](https://github.com/lifeafter619/NotionNext/blob/393b53654c4d3e27edc3ff4f1f23837fedf5ea48/blog.config.js)中第41行的配置，设置为空，重新部署后文章打不开，显示404后返回主页面（不知道是不是我理解错了，前后试了好几遍都不行。

bug2.notion中page icon较新图标加载不出来，更新[blog.config.js](https://github.com/lifeafter619/NotionNext/blob/393b53654c4d3e27edc3ff4f1f23837fedf5ea48/blog.config.js)中图标库后解决（图标库链接改为6.2.0）

**期望的正常结果**
正常打开post文章

**截图**
![2](https://user-images.githubusercontent.com/65111206/199240641-c67efc4d-32c3-47ac-bbef-9d660103e7f7.png)
![3](https://user-images.githubusercontent.com/65111206/199240650-04bc7e50-8687-4030-9ffa-5710db66db26.png)

**环境**

- 操作系统: windows[例如. iOS, Android, macOS, windows]
- 浏览器 edge[例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
我的blog在https://66619.eu.org

**Comment by tangly1024** [comment]
在最新的提交中已修复了上述问题，fontawesome版本默认升级为了6.2.0版本
