### ISSUE TITLE
【部署问题】vercel部署错误 - pageId is not a database

### ISSUE THREAD

**Issue by JossSong** [tangly1024/NotionNext#425]
**描述遇到的问题**
简单说明你遇到的问题，相关的日志、错误信息

**相应配置**
相关的配置，例如notion_page_id；你的网站地址

**截图**
相关的页面，应该用结果
![image](https://user-images.githubusercontent.com/40620197/199692339-e5da3d61-ee5c-43d5-a0b4-73094622d4ce.png)

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**Comment by tangly1024** [comment]
notion-page-id 格式错误，请去掉中间的中划线

**Comment by JossSong** [comment]
![image](https://user-images.githubusercontent.com/40620197/199895997-fb789441-d839-44d3-a2e2-0ab811664ac5.png)
很奇怪呢，页面id也没错啊

**Comment by tangly1024** [comment]
你截图中的 notion-id  页面有误，请Duplicate这个页面：
https://tanghh.notion.site/02ab3b8678004aa69e9e415905ef32a5?v=b7eb215720224ca5827bfaa5ef82cf2d

![图片](https://user-images.githubusercontent.com/15920488/200099894-c4cc866a-3c09-472b-b8c0-878854047f87.png)
