### ISSUE TITLE
【主题问题】几个有关主题的小问题，是否支持Team Plan

### ISSUE THREAD

**Issue by lifeafter619** [tangly1024/NotionNext#430]
**描述bug**
1.NEXT主题下 作者简介排版靠左，希望能选择居中
![3](https://user-images.githubusercontent.com/65111206/200472839-3f91d4a3-0b3b-41e5-8e3b-3c06488383a4.png)

2.切换主题后（用切换键或点看板切换），新主题下访问量的数据无显示，必须刷新页面才出现
![1](https://user-images.githubusercontent.com/65111206/200473182-b8eec825-46f8-4aad-9d81-caf0090c2b69.png)

3.hexo和example主题下最新文章板块会把隐藏的文章（好像只有post类型）也展示出来，如下图
![9](https://user-images.githubusercontent.com/65111206/200473525-d7b27842-3112-4f15-8a56-67b505ae612c.png)

**复现步骤**
最新版本就存在

**期望的正常结果**
1.希望能让大家选择排版方法
2.原来的版本好像是正常的？
3.希望能把文章隐藏啊，不然invisible就白设置了（

**截图**
相关的页面，应该用结果（如上

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
很喜欢这个blog项目，真心期望越来越完美~

**Comment by tangly1024** [comment]
确实出现了这些bug，但问题不大，尽快会修复

**Comment by tangly1024** [comment]
在最近的提交中已修复此问题，更新代码即可获取新特性

1.NEXT主题下 作者简介排版 居中

2.切换主题后（用切换键或点看板切换），新主题下访问量正常显示

3.hexo和example主题下最新文章板块不显示隐藏的文章

**Comment by lifeafter619** [comment]
还有一个小问题，这个项目的notion page是不支持team plan吗？我尝试将notion team版的页面id写入blog.config.js，重新部署后仍然是按照原来的page更新的。 @tangly1024 （求求了，有超大图片传不上去，team版的才可以

**Comment by tangly1024** [comment]
> 还有一个小问题，这个项目的notion page是不支持team plan吗？我尝试将notion team版的页面id写入blog.config.js，重新部署后仍然是按照原来的page更新的。 @tangly1024 （求求了，有超大图片传不上去，team版的才可以

很遗憾，我的notion并不是team plan的，导致我并没有尝试过team plan 的page；
可以的话，提供一下你的team plan 页面id，或访问地址，我可以查看一下问题。

**Comment by lifeafter619** [comment]
> 很遗憾，我的notion并不是team plan的，导致我并没有尝试过team plan 的page； 可以的话，提供一下你的team plan 页面id，或访问地址，我可以查看一下问题。

我的team plan就是中文社区的 可以从 https://linmi.cc/s 这里加入
链接的话就是 https://www.notion.so/cnotion/e39a8757aa1b44268c7a6f99b6bfd5d2?v=2e682a80cd9b43baac9e77b496d838a0
> ![1](https://user-images.githubusercontent.com/65111206/200774729-e80642c7-3262-49c5-8006-0345198d2215.png)
很确定是share并正确设置了的，但又试了一遍，好像还是不行

**Comment by tangly1024** [comment]
## 1.Team-Plan 是被支持的
hello，经过测试这个[Notion页面](https://www.notion.so/cnotion/e39a8757aa1b44268c7a6f99b6bfd5d2?v=2e682a80cd9b43baac9e77b496d838a0) 是没有问题的，当我将NotionPageId设置为你的 `e39a8757aa1b44268c7a6f99b6bfd5d2`时，页面正常显示：

为了测试，我冒昧地将notion中的页面标题做了，网页上也显示生效了。

![图片](https://user-images.githubusercontent.com/15920488/201263606-7b8450ba-3ad4-4172-a531-894564a38e60.png)



## 2.建议的解决方案
应该是你在修改配置文件时，出现了格式错误导致，可将配置文件重置再尝试一下；
还是不行的话，可以将你的vercel部署日志提供出来，我将为你排查。


# 

> > 很遗憾，我的notion并不是team plan的，导致我并没有尝试过team plan 的page； 可以的话，提供一下你的team plan 页面id，或访问地址，我可以查看一下问题。
> 
> 我的team plan就是中文社区的 可以从 https://linmi.cc/s 这里加入 链接的话就是 https://www.notion.so/cnotion/e39a8757aa1b44268c7a6f99b6bfd5d2?v=2e682a80cd9b43baac9e77b496d838a0
> 
> > ![1](https://user-images.githubusercontent.com/65111206/200774729-e80642c7-3262-49c5-8006-0345198d2215.png)
> > 很确定是share并正确设置了的，但又试了一遍，好像还是不行

**Comment by lifeafter619** [comment]
谢谢开发者大哥，找到问题了，我的NOTION_PAGE_ID设置在vercel环境变量里了，但是我只更新了github内的blog.config.js，所以一直是用我原来配置的NOTION_PAGE_ID更新页面了，，
但是我是在仔细看了vercel的部署日志才发现问题，这样好像并不方便大家找到问题，能否将vercel的环境变量与GitHub里的blog.config.js进行同步更改？（直接写在自己的blog.config.js吧感觉页面不大安全，写在vercel里吧又容易忘记改）我这样健忘的人真的想不起来改vercel环境变量。。。

**Comment by tangly1024** [comment]
vercel的环境变量配置Notion_Page_ID是为了安全隐私考虑。

vercel 是服务器托管平台，github是代码托管平台，目前似乎没有办法能做到同步😂

建议是配置文件中的page_id不要操作，优先在vercel中配置。


> 谢谢开发者大哥，找到问题了，我的NOTION_PAGE_ID设置在vercel环境变量里了，但是我只更新了github内的blog.config.js，所以一直是用我原来配置的NOTION_PAGE_ID更新页面了，， 但是我是在仔细看了vercel的部署日志才发现问题，这样好像并不方便大家找到问题，能否将vercel的环境变量与GitHub里的blog.config.js进行同步更改？（直接写在自己的blog.config.js吧感觉页面不大安全，写在vercel里吧又容易忘记改）我这样健忘的人真的想不起来改vercel环境变量。。。
