### ISSUE TITLE
【部署问题】在Vercel部署的时候发现了HTTP Error , Response code 400 (Bad Request)

### ISSUE THREAD

**Issue by catmangox** [tangly1024/NotionNext#435]
**描述遇到的问题**
在Vercel部署的时候发现了HTTP Error

**相应配置**
[notion-next-bice-xi.vercel.app](https://notion-next-bice-xi.vercel.app/)
https://catmango.notion.site/83d252b4645a42c98024b85ece67c618?v=d76e348b884f49c1afe6e2846663eed5

**截图**

<img width="1374" alt="スクリーンショット 2022-11-10 17 48 09" src="https://user-images.githubusercontent.com/9482245/201043748-dbb8ee95-09f4-4158-a260-8d24f53c21ca.png">

NotionAPI getSignedfileUrls error HTTPError: Response code 400 (Bad Request)
17:27:50.544 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:118:42)
17:27:50.545 | at runMicrotasks (<anonymous>)
17:27:50.545 | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
17:27:50.545 | code: 'ERR_NON_2XX_3XX_RESPONSE',
17:27:50.545 | timings: {
17:27:50.545 | start: 1668068870493,
17:27:50.545 | socket: 1668068870494,
17:27:50.545 | lookup: 1668068870494,
17:27:50.546 | connect: 1668068870495,
17:27:50.546 | secureConnect: 1668068870498,
17:27:50.546 | upload: 1668068870498,
17:27:50.546 | response: 1668068870539,
17:27:50.546 | end: 1668068870539,
17:27:50.546 | error: undefined,
17:27:50.546

<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

**环境**

- 操作系统: macOS 13.0.1（22A400）
- 浏览器 safari 
- 版本 16.1 (18614.2.9.1.12)

**Comment by tangly1024** [comment]
https://catmango.notion.site/83d252b4645a42c98024b85ece67c618?v=d76e348b884f49c1afe6e2846663eed5

此页面我无法访问，需要检查一下路径是否正确，以及打开共享哦

<img width="857" alt="图片" src="https://user-images.githubusercontent.com/15920488/201460126-e523c665-3c20-42b7-80a1-9bc76b18ac6d.png">

**Comment by catmangox** [comment]
我后来换了page id貌似还有：https://catmangox.notion.site/cb9d51b3be09416ca251c3a3bce31c4c?v=0671e365028f4ccc8ccdeae0cc878b85

**Comment by tangly1024** [comment]
将在此 https://github.com/tangly1024/NotionNext/issues/443 跟进问题
