### ISSUE TITLE
关于字体,不喜欢默认字体

### ISSUE THREAD

**Issue by wxyhgk** [tangly1024/NotionNext#436]
在老版本中字体是和notion中显示是一样的,新版本是楷体,我不喜欢楷体,并且,我把自定义字体关闭了,我该怎么用回原来的字体

**Comment by tangly1024** [comment]
似乎是个bug，按照你的配置，关闭后就应该显示原来的字体，我将尽快修复此bug

**Comment by wxyhgk** [comment]
> 似乎是个bug，按照你的配置，关闭后就应该显示原来的字体，我将尽快修复此bug

我重新部署了几次,没问题了

**Comment by tangly1024** [comment]
> > 似乎是个bug，按照你的配置，关闭后就应该显示原来的字体，我将尽快修复此bug
> 
> 我重新部署了几次,没问题了

ok~ 那就好
