### ISSUE TITLE
【部署问题】Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by catmangox** [tangly1024/NotionNext#443]
**描述遇到的问题**
Vercel部署错误，但是我新的page id应该没有什么问题。

**相应配置**
notion_page_id: cb9d51b3be09416ca251c3a3bce31c4c

**截图**

<img width="1258" alt="スクリーンショット 2022-11-13 16 39 07" src="https://user-images.githubusercontent.com/9482245/201511267-8ddfcaef-e7a1-462e-9992-e10e4c0aafba.png">

**环境**

操作系统: macOS 13.0.1（22A400）
浏览器 safari
版本 16.1 (18614.2.9.1.12)

**Comment by tangly1024** [comment]
紧急修复了此bug ： https://github.com/tangly1024/NotionNext/commit/348812684db30301400dd91506dc8a12e2ef7c30
重新更新代码即可生效
