### ISSUE TITLE
HEXO主题下的代码块显示问题：建议代码自适应换行 现有显示有些丑

### ISSUE THREAD

**Issue by jarlin8** [tangly1024/NotionNext#448]
**为什么提出这个新的特性改动**
『HEXO主题下的代码块显示问题：建议代码自适应换行 现有显示有些丑』

**描述一下你推荐的解决方案**
『建议代码自适应换行 现有显示有些丑』

**描述一下你考虑过的其它替代解决方案**
line-break: anywhere;

**补充说明**
现有显示效果
[![zEGqMT.jpg](https://s1.ax1x.com/2022/11/15/zEGqMT.jpg)](https://imgse.com/i/zEGqMT)
建议显示效果
[![zEGLsU.jpg](https://s1.ax1x.com/2022/11/15/zEGLsU.jpg)](https://imgse.com/i/zEGLsU)

**Comment by tangly1024** [comment]
hello 感谢你的反馈，也许你说的是这样的效果：

https://tw.andys.pro/article/prismjs-mac-style-for-blog

<img width="841" alt="图片" src="https://user-images.githubusercontent.com/15920488/201853074-1dac8efd-98f2-467d-8995-26ca1396449e.png">

**Comment by jarlin8** [comment]
感谢回复。是的 类似这种美化效果。

**Comment by tangly1024** [comment]
👌，感谢反馈，将在3.6.0版本中加入此特性

**Comment by tangly1024** [comment]
功能已更新
https://github.com/tangly1024/NotionNext/releases/tag/v3.6.0

**Comment by jarlin8** [comment]
perfect！
