### ISSUE TITLE
Next主题要可以关闭文章头图、并渲染Notion的icon

### ISSUE THREAD

**Issue by tangly1024** [tangly1024/NotionNext#449]

**Comment by kchen0x** [comment]
<img width="899" alt="image" src="https://user-images.githubusercontent.com/9739009/202336278-86d1bfce-50a0-4390-9eb0-4a864de7c0ae.png">
觉得文章头图占用渲染流量，因此把文章的头图去掉之后，变成了这样。

**Comment by kchen0x** [comment]
另外，建议能不能把 Notion 里面的 icon 拿过来，这个图片的体积小了很多，其实我有为每篇文章加上合适的 icon，只能在page中用有点可惜了。
<img width="474" alt="image" src="https://user-images.githubusercontent.com/9739009/202336866-bad1998e-60b6-460f-9936-afbfb1dc0d23.png">

**Comment by tangly1024** [comment]
功能已更新
https://github.com/tangly1024/NotionNext/releases/tag/v3.6.0
