### ISSUE TITLE
文章底部的上一页下一页会跳转到隐藏文章

### ISSUE THREAD

**Issue by leewint** [tangly1024/NotionNext#456]
**描述bug**
文章底部的上一页下一页会跳转到隐藏文章。

**复现步骤**
1、新建一个隐藏文章Invisible
2、虽然文章列表不显示，但是文章底部的上一页下一页会显示，还可以跳转过去

**期望的正常结果**
过滤掉隐藏文章，只显示公开文章。

**截图**
就是这个位置。
![image](https://user-images.githubusercontent.com/44335558/202338350-391643dd-7be1-4bf3-ab6c-aa6563ddb8a7.png)

**环境**
- 浏览器 [Edge]

**Comment by tangly1024** [comment]
功能已更新
https://github.com/tangly1024/NotionNext/releases/tag/v3.6.0
