### ISSUE TITLE
【部署问题】Build error occurred

### ISSUE THREAD

**Issue by hejijii** [tangly1024/NotionNext#458]
**描述遇到的问题**
安装过程出现错误

**相应配置**
相关的配置，例如notion
_page_id；你的网站地址

**截图**
[![zeO15q.jpg](https://s1.ax1x.com/2022/11/17/zeO15q.jpg)](https://imgse.com/i/zeO15q)
**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**Comment by tangly1024** [comment]
pageid有误 
请去掉 `?v=[xxx]`的部分

**Comment by hejijii** [comment]
但是我没有填
[img]https://p1.meituan.net/dpplatform/c43ca01e1ce5cb1e4d3eee4b249f209f31062.jpg[/img]

**Comment by hejijii** [comment]
但是我没填，是自动加上的吗？
[![zmi48H.jpg](https://s1.ax1x.com/2022/11/17/zmi48H.jpg)](https://imgse.com/i/zmi48H)

**Comment by tangly1024** [comment]
可能是在你的vercel 环境变量中配置了 NOTION_PAGE_ID
