### ISSUE TITLE
【字体】落霞文楷字体优化

### ISSUE THREAD

**Issue by kchen0x** [tangly1024/NotionNext#463]
**为什么提出这个新的特性改动**
现在使用的 LXGW Wenkai Screen 的 Bold 字重只要字型稍微复杂一点，笔画就会糊到一块：

<img width="203" alt="image" src="https://user-images.githubusercontent.com/9739009/202645582-3d260076-f73f-4cc8-8a87-ea0237d49c28.png">

**描述一下你推荐的解决方案**
如果改使用 LXGW Wenkai，无论是 Lighter 还是 Bold 字重的笔画都会比较不错，缺点是 Bold 并不算明显，但我觉得这是因为 Lighter 字重的笔画本来就比较粗所以才拉不开的。

<img width="181" alt="image" src="https://user-images.githubusercontent.com/9739009/202646320-1a4b038a-764b-4f2c-bb1b-e70055506ca8.png">
图中标题【折叠列表】为  LXGW Wenkai 的 Bold 字重。

**描述一下你考虑过的其它替代解决方案**
现在的 CUSTOM_FONT 是可以解决这个问题的，但我还是建议修改一下默认值。

**补充说明**

**Comment by kchen0x** [comment]
补充一下screen与否的效果。

![image](https://user-images.githubusercontent.com/9739009/202681160-30aa32ab-7d0a-40a5-987f-718ca20f5e24.png)

![image](https://user-images.githubusercontent.com/9739009/202681193-1b485061-170d-438c-90f2-735c864b4cc4.png)

**Comment by tangly1024** [comment]
感谢提议，如您所言，最新版本默认字体将被更新为 LXGW Wenkai

**Comment by tangly1024** [comment]
功能已更新
https://github.com/tangly1024/NotionNext/releases/tag/v3.6.0
