### ISSUE TITLE
修改notion_page_id为我自己的notion的时候报错

### ISSUE THREAD

**Issue by XcloudFance** [tangly1024/NotionNext#465]
**描述bug**

修改pageid后访问网页，就出现了TypeError: Cannot read properties of undefined (reading 'filter')

**复现步骤**
把我自己的notion pageid复制进去后，重新运行

**截图**
![报错结果](https://user-images.githubusercontent.com/34064977/202652719-2bd0f151-5202-46ca-9197-1b2cb5a679bc.png)

![我的notion](https://user-images.githubusercontent.com/34064977/202652725-692b36b1-7f7e-43df-a870-0f647b1a25a1.png)

**环境**

- 操作系统: Windows
- 浏览器 : Edge

**Comment by tangly1024** [comment]
请提供一下你的 notionpageid

**Comment by XcloudFance** [comment]
> 请提供一下你的 notionpageid

ca59b945421d4d908eb0331accc8423d?v=3ec22f1013f74404b0168e445e7fb0de

**Comment by tangly1024** [comment]
# PageId的格式有误
你的notion-page-id格式有误：
> ca59b945421d4d908eb0331accc8423d?v=3ec22f1013f74404b0168e445e7fb0de

## 问题
需要将后面的     `?v=3ec22f1013f74404b0168e445e7fb0de` 这部分去掉，

## 如何正确配置
正确的NotionPageId只需要配置 `ca59b945421d4d908eb0331accc8423d`  这一串就足够了


# 另外的提示
你的第一篇博文没有开启共享权限，在网站上可能无法显示：

<img width="1089" alt="图片" src="https://user-images.githubusercontent.com/15920488/202723990-dd9efee1-186d-49e7-9b38-dc50593ba410.png">

**Comment by XcloudFance** [comment]
> # PageId的格式有误
> 你的notion-page-id格式有误：
> 
> > ca59b945421d4d908eb0331accc8423d?v=3ec22f1013f74404b0168e445e7fb0de
> 
> ## 问题
> 需要将后面的 `?v=3ec22f1013f74404b0168e445e7fb0de` 这部分去掉，
> 
> ## 如何正确配置
> 正确的NotionPageId只需要配置 `ca59b945421d4d908eb0331accc8423d` 这一串就足够了
> 
> # 另外的提示
> 你的第一篇博文没有开启共享权限，在网站上可能无法显示：
> 
> <img alt="图片" width="1089" src="https://user-images.githubusercontent.com/15920488/202723990-dd9efee1-186d-49e7-9b38-dc50593ba410.png">

OKOK,  我的问题不好意思，谢谢解答！
