### ISSUE TITLE
【Hexo主题】首页布局引导语

### ISSUE THREAD

**Issue by sorabug** [tangly1024/NotionNext#466]
我想把next主题的开头的样式回到原来的居中应该怎么改回去，之前是图二这种样式
![1](https://user-images.githubusercontent.com/45709238/202742702-b3d0e6d3-2e37-4f2c-afbc-02eeb9d71cb0.png)
![2](https://user-images.githubusercontent.com/45709238/202742713-9049f639-c0e1-4596-ac41-198aec7c44b9.png)

**Comment by tangly1024** [comment]
设计的时候是希望居中的，这里显示偏上 不符合预期的效果，我调整一下

**Comment by tangly1024** [comment]
功能已更新
https://github.com/tangly1024/NotionNext/releases/tag/v3.6.0
