### ISSUE TITLE
【页面跳转】其他页面跳转到首页未生效

### ISSUE THREAD

**Issue by OctalZero** [tangly1024/NotionNext#471]
**描述bug**
其他页面通过底部跳转到首页会没有反应，但是可以通过首页跳转到其他页面，并且能够在其他页面正常跳转

**复现步骤**
从其他页面的底部选择 1，挑转到首页，不生效

**期望的正常结果**
应该能够直接跳转到首页

**截图**
![image](https://user-images.githubusercontent.com/75478802/202841722-47abbcb5-b2c8-426c-b3f1-7c72e03bf55a.png)

**环境**

- 操作系统: [windows]
- 浏览器 [chrome]
- 版本 [e.g. 22]

**补充说明**
应该是跳转机制的实现出问题了，跳转应该是通过 url 中的 page 进行跳转，首页可能没有设置 page

**Comment by tangly1024** [comment]
已提交修复补丁 https://github.com/tangly1024/NotionNext/pull/475 ，升级代码到最新版即可体验
