### ISSUE TITLE
【文章报错】undefined is not iterable 在 Vercel 中配置 NEXT_PUBLIC_THEME 环境变量后，打开博客文章页报错

### ISSUE THREAD

**Issue by nanvon** [tangly1024/NotionNext#472]
**描述bug**
Vercel 内配置环境变量：NEXT_PUBLIC_THEME 为 medium
部署后打开[博客](https://www.nanvon.cn)，此时未报错，点击进入任意文章，文章显示正常，大概1秒后，屏幕只显示如下一行信息：
```
Application error: a client-side exception has occurred (see the browser console for more information).
```
控制台报错见下方截图

**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
![image](https://user-images.githubusercontent.com/36064282/202841725-dbaa6b59-762e-45de-93d0-40ec235b385c.png)
![image](https://user-images.githubusercontent.com/36064282/202841870-22e680dd-105e-4ae6-bffa-b02d38602d70.png)

**环境**

- 操作系统: windows 10
- 浏览器 chrome, edge
- 版本 107, 107

**补充说明**
我将环境变量全删掉，逐一添加后，才发现是配置主题环境变量 NEXT_PUBLIC_THEME 导致的问题。

**Comment by tangly1024** [comment]
hello，根据你的描述，我刚提交了一个补丁 https://github.com/tangly1024/NotionNext/pull/474 ， 请将代码升级到最新版，再试试看问题是否还会出现

感谢你的反馈.

**Comment by nanvon** [comment]
@tangly1024 问题已解决。辛苦~
