### ISSUE TITLE
【搜索功能】搜尋功能英文大小寫結果不同

### ISSUE THREAD

**Issue by nagongze** [tangly1024/NotionNext#473]
**截圖**
<img width="849" alt="CleanShot 2022-11-19 at 19 12 55" src="https://user-images.githubusercontent.com/68653451/202847860-d92305f8-eab0-4414-8f34-07f5a0197de9.png">
<img width="849" alt="CleanShot 2022-11-19 at 19 13 25" src="https://user-images.githubusercontent.com/68653451/202847875-cbfc5c3f-01ce-4e4e-a7fa-a9157cd57199.png">
<img width="857" alt="CleanShot 2022-11-19 at 19 13 55" src="https://user-images.githubusercontent.com/68653451/202847902-fcfb3a04-1f2c-4f1f-a963-dd32ba36a877.png">
![CleanShot 2022-11-19 at 19 14 51](https://user-images.githubusercontent.com/68653451/202847947-d18a8a96-5126-405c-8a2c-79263c1ef083.png)
<img width="361" alt="CleanShot 2022-11-19 at 19 15 11" src="https://user-images.githubusercontent.com/68653451/202847956-7d9539cb-b617-45dc-91d3-694609c7cc09.png">

**期望的正常结果**
例圖所示，我實際有關鍵字的文章總共有六篇，但每個結果都不一樣，希望可以不管輸入ray Ray RAY都能找到文章結果

**Comment by tangly1024** [comment]
最新版本中已支持 该功能
