### ISSUE TITLE
【搜索功能】搜索一个字符的时候显示异常

### ISSUE THREAD

**Issue by Ylarod** [tangly1024/NotionNext#479]
**描述bug**

搜索的时候只填一个字符/汉字会显示异常
1. 出现html代码
2. 简介变为文章的部分内容，而且没有格式

<img width="1209" alt="截屏2022-11-20 09 24 11" src="https://user-images.githubusercontent.com/30978685/202878289-75a50e21-3bcc-4141-994a-a7f0c565ef31.png">

**复现步骤**
搜索的时候只填一个字符/汉字

**期望的正常结果**
出现对应的文章
<img width="643" alt="截屏2022-11-20 09 25 48" src="https://user-images.githubusercontent.com/30978685/202878316-f4a9cba4-28cf-4ae5-806b-11bc484258d6.png">

**Comment by SwwweetOrange** [comment]
问题应该是直接替换搜索结果的innerHTML导致的，可以把这个issue分配给我吗，我可以提交一个PR修复它

**Comment by tangly1024** [comment]
> 问题应该是直接替换搜索结果的innerHTML导致的，可以把这个issue分配给我吗，我可以提交一个PR修复它

非常感谢 ♥️，这当然可以 🙏

**Comment by SwwweetOrange** [comment]
> > 问题应该是直接替换搜索结果的innerHTML导致的，可以把这个issue分配给我吗，我可以提交一个PR修复它
> 
> 非常感谢 ♥️，这当然可以 🙏

PR已经提交，可以帮忙review一下代码 #522
