### ISSUE TITLE
【字体加载】本地字体提升网站加载速度

### ISSUE THREAD

**Issue by tangly1024** [tangly1024/NotionNext#491]
**为什么提出这个新的特性改动**
来自讨论组 https://github.com/tangly1024/NotionNext/discussions/453

**Comment by SwwweetOrange** [comment]
我看了一下现有的字体库应该都是挂载在cdn上的，配合上缓存设置，按理来说第二次打开就不会有特别长的延时，这个地方的本地加载字体要怎么做呢

**Comment by tangly1024** [comment]
是的，如您所言：第二次打开是不会有加载字体的延时的；最近我关注到也许有别的原因导致页面会处于持续加载的状态，我会持续跟进；

另外，关于本地加载字体，在 Nobelium中，font字体是放在项目中的public目录下 ： https://github.com/craigary/nobelium/tree/main/public/fonts 目录下，这样可以避免加载远程css。然而即使如此，如果用的是庞大的中文字体，也无法避免“首次打开页面时字体css对网站速度的拖慢”。

关于字体加载的速度优化，我在考虑用这种方式彻底优化：https://maxket.com/web-font-optimization-for-chinese-pages/

**Comment by tangly1024** [comment]
新版本中，已将fontjs引入到代码本地中
