### ISSUE TITLE
更新了3.6 代码框bug

### ISSUE THREAD

**Issue by wxyhgk** [tangly1024/NotionNext#495]
有时候显示代码的行数,有时候不显示,有时候乱了

不显示代码行数
![image](https://user-images.githubusercontent.com/37659181/203464406-a1d4c476-6716-4da5-9fb9-7647f267d2fa.png)

乱了
![image](https://user-images.githubusercontent.com/37659181/203464466-dfe3d32d-b1ec-4a90-a51c-1fd516a7f893.png)

**Comment by tangly1024** [comment]
嗨，3.6.0版本发布后有在2022-11-21提交了几个版本的hotfix补丁修复了此问题：
<img width="1248" alt="图片" src="https://user-images.githubusercontent.com/15920488/204092021-1efdd14b-b292-4b5b-87e1-c503bd2e3876.png">


可以尝试查看：
https://preview.tangly1024.com/

**Comment by chwl66** [comment]
> 

刚才查看了修复了的网页，还是存在不显示行数的问题，切换主题后就显示了！

**Comment by wxyhgk** [comment]
还是有问题

**Comment by tangly1024** [comment]
在刚提交的最新补丁中修复了此问题：

https://github.com/tangly1024/NotionNext/pull/508

https://preview.tangly1024.com/article/example-1

**Comment by wxyhgk** [comment]
> 在刚提交的最新补丁中修复了此问题：
> 
> #508
> 
> https://preview.tangly1024.com/article/example-1

感谢作者

**Comment by wxyhgk** [comment]
> 在刚提交的最新补丁中修复了此问题：
> 
> #508
> 
> https://preview.tangly1024.com/article/example-1

似乎依旧有bug,有些命令无法显示

<img width="716" alt="image" src="https://user-images.githubusercontent.com/37659181/204123313-68397f67-eeb6-4206-8e2c-c29ae205cab1.png">

<img width="709" alt="image" src="https://user-images.githubusercontent.com/37659181/204123363-b9e730d7-2921-4d8e-8491-8c1d32037958.png">

**Comment by tangly1024** [comment]
已在最新的 [v3.6.1 版本](https://github.com/tangly1024/NotionNext/releases/tag/v3.6.1)中修复此特性

体验页面 ：https://preview.tangly1024.com/article/example-1#349808ed27944012a180f278295b7714

**Comment by wxyhgk** [comment]
> 已在最新的 [v3.6.1 版本](https://github.com/tangly1024/NotionNext/releases/tag/v3.6.1)中修复此特性
> 
> 体验页面 ：https://preview.tangly1024.com/article/example-1#349808ed27944012a180f278295b7714

谢谢,没问题了
