### ISSUE TITLE
在嵌入 codepen 块时两侧被隐藏

### ISSUE THREAD

**Issue by yuzhanglong** [tangly1024/NotionNext#50]
优秀的项目！

体验后发现一个 bug，使用 iframe 时两侧会被隐藏，next 主题。
<img width="923" alt="image" src="https://user-images.githubusercontent.com/56540811/153896935-c3a49708-515c-4ac8-8b79-b7671d977d2f.png">

**Comment by tangly1024** [comment]
感谢你对该项目的认可😆

## 如何复现
是如何使用Iframe的呢，可以的话提供一下代码，我才好调试😆
![image](https://user-images.githubusercontent.com/15920488/153981178-8cc1b0e9-41c7-4171-b598-6de720e67ab6.png)

## 提示
为了排版整洁，博客左右两侧的组件都做了响应式处理，仅在窗口宽度大于1024px时才会显示。
参考代码：
(SideAreaLeft.js)[https://github.com/tangly1024/NotionNext/blob/main/themes/NEXT/components/SideAreaLeft.js] 的第24行
(SideAreaRight.js)[https://github.com/tangly1024/NotionNext/blob/main/themes/NEXT/components/SideAreaRight.js] 的第33行

```
className='hidden lg:block flex-col w-60 mr-4'
```

相关文档 [TailwindCSS-响应式](https://www.tailwindcss.cn/docs/responsive-design)

**Comment by yuzhanglong** [comment]
> 感谢你对该项目的认可😆
> 
> ## 如何复现
> 是如何使用Iframe的呢，可以的话提供一下代码，我才好调试😆 ![image](https://user-images.githubusercontent.com/15920488/153981178-8cc1b0e9-41c7-4171-b598-6de720e67ab6.png)
> 
> ## 提示
> 为了排版整洁，博客左右两侧的组件都做了响应式处理，仅在窗口宽度大于1024px时才会显示。
> 
> ```
> className='hidden lg:block'
> ```
> 
> 实现方式参考 [TailwindCSS文档-响应式](https://www.tailwindcss.cn/docs/responsive-design)
> 
> 项目中对应的代码： [!SideAreaLeft.js](https://github.com/tangly1024/NotionNext/blob/main/themes/NEXT/components/SideAreaLeft.js) 的第24行 [!SideAreaRight.js](https://github.com/tangly1024/NotionNext/blob/main/themes/NEXT/components/SideAreaRight.js) 的第33行
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/56540811/153982416-a856e616-a1fb-45ec-bdbd-cba4218fe5a9.png">

此链接可复现（拖到最底下）：https://blog.yuzzl.top/article/how-frontend-monitor-works-part-1

原 notion 文档：https://www.notion.so/yuzhanglong/web-fdf52e0669eb4360b9771163c38ec60c

**Comment by tangly1024** [comment]
奇怪的是，[我创建了一个codepen块](https://notion-next.tangly1024.com/article/example#fcf1b41edcd6408e9582117ef7876fed)，并且显示正常，并没有出现iframe的左右两端被隐藏😂
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/15920488/154007221-1cd05737-4e94-4bdd-aba2-0177997c28f6.png">

**Comment by yuzhanglong** [comment]
> 

嗯我现在也没问题了，应该是在notion 编辑的时候那个块拖动的太宽了，然后这边显示就出现了问题~
感谢你的帮助哈
