### ISSUE TITLE
在拉取V3.6.0版本，并合并自己的修改时，部署报错了

### ISSUE THREAD

**Issue by aron-xx** [tangly1024/NotionNext#503]
**描述遇到的问题**
我看到原作者更新部分内容，我就拉取到自己的仓库，然后更新了自己的配置文件。结果在vercel上部署遇到了致命错误。
*报错信息如下图所示：*
![chrome_3mWr3Yq3Uo](https://user-images.githubusercontent.com/52649364/203584319-98569b56-687d-43f3-bc32-d0a7b7d31ac7.png)

**相应配置**
我的网站：
https://www.spiderobot.top/

**截图**
![chrome_t8n8V55Pm8](https://user-images.githubusercontent.com/52649364/203587007-238a8bee-c9b0-4f7e-be39-0e6cc693389b.png)

**环境**

- 操作系统:windows10
- 浏览器 : chrome
- 版本 107.0

**Comment by tangly1024** [comment]
嗨，错误的原因是 在3.6.0 版本中 配置文件版本做了大的改动； 你的配置文件还是使用的旧版本导致不兼容。


# 解决
我已经向你的代码仓库中提交了 修复的PR： https://github.com/aron-xx/kiki-s-blog/pull/1

你只需要同意合并我的修改即可

**Comment by aron-xx** [comment]
😘😘😘😘😘
