### ISSUE TITLE
【Mermaid渲染】支持思维导图 、饼图 、 甘特图

### ISSUE THREAD

**Issue by tangly1024** [tangly1024/NotionNext#511]
https://mp.weixin.qq.com/s/LGb-13wwZEcp5yKo_3APwQ

**Comment by jarlin8** [comment]
pie图也希望支持一下哟

**Comment by tangly1024** [comment]
已在[v3.6.1](https://github.com/tangly1024/NotionNext/releases/tag/v3.6.1)版本中支持了思维导图、pie图、甘特图等特性;

体验页面： https://notionnext-5ymk2gp44-tlyong1992.vercel.app/article/example-1#32a7b6a9e1ba44a5982fa055f5b01366
