### ISSUE TITLE
wolai支持

### ISSUE THREAD

**Issue by Durobert** [tangly1024/NotionNext#515]
你好，最近一直在看怎么使用wolai个人建站，wolai可以说是中国版的notion，因为wolai在本地化上比notion做的好，所以购买了wolai的会员，但是网上搜了很多，没有看到像notion这样可以使博客界面像作者这样丰富多彩，作者是否可以在代码中增加wolai的支持，这样的话，对国内wolai用户是一个利好，也可以让更多的人使用作者的框架。

**Comment by hi-nikola** [comment]
wolai 也可以实现吗？还没看到过

**Comment by tangly1024** [comment]
感谢您的提议！

很遗憾，尽管wolai的展现形式以及数据结构都与Notion很相似，但本质上不是同一个产品，要让NotionNext支持wolai有些困难：

- 首先，两者只是相似，但实现的api接口、页面样式等等都有很大的不同，开发并适配这些功能需要很大的工作量，凭借我一己之力几乎是做不到的。Notion能有今天的成就，离不开国外众多大神们的共同努力，大家热爱notion这款产品，并自发地为notion开发各式各样的插件、功能、扩展等等。

- 其次，我并非wolai的受众，我更习惯于在notion上维护我的知识数据库，所以很可惜我没有开发适配wolai建站的理由。

也许未来随着wolai产品的不断完善，能够在国内甚至国际上大放异彩，一款名为 “WolaiNext”的项目就自然诞生了。

最后，感谢您对 NotionNext项目的关注，祝您好运，祝wolai好运~
