### ISSUE TITLE
[v3.6.0]代码块显示不完整

### ISSUE THREAD

**Issue by fatekey** [tangly1024/NotionNext#520]
**描述bug**
渲染出来的代码块有时比 notion 原本的代码块里的内容缺少一部分。如
![image](https://user-images.githubusercontent.com/32138014/205233089-9c6c1214-2bff-4fd1-9b13-15b25ac8c815.png)
![image](https://user-images.githubusercontent.com/32138014/205233156-c83a0a37-4ad0-4a09-b6a8-5b6d076c5339.png)
少了开始的┌──
![image](https://user-images.githubusercontent.com/32138014/205233292-773a2ffc-daf7-49f8-96b4-cc37fdbe4582.png)
![image](https://user-images.githubusercontent.com/32138014/205233357-680b5661-d018-41ba-8c16-c940e1aa31e9.png)
这个直接少了开始的一行
**复现步骤**
创建代码块，语言为 bash，贴入以下内容
PORT     STATE SERVICE VERSION
3632/tcp open  distccd distccd v1 ((GNU) 4.2.4 (Ubuntu 4.2.4-1ubuntu4))
渲染后缺失第一行

**期望的正常结果**
代码显示完整

**截图**

**环境**

- 操作系统: macOS
- 浏览器 chrome

**补充说明**

**Comment by tangly1024** [comment]
hello 请尝试升级到v3.6.1版本，在最新版本中修复了代码显示的bug
