### ISSUE TITLE
【部署错误】v3.6.1 修改blog.config.js后部署时报错

### ISSUE THREAD

**Issue by IoriMaboroshi** [tangly1024/NotionNext#521]
如果不修改blog.config.js部署顺利
但一旦修改后就会报错编译失败

NotionPageID: a77c044aa3114463bb97180d2eaebb4a?v=c64e2a0660ff43a0b7c385cd8b8e8373
暂未部署成功

![22-12-03-134035](https://user-images.githubusercontent.com/117876175/205426228-c53d86a4-4bb4-42d4-b116-ba74b22aad51.png)

- 操作系统: Windows10
- 浏览器: Microsoft edge
- 版本: v3.6.1

**Comment by IoriMaboroshi** [comment]
更多报错截图补充
![22-12-03-134512](https://user-images.githubusercontent.com/117876175/205426282-78558a52-792b-48a1-9191-b82f6a310dc3.png)
![22-12-03-134541](https://user-images.githubusercontent.com/117876175/205426298-966b8428-e106-4393-af8e-6a6fb27ed7df.png)
![22-12-03-134558](https://user-images.githubusercontent.com/117876175/205426307-61754f3e-9221-477e-a88a-630109c2e9b1.png)
![22-12-03-134611](https://user-images.githubusercontent.com/117876175/205426311-94b0173b-c5c3-4c73-b449-082dfb04c028.png)

**Comment by tangly1024** [comment]
配置文件有误： 
参考此方式修改 https://github.com/IoriMaboroshi/NotionNext/compare/main...tangly1024:NotionNext:patch-2

**Comment by IoriMaboroshi** [comment]
修改后依旧报错...
在blog.config.js中如果不写NOTION_PAGE_ID
而在变量中配置NOTION_PAGE_ID
也会如此一样的报错
