### ISSUE TITLE
请问如何在自己的服务器部署？

### ISSUE THREAD

**Issue by DuckDuck88** [tangly1024/NotionNext#525]
运行代码后在哪里配置我的Notion page

**Comment by tangly1024** [comment]
嗨，这需要一篇完整的教程来说明，我会尽快发布相关文章。

**Comment by DuckDuck88** [comment]
好的，新文章发布后告诉我就更好啦。感谢～

**Comment by tangly1024** [comment]
请参考此篇教程

[《如何在自己的服务器部署NotionNext》](https://tangly1024.com/article/deploy-notion-next-on-vps)

**Comment by DuckDuck88** [comment]
感谢～
