### ISSUE TITLE
【代码块】代码配色、代码换行、代码块显示方式改进

### ISSUE THREAD

**Issue by expoli** [tangly1024/NotionNext#540]
**为什么提出这个新的特性改动**
1. 现阶段博客的代码部分的默认底色是深黑色，显示的时候看起来并不是很直观，尤其是注释部分。
- 博客配色
![image](https://user-images.githubusercontent.com/31023767/206095811-b423d05d-95fd-4305-acd0-e768ebae5e42.png)
- notion 配色
![image](https://user-images.githubusercontent.com/31023767/206095887-22009740-dde3-44ef-8c05-9a2a8ca84fe1.png)

2. 同时与 notion 的代码配色不同的是，有一些语言没有高亮配色，比如下面的汇编部分 
- 博客的显示
![image](https://user-images.githubusercontent.com/31023767/206095597-1a0c439b-bc58-44f4-be42-adea6f1d1eec.png)
- notion 内部的显示
![image](https://user-images.githubusercontent.com/31023767/206096206-06c2e2fb-1c95-47d8-98f7-b36c91e103a1.png)

3. 与 notion 不同的是 博客的代码块部分是将每一行显示的字符数量限定了，将超出的部分自动进行了换行处理，而且在前面还加入了不应该存在的行号。
比如下面的第一行的注释部分。我觉得可以参考 notion 的代码块的实现，当一行显示不完全的时候，提供一个行的拖动条，无需自动将代码进行折叠。
- 博客
![image](https://user-images.githubusercontent.com/31023767/206095597-1a0c439b-bc58-44f4-be42-adea6f1d1eec.png)
- notion
![image](https://user-images.githubusercontent.com/31023767/206096809-3d96981b-3f77-48fc-ac3b-67e8c7128d8c.png)

**描述一下你推荐的解决方案**
- 个人觉得这个部分可以改进一下，可以尝试添加一个可以自选代码配色方案的配置项。也可以直接把 notion 的代码配色方案直接搬过来？
- 对于代码块大小这部分，我看现在的代码块的大小是恒定的，当行数过多的时候，会自动加入列的滚动条（个人觉得如果代码比较长的话，直接全部显示是不是更好，这样的话还不需要上下滚动去查找一些代码，当然这也会让页面长度比较长，就类似于 notion 的代码块实现，提供横向的滚动条，纵向直接全部显示）

**描述一下你考虑过的其它替代解决方案**
是否能够使用这个代码高亮配置？
https://github.com/highlightjs/highlight.js
https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md

**补充说明**
补充与此特性相关的内容

**Comment by tangly1024** [comment]
感谢反馈
> 1. 现阶段博客的代码部分的默认底色是深黑色，显示的时候看起来并不是很直观，尤其是注释部分。
> 2. 同时与 notion 的代码配色不同的是，有一些语言没有高亮配色，比如下面的汇编部分

问题1和2 是因为，汇编语言在prismjs的渲染有点问题，我会尝试修复，

> 3.与 notion 不同的是 博客的代码块部分是将每一行显示的字符数量限定了，将超出的部分自动进行了换行处理，而且在前面还加入了不应该存在的行号。
> 比如下面的第一行的注释部分。我觉得可以参考 notion 的代码块的实现，当一行显示不完全的时候，提供一个行的拖动条，无需自动将代码进行折叠。


关于自动换行，的确notion的方式会更加直观。这个特性后续会更新。

**Comment by tangly1024** [comment]
更新一下：

关于自动换行的补充：
1. 单行代码过长导致一个代码框显示不下的情况下。如果在手机移动端 更偏向自动换行，要比横向滚动条方便的多 。
2. prismjs 中 显示行号的插件line-numbers 就必须开启换行，导致需要改动成横向滚动的方式变得困难。

**Comment by tangly1024** [comment]
后续版本会加入一个特性；

支持选择代码是换行显示还是横向滚动。

**Comment by zfhxi** [comment]
> 后续版本会加入一个特性；
> 
> 支持选择代码是换行显示还是横向滚动。

不知道后续是否会支持代码块选择成为亮色主题，比如说在 blog.config.js 里进行配置

**Comment by tangly1024** [comment]
> > 后续版本会加入一个特性；
> > 支持选择代码是换行显示还是横向滚动。
> 
> 不知道后续是否会支持代码块选择成为亮色主题，比如说在 blog.config.js 里进行配置

hi,最新版本支持了代码样式，并且默认为亮色主题，在此处可以自定义配置其它主题：
https://github.com/tangly1024/NotionNext/blob/c1fc29749b6e5ecb68ab2137ed7197511a41608c/pages/_app.js#L13

**Comment by tangly1024** [comment]
> 最新的 3.7.0 代码块的长度变成了与内容相关的，感觉非常奇怪，确定以后要这样实现嘛？ ![图片](https://user-images.githubusercontent.com/31023767/209488983-a5c530dd-f308-4bd8-bdc5-8e918edad32b.png)

不确定，只是一个尝试
