### ISSUE TITLE
【PDF模块显示】关于横向版面的PDF不能直接显示完整的画面，需要通过滑块左右移动

### ISSUE THREAD

**Issue by 274802235** [tangly1024/NotionNext#546]
**为什么提出这个新的特性改动**
PDF模块显示小问题

如果是横向版面的PDF，在BLOG不会自适应显示完整画面(会出现横向滑轨，需要左右滑动才能看到完整的画面），希望可以自动适应版面 直接显示完整的画面。

此问题也不是很重要，能解决就更完美啦~

BLOG测试链接：https://pdf-weld-ten.vercel.app/article/49169d94-791d-4c48-9398-0d13b00d33bf

NOTION原链接可以直接显示完整的画面：https://www.notion.so/Test1-a6271da06b8f47a39735e8fa770f1d9f#75cd9f2882de41f7a5f2af4e0055aaf1

![image](https://user-images.githubusercontent.com/82162031/206183761-5abb1982-0a71-457c-a97a-1ef2334ca9cc.png)

**描述一下你推荐的解决方案**

**描述一下你考虑过的其它替代解决方案**

**补充说明**

**Comment by tangly1024** [comment]
在 https://github.com/tangly1024/NotionNext/pull/550 已修复此问题。

**Comment by tangly1024** [comment]
进一步完善pdf样式
