### ISSUE TITLE
测试环境中能够正常部署成功，在生产环境中就无法部署

### ISSUE THREAD

**Issue by expoli** [tangly1024/NotionNext#547]
**描述bug**
测试环境中能够正常部署成功，在生产环境中就无法部署？直接失败了、直接使用最新的主分支也是这样

**复现步骤**
测试环境正常部署构建部署成功，一旦部署至生产环境中就 Error 错误。

**期望的正常结果**
生产环境中也可正常部署

**截图**
点击部署至生产环境中就构建错误
![image](https://user-images.githubusercontent.com/31023767/206186803-7c106341-f161-4249-86fb-d5d6a24c7b8b.png)

我的分支：https://github.com/expoli/NotionNext

猜测与博客配置文件中的检测生产环境的环境变量 isprod 有关 

![image](https://user-images.githubusercontent.com/31023767/206187294-91019155-152b-4433-a090-b26560f2aab6.png)

**环境**

- 操作系统: [iOS, Android, macOS, windows]
- 浏览器 [firefox]
- 版本 [主分支代码]

**补充说明**
与问题相关的其它说明

**Comment by Ylarod** [comment]
相同问题

**Comment by tangly1024** [comment]
感谢反馈问题；感谢 @Ylarod  提交的修复；
更新至最新代码，即可编译成功。
