### ISSUE TITLE
希望能加入notion数据库中的日历模式

### ISSUE THREAD

**Issue by ohjoij-ys** [tangly1024/NotionNext#557]
**为什么提出这个新的特性改动**

目前notion中数据库中的日历模式无法正常识别，notion的日历规划很方便
![image](https://user-images.githubusercontent.com/119778444/206382096-c7a38bc0-8f42-44c4-ac8b-e41396d05923.png)

**描述一下你推荐的解决方案**

在修复完数据库的日历模式后，如果能直接在首页添加模块映射日历，我觉得应该挺好的，或者首页添加个热力图插件也可以

**描述一下你考虑过的其它替代解决方案**
导航栏添加日历文字，点击后进入帖子，里面是notion数据库的日历视图

**补充说明**
补充与此特性相关的内容

**Comment by SwwweetOrange** [comment]
日历目前在底层库react-notion-x中还没有支持， 可以看[issue](https://github.com/NotionX/react-notion-x/issues/36)😂，已经过了一年多作者还没有完成，估计短时间内不会有，可以尝试提一个PR

**Comment by ohjoij-ys** [comment]
> 日历目前在底层库react-notion-x中还没有支持， 可以看[问题](https://github.com/NotionX/react-notion-x/issues/36)😂，已经过了一年多作者还没有完成，估计短时间内不会有，可以尝试提一个PR

好的，谢谢
