### ISSUE TITLE
生产环境中构建部署的时候、解析带有 Github 链接的 page 时出错

### ISSUE THREAD

**Issue by expoli** [tangly1024/NotionNext#561]
**描述遇到的问题**
测试环境中构建正常、生产环境中构建失败、看出错日志是在解析 GitHub 链接的页面时出错了？
![image](https://user-images.githubusercontent.com/31023767/206440213-f981bdd5-7d63-4dd1-a980-84157024a132.png)

**相应配置**
https://expoli.tech

**截图**
![image](https://user-images.githubusercontent.com/31023767/206440640-2c115f64-0693-4173-91b1-a0d389786e6d.png)

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [最新的 main 分支]

**Comment by tangly1024** [comment]
尝试更新到最新的3.6.4版本 看是否还有此错误出现

**Comment by tangly1024** [comment]
能否提供一下 相关的notion页面信息呢， 我需要尝试复现此bug

**Comment by tangly1024** [comment]
感谢反馈，问题在最新的提交中已经修复 https://github.com/tangly1024/NotionNext/commit/fbce1f079b78958ad50a18f885a5705385e31e96
