### ISSUE TITLE
【Waline评论】近期评论跨域、无法加载

### ISSUE THREAD

**Issue by expoli** [tangly1024/NotionNext#565]
**描述bug**
开启近期评论之后、发现近期评论并没有显示、查看网络请求发现是查看近期评论的 waline 请求出现了跨域问题、被浏览器禁止了
- 单独请求近期请求对应的 URL 接口是可以正常工作的。只是单纯的请求近期评论的接口存在跨域问题。文章页面里面的评论也是可以正常显示的。
![image](https://user-images.githubusercontent.com/31023767/206620062-807c68ff-735d-432e-8f5a-5902efe509ba.png)

**复现步骤**
开启 waline 近期评论

**期望的正常结果**
显示近期评论

**截图**
![image](https://user-images.githubusercontent.com/31023767/206619912-698a63d9-c1d0-499c-b17b-2ccc15a25f93.png)

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [3.6.3 3.6.4]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
hi，我注意到你的 waline地址中多了一个斜杆：xx.com//comment，路径错误是导致跨域的原因。

## 请修改waline_url配置

- 正确的配置waline 应当是 
`https://waline.exploli.tech`
而非
`https://waline.exploli.tech/`
