### ISSUE TITLE
【边栏显示】边栏显示异常

### ISSUE THREAD

**Issue by lifeafter619** [tangly1024/NotionNext#576]
**描述bug**
对不起但是，我又来了，这次发现边栏的一个bug
![image](https://user-images.githubusercontent.com/65111206/206822876-f3dad462-04f6-4a19-afa1-8f4283fbb579.png)

**复现步骤**
很明显，下面一个才是我在notion中设置的（图标不同）
![image](https://user-images.githubusercontent.com/65111206/206822929-e71e63f4-953f-4678-94dd-4db11d19989b.png)
上面的几个能否设置一下让大家选择是否显示？感觉有的用不到...

**期望的正常结果**
显示下方的“关于”

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
开关原先就支持的，修改`/themes/next/config_next.js`文件即可： 
https://github.com/tangly1024/NotionNext/blob/e46756a2e58bfc694bdf10d04f4a1200b1e86a35/themes/next/config_next.js#L22-L27

**Comment by tangly1024** [comment]
至于两个关于的问题，我会修复这个bug。

把系统自带的`关于`删除。

**Comment by tangly1024** [comment]
更新已提交。

**Comment by lifeafter619** [comment]
> 开关原先就支持的，修改`/themes/next/config_next.js`文件即可：
> 
> https://github.com/tangly1024/NotionNext/blob/e46756a2e58bfc694bdf10d04f4a1200b1e86a35/themes/next/config_next.js#L22-L27

噢噢，这....没注意到
但这些组件能排序不？
