### ISSUE TITLE
【自定义修改主题】在应用hexo主题时,下拉后怎么做不会遮挡背景呐

### ISSUE THREAD

**Issue by ke-xi** [tangly1024/NotionNext#577]
**描述遇到的问题**
问一个问题哈
这里绿色的地方和蓝色的地方应该互不影响吧,那么怎么把绿色的地方隐藏呐,拜托帮帮咱吧,在hexo文件夹里找半天不会弄,谢谢大佬了

**相应配置**
网站:https://kexi.ga/
https://github.com/ke-xi/NotionNext

**截图**
![Snipaste_2022-12-10_11-30-44.png](https://tva1.sinaimg.cn/large/005REQzJly1h8ykqxgj2aj31z413cx6p.jpg)
![Snipaste_2022-12-10_11-31-00.png](https://tva2.sinaimg.cn/large/005REQzJly1h8ykqyjy5lj31z413i7wi.jpg)
**环境**

- 操作系统: [windows]
- 浏览器 [edge]
- 版本 [108.0.1462.42]

**Comment by tangly1024** [comment]
绿色是 css 中的 padding 属性:
将 `/themes/hexo/LayoutBase.js`第62行的代码稍作调整即可：
https://github.com/tangly1024/NotionNext/blob/e46756a2e58bfc694bdf10d04f4a1200b1e86a35/themes/hexo/LayoutBase.js#L62

```
      <main id="wrapper" className="w-full py-8 md:px-8 lg:px-24 min-h-screen">
```
```

**Comment by ke-xi** [comment]
> 绿色是 css 中的 play 属性： 将 第62行的代码稍作调整即可：`/themes/hexo/LayoutBase.js`
> 
> https://github.com/tangly1024/NotionNext/blob/e46756a2e58bfc694bdf10d04f4a1200b1e86a35/themes/hexo/LayoutBase.js#L62
> 
> 原先：
> 
> ```
>       <main id="wrapper" className="w-full py-8 md:px-8 lg:px-24 min-h-screen">
> ```
> 
> 修改后：
> 
> ```
>       <main id="wrapper" className="w-full py-8 md:px-8 min-h-screen">
> ```
> 
> ## 说明
> * PX-8 表示横向边距8个单位
> * lg：px-24 表示在大屏幕的浏览器中横向边距24个单位

![Snipaste_2022-12-10_15-50-45.png](https://tva4.sinaimg.cn/large/005REQzJly1h8yrlhby14j31x613ix3m.jpg)
改了也没什么变化,想要实现上图的效果,好像很难哎,那就算了吧,谢谢啦

**Comment by IoriMaboroshi** [comment]
大佬可以讲讲修改css如何实现吗...
因为不是css语言，所以不知道怎么下手
想自己改一改主题

**Comment by ke-xi** [comment]
> 是希望背景图片始终固定在页面上，不随滚动条移出画面吗

对的,本来以为把白色调透明就可以了,但是好像没那么简单哎

**Comment by tangly1024** [comment]
> > 是希望背景图片始终固定在页面上，不随滚动条移出画面吗
> 
> 对的,本来以为把白色调透明就可以了,但是好像没那么简单哎



> 大佬可以讲讲修改css如何实现吗... 因为不是css语言，所以不知道怎么下手 想自己改一改主题

需要样式修改，简单的做法是在[styles/global.css](https://github.com/tangly1024/NotionNext/blob/main/styles/globals.css)中添加css内容。然后在代码中引用，举例：

- /styles/global.css
```
.custom-card {
  background-color: red;
}
```
- /themes/example/LayoutBase.js
```
<div className='custom-card'>
   xxx
</div>
```

- 更高级的做法 可以参考以下博文：在react中嵌入css的方式

https://juejin.cn/post/7089393721397116958

- 另外，项目引用的tailwindcss工具也十分好用，可以尝试体验一下
https://www.tailwindcss.cn/docs

**Comment by tangly1024** [comment]
> > 是希望背景图片始终固定在页面上，不随滚动条移出画面吗
> 
> 对的,本来以为把白色调透明就可以了,但是好像没那么简单哎

不太简单，html的页面布局也要改动才能支持(づ｡◕‿‿◕｡)づ

**Comment by IoriMaboroshi** [comment]
好的懂了 谢谢大佬

**Comment by ke-xi** [comment]
> > > 是希望背景图片始终固定在页面上，不随滚动条移出画面吗
> > 
> > 
> > 对的,本来以为把白色调透明就可以了,但是好像没那么简单哎
> 
> 不太简单，html的页面布局也要改动才能支持(づ｡◕‿‿◕｡)づ

好勒,完全放弃了,谢谢啦
