### ISSUE TITLE
输出到网页，显示有问题

### ISSUE THREAD

**Issue by hprandom** [tangly1024/NotionNext#578]
**描述bug**
一篇输出到 blog 的文章（也只有这篇文章），会有奇怪的大片空白存在，我猜可能是判定为图片了，可事实上 notion 原文中那里并没有任何东西。blog 开白处的上下文，在 notion 中是连续的。

**复现步骤**
我不知道怎么复现，但是我可以截图看。

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
notion 原文截图：
![prCYUg_tGn2lc](https://cdn.jsdelivr.net/gh/hprandom/pic@main/macOS/prCYUg_tGn2lc%20.png)
Blog 的显示效果：
![dNaaCS_9jdIEf](https://cdn.jsdelivr.net/gh/hprandom/pic@main/macOS/dNaaCS_9jdIEf%20.png)

**环境**

- 在 Chome Safari 上，都会出现这个问题。

**补充说明**
其他文章并没有这样的问题，只有这一篇……  会不会是因为那几个灯泡的缘故？
另外，空白处，鼠标指上去会有变成放大图标，看着像是那里有个图片，点击后也会把背景模糊掉，可事实上什么都没显示。

**Comment by tangly1024** [comment]
提供一下notion页面以及网页地址

**Comment by hprandom** [comment]
已通过邮件发到您的邮箱，是通过proton.me 的邮箱发送的。

**Comment by tangly1024** [comment]
hi，查看之后发现你的notion页面上有一个看不见的图片：
<img width="846" alt="图片" src="https://user-images.githubusercontent.com/15920488/206897816-bb0de6c4-320f-4ed7-9d81-90955785a64e.png">

请尝试一下能否删除它

**Comment by hprandom** [comment]
谢谢，确实有很多行的 [data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%2730%27%20height=%2730%27/%3e](data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%2730%27%20height=%2730%27/%3e)

可能是从 openai 那里复制过来的时候带过来的，不过 notion 中删除不了。我把它们都移到了最下方，不去管它们了。
