### ISSUE TITLE
【打包优化】多主题打包

### ISSUE THREAD

**Issue by liqun98** [tangly1024/NotionNext#582]
**为什么提出这个新的特性改动**
之前的模块打包优化过程中，注意到NotionNext的包结构，把四个主题都包括进去了，这在Debug的时候确实很好用，但是实际使用时大部分用户应该只会看一种主题的文件，是不是可以考虑在开发模式时将四个主题都进行打包，而实际生产环境部署只使用一种主题方案，考虑到未来可能会有更多的主题加入，如果依旧采取当前这种打包方式，可能会使包体积不断膨胀，进而损害了用户体验。
***client打包文件***
<img width="1440" alt="截屏2022-12-10 16 32 12" src="https://user-images.githubusercontent.com/71168966/206841340-35f0b225-18f0-4747-b151-dd73aac4f2be.png">

**描述一下你推荐的解决方案**
通过修改webpack打包配置，在开发环境包括全量主题，生产环境只打包配置的特定主题
或者将配置主题直接引入，其他主题动态引入的方式，进行更细致的分包

**描述一下你考虑过的其它替代解决方案**

**补充说明**
补充与此特性相关的内容

**Comment by SwwweetOrange** [comment]
这几个包确实很大，不过现在用动态引入的方式，应该也是和主包进行了分离，只有在需要的时候才会请求对应的组件，感觉和外部加载速度应该差别不大吧。
还有一个想法就是能不能将组件的一些共有配置抽离出来，这样修改一个地方就能反馈到多个模板上，不需要针对每个模板都修改一次
