### ISSUE TITLE
【toggle header 样式错误】标题前的标识符号与题目不在同一个位置，同时博客目录信息显示错误

### ISSUE THREAD

**Issue by expoli** [tangly1024/NotionNext#589]
**描述bug**
1. Notion toggle header 样式错误
2. 同时使用 toggle header  的时候右侧目录里 toggle header 相关信息也显示错误（位置错误）

**复现步骤**
随意一个 toggle header 样式

**期望的正常结果**
1. toggle header 的文字应该与 三角下拉箭头在一个位置，把标题的文字显示出来、现在是错了一行的位置
2. 目录顺序显示正常

**截图**
- 标题样式错误
![image](https://user-images.githubusercontent.com/31023767/207011845-37f71cab-ddf2-45f5-8f31-d770e973b1a5.png)
- 目录显示错误
![image](https://user-images.githubusercontent.com/31023767/207013710-4db60578-6081-4156-84d3-f088ad88f52b.png)

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
notion 文章链接：https://magnificent-borogovia-21b.notion.site/PDF-pdf-tocgen-f03fa56b459f4d7d85aeaf023a9d3858
博客文章链接：https://www.expoli.tech/articles/2022/12/12/tools-pdf.tocgen

**Comment by tangly1024** [comment]
感谢反馈！
