### ISSUE TITLE
【新主题】Matery

### ISSUE THREAD

**Issue by wxyhgk** [tangly1024/NotionNext#596]
主题样式如图,这是我原来的hexo博客 [wxyhgk.gitee.io](url)

## 首页
看起来很大气
![image](https://user-images.githubusercontent.com/37659181/207308916-b888c5bb-ec77-40d0-8225-a9a70c85a4fa.png)

## 文章页
文章页中文章处在中间,右边是目录,看起来更加舒服
![image](https://user-images.githubusercontent.com/37659181/207308714-f496ba19-6f52-4c44-a824-d5e7900dc67a.png)

**Comment by tangly1024** [comment]
感谢你推荐的这个主题，我已经在最新的3.8.0版本中上线。实际效果很不错，我非常喜欢，并且作为我的第一主题在使用。
感谢分享。

**Comment by wxyhgk** [comment]
> 感谢你推荐的这个主题，我已经在最新的3.8.0版本中上线。实际效果很不错，我非常喜欢，并且作为我的第一主题在使用。
> 感谢分享。

看了下目录显示部分有bug,目录部分的css可以看 hexo 博客的 fluid 主题 https://github.com/fluid-dev/hexo-theme-fluid

还有就是去掉下拉动画,这个会感觉卡顿

**Comment by tangly1024** [comment]
感谢反馈！
目录和下拉卡顿的问题我也有发现，在昨天有提交了补丁修复，可以更新代码查看效果，或者直接访问[我的主页](https://tangly1024.com)查看。

**Comment by wxyhgk** [comment]
> 感谢反馈！
> 目录和下拉卡顿的问题我也有发现，在昨天有提交了补丁修复，可以更新代码查看效果，或者直接访问[我的主页](https://tangly1024.com)查看。

似乎还是有问题,目录设计不合理,看这个动图

![iShot_2022-12-28_23 04 39](https://user-images.githubusercontent.com/37659181/209832234-d57684b7-6ca6-4823-8ebb-97a2bed1ee3c.gif)

**Comment by SkysCrystal** [comment]
我发现该主题的首页文章顺序，是按照 Notion 数据库页面先后顺序竖排的？我认为横排可能更好吧~
