### ISSUE TITLE
文章访问次数，刷新一次，+2

### ISSUE THREAD

**Issue by tobemaster56** [tangly1024/NotionNext#600]
**描述bug**
新博客，刚刚开张，应该只有我自己访问，文章访问次数，现在刷新一下，就+2，不应该是+1吗
**复现步骤**

**期望的正常结果**
+1，不是加2

**截图**
文章访问次数有问题
链接：https://lusun.com/v/Ka4hC1zrlT6

**Comment by tangly1024** [comment]
感谢反馈，显然一个bug，将尽快修复

**Comment by tangly1024** [comment]
已修复此问题

**Comment by tobemaster56** [comment]
👍，已经好了，🙏，速度给力
