### ISSUE TITLE
【问题反馈】Hexo主题如何隐藏首页分类导航按钮，归档页面夜间模式配色

### ISSUE THREAD

**Issue by sorabug** [tangly1024/NotionNext#614]
为什么提出这个新的特性改动
『我不是很喜欢现在的样式，想要和之前使用的next主题一样』
描述一下你推荐的解决方案
我想要在有**category**不在这里显示，就和之前一样，是否能加一个开关的配置，或者告诉我怎么改吗？
![4](https://user-images.githubusercontent.com/45709238/208235007-b6aa4db3-9033-453a-8053-c753622ab939.png)

**Comment by tangly1024** [comment]
可以在此处修改：
https://github.com/tangly1024/NotionNext/blob/a07bf51cb52de4f0be6cd2c05ee4c8491e41be9f/themes/hexo/config_hexo.js#L5

将true改为false即可

**Comment by sorabug** [comment]
> 可以在此处修改：
> 
> https://github.com/tangly1024/NotionNext/blob/a07bf51cb52de4f0be6cd2c05ee4c8491e41be9f/themes/hexo/config_hexo.js#L5
> 
> 将true改为false即可

好的，改了就可以了，谢谢

**Comment by sorabug** [comment]
我发现了时间轴的夜间模式，似乎不是全黑的，这个是bug还是特性
![image](https://user-images.githubusercontent.com/45709238/208236982-703f39f9-9ea3-4a07-a7c7-6b7dadb37dd2.png)

**Comment by tangly1024** [comment]
是个bug，感谢反馈
