### ISSUE TITLE
关于sitemap.xml文件内url的"/"被转义成“%2”

### ISSUE THREAD

**Issue by Hscpro** [tangly1024/NotionNext#616]
**描述bug**
sitemap.xml文件内url的"/"被转义成“%2”

**复现步骤**
访问生成的sitemap.xml

**期望的正常结果**
“%2”应为"/"

**截图**
![image](https://user-images.githubusercontent.com/13926044/208244028-96d521ea-d494-493c-99e9-8c38ec06f50c.png)
![image](https://user-images.githubusercontent.com/13926044/208244295-27820fd2-1adb-43e4-9e48-d2f1e0c6fe20.png)

**补充说明**
简单分析或许是生成的文件“article”应该是一个文件夹，但实际情况是 article 与文章短链进行了合并生成一个文件，或许会导致 sitemap 包对"/"进行转义（文件名不允许"/"），但还不明sitemap文件url里含“%2”会不会对搜索引擎抓取产生影响。

**Comment by tangly1024** [comment]
嗨， 很感谢你的反馈，
sitemap中出现 ‘%2’ 很明显不是我们想要的预期结果，无论是否会对搜索引擎产生影响，这个bug都应被修复。
