### ISSUE TITLE
【音乐自动暂停播放】自动播放开启后，打开多个页面、音乐重音；希望切换标签后自动暂停播放

### ISSUE THREAD

**Issue by expoli** [tangly1024/NotionNext#679]
**描述bug**
在打开播放器的自动播放时，打开多个页面、多个页面会同时播放导致重音

**复现步骤**
启用播放器、并开启自动播放

**期望的正常结果**
启用播放器、并开启自动播放，打开多个页面只有激活活动的浏览器标签页播放音乐

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 3.8.0]

**补充说明**
与问题相关的其它说明

**Comment by lifeafter619** [comment]
播放器使用meting，能默认不显示歌词么，遮挡内容了

**Comment by lifeafter619** [comment]
可能这个issue会有所帮助
https://github.com/DIYgod/APlayer/issues/725

**Comment by oeyoews** [comment]
> 播放器使用meting，能默认不显示歌词么，遮挡内容了

![image](https://user-images.githubusercontent.com/72405338/211299013-58b3e050-cb30-4aa3-9d17-ac7dcf51ef83.png)

我记得是这个
