### ISSUE TITLE
[修改站点标题] 希望博客标题优先读取配置、而不是Notion的标题

### ISSUE THREAD

**Issue by JossSong** [tangly1024/NotionNext#680]
**描述bug**
简单说明bug的现象、相关的错误提示、日志等

**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
设计是优先读取Notion标题；
若要 优先读取代码，则可以 参考此处修改：

https://github.com/tangly1024/NotionNext/compare/main...demo/notion-title

具体代码行数：

https://github.com/tangly1024/NotionNext/blob/80975b82c8263c9b424693b29eec3aedd82f6422/lib/notion/getNotionData.js#L126-L127

**Comment by tangly1024** [comment]
如何修改站点信息，请访问 [操作手册](https://tangly1024.com/article/notion-next-guide) 获取帮助
