### ISSUE TITLE
【如何更新代码】关于如何更新库到作者最新的库

### ISSUE THREAD

**Issue by lanhuakai** [tangly1024/NotionNext#688]
**描述遇到的问题**
我现有的网站样式还是很久之前fork的作者的库，请问如何更新到作者最新的库？怎么操作？

**Comment by lanhuakai** [comment]
是不是点击我的库里的  syrn fork？

**Comment by lanhuakai** [comment]
@tangly1024

**Comment by lanhuakai** [comment]
@expoli 更新后我个人修改的一些代码是不是就被覆盖了？需要重新修改？

**Comment by SkysCrystal** [comment]
> @expoli 更新后我个人修改的一些代码是不是就被覆盖了？需要重新修改？

可以看看这两篇博文，希望有所帮助。  
1. [NotionNext更新指南](https://tangly1024.com/article/how-to-update-notionnext) 
2. [手动 NotionNext 版本更新教程](https://www.dsuper.xyz/article/notionnext_update_221228) 有代码冲突的详细操作参考。
