### ISSUE TITLE
【toggle header 样式错误】标题前的标识符号与题目不在同一个位置，同时博客目录信息显示错误

### ISSUE THREAD

**Issue by expoli** [tangly1024/NotionNext#689]
与原来的这个 issue 一样

https://github.com/tangly1024/NotionNext/issues/589#issue-1491440259

3.8.1 这个问题又再次出现了。
问题文章：https://www.expoli.tech/articles/2022/12/12/tools-pdf.tocgen.html#3255f09a46be42d1baccdeee354c23f0

截图：
![图片](https://user-images.githubusercontent.com/31023767/211300137-49276858-aac9-44e3-bb62-8e8ce57aab4a.png)

我的 fork 链接：https://github.com/expoli/NotionNext

- 版本 [e.g. 3.8.1]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
已提交修复补丁，更新体验
