### ISSUE TITLE
''目录''菜单 没有翻译

### ISSUE THREAD

**Issue by staofr** [tangly1024/NotionNext#691]
**目录 没有翻译**
目录 这个菜单  在任何语言下 都是中文  并没有转换成本地语言

**如图这里**
![63bd4e2982826](https://user-images.githubusercontent.com/101335940/211543806-3da82f90-c9c0-4d58-a757-632d53053f15.png)

**Comment by tangly1024** [comment]
感谢反馈，最新版本已修复此问题 https://github.com/tangly1024/NotionNext/commit/79dcb0d78ad1f6fb7b3260b9986f8b2c8c8c1ee3
