### ISSUE TITLE
【Sitemap】Google Search Console 提交 sitemap 提示 Couldn't fetch

### ISSUE THREAD

**Issue by SkysCrystal** [tangly1024/NotionNext#697]
**描述bug**

在 Google Search Console 提交 https://www.dsuper.xyz/sitemap.xml 报错，Google 搜索站点链接仅收录博客首页。
![image](https://user-images.githubusercontent.com/49473463/212548988-4d19aeb2-9a1f-4cd4-bec1-9ab0d0667cd8.png)

提交百度站点无法收录。

**复现步骤**
在相应网站提交。[Google search console](https://search.google.com/search-console)

**期望的正常结果**
没有报错，博客文章可以搜索。

**截图**
见上

**环境**
Chrome

**补充说明**
无

**Comment by tangly1024** [comment]
sitemap.xml是动态生成的，首次生成会有延时；因此一开始会显示无法抓取，稍等一会就会自动显示为抓取成功。

<img width="901" alt="图片" src="https://user-images.githubusercontent.com/15920488/213202508-2f364767-ee2e-47b1-8968-4d568e880e9a.png">

**Comment by SkysCrystal** [comment]
我在地址最后加了个 `/` 目前能读取了（不知道为什么但是有效），谢谢！

![image](https://user-images.githubusercontent.com/49473463/213334857-adaf1497-6134-4e58-9c65-34f4b91b18ff.png)

**Comment by fatekey** [comment]
我也这样，几个月了来来回回删除添加几次了都不抓取，加/也不管用
