### ISSUE TITLE
【图片显示】自定义域名无法显示图片

### ISSUE THREAD

**Issue by eddiehe99** [tangly1024/NotionNext#698]
**描述bug**
在 Vercel 中添加自定义域名，blog 能打开，文章也能打开，除了图片不能显示之外，其他功能正常。
比如 Vercel 项目原本的域名是：domain.vercel.app，这个网址打开一切正常。
自定义的域名：www.selfdomain.com，这个网址能访问 blog，但是图片无法显示。

**复现步骤**
访问 [https://eddiehe.vercel.app/article/my-friend-had-settled-down](https://eddiehe.vercel.app/article/my-friend-had-settled-down) 可以正常显示图片。
但是访问使用自定义域名的同一篇文章 [https://www.eddiehe.xyz/article/my-friend-had-settled-down](https://www.eddiehe.xyz/article/my-friend-had-settled-down) 无法显示图片。

**期望的正常结果**
自定义域名的 blog 也能显示图片。

**截图**
<img width="165" alt="image" src="https://user-images.githubusercontent.com/40681449/212694497-417a4583-d5b4-4e15-9d58-52335403fb3c.png">

**环境**

- 操作系统：windows 11
- 浏览器：Edge
- 版本：109.0.1518.52

**补充说明**
1. 通过开发者工具看图片的链接，图片是存储在 Amazon AWS，不过使用 Vercel 默认域名的文章的图片链接，和使用自定义域名文章的图片链接不一样。
2. 域名购买自硅云，是我的设置有误有漏吗？

**Comment by SkysCrystal** [comment]
图片偶尔需要刷新几次，我可以看到 https://www.eddiehe.xyz/article/my-friend-had-settled-down 页面的图片。

![image](https://user-images.githubusercontent.com/49473463/212798242-b5145075-bdef-4d3b-9b8b-c1c7159bfe0d.png)

**Comment by tangly1024** [comment]
如上，我也可以看到这篇文章的图片，图片的显示与选用的域名应该是无关的；

目前推测，可能是notion用的aws-s3图床会出现网络抽风的情况，导致无法显示

**Comment by greyair** [comment]
aws-s3的图床图片有些会被浏览器的安全策略拦截

**Comment by Ylarod** [comment]
是否可以缓存所有图片，从而让Cloudflare提供缓存。
还有就是，头像使用外链的时候会加上 notion.so 前缀，我不清楚这是否必要，在无科学环境下无法加载国内头像。
如：[我的头像](https://www.notion.so/image/https%3A%2F%2Fq1.qlogo.cn%2Fg%3Fb%3Dqq%26k%3DH8nCdsiafhEJd7MOHGiabxeA%26kti%3DY3Xv6wAAAAA%26s%3D640?table=collection&id=4951996c-db7a-47a7-8be1-958b3e2aa10a)

**Comment by lifeafter619** [comment]
也许可以把要用的图先传图床，在用url插入notion，加载的时候就是图床的地址了

**Comment by eddiehe99** [comment]
的确多刷新几次可以解决问题。
