### ISSUE TITLE
折叠标题与notion官方的折叠标题不一致，箭头和标题不在同一行内

### ISSUE THREAD

**Issue by zs6** [tangly1024/NotionNext#701]
**为什么提出这个新的特性改动**
一个是不方便阅读，箭头占用了太多行。一个是不美观

**描述一下你推荐的解决方案**
与notion官方折叠标题一样，箭头和标题在同一行内

**Comment by lifeafter619** [comment]
最近遇到了相同错误，以前是正常的来着

**Comment by lifeafter619** [comment]
![image](https://user-images.githubusercontent.com/65111206/213079678-19f64119-0d89-4a89-af0d-74730a638c99.png)

**Comment by tangly1024** [comment]
已确认bug，与之前的 #689 #589 是相同的错误

**Comment by tangly1024** [comment]
已提交修复补丁，更新体验

**Comment by lifeafter619** [comment]
> 已提交修复补丁，更新体验

感谢大佬，该问题已修复
但刚才的aplayer音乐插件貌似出了bug，我的感觉没错的话是引入链接引号的问题，现在完全不显示了

**Comment by tangly1024** [comment]
> 感谢大佬，该问题已修复 但刚才的aplayer音乐插件貌似出了bug，我的感觉没错的话是引入链接引号的问题，现在完全不显示了 @tangly1024

我没有遇到播放器插件的问题，检查了你的代码后发现：
此处配置有问题：
https://github.com/lifeafter619/NotionNext/blob/52970cbcab2ec836c1a18a2399b5cef0ae0c7b77/components/CommonScript.js#L106

```
    {JSON.parse(BLOG.MUSIC_PLAYER) && <script async src="BLOG.MUSIC_PLAYER_CDN_URL" />}
```

修改为以下内容即可：

```
    {JSON.parse(BLOG.MUSIC_PLAYER) && <script async src={BLOG.MUSIC_PLAYER_CDN_URL} />}
```
