### ISSUE TITLE
【404 页面处理】超时时间 20s 跳转 404 ，缩短到8-10秒

### ISSUE THREAD

**Issue by expoli** [tangly1024/NotionNext#707]
**为什么提出这个新的特性改动**
这种处理方式将极大程度的延长页面响应时间，请问有没有更好的实现方式？比如直接查询相应的部分是否存在？

**描述一下你推荐的解决方案**
20s 太长了、我觉得 8-10 秒，应该是一个比较合适的值

**Comment by tangly1024** [comment]
很感谢提议，我觉得确实需要调整这个逻辑
