### ISSUE TITLE
font-family 中 emoji 字体的位置问题

### ISSUE THREAD

**Issue by ouuan** [tangly1024/NotionNext#711]
**描述bug**

`font-family` 中 `Apple Color Emoji` 等 emoji 字体放在了靠前的位置，导致在一些系统上数字会显示成 emoji，应当放在最后。 

https://github.com/tangly1024/NotionNext/blob/6e58f5a335cd5272be5d87e78f96464e3f996cca/lib/font.js#L36-L44

**复现步骤**

安装了 https://github.com/samuelngs/apple-emoji-linux 且没有安装 `font-family` 中靠前的几个字体时，访问博客，数字显示为 emoji

**期望的正常结果**

数字显示为正常字体

**截图**

![图片](https://user-images.githubusercontent.com/30581822/213901810-15b760d7-9e31-4d3f-8c04-a11df9b0a222.png)

**环境**

- 操作系统: Arch Linux
- 浏览器 Firefox
- 版本 109.9

**补充说明**

**Comment by tangly1024** [comment]
收到反馈，最新版本中已经调整了默认emoji字体的顺序
