### ISSUE TITLE
部分文章部署错误

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#712]
**描述遇到的问题**
简单说明你遇到的问题，相关的日志、错误信息
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/32816780/213929421-434ebdd4-4534-4c3e-a461-734dff2b4b36.png">

**相应配置**
相关的配置，例如notion_page_id；你的网站地址

**截图**
相关的页面，应该用结果

**环境**
怎么查找/article%2F0d9b1643-f322-47c8-afee-1bc61a370027 这个文章
- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**Comment by SkysCrystal** [comment]
根据我的经验，你可能在博客页面嵌入了其他Notion页面的链接。
可以使用短链工具，将博客嵌入的 `https://xxx.notion.so/` , `https://xxx.notion.site/` 这类链接转换一下，再复制到博客文本中，这个可以暂时解决问题。

**Comment by Angel0726** [comment]
> 根据我的经验，你可能在博客页面嵌入了其他Notion页面的链接。 可以使用短链工具，将博客嵌入的 `https://xxx.notion.so/` , `https://xxx.notion.site/` 这类链接转换一下，再复制到博客文本中，这个可以暂时解决问题。

具体怎么查找是哪篇文章，以及如何使用短链工具

**Comment by SkysCrystal** [comment]
> > 根据我的经验，你可能在博客页面嵌入了其他Notion页面的链接。 可以使用短链工具，将博客嵌入的 `https://xxx.notion.so/` , `https://xxx.notion.site/` 这类链接转换一下，再复制到博客文本中，这个可以暂时解决问题。
> 
> 具体怎么查找是哪篇文章，以及如何使用短链工具

链接： https://coolnext.vercel.app/article%2F0d9b1643-f322-47c8-afee-1bc61a370027 似乎和我说的情况不一样

我说的在这：
![](https://raw.githubusercontent.com/SkysCrystal/Figurebed/master/img/notion_next_error_123.png)

页面： https://coolnext.vercel.app/4d7cafcd57a4425590c5821a6f40dfe8
短链软件： bitly.com 或者自建之类

**Comment by Angel0726** [comment]
> > > 根据我的经验，你可能在博客页面嵌入了其他Notion页面的链接。 可以使用短链工具，将博客嵌入的 `https://xxx.notion.so/` , `https://xxx.notion.site/` 这类链接转换一下，再复制到博客文本中，这个可以暂时解决问题。
> > 
> > 
> > 具体怎么查找是哪篇文章，以及如何使用短链工具
> 
> 链接： https://coolnext.vercel.app/article%2F0d9b1643-f322-47c8-afee-1bc61a370027 似乎和我说的情况不一样
> 
> 我说的在这： ![](https://raw.githubusercontent.com/SkysCrystal/Figurebed/master/img/notion_next_error_123.png)
> 
> 页面： https://coolnext.vercel.app/4d7cafcd57a4425590c5821a6f40dfe8 短链软件： bitly.com 或者自建之类

我的操作跟你图片中一样，我在3.4.2版本是可以的。但是现在升级到3.8.2不可以了。然后 https://coolnext.vercel.app/article%2F0d9b1643-f322-47c8-afee-1bc61a370027链接并不是我的博客链接，这是楼主的示例模板，我也不清楚为什么

**Comment by SkysCrystal** [comment]
> https://coolnext.vercel.app/article%2F0d9b1643-f322-47c8-afee-1bc61a370027

换成我的博客域名也访问不出来 https://www.dsuper.xyz/article%2F0d9b1643-f322-47c8-afee-1bc61a370027
这应该属于应该跳转 404 的页面？

**Comment by Angel0726** [comment]
> > https://coolnext.vercel.app/article%2F0d9b1643-f322-47c8-afee-1bc61a370027
> 
> 换成我的博客域名也访问不出来 https://www.dsuper.xyz/article%2F0d9b1643-f322-47c8-afee-1bc61a370027 这应该属于应该跳转 404 的页面问题？ #707



> > https://coolnext.vercel.app/article%2F0d9b1643-f322-47c8-afee-1bc61a370027
> 
> 换成我的博客域名也访问不出来 https://www.dsuper.xyz/article%2F0d9b1643-f322-47c8-afee-1bc61a370027 这应该属于应该跳转 404 的页面问题？ #707



> > https://coolnext.vercel.app/article%2F0d9b1643-f322-47c8-afee-1bc61a370027
> 
> 换成我的博客域名也访问不出来 https://www.dsuper.xyz/article%2F0d9b1643-f322-47c8-afee-1bc61a370027 这应该属于应该跳转 404 的页面问题？ #707

我知道访问不了的原因了，因为我的网站是作者的演示网站，但是现在要上线的是自己网站。这个文章应该是我的，但是只知道/article%2F0d9b1643-f322-47c8-afee-1bc61a370027不知道是哪个文章，我的共享网站https://jeweled-trilby-556.notion.site/52fe045a5b7c46308a5a8bed9a192582?v=fbe6fd48403f428890b7d87a32355678

**Comment by tangly1024** [comment]
> 我知道访问不了的原因了，因为我的网站是作者的演示网站，但是现在要上线的是自己网站。这个文章应该是我的，但是只知道/article%2F0d9b1643-f322-47c8-afee-1bc61a370027不知道是哪个文章，我的共享网站https://jeweled-trilby-556.notion.site/52fe045a5b7c46308a5a8bed9a192582?v=fbe6fd48403f428890b7d87a32355678

对应的是这篇文章 ：https://jeweled-trilby-556.notion.site/Teacher-forcing-0d9b1643f32247c8afee1bc61a370027

**Comment by Angel0726** [comment]
> 
> > 我知道访问不了的原因了，因为我的网站是作者的演示网站，但是现在要上线的是自己网站。这个文章应该是我的，但是只知道/article%2F0d9b1643-f322-47c8-afee-1bc61a370027不知道是哪个文章，我的共享网站https://jeweled-trilby-556.notion.site/52fe045a5b7c46308a5a8bed9a192582?v=fbe6fd48403f428890b7d87a32355678
> 
> 对应的是这篇文章 ：https://jeweled-trilby-556.notion.site/Teacher-forcing-0d9b1643f32247c8afee1bc61a370027

怎么找到的可以教一教我吗

**Comment by tangly1024** [comment]
> /article%2F0d9b1643-f322-47c8-afee-1bc61a370027

文章地址包含了页面id，可以直接找到 ；
从错误日志来看，这篇文章生成失败是因为请求notion数据超时 ‘timing out’
![image](https://user-images.githubusercontent.com/15920488/215365948-4522cdf0-35dd-49e4-b9dc-06c7e873af6d.png)

有可能是notion网络抽风导致，可以尝试重新部署

**Comment by Angel0726** [comment]
> > /article%2F0d9b1643-f322-47c8-afee-1bc61a370027
> 
> 文章地址包含了页面id，可以直接找到 ； 从错误日志来看，这篇文章生成失败是因为请求notion数据超时 ‘timing out’ ![image](https://user-images.githubusercontent.com/15920488/215365948-4522cdf0-35dd-49e4-b9dc-06c7e873af6d.png)
> 
> 有可能是notion网络抽风导致，可以尝试重新部署

多次尝试部署失败。
目前方式是，将这篇文章的published给成idea，部署成功；部署成功之后又将idea改成了published
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/32816780/215375569-ed288ab2-3f7f-472d-9a81-35df419123a0.png">

**Comment by Angel0726** [comment]
> > > /article%2F0d9b1643-f322-47c8-afee-1bc61a370027
> > 
> > 
> > 文章地址包含了页面id，可以直接找到 ； 从错误日志来看，这篇文章生成失败是因为请求notion数据超时 ‘timing out’ ![image](https://user-images.githubusercontent.com/15920488/215365948-4522cdf0-35dd-49e4-b9dc-06c7e873af6d.png)
> > 有可能是notion网络抽风导致，可以尝试重新部署
> 
> 多次尝试部署失败。 <img alt="image" width="1002" src="https://user-images.githubusercontent.com/32816780/215375569-ed288ab2-3f7f-472d-9a81-35df419123a0.png"> 目前方式是，将这篇文章的published给成idea，部署成功；部署成功之后又将idea改成了published，能够成功[搜索](https://coolnext.vercel.app/search/Teacher%20forcing)到这篇文章，但是打开之后又是404. 如何文章到底是哪里出了错误
> 
> ![image](https://user-images.githubusercontent.com/32816780/215473496-a75c0451-ffa3-4a59-bdb1-0332ddbc6386.png)
是不是因为表格中使用了公式
![image](https://user-images.githubusercontent.com/32816780/215475287-9d0d34dc-918f-4be4-87f5-c4b4e2568786.png)

**Comment by tangly1024** [comment]
> 如前面所说，用api请求此notion页面数据，始终是超时 ‘timing out’

建议的解决： 备份内容， 删除此notion页面，新建一个页面，将内容**部分**粘贴进来。
