### ISSUE TITLE
medium 主题嵌入文件，手机端名称显示过长

### ISSUE THREAD

**Issue by SkysCrystal** [tangly1024/NotionNext#713]
**描述bug**
medium 主题手机访问，嵌入文件主题名称过长，显示超出页面。

**复现步骤**
启用 medium 主题，在 Notion 嵌入 `.zip` 文件，访问博客页面 [🔗 Link](https://www.dsuper.xyz/article/trados-2022-v17.0.0.11594)。

**期望的正常结果**
名称可以滚动，或者缩略显示。

**截图**
![](https://raw.githubusercontent.com/SkysCrystal/Figurebed/master/img/notionnext_medium_zip_bug.jpeg)

**环境**

- 操作系统: [iOS]
- 浏览器 [chrome]
- 版本 [108.0.]

**补充说明**
暂无

**Comment by tangly1024** [comment]
最新提交中修复此问题；文件名溢出将支持滚动。https://github.com/tangly1024/NotionNext/commit/ad5e68564f258e7956c3d46d0d43f8db1f2c6215

**Comment by tangly1024** [comment]
https://github.com/tangly1024/NotionNext/releases/tag/v3.9.0
