### ISSUE TITLE
【分享功能】其他主题都加入分享功能；手机端按钮优化

### ISSUE THREAD

**Issue by lifeafter619** [tangly1024/NotionNext#715]
**为什么提出这个新的特性改动**
next主题下手机端文章结束后由于横向空间较小，显示时效果不佳，如下
![Screenshot_20230124_211500.jpg](https://user-images.githubusercontent.com/65111206/214339407-8bb4d42a-5744-49c3-81a7-aae4c7dc7fc1.jpg)
并且我发现其它主题的config.js中并没有设置分享按钮的选项，于我而言，这是一个很有用的功能，希望大大能在其它主题中也加入

**描述一下你推荐的解决方案**
其它主题中也加入分享功能，还有hexo主题下貌似有下一篇文章推荐的小板块，也希望在其它主题中加入。
关于分享按钮的显示，我希望在手机端上将其和category和tags分为三行显示。

**描述一下你考虑过的其它替代解决方案**
关于分享按钮，也许也可以在手机端上进行分行，入分为两行显示，但在tags较多的情况下也许没有上一种想法好

**补充说明**
补充与此特性相关的内容

**Comment by tangly1024** [comment]
https://github.com/tangly1024/NotionNext/releases/tag/v3.13.5
