### ISSUE TITLE
【favicon】标签页无法显示自定义favicon.ico

### ISSUE THREAD

**Issue by eddiehe99** [tangly1024/NotionNext#716]
**描述bug**
更换`public`文件夹中的 favicon.ico 后 blog 标签页无法显示 favicon，但是访问 blog 地址加上`/favicon.ico`可正常显示`.ico`，而且标签页上的 favicon 也能正常显示。

**复现步骤**
访问 [www.eddiehe.xyz](www.eddiehe.xyz) 无法在标签页中看到新的 favicon，但是访问 [www.eddiehe.xyz/favicon.ico](www.eddiehe.xyz/favicon.ico) 能访问 ico 文件，而且标签页上的 favicon 正常显示。

**期望的正常结果**
希望更换 favicon 后能正常显示。

**截图**
<img width="188" alt="image" src="https://user-images.githubusercontent.com/40681449/215266402-aede964f-05d2-426e-8e02-af4b53fab0ae.png">

<img width="189" alt="image" src="https://user-images.githubusercontent.com/40681449/215267009-b1e9bc44-fd58-4c5c-afbe-4edaa3e02fdb.png">

**环境**

- 操作系统: windows 11
- 浏览器: Edge
- 版本: 109.0.1518.69

**补充说明**
按 F12 之后看调试信息，发现 favicon.ico 文件是能正常获取的。
把 favicon.ico 文件换回之前能显示的仍然不 work。

**Comment by tangly1024** [comment]
已修复，请更新到最新版本代码；
另外，你的favicon.ico文件过大，建议用ico工具生成一个小于10kb的图标 ： https://www.bitbug.net/
