### ISSUE TITLE
【自定义CSS和JS】

### ISSUE THREAD

**Issue by Vixcity** [tangly1024/NotionNext#720]
**为什么提出这个新的特性改动**
可以增加DIY的个性程度，使用户的博客页面可以更个性化

**描述一下你推荐的解决方案**
在blog.config.js文件里面添加可导入的CSS和JS数组

**描述一下你考虑过的其它替代解决方案**
在blog.config.js文件里面添加可导入的CSS和JS数组

**补充说明**
无

**Comment by tangly1024** [comment]
已新增特性
https://github.com/tangly1024/NotionNext/releases/tag/v3.9.0
