### ISSUE TITLE
【Safari卡顿】macOS safari浏览器使用hexo主题卡顿

### ISSUE THREAD

**Issue by evibhm** [tangly1024/NotionNext#721]
**描述bug**
macOS中Safari浏览器使用hexo主题卡顿，具体表现为上下滑动时非常卡顿，而且上滑到背景大图页面部分会自动掉到有文章的页面部分。

**复现步骤**
macOS的Safari浏览器使用hexo主题的任意博客，在有背景大图的页面向下滑动到有文章的页面部分，再上滑到背景大图页面部分，滑动过程非常卡顿，并且滑动到背景大图部分时，会自动跳转到有文章的页面部分。

**期望的正常结果**
滑动流畅且不会自动跳转到下面部分

**截图**
卡顿的形式无法用截图表达

**环境**

- 操作系统: macOS Ventura 13.1 Apple M1
- 浏览器: Safari Version 16.2 (18614.3.7.1.5)
- 版本 ad5e68564f258e7956c3d46d0d43f8db1f2c6215

**补充说明**
在macOS的Chrome浏览器中正常，在iOS浏览器中正常。

**Comment by tangly1024** [comment]
收到反馈，这是由于mac 屏幕尺寸和 页面动画冲突导致的；
新版将考虑去掉自动滚动的动画。

**Comment by tangly1024** [comment]
已修复此问题
https://github.com/tangly1024/NotionNext/releases/tag/v3.9.0
