### ISSUE TITLE
search界面分类错误

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#722]
**描述bug**
简单说明bug的现象、相关的错误提示、日志等
[首页](https://coolnext.vercel.app/)有人工智能分类，[search界面](https://coolnext.vercel.app/search)没有人工智能分类。search界面缺少人工智能分类

**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
相关的页面，应该用结果
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/32816780/215471129-eda851c6-0091-4198-a8bc-5da179517564.png">
![image](https://user-images.githubusercontent.com/32816780/215471211-e37873b0-9434-4f14-a35a-5b0de2f6ffb5.png)

**环境**

- 操作系统: [macOS]
- 浏览器 [例如. chrome]
- 版本 [e.g. 3.8.1]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
可能是刚更新分类，缓存导致分类不同步：

刷新页面后可查看
![image](https://user-images.githubusercontent.com/15920488/215635533-6f062ee0-96c8-491d-abd3-503d91ec2431.png)
