### ISSUE TITLE
【样式排版】博客排版比Notion宽松

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#724]
**描述bug**
简单说明bug的现象、相关的错误提示、日志等
[notion中的文章](https://jeweled-trilby-556.notion.site/Transformer-a291e09c3b09484eb9aa2d895e9e3a89)显示是十分紧凑的，但是[博客中显示](https://coolnext.vercel.app/article/a291e09c-3b09-484e-b9aa-2d895e9e3a89#3878abe8a1c34899bf450bc7a3441648)差强人意
**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**

**文章中的显示，十分紧凑**
<img width="809" alt="image" src="https://user-images.githubusercontent.com/32816780/215742268-f25737c9-3847-4442-9a33-e3513c4fcaf1.png">
**博客中的显示，有很多空白**
<img width="858" alt="image" src="https://user-images.githubusercontent.com/32816780/215742430-be225481-c0d2-4e5b-8a81-052122ae112f.png">

**环境**

- 操作系统: [例如. macOS]
- 浏览器 [例如. chrome]
- 版本 [e.g. 3.8.2]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
博客的样式，并没有和notion完全一致；

你的意思是更喜欢紧凑的排版吗

**Comment by Angel0726** [comment]
> **描述bug** 简单说明bug的现象、相关的错误提示、日志等 [notion中的文章](https://jeweled-trilby-556.notion.site/Transformer-a291e09c3b09484eb9aa2d895e9e3a89)显示是十分紧凑的，但是[博客中显示](https://coolnext.vercel.app/article/a291e09c-3b09-484e-b9aa-2d895e9e3a89#3878abe8a1c34899bf450bc7a3441648)差强人意 **复现步骤** 出现这个bug的操作步骤
> 
> **期望的正常结果** 希望按这个步骤，正常操作结果是什么
> 
> **截图** 相关的页面，应该用结果 文章中的显示，十分紧凑 <img alt="image" width="809" src="https://user-images.githubusercontent.com/32816780/215742268-f25737c9-3847-4442-9a33-e3513c4fcaf1.png"> 博客中的显示，有很多空白 <img alt="image" width="858" src="https://user-images.githubusercontent.com/32816780/215742430-be225481-c0d2-4e5b-8a81-052122ae112f.png">
> 
> **环境**
> 
> * 操作系统: [例如. macOS]
> * 浏览器 [例如. chrome]
> * 版本 [e.g. 3.8.2]
> 
> **补充说明** 与问题相关的其它说明



> 博客的样式，并没有和notion完全一致；
> 
> 你的意思是更喜欢紧凑的排版吗



> 博客的样式，并没有和notion完全一致；
> 
> 你的意思是更喜欢紧凑的排版吗



> 博客的样式，并没有和notion完全一致；
> 
> 你的意思是更喜欢紧凑的排版吗

我希望notion跟博客排版一样。因为在notion写文章的时候，就自然会考虑美观问题，如果在博客中发现版本跟notion中不一样就会很别扭。上面的问题，体现在美观上就是能不能对齐的问题

**Comment by tangly1024** [comment]
了解了，将更新一个补丁版本修复此排版问题。

**Comment by tangly1024** [comment]
https://github.com/tangly1024/NotionNext/releases/tag/v3.9.0
修复此问题
