### ISSUE TITLE
medium 主题无法正常加载目录和评论

### ISSUE THREAD

**Issue by SkysCrystal** [tangly1024/NotionNext#742]
**描述bug**
medium 主题不显示目录 和 评论

**复现步骤**
我的博客使用 medium 主题，内容如： ~~[页面](https://www.dsuper.xyz/article/waline-setting)~~ 文章长度足够，但是右侧栏不显示目录（关于也无法正常显示）。

**期望的正常结果**
正常显示**目录、关于** 内容

**截图**
![目录无法显示](https://raw.githubusercontent.com/SkysCrystal/Figurebed/master/img/202302041350107.png)

**环境**
- NotionNext: 更新的最新版
- 操作系统: [windows]
- 浏览器 [chrome, edge, safari]
- 版本 [e.g. 22]

**补充说明**
暂无

**Comment by SkysCrystal** [comment]
medium 主题的评论也不能正常加载出来 
![](https://raw.githubusercontent.com/SkysCrystal/Figurebed/master/img/202302051114536.png)

**Comment by tangly1024** [comment]
奇怪了，在我的电脑上访问您的页面，评论区、目录、关于的动画显示都是正常的：
![image](https://user-images.githubusercontent.com/15920488/216871676-d5d68849-ef2b-4a34-9546-4fb6bd0281e3.png)

**Comment by SkysCrystal** [comment]
> 奇怪了，在我的电脑上访问您的页面，评论区、目录、关于的动画显示都是正常的： ![image](https://user-images.githubusercontent.com/15920488/216871676-d5d68849-ef2b-4a34-9546-4fb6bd0281e3.png)

我现在换了 matery 主题了，看您这界面好像还是 medium 主题页面。我换成 medium 就会加载不出来

**Comment by tangly1024** [comment]
我在新版本中提交了一个 关于目录评论区动画不显示的补丁，尝试更新一下，希望能解决您的问题

https://github.com/tangly1024/NotionNext/commit/dbdad58c2de23c4c62e0b1fc2f400de76f13baf8

**Comment by SkysCrystal** [comment]
> 我在新版本中提交了一个 关于目录评论区动画不显示的补丁，尝试更新一下，希望能解决您的问题
> 
> [dbdad58](https://github.com/tangly1024/NotionNext/commit/dbdad58c2de23c4c62e0b1fc2f400de76f13baf8)

您好，我重新更新部署了，仍然没有加载出来目录和评论。不知道别人有没有这个问题……
![](https://pan.swin.ltd/d/share/Figurebed/202302072353559.png)

medium 主题我用 chrome edge firefox opear 打开都加载不出来目录和评论。

我先换个主题用用……

**Comment by xloong** [comment]
> 我在新版本中提交了一个 关于目录评论区动画不显示的补丁，尝试更新一下，希望能解决您的问题
> 
> [dbdad58](https://github.com/tangly1024/NotionNext/commit/dbdad58c2de23c4c62e0b1fc2f400de76f13baf8)

我也用的medium主题，更新后问题依旧，fade-up动画失效，感觉像是没有侦测到鼠标滚动，目录一直是在页面展示位置靠下面一点 opacity:0 透明的

**Comment by tangly1024** [comment]
> > 我在新版本中提交了一个 关于目录评论区动画不显示的补丁，尝试更新一下，希望能解决您的问题
> > [dbdad58](https://github.com/tangly1024/NotionNext/commit/dbdad58c2de23c4c62e0b1fc2f400de76f13baf8)
> 
> 我也用的medium主题，更新后问题依旧，fade-up动画失效，感觉像是没有侦测到鼠标滚动，目录一直是在页面展示位置靠下面一点 opacity:0 透明的

感谢您提供的反馈， 我已经定位到问题。

原因是  在 medium主题下，我没有初始 AOS动画的组件导致 ；

而如果使用其它主题，再在页面上切换到medium主题，动画就会生效。

**Comment by tangly1024** [comment]
已提交动画修复补丁，解决了 目录评论区动画无法显示的bug：
https://github.com/tangly1024/NotionNext/commit/983504795e9aae31a6b5a837fa72c1d72c73b3d4

**Comment by xloong** [comment]
> 已提交动画修复补丁，解决了 目录评论区动画无法显示的bug： [9835047](https://github.com/tangly1024/NotionNext/commit/983504795e9aae31a6b5a837fa72c1d72c73b3d4)

已更新，问题已修复
