### ISSUE TITLE
【文章空封面】提供一个控制选项，用户可用来选择是否允许空封面

### ISSUE THREAD

**Issue by expoli** [tangly1024/NotionNext#745]
**为什么提出这个新的特性改动**
原来文章不设置封面，默认使用主页背景封面，但是现在默认允许空封面，感觉有点不和谐，同时大量更改起来也不方便，能否提供一个配置的控制选项

**描述一下你推荐的解决方案**
提供一个配置的控制选项

**描述一下你考虑过的其它替代解决方案**
提供一个配置的控制选项

**补充说明**
![图片](https://user-images.githubusercontent.com/31023767/216803848-f17df53d-2593-4fec-a6cf-2b918bc25a3a.png)

**Comment by tangly1024** [comment]
ok， 感谢反馈 

最新版本已在config_hexo.js中加入此配置 
```
  POST_LIST_COVER_DEFAULT: true, // 封面为空时用站点背景做默认封面
```
且目前默认设置是，封面为空时，使用站点背景做为封面
