### ISSUE TITLE
排版问题

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#753]
**描述bug**
简单说明bug的现象、相关的错误提示、日志等
notion中的排版与博客中的排版不一样。希望博客中的排版跟notion中保持一致，这样写博客的时候就不用考虑博客中的排版了。所见即所得。
目前3.9.4版本：图片、思维导图、行内公式都不一样

**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图（公式、思维导图）**
相关的页面，应该用结果
- notion中的排版：https://jeweled-trilby-556.notion.site/Transformers-BERT-38339f4a73354d4eae1f36a0ca9f61ab
![image](https://user-images.githubusercontent.com/32816780/217540552-42a8cf20-8006-4829-9c95-025235cba1b2.png)
![image](https://user-images.githubusercontent.com/32816780/217541530-19c74654-a3a5-4f63-9c90-b39c39368ae5.png)

- 博客中的排版：https://coolnext.vercel.app/article/38339f4a-7335-4d4e-ae1f-36a0ca9f61ab
![image](https://user-images.githubusercontent.com/32816780/217541350-92ebdc42-19ee-4788-8bb8-aae40f660c4d.png)
![image](https://user-images.githubusercontent.com/32816780/217541709-c1949390-8215-48d4-b9ce-a7b0cbfbef7e.png)

**截图（图片）**
相关的页面，应该用结果

- notion：https://jeweled-trilby-556.notion.site/Transformer-a291e09c3b09484eb9aa2d895e9e3a89
![image](https://user-images.githubusercontent.com/32816780/217545093-850856b7-7a2c-4829-898a-4f5ff8c3a409.png)

- 博客：使用平板查看 https://coolnext.vercel.app/article/a291e09c-3b09-484e-b9aa-2d895e9e3a89
![image](https://user-images.githubusercontent.com/32816780/217544691-ba71fd3b-6f73-4f7c-8ccb-5eae25a15e85.png)

**环境**

- 操作系统: [例如. Android, macOS]
- 浏览器 [例如. chrome]
- 版本 [e.g. 3.9.4]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
mermaid 排班居中 https://github.com/tangly1024/NotionNext/pull/759

**Comment by Angel0726** [comment]
> mermaid 排版居中 #759

其他的问题呢，行间距等问题

**Comment by tangly1024** [comment]
公式行高导致留白:  https://github.com/tangly1024/NotionNext/commit/cadb41c0eaceaa41aa27c19b2cfe915010ac87ac

**Comment by Angel0726** [comment]
> 公式行高导致留白: [cadb41c](https://github.com/tangly1024/NotionNext/commit/cadb41c0eaceaa41aa27c19b2cfe915010ac87ac)

更新了最新的代码并没有得到结果 https://coolnext.vercel.app/article/38339f4a-7335-4d4e-ae1f-36a0ca9f61ab
<img width="922" alt="image" src="https://user-images.githubusercontent.com/32816780/217774340-68f9bf69-26fc-4424-9eb7-d753136d525f.png">

**Comment by Angel0726** [comment]
> 公式行高导致留白: [cadb41c](https://github.com/tangly1024/NotionNext/commit/cadb41c0eaceaa41aa27c19b2cfe915010ac87ac)

em .katex-display {
  margin: 0 0 !important;
删除上述代码吗？

**Comment by tangly1024** [comment]
已提交补丁，再更新即可
