### ISSUE TITLE
hexo 主题百度统计主页无法获取统计信息

### ISSUE THREAD

**Issue by mumudm** [tangly1024/NotionNext#76]
hexo 主题百度统计主页无法获取统计信息
![image](https://user-images.githubusercontent.com/46308185/156479924-e7c69e91-c656-4aee-97b9-2204aafcf689.png)

**Comment by tangly1024** [comment]
hi 🙋🏻‍♂️, 请问现在问题还存在吗，我访问了你的博客站点，发现百度统计的代码已经正常安装了。（页面已经注入了百度的代码，并且网络请求日志中已经连接上了百度请求中心）

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/15920488/157160063-5c817975-f709-4c84-bf28-16dfa8d1daf0.png">

也许是因为页面缓存的缘故，百度检查到统计代码有些延迟🤔

另外，也再检查一下你百度后台配置，我发现我的设置页面和你的有点不一样😂，我的后台有显示当前检查的页面，也许你可以试着手动输入你的页面进行检查。
<img width="599" alt="image" src="https://user-images.githubusercontent.com/15920488/157160382-9611f7eb-7534-4d26-8552-2f175b0166c6.png">
