### ISSUE TITLE
【深色模式】Giscus 组件样式错误

### ISSUE THREAD

**Issue by Pylogmon** [tangly1024/NotionNext#771]
**描述bug**

giscus 样式出错

**复现步骤**

~~如果页面的默认主题是light的话没有任何问题，但如果默认主题设置为dark或auto使得页面打开后的主题是dark,这时候如果手动切换到light模式，就会出现上面的问题。~~

**当系统处于深色模式的时候，无论页面主题是亮是暗，giscus都会有一个深色的背景色。**

**期望的正常结果**

正常显示亮暗的样式

**截图**

![图片](https://user-images.githubusercontent.com/59004461/218290761-9e54cbd8-49a8-416e-a8df-cdd01b60926b.png)

**环境**

- 操作系统: [linux]
- 浏览器 [firefox 109]
- 版本 [3.10.0]

**补充说明**

**Comment by Pylogmon** [comment]
补充一点，发现是系统处在深色模式下才会有这个问题，页面不论亮暗都会有问题。

**Comment by tangly1024** [comment]
已提提交补丁 修复此问题

**Comment by Pylogmon** [comment]
在Chrome DevTools中切换深色和浅色模式会发现只有深色会有问题
![image](https://user-images.githubusercontent.com/59004461/218980969-53e4031a-dc1f-4adb-979a-fcb0a3f2a5cd.png)

**Comment by Pylogmon** [comment]
应该是giscus/react的问题，这个问题在2.0.1版本中已经被修复[https://github.com/giscus/giscus-component/pull/45](https://github.com/giscus/giscus-component/pull/45)，请更新依赖版本。

**Comment by tangly1024** [comment]
感谢反馈！

已升级至最新版 https://github.com/tangly1024/NotionNext/commit/d81c2ef77f5f49cb11e33570899a04ae22ea51d7
