### ISSUE TITLE
hexo主题首页文章列表中每篇文章占的太宽了,可否紧密些.

### ISSUE THREAD

**Issue by 668168** [tangly1024/NotionNext#782]
**为什么提出这个新的特性改动**
文章列表太稀疏了
**描述一下你推荐的解决方案**
当关闭文章封面后, 建设每篇文章宽度
```
  POST_LIST_COVER: false, // 列表显示文章封面
  POST_LIST_COVER_DEFAULT: false, // 封面为空时用站点背景做默认封面
  POST_LIST_SUMMARY: true, // 文章摘要
  POST_LIST_PREVIEW: false, // 读取文章预览
```

**关掉文章封面后, 还是很稀疏**
![image](https://user-images.githubusercontent.com/1046701/218742418-3a66589c-5dec-45e8-9a02-bd72b70515b3.png)

**Comment by tangly1024** [comment]
不错的提议，当关闭文章封面时，适当压缩高度

**Comment by 22Goose** [comment]
请问一下这个列表每个块的行高可以人为修改吗？我翻了一圈没找到可以修改的地方🤦‍♂️（我用的是simple主题）。
如果没有的话建议加一个可以认为修改的😇
