### ISSUE TITLE
是否可以vps部署上增加缓存功能

### ISSUE THREAD

**Issue by 668168** [tangly1024/NotionNext#783]
**为什么提出这个新的特性改动**
相当于增加了一个正向代理, 用户直接访问vps上的缓存资源, 比如图片, 字体. 解决了国内访问google 字体或者notion 图片缓慢的问题.
**描述一下你推荐的解决方案**
如描述

**Comment by tangly1024** [comment]
1. 可以在nginx上配置图片字体的缓存
2. notion图片缓慢目前只能用第三方图床的方式解决，或者您可以使用自己的vps作为图床服务器
3. 网站套上cdn可以大大提高缓存效率

**Comment by 668168** [comment]
套cf是好办法,谢谢您
