### ISSUE TITLE
【排序问题】按照时间排序Or按照Notion排序

### ISSUE THREAD

**Issue by 668168** [tangly1024/NotionNext#784]
**描述bug**
next 主题文章列表排序错误. 
既不是按照日期顺序或者倒序排列的.
换hexo主题正常

**复现步骤**
直接换next主题即可复现问题.

**Comment by tangly1024** [comment]
切换至next主题后尝试刷新一下页面，怀疑是缓存导致

**Comment by 668168** [comment]
谢谢,的确是cache 导致.
额外请教一下: 目前默认是按照"日期-时刻"排序的吗?
我发现最新的日期在最上面, 但每天的文章里面并不是最新的在最上面. 这个是预期的吗? 
以wordpress为例子, 一般都是最新的时刻在最上边.

**Comment by tangly1024** [comment]
默认是在Notion中手动控制排序。
当然您也可以设置为按照时间排序：https://github.com/tangly1024/NotionNext/blob/339be04d0fa7396a6a0f88840335ad4e74081509/blog.config.js#L76
