### ISSUE TITLE
【多语言】Notionnext 博客调整为英文模式

### ISSUE THREAD

**Issue by yiranzhimo** [tangly1024/NotionNext#789]
**为什么提出这个新的特性改动**
我是一名做科研的学生，想通过 NotionNext 建立网站作为一张个人学术名片，那么网站的语言我需要设置为全英文的。

**描述一下你推荐的解决方案**
我想到两种方法，1）一种是模版自动选择 hexo-cn / hexo-en 的模式；2）第二种是明确所有中文的位置，我可以自己发时间修改为对应的英文

**描述一下你考虑过的其它替代解决方案**
暂时没有想到其他的

**补充说明**
最后，我有一个问题：
1）这里的「搜索」和「存档」我一直翻遍所有的 js 配置文件，都没有找到对应的修改为英文的位置？
![截屏2023-02-18 22 19 10](https://user-images.githubusercontent.com/40296363/219870794-db4e7436-d704-4d52-8583-705f3d8c82d4.png)

**Comment by tangly1024** [comment]
很高兴NotionNext 能够帮助到您；
-  NotionNext 本身是支持多语言的，预览效果： https://preview.tangly1024.com/?lang=en-US
- 配置语言方式 修改此文件即可 ：https://github.com/tangly1024/NotionNext/blob/main/blog.config.js#L9
- 已支持的语言，查看： https://github.com/tangly1024/NotionNext/tree/main/lib/lang

**Comment by yiranzhimo** [comment]
非常感谢🙏，我的疑问已得到解决！
