### ISSUE TITLE
升级react-notion-x

### ISSUE THREAD

**Issue by liqun98** [tangly1024/NotionNext#791]
**为什么提出这个新的特性改动**
 近期react-notion-x的作者发布了新版本6.16.0，解决了这个组件存在的一些bug，之前我提的pdf样式修复pr也被合入了master分支，当时是在NotionNext仓库写了CSS解决了这个问题#422 ，引入新版本后就可以将这段代码进行删除。

**描述一下你推荐的解决方案**
升级react-notion-x到6.16.0

**描述一下你考虑过的其它替代解决方案**
无

**补充说明**
不是很重大的改动，您有时间的话可以弄一下，或者我也能提一个PR进行合并

**Comment by tangly1024** [comment]
感谢，可以的话欢迎提交一个PR，成为此项目的贡献者。
