### ISSUE TITLE
【Video2Text】启动pythone项目报错

### ISSUE THREAD

**Issue by lgh108168** [tangly1024/NotionNext#793]
**描述bug**
我在测试页面：https://tangly1024.com/article/learning-python-video-to-text 提供的源代码时，出现一个错误：
oduleNotFoundError: No module named 'video_converter'
但是我的python已经安装了一个叫‘video_converter’的模块，执行后仍然出现这个错误。
是不是我安装的这个‘video_converter’与这个案例中自己使用的‘video_converter’不是一个模块？
请问，他用的是哪个‘video_converter’？
有安装网址吗？

**截图**
![image](https://user-images.githubusercontent.com/125803833/220228910-1f3a4f6f-7861-4cf5-b3d3-0f561d4837cd.png)
![image](https://user-images.githubusercontent.com/125803833/220228981-704bb407-da92-4069-bde1-da764e02bde4.png)

**环境**

- 操作系统: [windows]
- 浏览器 [chrome]

请费心提供帮助，多谢。

**Comment by tangly1024** [comment]
您好，我更新了文档说明，您可以参考我的启动步骤，使用venv的方式启动：


文章最新地址：
https://tangly1024.com/article/learning-python-video-to-text#6f52cbd1f4c748c5a5ce009d9f8bed53

相关截图：
![image](https://user-images.githubusercontent.com/15920488/220241383-d7ceffeb-061f-4195-9ecb-a3fea5b9e364.png)
