### ISSUE TITLE
【Cloudflare】维护cf分支代码

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#794]
**为什么提出这个新的特性改动**
简要说明此特性解决的问题，例如，『博客站点的读者互动性不够强，和读者无法建立紧密的联系...』
将博客部署到cf平台，可以参考https://www.haixin.io/article/notion-next-on-cf 。 但是文章中的分支长时间没有更新，您以后可以将这个分支fork到自己的仓库，并维护起来吗？

**Comment by tangly1024** [comment]
新增cloudflare教程 ： https://tangly1024.com/article/notion-next-cloud-flare
新增cloudflare分支： https://github.com/tangly1024/NotionNext/tree/deploy/cloudflare-support
