### ISSUE TITLE
bug(or feature?): notion 侧开启筛选器时博客的文章也被筛选了 

### ISSUE THREAD

**Issue by yuzhanglong** [tangly1024/NotionNext#80]
notion 侧开启筛选功能，博客侧只能显示筛选后的文章了。
<img width="339" alt="image" src="https://user-images.githubusercontent.com/56540811/157812654-e65030fc-a5d5-456a-8a10-266daaf5f2e2.png">

一般来说 notion 筛选只是博客编写者为了方便找自己的文章，有时候筛选完了忘记恢复，结果博客这边也没了。

**Comment by tangly1024** [comment]
我也遇到过这个问题，也许你可以尝试一下我的解决方法：
首先：notionnext绑定的这个notion页面我们称之为`博客列表`。

1.我的 `博客列表`主要用来定义排序、以及文章的模板格式。
2. 另外，我在notion中建了一个`链接视图`（notion的linked database），`链接视图`允许用户引用一个源数据，在视图中进行分组、分类、排序、筛选等操作，重要的是这不会修改到原数据本身的排序😄
3. 创建链接试图的方法很简单：复制`博客列表`的页面地址，在其它`博客列表`页面中粘贴，在粘贴时弹出的菜单中选择’linked todatabase’
![44714A76-DFE2-4995-81AC-4519026D3D7C](https://user-images.githubusercontent.com/15920488/157994699-b08c5a44-dbb7-400e-b98f-e34689028147.jpeg)

**Comment by yuzhanglong** [comment]
好，谢谢~ 然后还有个问题，刚刚发现进入开发环境时项目报错了，显示 
```plain
TypeError: categoryOptions.forEach is not a function
  21 |   const list = []
  22 |   console.log(categoryOptions)
> 23 |   categoryOptions.forEach(c => {
     |                  ^
  24 |     const count = categoryObj[c.value]
  25 |     if (count) {
  26 |       list.push({ id: c.id, name: c.value, color: c.color, count })
error - lib/notion/getAllCategories.js (23:18) @ getAllCategories
```

https://github.com/tangly1024/NotionNext/blob/ad79b2f841fbbae74330887b0c3ac531beb50fc6/lib/notion/getAllCategories.js#L22 这个地方，categoryOptions 应该是个 Object。

**Comment by tangly1024** [comment]
感谢你的反馈！😁

categoryOptions 取的是notion中的所有文章分类。它的期望值应该是一个对象数组[Obejct...]，

我自己开发环境中并没有出现该问题，原因是此异常仅在获取分类列表失败或为空时才会抛出，我将尽快修复这个bug。

**Comment by tangly1024** [comment]
在最新的提交中已修复该问题 https://github.com/tangly1024/NotionNext/commit/3030423cf229665a4ee75dbc6c6cc985fbe7e8c7
