### ISSUE TITLE
【数据有误】主页 / Search / Archive 页面文章数、目录数、标签数不一致

### ISSUE THREAD

**Issue by yiranzhimo** [tangly1024/NotionNext#800]
**描述bug**
在网站的 Search / Archive 页面，显示出的信息与正确信息不匹配。
如下面截图：
主页显示的「文章数」「目录数」「标签数」都是对的，
但是在 Search 页面和 Archive 页面，显示的「文章数」「目录数」「标签数」都是有误的。

**复现步骤**
点击网站的 Search / Archive 按钮

**期望的正常结果**
出现正确的结果

**截图**
【主页显示结果】
![截屏2023-02-25 17 49 10](https://user-images.githubusercontent.com/40296363/221350650-ec5ce514-68fd-418a-8d26-812e43650d30.png)
【Search 页面结果】
![截屏2023-02-25 17 51 41](https://user-images.githubusercontent.com/40296363/221350663-865f4960-869a-4004-b8f6-86cbb5febfe3.png)
【Archive 页面结果】
![截屏2023-02-25 17 51 49](https://user-images.githubusercontent.com/40296363/221350665-84a7b1d1-8e67-446b-8250-0aefd19d6aba.png)

**环境**

- 操作系统: macOS
- 浏览器: Google Chrome,
- 版本: 10.0.5481.100

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
可能页面缓存导致，刷新一下

**Comment by tangly1024** [comment]
- 主页
![image](https://user-images.githubusercontent.com/15920488/221456146-d05b22ef-5cf7-4c62-8a4f-693761e5b60c.png)

- Archive
![image](https://user-images.githubusercontent.com/15920488/221456038-55780ed3-a7d7-48d4-830d-cf02a30cf450.png)

- Search
![image](https://user-images.githubusercontent.com/15920488/221456087-5a54286f-0423-4757-a574-3126e1566a65.png)

**Comment by yiranzhimo** [comment]
> 可能页面缓存导致，刷新一下

清楚缓存是有效的，感谢🙏
