### ISSUE TITLE
blog.config.js文件中的作者、描述、keyword等修改为环境变量

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#805]
**为什么提出这个新的特性改动**

能够把作者昵称跟keywords也改为环境变量吗？如果改为环境变量，那么每次同步代码，就不需要修改配置文件。只需要在vercel或者zeabur配置环境变量就可以了
![image](https://user-images.githubusercontent.com/32816780/221525652-8f871ef0-a52f-4ce1-90c1-60b9288e0a78.png)

**描述一下你推荐的解决方案**
简要说明你的解决方案建议，例如，『Giscus评论插件功能更加强大，用户只需留言既可在你的邮箱收到通知。。。』

**描述一下你考虑过的其它替代解决方案**
简要说明你所有想过的有可能解决此问题的方案。

**补充说明**
补充与此特性相关的内容

**Comment by tangly1024** [comment]
感谢反馈，最新版已添加此特性 https://github.com/tangly1024/NotionNext/blob/main/blog.config.js
