### ISSUE TITLE
【性能问题】最新版本异常卡顿

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#816]
**描述bug**
简单说明bug的现象、相关的错误提示、日志等
更新之后博客首页能打开https://coolnext.vercel.app/ ，但是所有文章都无法打开。显示404页面
我可以确定的是87e4b2c版本没有问题，但是d3dcb91355c2cc0ac348e353fd286988b2e40d25版本就无法打开具体文章

**是不是优化加载出了问题**

**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
相关的页面，应该用结果
![image](https://user-images.githubusercontent.com/32816780/222186670-6f03e6e9-8274-4953-9378-3364be22798a.png)
![image](https://user-images.githubusercontent.com/32816780/222187096-c06bde2e-2f7a-4dc4-b606-5709bb8d3f8e.png)

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
与问题相关的其它说明

**Comment by Angel0726** [comment]
> **描述bug** 简单说明bug的现象、相关的错误提示、日志等 更新之后博客首页能打开[https://coolnext.vercel.app/，但是所有文章都无法打开。显示404页面](https://coolnext.vercel.app/%EF%BC%8C%E4%BD%86%E6%98%AF%E6%89%80%E6%9C%89%E6%96%87%E7%AB%A0%E9%83%BD%E6%97%A0%E6%B3%95%E6%89%93%E5%BC%80%E3%80%82%E6%98%BE%E7%A4%BA404%E9%A1%B5%E9%9D%A2) 我可以确定的是87e4b2c版本没有问题，但是d3dcb91355c2cc0ac348e353fd286988b2e40d25版本就无法打开具体文章
> 
> **是不是优化加载出了问题**
> 
> **复现步骤** 出现这个bug的操作步骤
> 
> **期望的正常结果** 希望按这个步骤，正常操作结果是什么
> 
> **截图** 相关的页面，应该用结果 ![image](https://user-images.githubusercontent.com/32816780/222186670-6f03e6e9-8274-4953-9378-3364be22798a.png) ![image](https://user-images.githubusercontent.com/32816780/222187096-c06bde2e-2f7a-4dc4-b606-5709bb8d3f8e.png)
> 
> **环境**
> 
> * 操作系统: [例如. iOS, Android, macOS, windows]
> * 浏览器 [例如. chrome, safari, firefox]
> * 版本 [e.g. 22]
> 
> **补充说明** 与问题相关的其它说明

好像多次刷新之后是可以显示；但是感觉不仅加载速度明显变慢了，而且还卡顿。
博客中的代码是自动换行的，但是notion中的代码不是自动换行的。可以跟notion统一吗
![image](https://user-images.githubusercontent.com/32816780/222191147-ff3cbfb3-edf2-42f8-b067-943c6f4bb931.png)
![image](https://user-images.githubusercontent.com/32816780/222191405-b3b37c1a-109f-47d9-9768-c7d679bce9f7.png)

**Comment by Angel0726** [comment]
> > **描述bug** 简单说明bug的现象、相关的错误提示、日志等 更新之后博客首页能打开[https://coolnext.vercel.app/，但是所有文章都无法打开。显示404页面](https://coolnext.vercel.app/%EF%BC%8C%E4%BD%86%E6%98%AF%E6%89%80%E6%9C%89%E6%96%87%E7%AB%A0%E9%83%BD%E6%97%A0%E6%B3%95%E6%89%93%E5%BC%80%E3%80%82%E6%98%BE%E7%A4%BA404%E9%A1%B5%E9%9D%A2) 我可以确定的是87e4b2c版本没有问题，但是d3dcb91355c2cc0ac348e353fd286988b2e40d25版本就无法打开具体文章
> > 
> > **是不是优化加载出了问题**
> > 
> > **复现步骤** 出现这个bug的操作步骤
> > 
> > **期望的正常结果** 希望按这个步骤，正常操作结果是什么
> > 
> > **截图** 相关的页面，应该用结果 ![image](https://user-images.githubusercontent.com/32816780/222186670-6f03e6e9-8274-4953-9378-3364be22798a.png) ![image](https://user-images.githubusercontent.com/32816780/222187096-c06bde2e-2f7a-4dc4-b606-5709bb8d3f8e.png)
> > 
> > **环境**
> > 
> > * 操作系统: [例如. iOS, Android, macOS, windows]
> > * 浏览器 [例如. chrome, safari, firefox]
> > * 版本 [e.g. 22]
> > 
> > **补充说明** 与问题相关的其它说明
> 
> 好像多次刷新之后是可以显示；但是感觉不仅加载速度明显变慢了，而且还卡顿。
> 博客中的代码是自动换行的，但是notion中的代码不是自动换行的。可以跟notion统一吗
> ![image](https://user-images.githubusercontent.com/32816780/222191147-ff3cbfb3-edf2-42f8-b067-943c6f4bb931.png)
> ![image](https://user-images.githubusercontent.com/32816780/222191405-b3b37c1a-109f-47d9-9768-c7d679bce9f7.png)
> 
> 
新问题用手机刷博客，直接卡死，过一会浏览器就报异常

**Comment by tangly1024** [comment]
- 异常卡顿和404的问题，昨晚有提交了补丁修复，更新后应该会好很多。

- 修改代码换行逻辑，关闭掉行号显示即可实现和Notion一致：https://github.com/tangly1024/NotionNext/blob/440fcff60e64bfe7668c92275dc17e10c8e960c4/blog.config.js#L62

**Comment by Angel0726** [comment]
> - 异常卡顿和404的问题，昨晚有提交了补丁修复，更新后应该会好很多。
> 
> - 修改代码换行逻辑，关闭掉行号显示即可实现和Notion一致：https://github.com/tangly1024/NotionNext/blob/440fcff60e64bfe7668c92275dc17e10c8e960c4/blog.config.js#L62

代码换行逻辑修改了。更新了昨晚的补丁以后404问题解决了，但是卡顿异常还是存在，感觉不够丝滑

**Comment by tangly1024** [comment]
- 建议压缩一下图片大小
- hexo主题的动画效果，也有可能造成卡顿，我将在新版本中优化此问题

**Comment by Angel0726** [comment]
> * 建议压缩一下图片大小
> * hexo主题的动画效果，也有可能造成卡顿，我将在新版本中优化此问题
更新之后效果有改善，希望主页滚动更加平滑一些，封面加载动画更顺畅一些。

https://jeweled-trilby-556.notion.site/59c95f5032194328a2e7c13c9e25fcf9

**Comment by ikkz** [comment]
@tangly1024 发现了几个影响性能的地方
这里percent加入依赖数组会导致滚动时频繁地注册和取消事件监听，其他地方也有类似的代码
https://github.com/tangly1024/NotionNext/blob/b22475dec55702fbdff9dc6e7e05188e11e4aeb3/themes/hexo/components/Progress.js#L25-L28

scrollListener里有 clientHeight 等会触发回流的操作，也许应该做个节流，同样也不止一处
https://github.com/tangly1024/NotionNext/blob/b22475dec55702fbdff9dc6e7e05188e11e4aeb3/themes/hexo/LayoutBase.js#L41-L54

**Comment by Angel0726** [comment]
> @tangly1024 发现了几个影响性能的地方 这里percent加入依赖数组会导致滚动时频繁地注册和取消事件监听，其他地方也有类似的代码
> 
> https://github.com/tangly1024/NotionNext/blob/b22475dec55702fbdff9dc6e7e05188e11e4aeb3/themes/hexo/components/Progress.js#L25-L28
> 
> scrollListener里有 clientHeight 等会触发回流的操作，也许应该做个节流，同样也不止一处
> 
> https://github.com/tangly1024/NotionNext/blob/b22475dec55702fbdff9dc6e7e05188e11e4aeb3/themes/hexo/LayoutBase.js#L41-L54

那每次打开一个博客，封面的那个动画效果也是因为这个原因吗？

**Comment by ikkz** [comment]
> 那每次打开一个博客，封面的那个动画卡顿的问题也是因为这个原因吗？

不确定，我也是刚看到这个项目准备用用

**Comment by Angel0726** [comment]
之前我还一直以为是主题问题，看样子不是。这个用户的butter-fly主题就不卡顿https://www.sszsj.cc/

**Comment by Angel0726** [comment]
更新3.12之后还会存在卡顿问题。可以参考视频https://jeweled-trilby-556.notion.site/59c95f5032194328a2e7c13c9e25fcf9
版本号中多了一个引号
![image](https://user-images.githubusercontent.com/32816780/224071792-8012421e-e586-4a9e-a481-fa6f6d136891.png)

**Comment by Angel0726** [comment]
更新3.12.1之后还会存在卡顿问题，但是相比之前有所好转。可以参考视频https://jeweled-trilby-556.notion.site/59c95f5032194328a2e7c13c9e25fcf9
使用设备win、安卓都会卡顿，但是苹果不会卡顿

**Comment by Angel0726** [comment]
更新[4e9b9a0](https://github.com/tangly1024/NotionNext/commit/4e9b9a09cf7e15cd6de3418c81824dd4c679e8b2)之后卡顿依然存在，运行日志。
![image](https://user-images.githubusercontent.com/32816780/224287286-cf217325-8780-428f-9ef2-0c0125bebe2e.png)

**Comment by tangly1024** [comment]
v3.12.2 版本针对性能做了处理

**Comment by Angel0726** [comment]
还是会卡顿，博客首页卡顿严重。非首页好很多

**Comment by tangly1024** [comment]
已提交了新的补丁，优化首页动画性能问题

**Comment by Angel0726** [comment]
> 已提交了新的补丁，优化首页动画性能问题

问题依然存在，详情可以参考notion链接

**Comment by Angel0726** [comment]
卡顿问题完全解决点赞。但是图片加载有一点慢，不知道是不是网络问题。zeabur服务器有一点慢。next.zeabur.app

**Comment by Angel0726** [comment]
更新之后，博客首页每一篇博客高度变小而且高矮不一，是不是没有之前的好看；动画目前是文字飞入，是不是也有没有之前的好看

**Comment by tangly1024** [comment]
> 更新之后，博客首页每一篇博客高度变小而且高矮不一，是不是没有之前的好看；动画目前是文字飞入，是不是也有没有之前的好看

高矮不一确实不美观，目前已经调整回固定高度了；
动画显然原先的更好看：而处于性能优化的考虑，做成仅文字飞入的效果；出于美观考虑，动画的问题我再优化一下。
