### ISSUE TITLE
【Hexo主题】页面宽度不一致，不知道是否合理

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#831]
**描述bug**
简单说明bug的现象、相关的错误提示、日志等
窄：https://next.zeabur.app/article/acdc65c5-b851-4350-af34-8da0ad576eae
![image](https://user-images.githubusercontent.com/32816780/224259344-c84990c7-60a5-462f-aaa9-0d0469a5d072.png)

中：https://next.zeabur.app/article/cde8edb2-d473-46cf-9e05-3513db0b2e6f
![image](https://user-images.githubusercontent.com/32816780/224259555-14b264e7-8223-4ca7-81bf-d35e35163e4b.png)

宽：https://next.zeabur.app/article/9216b220-f232-45c1-b4c9-675301cd3393
![image](https://user-images.githubusercontent.com/32816780/224259181-ded84e41-5dc3-44c6-b557-23db57ba8f9d.png)

**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如.  windows]
- 浏览器 [例如.edge]
- 版本 [e.g. 3.12.1]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
如您所见，并不合理；这个问题将被尽快修复

**Comment by Angel0726** [comment]
> 如您所见，并不合理；这个问题将被尽快修复

卡顿的问题还会继续跟踪修复吗

**Comment by tangly1024** [comment]
新版本中此问题已不存在
