### ISSUE TITLE
希望可以增加一个关闭或许优化rss订阅

### ISSUE THREAD

**Issue by feihuobuzhun** [tangly1024/NotionNext#843]
**为什么提出这个新的特性改动**
目前文章设置密码并且修改链接之后，rss仍然会显示notion page的id，密码就形同虚设了
下图黄色部分
![屏幕截图 2023-03-11 195013](https://user-images.githubusercontent.com/76815389/224482681-956c8f6b-1ae7-4b98-94c9-e6f171e1594d.png)

**描述一下你推荐的解决方案**
希望可以增加一个关闭rss订阅，或许优化rss所提供的信息

谢谢

**Comment by tangly1024** [comment]
1. 将新增配置允许 开关rss订阅
2. rss信息中不体现notion-page-id，（但需要注意如果页面slug为空，默认会使用id作为文章路劲）

**Comment by feihuobuzhun** [comment]
大佬辛苦！
