### ISSUE TITLE
分享到微信图标 空链接

### ISSUE THREAD

**Issue by 668168** [tangly1024/NotionNext#845]
**描述bug**
在文章最后, share 分享图标上, 鼠标移动到微信, 点击, 无任何效果

**复现步骤**
在文章最后, share 分享图标上, 鼠标移动到微信, 点击, 无任何效果
**期望的正常结果**
有正常链接
**截图**
<img width="798" alt="image" src="https://user-images.githubusercontent.com/1046701/224493505-15167cbf-39e1-4893-bff3-3787e6302908.png">
**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
已提交补丁 https://github.com/tangly1024/NotionNext/commit/1862012d6949ec35bc7cd5738a2435d30418ac82
