### ISSUE TITLE
【图片问题】最新 master 分支代码，博客图片显示全挂了

### ISSUE THREAD

**Issue by expoli** [tangly1024/NotionNext#851]
**描述bug**
博客所有的图片全都无法显示

**复现步骤**
合并最新代码

**截图**

![image](https://user-images.githubusercontent.com/31023767/224548794-34698b03-97ee-4d1a-a454-d2c6ea063991.png)
- 访问地址： https://notion-next-d9sfb0bk4-expoli.vercel.app/
- 我的代码分支：https://github.com/expoli/NotionNext
  - 合并的时候，并没有相应的代码冲突
**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
收到反馈 ，问题将尽快被修复

**Comment by leewint** [comment]
> 

预览大图如果是notion上传的正常显示，我的github图床的图片都挂了

**Comment by tangly1024** [comment]
已提交图片问题补丁： https://github.com/tangly1024/NotionNext/commits/main ； 更新修复；


3.12.3版本为了修复由于图片过多、过大导致页面卡顿的问题调整了图片的逻辑，但似乎兼容性还有些问题，后续再尝试优化

**Comment by Angel0726** [comment]
> 已提交图片问题补丁： https://github.com/tangly1024/NotionNext/commits/main ； 更新修复；
> 
> 3.12.3版本为了修复由于图片过多、过大导致页面卡顿的问题调整了图片的逻辑，但似乎兼容性还有些问题，后续再尝试优化

现在是不卡顿了。图片我这边没挂但是加载太慢了，而且还有一个严重问题就是，太占资源了内存从之前200m现在1个多g。cpu从5%到70%
![image](https://user-images.githubusercontent.com/32816780/224552747-65372126-428c-4c9a-8787-a2d0dcb7f792.png)
![image](https://user-images.githubusercontent.com/32816780/224552799-d7159a4a-7ac5-4aa9-af2a-3c62c18c6b5c.png)

**Comment by tangly1024** [comment]
经过此次排查，主要引起网页卡顿的原因是：“博客封面图片过大导致”；

- cpu过度占用的原因是：为了保证首页的性能，我调用的nextjs的接口对图片进行压缩，然而这么做对服务器的压力很大

- 建议： 博客的封面图片进行适当压缩，在保证清晰的前提下，文件体积越小越好。我看到你首页原先的封面图最大的有7MB之多。

**Comment by Angel0726** [comment]
好的👌🏻

**Comment by tangly1024** [comment]
> ![image](https://user-images.githubusercontent.com/31023767/224601010-6bcbcb66-5a03-4361-9cc2-2d8b7ac124d1.png) 最新文章这里图片还是挂的

这个问题修复刚已提交

**Comment by tangly1024** [comment]
> 

确实偏低了，没有考虑到标题换行的情况

**Comment by betsyalan** [comment]
请问，这个显示高度偏低的问题，可以修改哪个配置？

**Comment by tangly1024** [comment]
> 同时这个主页的文章的显示界面，高度是不是有点过于低了 ![image](https://user-images.githubusercontent.com/31023767/224607935-6010a8dc-c429-40ea-ae92-ec922f01a5c5.png)

已提交修复高度过低的问题：https://github.com/tangly1024/NotionNext/commit/5fe62df504ee1bce4dff8980a0306bb19bbe4eef


自行修改的话要在代码中操作，相关代码：https://github.com/tangly1024/NotionNext/blob/main/themes/hexo/components/BlogPostCard.js
