### ISSUE TITLE
sitemap.xml 也包含了draft/Invisible 的文章

### ISSUE THREAD

**Issue by siygle** [tangly1024/NotionNext#861]
**描述bug**
sitemap.xml 也包含了draft/Invisible 的文章，是不是應該排除那些只放入 `Published` 狀態的文章？

**复现步骤**
目前的 NotionNext 任一 sitemap 都可以重現這個問題：
e.g., https://preview.tangly1024.com/sitemap.xml

**期望的正常结果**
Sitemap 只包含狀態為 `Published` 的文章

**截图**
可參考复现步骤裡面的連結。

**环境**

- 操作系统: macOS 13.2.1
- 浏览器 chrome v111

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
如您所说；sitemap只应当包含published文章，此问题将被修复
