### ISSUE TITLE
【Notion排版】next等各个主题，博客排版与notion不同

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#879]
除了hexo住客，其余主题博客排版与notion均有差异，例如next、simple等
- hexo：https://www.vabc.top/article/38339f4a-7335-4d4e-ae1f-36a0ca9f61ab
![image](https://user-images.githubusercontent.com/32816780/225267867-11e54299-0e61-4a92-a1c3-2faacff47c92.png)
- next：https://next.zeabur.app/article/38339f4a-7335-4d4e-ae1f-36a0ca9f61ab
![image](https://user-images.githubusercontent.com/32816780/225268290-523f4fcb-8916-45c5-acfe-952af026b3ed.png)
- simple：https://next.zeabur.app/article/38339f4a-7335-4d4e-ae1f-36a0ca9f61ab?theme=simple
![image](https://user-images.githubusercontent.com/32816780/225269047-3532c4c2-5dee-42f7-acd8-67de6f26f842.png)

**描述bug**
简单说明bug的现象、相关的错误提示、日志等

**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
问题根源是 不同主题的网页宽度不同导致。
将安排修复

**Comment by Angel0726** [comment]
next 主题还有一个 问题就是搜索页面的概述太长了，没有必要这么长。可以限制一下next的长度
![image](https://user-images.githubusercontent.com/32816780/226238576-66045bc5-f60f-4d39-9bc8-067684551b2e.png)

**Comment by Angel0726** [comment]
> 问题根源是 不同主题的网页宽度不同导致。 将安排修复

next主题可不可以先修复一下

**Comment by tangly1024** [comment]
duplicate https://github.com/tangly1024/NotionNext/issues/928
