### ISSUE TITLE
【Analytics】Audiences in Vercel Analytics

### ISSUE THREAD

**Issue by thedavidweng** [tangly1024/NotionNext#897]
**为什么提出这个新的特性改动**
Vercel 自带的 Analytics 功能

**描述一下你推荐的解决方案**
https://vercel.com/docs/concepts/analytics/audiences/quickstart 

**描述一下你考虑过的其它替代解决方案**
Google Analytics

**Comment by Angel0726** [comment]
同问，可以用Vercel 自带的 Analytics 功能吗

**Comment by dreamer2q** [comment]
这个费用不是一般的坑，超过次数要收费

**Comment by Angel0726** [comment]
> 这个费用不是一般的坑，超过次数要收费

Vercel Analytics要收费吗
