### ISSUE TITLE
一直显示没有找到文章

### ISSUE THREAD

**Issue by weizhenhuan** [tangly1024/NotionNext#9]
pageid已经改过了，为什么还显示找不到文章

![image](https://user-images.githubusercontent.com/55399998/148199465-295456dc-716e-4be3-87f0-209a1f8daa76.png)

**Comment by weizhenhuan** [comment]
share也开了

**Comment by tangly1024** [comment]
代码要重新更新一下哦，今天下午刚修复了一个bug，会导致找不到文章。

![F3D65861-2D55-4202-B43E-BFF65D85CF90](https://user-images.githubusercontent.com/15920488/148213228-1a3d0847-442f-4dd9-85cf-784c5550770d.jpeg)
