### ISSUE TITLE
【next 主题】搜索页面的概述太长

### ISSUE THREAD

**Issue by Angel0726** [tangly1024/NotionNext#916]
next 主题还有一个 问题就是搜索页面的概述太长了，没有必要这么长。可以限制一下next的长度
![image](https://user-images.githubusercontent.com/32816780/226238576-66045bc5-f60f-4d39-9bc8-067684551b2e.png)

**描述bug**
简单说明bug的现象、相关的错误提示、日志等

**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
与问题相关的其它说明

**Comment by Angel0726** [comment]
这是什么原因呀

**Comment by tangly1024** [comment]
已修复，更新体验
