### ISSUE TITLE
【Simple主题】搜索结果异常

### ISSUE THREAD

**Issue by Xauthub2019** [tangly1024/NotionNext#919]
**描述bug**
使用Simple主题时，搜索结果跳转时链接中含有search/，导致无法正常跳转。
**复现步骤**
使用Simple主题，使用顶部右上角的放大镜搜索，
网址为，[https://www.xauthub.top/](https://www.xauthub.top/)；
以搜索IT为例，搜索结果页[https://www.xauthub.top/search/IT](https://www.xauthub.top/search/IT)
第一个结果点击跳转，链接为[https://www.xauthub.top/search/article/情报总橘IT技术部纳新公告](https://www.xauthub.top/search/article/情报总橘IT技术部纳新公告)
多了search/，所以无法正常跳转。
同时，点击页面顶部左上角的的搜索，会直接提示**没有更多了 😰**，而不跳出搜索框。

**期望的正常结果**
希望Simple主题搜索结果跳转不含search/，且点击顶部左上角的搜索，可以正常弹出搜索框。

**截图**
![image](https://user-images.githubusercontent.com/128889181/227754976-4e781315-9a2c-4b1d-b933-3b9d95456dd0.png)
![image](https://user-images.githubusercontent.com/128889181/227754983-19e0be9d-4cda-4d29-81a1-58cc18eaf41c.png)

**环境**

- 操作系统: Windows
- 浏览器 Edge
- 版本 111.0.1661.54 (正式版本) (64 位)

**补充说明**
无

**Comment by tangly1024** [comment]
奇怪的是，我打开访问时链接是正常的，没有带/search 呆：
<img width="759" alt="图片" src="https://user-images.githubusercontent.com/15920488/227755236-941108b0-d13d-42ee-866b-2c254743ade2.png">

点击跳转也是正常
<img width="1019" alt="图片" src="https://user-images.githubusercontent.com/15920488/227755246-7bfe5112-a947-41b0-99e8-b4b5f3ef635d.png">

**Comment by Xauthub2019** [comment]
那可能我的问题吧，麻烦博主了

**Comment by tangly1024** [comment]
很好奇此问题出现的原因，奈何我无法重现😳
