### ISSUE TITLE
[v3.13]首页无法显示文章

### ISSUE THREAD

**Issue by ke-xi** [tangly1024/NotionNext#924]
**描述遇到的问题**
网站首页无法显示文章,不知道是不是因为把这里<img width="966" alt="Snipaste_2023-03-26_19-23-54" src="https://user-images.githubusercontent.com/58284266/227772913-d7fab7a5-7c4c-474d-8c58-e7fb9b43a434.png">改了的原因,但是已经改了好久了,之前也没事的

**相应配置**

notion_page_id；428b80890ff0461fa84371995d20a8a3
你的网站地址https://blog.kexi.ga/

**截图**
<img width="1245" alt="Snipaste_2023-03-26_19-23-39" src="https://user-images.githubusercontent.com/58284266/227772943-4021785a-976b-4e98-a16a-93404f8ecedd.png">

**环境**
- 操作系统: [ windows]
- 浏览器 [edge]
- 版本 [e.g. 22]

**Comment by ke-xi** [comment]
[img]https://image.baidu.com/search/down?url=https://tvax3.sinaimg.cn/large/005REQzJgy1hcdhmogyacj31hn0hfqpi.jpg[/img]
![Snipaste_2023-03-26_19-23-39.png](https://image.baidu.com/search/down?url=https://tvax3.sinaimg.cn/large/005REQzJgy1hcdhjtnf9fj31x613in4p.jpg)

**Comment by tangly1024** [comment]
向你的仓库提交了PR，修复首页文章不见的问题

**Comment by ke-xi** [comment]
> 向你的仓库提交了PR，修复首页文章不见的问题

好了,谢谢啦
