### ISSUE TITLE
 文章密码可绕过

### ISSUE THREAD

**Issue by admin-set** [tangly1024/NotionNext#976]
**描述bug**
文章上锁密码可绕过

**复现步骤**
前端查看源代码搜索 @NcA" 可获取取文章上锁密码。从而进行获取加密内容

**期望的正常结果**
查看前端源代码无法访问到文章上锁密码。

**截图**

<img width="2004" alt="image" src="https://user-images.githubusercontent.com/63496176/232098600-b79a23ab-6462-41d6-90b3-f2e42c6472ee.png">

<img width="1630" alt="image" src="https://user-images.githubusercontent.com/63496176/232098827-00560104-98e3-4fa4-8242-5c97870d1511.png">

**环境**

- 操作系统: macOS
- 浏览器 chrome
- 版本 最新版本

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
感谢反馈，此问题将被紧急修复
