### ISSUE TITLE
url前缀路径 文章标题可正常跳转 Continue Reading 拼接有问题

### ISSUE THREAD

**Issue by RedhairHambagu** [tangly1024/NotionNext#984]
**描述bug**
tags，search，category 都会叠加slug， 类似  #919 
简单说明bug的现象、相关的错误提示、日志等

**复现步骤**
https://tangly1024.com/tag 页面下点击任何标签，对应标签下文章 直接点击标题对应的link是正常的。
但是“Continue Reading”的link  就会叠加/tag 变成 tangly1024.com/**tag/article/notion-next-secondary-menu

**期望的正常结果**
“Continue Reading”的link  不会叠加“tag/search/category”

**截图**
![image](https://user-images.githubusercontent.com/129669334/232522396-854e2158-67e8-48cb-8a6e-980c260846ed.png)

**环境**

- 操作系统:  macOS
- 浏览器 chrome
- 版本 111.0.5563.146
IOS Safari 也能遇到这个

**补充说明**
tag/article/xxx 页面最后会跳到404， 如果有音乐播放器（自动播放已设置为**False**），会触发播放音乐

**Comment by tangly1024** [comment]
感谢反馈！
